/* ============================================================================
   BELONGING GATE (8/12/26, FACTIONS lane) — THERE IS SOMETHING BEHIND THE DOOR.

   Law:   laws/BOHEMIA_ADDENDUM_WHAT_THEY_WANT_FROM_YOU_8_12_26.md
   Organ: engine/bohemia_belonging.js (generated by tools/bohemia_belonging.py)
   Page:  slices/BOHEMIA_WHAT_THEY_WANT_8_12_26.html  (LIFE tab)

   WHAT THIS IS DEFENDING. Two turns built a door (sixteen ways to learn a name)
   and a lock (the Mob will not be asked; somebody inside has to vouch). Walk
   through it and there was NOTHING IN THERE — no reason to want in, no idea what
   they wanted, no idea what it was worth. Both halves of that answer had been
   sitting in his dossiers since 8/2, thumbed up, read by nothing:
   WHAT THEY WANT FROM YOU and WHAT THEY TRADE / CONTROL.

   THE FIVE WAYS THIS BREAKS, and every claim is aimed at one:

     1. THE SHAPE DRIFTS OFF THE WORDS. The `wants` kind is a READING of his
        sentence. Reword the dossier and the reading is silently wrong.
        -> A: 32 anchors (two per faction) must be verbatim in their own dossier,
           and the generator is RE-RUN and diffed.

     2. IT COLLAPSES INTO ONE BARGAIN. Sixteen outfits that all "want help" and
        all "have supplies" is decoration with sixteen names on it.
        -> B: distinctness measured across what the player actually reads.

     3. BELONGING BECOMES STANDING WEARING A HAT. This lane already has a
        reputation organ. If the ladder walks off standing, it is the same system
        twice and the second one is a lie.
        -> C: the counter is a COUNT of positive authored deeds, driven through a
           REAL quest, and it must move independently of the standing number.

     4. WIRED BY NAME AND DEAD IN FACT (advance_territory 8/9, the allegiance line
        8/11 — this lane has shipped it twice).
        -> D: the REAL built run in a REAL browser, reading the REAL card node.

     5. IT DECIDES SOMETHING THAT IS HIS. The Mob dossier carries an explicit open
        question about the Cartel and the guarantor seat.
        -> A5/E: it is carried through as PENDING and nothing resolves it.

   node gates/belonging_gate.js
   ============================================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.dirname(__dirname);
const ORGAN = path.join(ROOT, 'engine/bohemia_belonging.js');
const TOOL = path.join(ROOT, 'tools/bohemia_belonging.py');
const DOSSIERS = path.join(ROOT, 'records/factions');
const RUN_SRC = path.join(ROOT, 'slices/BOHEMIA_RUN_SLICE_7_26_26.html');
const RUN_FILE = path.join(ROOT, 'slices/BOHEMIA_RUN_CURRENT.html');
const PAGE = path.join(ROOT, 'slices/BOHEMIA_WHAT_THEY_WANT_8_12_26.html');

let pass = 0, fail = 0;
function ok(claim, cond, detail) {
  if (cond) { pass++; console.log('  ok  ' + claim); }
  else { fail++; console.log('  FAIL ' + claim + (detail ? '\n       ' + detail : '')); }
}
function requirePlaywright() {
  const globals = ['/opt/node22/lib/node_modules', '/usr/lib/node_modules', '/usr/local/lib/node_modules'];
  for (const g of globals) { try { return require(path.join(g, 'playwright')); } catch (_e) {} }
  return require('playwright');
}

const B = require(ORGAN);

/* ------------------------------------------------------- A. IT IS HIS CANON */
function partA() {
  console.log('A. BOTH HALVES ARE HIS, AND THEY HAVE NOT DRIFTED');

  const files = fs.readdirSync(DOSSIERS)
    .filter(f => /^BOHEMIA_FACTION_.*\.md$/.test(f))
    .map(f => f.replace(/^BOHEMIA_FACTION_/, '').replace(/\.md$/, ''));
  const keys = B.keys();
  ok('A1 every faction dossier on disk has a bargain, and no bargain is an orphan',
    files.every(f => keys.includes(f)) && keys.every(k => files.includes(k)) &&
    keys.length === 16, keys.length + ' bargains, ' + files.length + ' dossiers');

  let anchored = 0, quoted = 0;
  keys.forEach(k => {
    const r = B.RULES[k];
    const flat = fs.readFileSync(path.join(DOSSIERS, 'BOHEMIA_FACTION_' + k + '.md'), 'utf8')
      .replace(/\s+/g, ' ');
    if (r.anchorWant && flat.includes(r.anchorWant) &&
        r.anchorHold && flat.includes(r.anchorHold)) anchored++;
    if (r.want && flat.includes(r.want.slice(0, 100)) &&
        r.hold && flat.includes(r.hold.slice(0, 100))) quoted++;
  });
  ok('A2 all 32 anchors (two per faction) are verbatim in their own dossier',
    anchored === 16, anchored + '/16');
  ok('A3 both canon paragraphs are carried verbatim, not paraphrased',
    quoted === 16, quoted + '/16');

  const before = fs.readFileSync(ORGAN, 'utf8');
  let regen;
  try { execFileSync('python3', [TOOL], { cwd: ROOT, stdio: 'pipe' }); regen = fs.readFileSync(ORGAN, 'utf8'); }
  catch (e) { regen = 'GENERATOR REFUSED: ' + (e.stderr || e.message); }
  ok('A4 the baked organ is exactly what the generator produces right now',
    regen === before,
    String(regen).startsWith('GENERATOR REFUSED') ? String(regen).slice(0, 300)
      : 'hand-edited, or a dossier changed under it');

  /* HIS OPEN QUESTION SURVIVES. The Mob dossier says outright that whether the
     Mob IS the Cartel, and whether they hold the guarantor seat, is not decided.
     A system that quietly answered it would be inventing canon. */
  ok('A5 the Mob\'s open question is carried through as PENDING, not answered',
    /guarantor seat/i.test(B.RULES.MOB.pending || '') &&
    /nothing here decides it|open/i.test(B.RULES.MOB.pending || ''),
    JSON.stringify(B.RULES.MOB.pending));
}

/* --------------------------------------------------- B. SIXTEEN ECONOMIES */
function partB() {
  console.log('B. SIXTEEN ECONOMIES, NOT SIXTEEN NAMES FOR ONE');

  const keys = B.keys();
  /* what the player actually reads off a card. If these collapse, so does the
     feature, whatever the data looks like underneath. */
  const sig = k => { const b = B.bargain(B.RULES[k], 0);
    return JSON.stringify([b.wantWord, b.pays, b.refuses, b.theyFirst, b.noOffer]); };
  const distinct = new Set(keys.map(sig)).size;
  ok('B1 at least 14 of the sixteen bargains read differently to the player',
    distinct >= 14, distinct + '/16 distinct');

  ok('B2 every kind of want his canon describes is actually used',
    new Set(keys.map(k => B.RULES[k].wants)).size >= 6,
    [...new Set(keys.map(k => B.RULES[k].wants))].join(','));

  /* the named-in-canon ones, driven rather than read */
  ok('B3 REMNANTS want what you know and pay in ammunition, not loyalty',
    B.RULES.REMNANTS.wants === 'information' &&
    B.bargain(B.RULES.REMNANTS, 0).pays === 'AMMUNITION' &&
    /Not loyalty/.test(B.RULES.REMNANTS.want));
  ok('B4 MOB want you LISTED - not loyal, not employed',
    B.RULES.MOB.wants === 'legibility' && /listed/i.test(B.RULES.MOB.want));
  ok('B5 CARTEL and CHURCH both move first, which is the whole horror of it',
    B.bargain(B.RULES.CARTEL, 0).theyFirst === true &&
    B.bargain(B.RULES.CHURCH, 0).theyFirst === true);
  ok('B6 VOLUNTEERS refuse a gift that would make them worth robbing',
    /ROBBING/i.test(B.bargain(B.RULES.VOLUNTEERS, 0).refuses || ''));
  ok('B7 KARENS refuse ambiguity, which is the one thing they cannot process',
    /AMBIGUITY/i.test(B.bargain(B.RULES.KARENS, 0).refuses || ''));
  ok('B8 AMALGAMATION makes no offer and has no ladder to climb',
    B.bargain(B.RULES.AMALGAMATION, 0).noOffer === true &&
    B.rungOf(B.RULES.AMALGAMATION, 99) === null &&
    B.nextRung(B.RULES.AMALGAMATION, 0) === null);

  /* THE ~85% WHO RUN WITH NOBODY have no bargain, because there is no outfit --
     saying "they want nothing from you" would be a statement about the PERSON. */
  ok('B9 somebody who runs with nobody has no bargain at all, not an empty one',
    B.bargain(B.DEFAULT, 0) === null && B.ruleOf(null) === B.DEFAULT &&
    B.ruleOf('NOT_A_FACTION') === B.DEFAULT);
  ok('B10 all three faction vocabularies resolve',
    B.ruleOf('Remnants') === B.RULES.REMNANTS &&
    B.ruleOf('Social Forces') === B.RULES.SOCIAL_FORCES &&
    B.ruleOf('Triads') === B.RULES.SOCIAL_FORCES);
}

/* ------------------------------------- C. A GRADIENT, AND NOT STANDING AGAIN */
function partC() {
  console.log('C. YOU DRIFT INWARD BY DOING THE THING, AND IT IS NOT STANDING');

  const r = B.RULES.BLUES;
  ok('C1 the ladder is monotonic and starts at stranger',
    B.rungOf(r, 0).key === 'stranger' &&
    B.RUNGS.every((x, i) => i === 0 || x.at > B.RUNGS[i - 1].at));
  ok('C2 one peripheral act is the whole entry - it is meant to be small',
    B.rungOf(r, 1).key === 'peripheral' && B.RUNGS[1].at === 1);
  ok('C3 the ladder actually moves, and says what would move it next',
    B.rungOf(r, 3).key === 'useful' && B.rungOf(r, 6).key === 'counted' &&
    B.rungOf(r, 10).key === 'inside' &&
    B.nextRung(r, 3).more === 3 && B.nextRung(r, 10) === null);

  /* THE COUNTER IS A COUNT, AND IT IS DRIVEN BY A REAL AUTHORED QUEST. Standing
     is what they THINK of you; this is how many times you did the thing. If they
     were the same number this whole organ would be the reputation system wearing
     a hat. */
  const L = require(path.join(ROOT, 'engine/bohemia_loop.js'));
  const Q = kind => ['@QUEST q' + kind + '  Q', '@ACT 1', '@ONCE false',
    '@STAGE 10', '@STAGE 20 COMPLETE', '@TALK t entry=stage>=10', '  @SAY x.',
    '  @OPT "do it" [gate: none] @DO faction REMNANTS ' + kind + ' @DO set_stage 20 -> END',
    '@END'].join('\n');
  const ctx = L.boot({ seed: 'bohemia' });
  function play(src) {
    const rt = ctx.quests.start(src);
    const v = rt.begin('t');
    rt.choose(v.options[0].i);
  }
  play(Q('+6'));
  const after1 = JSON.parse(JSON.stringify(ctx.save.meta.gave || {}));
  const stand1 = ctx.factions.factions.get('Remnants').standingWith('player');
  play(Q('+1'));
  const after2 = JSON.parse(JSON.stringify(ctx.save.meta.gave || {}));
  const stand2 = ctx.factions.factions.get('Remnants').standingWith('player');

  ok('C4 an authored quest that helps a faction counts as ONE thing done for them',
    (after1.Remnants | 0) === 1, JSON.stringify(after1));
  ok('C5 the count is a COUNT, not the standing number: +6 then +1 is 2 deeds, not 7',
    (after2.Remnants | 0) === 2 && stand2 === 7 && stand1 === 6,
    'gave ' + JSON.stringify(after2) + ' standing ' + stand2);

  play(Q('-9'));
  const after3 = JSON.parse(JSON.stringify(ctx.save.meta.gave || {}));
  ok('C6 hurting them is NOT a step toward belonging - that axis is standing',
    (after3.Remnants | 0) === 2 &&
    ctx.factions.factions.get('Remnants').standingWith('player') < stand2,
    JSON.stringify(after3));

  /* ---- THE PERIPHERAL ACT. A bargain you can read and cannot act on is the
     inverse of yesterday's rule: not a button that does nothing, a button that
     does not exist. Two kinds correctly have none, and both are his canon. */
  ok('C8 every kind of want that CAN be acted on has exactly one act',
    Object.keys(B.ACTS).length === 5 &&
    ['presence', 'information', 'labour', 'debt', 'legibility']
      .every(k => typeof B.ACTS[k] === 'string' && B.ACTS[k].length > 3),
    JSON.stringify(B.ACTS));
  ok('C9 you cannot press a button to be safe to be around, or to be offered nothing',
    B.actFor(B.RULES.COLORFUL, {}) === null &&
    B.actFor(B.RULES.SOCIAL_FORCES, {}) === null &&
    B.actFor(B.RULES.AMALGAMATION, {}) === null &&
    /STILL DECIDING/.test(B.noActBecause(B.RULES.COLORFUL, {})) &&
    /NO OFFER/.test(B.noActBecause(B.RULES.AMALGAMATION, {})));
  ok('C10 the act names the thing that outfit actually wants, not a generic favour',
    B.actFor(B.RULES.REMNANTS, {}).label === B.ACTS.information &&
    B.actFor(B.RULES.MOB, {}).label === B.ACTS.legibility &&
    B.actFor(B.RULES.CARTEL, {}).label === B.ACTS.debt &&
    B.ACTS.information !== B.ACTS.legibility);
  ok('C11 once a day, and the surface is told WHY there is nothing to press',
    B.actFor(B.RULES.REMNANTS, { gaveToday: true }) === null &&
    /COME BACK TOMORROW/.test(B.noActBecause(B.RULES.REMNANTS, { gaveToday: true })));
  ok('C12 somebody who runs with nobody has no act, because there is no bargain',
    B.actFor(B.DEFAULT, {}) === null && B.noActBecause(B.DEFAULT, {}) === '');

  /* ONE WRITER. The world bridge and the card both move this number, and the
     three spellings of a faction have already bitten this codebase three times.
     Both callers must land on the SAME key or the ladder splits in two. */
  const sv = { meta: {} };
  B.record(sv, 'REMNANTS', 3);
  B.record(sv, 'Remnants', 3);
  B.record(sv, 'remnants', 4);
  ok('C13 three spellings of one outfit are one count, not three',
    Object.keys(sv.meta.gave).length === 1 && B.gaveOf(sv, 'Remnants') === 3 &&
    B.gaveOf(sv, 'REMNANTS') === 3, JSON.stringify(sv.meta.gave));
  ok('C14 the day is recorded under the same single key',
    Object.keys(sv.meta.gaveDay).length === 1 && B.gaveDayOf(sv, 'REMNANTS') === 4);
  ok('C15 the world bridge writes through the same one writer the card uses',
    /belongingModule\(\)/.test(
      fs.readFileSync(path.join(ROOT, 'engine/bohemia_loop.js'), 'utf8')) &&
    /BEL\.record\(save, real, null\)/.test(
      fs.readFileSync(path.join(ROOT, 'engine/bohemia_loop.js'), 'utf8')));

  /* it has to survive a reload or the ladder resets every time he closes the app */
  const blob = L.captureSave(ctx);
  const ctx2 = L.boot({ saveText: blob });
  ok('C7 the count rides the save, so the ladder does not reset on a reload',
    ((ctx2.save.meta.gave || {}).Remnants | 0) === 2,
    JSON.stringify(ctx2.save.meta && ctx2.save.meta.gave));
}

/* ------------------------------------------------- D. IT REACHES THE PLAYER */
async function partD() {
  console.log('D. IT REACHES THE PLAYER (the built run, in a real browser)');

  const built = fs.readFileSync(RUN_FILE, 'utf8');
  const src = fs.readFileSync(RUN_SRC, 'utf8');
  ok('D0 the organ is inlined in the file the alpha actually loads',
    built.includes('bohemia_belonging.js') && built.includes('BohemiaBelonging'));
  ok('D1 the bargain owns its own node, after the card is built',
    /function showBargain\(/.test(src) && /showBargain\(host, fid\)/.test(src),
    'anything written into #idcard before cardFor() is wiped - 8/11');

  const { chromium } = requirePlaywright();
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = [];
  page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
  try {
    await page.goto('file://' + RUN_FILE);
    await page.waitForFunction(() => window.__RUN_READY === true, null, { timeout: 90000 });
    await page.evaluate(() => window.__RUN.wipeSaves());

    const out = await page.evaluate(() => {
      const a = (SIM && SIM.agents || [])[0];
      if (!a) return null;
      const orig = window.factionForPerson;
      const read = () => { const n = document.getElementById('bargain');
        return n ? n.innerText : null; };
      window.factionForPerson = function () { return 'REMNANTS'; };
      openPerson(a); const cold = read();
      if (CTX && CTX.save && CTX.save.meta) CTX.save.meta.gave = { Remnants: 4 };
      openPerson(a); const warm = read();
      window.factionForPerson = function () { return null; };
      openPerson(a); const none = read();
      window.factionForPerson = orig;
      return { cold, warm, none };
    });

    ok('D2 the real card tells you what the outfit wants and what it holds',
      !!out && /WHAT YOU KNOW/.test(out.cold) && /Ammunition/.test(out.cold),
      JSON.stringify(out && out.cold));
    ok('D3 it tells you what they pay in, in his canon\'s own currency',
      /AMMUNITION/.test(out.cold));
    ok('D4 it says how far in you are, and what would move it',
      /A STRANGER/.test(out.cold) && /1 MORE TO/.test(out.cold), out.cold);
    ok('D5 doing the thing four times really moves the rung on the real card',
      /USEFUL/.test(out.warm) && !/A STRANGER/.test(out.warm), out.warm);
    ok('D6 somebody who runs with nobody gets no bargain block at all',
      !out.none || out.none.trim() === '', JSON.stringify(out.none));
    /* THE WHOLE LOOP, THROUGH THE REAL DOM: read the bargain, press the act, watch
       the rung move, and find the button gone until tomorrow. */
    const loop = await page.evaluate(() => {
      const a = (SIM && SIM.agents || [])[0];
      const orig = window.factionForPerson;
      window.factionForPerson = function () { return 'REMNANTS'; };
      /* START FROM ZERO. D5 above deliberately plants a count of 4 to prove the
         rung moves, and the first version of this claim inherited it and then
         asserted "one act takes you from a stranger" against a tree where you
         were already USEFUL. The probe was wrong, not the code. */
      if (CTX && CTX.save && CTX.save.meta) { CTX.save.meta.gave = {}; CTX.save.meta.gaveDay = {}; }
      const rung = () => { const n = document.getElementById('bargain');
        const t = n ? n.innerText : '';
        const i = t.indexOf('YOU ARE');
        return i < 0 ? t : t.slice(i, t.indexOf('\n', t.indexOf('\n', i) + 1) + 1) || t.slice(i);
      };
      openPerson(a);
      const btn = document.getElementById('pplgive');
      const label = btn ? btn.textContent : null;
      const before = rung();
      if (btn) btn.click();
      openPerson(a);
      const after = rung();
      /* the WHOLE block too: rung() deliberately slices out just the YOU ARE
         lines, and the reason-there-is-no-button lives below them. */
      const whole = (document.getElementById('bargain') || {}).innerText || '';
      const second = document.getElementById('pplgive');
      const gave = JSON.parse(JSON.stringify((CTX.save.meta || {}).gave || {}));
      window.factionForPerson = orig;
      return { label, before, after, whole, second: !!second, gave };
    });
    ok('D8 the card offers the act this outfit actually wants',
      loop.label === B.ACTS.information, JSON.stringify(loop.label));
    ok('D9 doing it once really moves the rung on the real card',
      /A STRANGER/.test(loop.before) && /SOMEBODY WHO SHOWED UP/.test(loop.after),
      loop.before.split('\n').pop() + ' -> ' + loop.after.split('\n').pop());
    ok('D10 the count landed under ONE key, whichever spelling the card used',
      Object.keys(loop.gave).length === 1, JSON.stringify(loop.gave));
    ok('D11 the button is gone until tomorrow, and the card says so',
      loop.second === false && /COME BACK TOMORROW/.test(loop.whole),
      'button ' + loop.second + ' | ' + loop.whole.split('\n').pop());

    /* NO NEW PRICE WAS INVENTED. TIME IS SPENT BY ACTIONS (7/26) makes the
       action-cost table canon and forbids a lane writing one. The act reuses the
       HANGOUT moment he already priced at 1 hour. */
    ok('D12 the act costs an hour by REUSING his priced moment, not a new one',
      /spendTime\('HANGOUT'/.test(src) &&
      (src.match(/var MOMENTS = \[[^\]]*\]/) || [''])[0].split('name:').length - 1 === 3,
      'a new priced moment would be a lane writing the action-cost table');

    ok('D7 the run threw no errors doing any of that',
      errors.length === 0, errors.slice(0, 3).join(' | '));
  } finally { await browser.close(); }
}

/* ------------------------------------------------------------- E. THE PAGE */
function partE() {
  console.log('E. HE CAN SEE IT WITHOUT HUNTING');

  const page = fs.readFileSync(PAGE, 'utf8');
  ok('E1 the page runs the REAL organ, inlined, not a retelling',
    page.includes('function bargain(rule, given)') && page.includes('BohemiaBelonging.bargain('));
  ok('E2 it quotes both of his paragraphs on every card',
    B.keys().every(k => page.includes(B.RULES[k].want.slice(0, 60)) &&
                        page.includes(B.RULES[k].hold.slice(0, 60))));
  ok('E3 he can walk the ladder himself rather than read about it',
    page.includes("getElementById('given')") && page.includes('STEPS'));
  ok('E4 it names the research instead of asserting the shape',
    /Lave/.test(page) && /Wenger/.test(page));
  ok('E5 it asks him for nothing: no thumb controls, no verdict export',
    ![/id=["']export/i, /class=["'][^"']*thumb/i, /data-(vote|verdict|thumb)=/i]
      .some(re => re.test(page)));
  ok('E6 it surfaces his own open question rather than burying it',
    /STILL YOURS TO DECIDE/.test(page));

  const hub = fs.readFileSync(path.join(ROOT, 'slices/BOHEMIA_LIFE_CURRENT.html'), 'utf8');
  ok('E7 the LIFE tab links to it, so it is a room he can reach',
    hub.includes('BOHEMIA_WHAT_THEY_WANT_8_12_26.html'));
}

(async function main() {
  console.log('BELONGING GATE — what they want, and what it is worth\n');
  partA();
  partB();
  partC();
  await partD();
  partE();
  console.log('\nBELONGING GATE: ' + pass + ' passed, ' + fail + ' failed');
  process.exit(fail ? 1 : 0);
})().catch(e => { console.error('BELONGING GATE CRASHED: ' + (e && e.stack || e)); process.exit(1); });
