#!/usr/bin/env node
/* BOHEMIA — THE FIRST NOTICE GATE (9/21/26, WORLD lane, row [horror world])
 *
 * Holds engine/bohemia_notice.js and the page the VOTE tab opens for it.
 *
 * WHAT IT IS ACTUALLY GUARDING, and it is not prose quality:
 *
 *  A  A NOTICE WITH A HOLE IN IT IS NOT A NOTICE. The whole idea is that the
 *     FORM is immaculate while the world behind it is gone. A notice missing its
 *     cut time, its total, its dispute window or its appeal contact is not
 *     horror, it is a bug, and it looks exactly the same on a phone. So every
 *     required slot is checked, and the module's refusals are checked too: the
 *     thing must say no rather than print a plausible document.
 *
 *  B  NOT ONE NUMBER IS TYPED. This lane has shipped a hard-coded list behind a
 *     string stripper before and the check passed while the list was wrong. So
 *     this is BEHAVIOURAL, never a grep: move the ONE in his own PAYOUT table and
 *     watch the notice's arithmetic follow it. A reading gate can be fooled by a
 *     comment; a moved number cannot.
 *
 *  C  THE HORROR IS MEASURED AND CAN SHRINK. unanswered() must refuse to claim
 *     anything with no list to check against, and must report FEWER unanswered
 *     slots the moment one of the bodies exists. A count that cannot go down is
 *     an assertion wearing a number's clothes.
 *
 *  D  LANGUAGE NEVER GATES REQUIRED INFORMATION (8/25). Every issued notice
 *     carries an English issue, and every number in the Spanish issue also
 *     appears in the English one. Checked by comparing the digits, not by
 *     trusting that both were written at the same time.
 *
 *  E  THE PAGE IS NOT STALE. slices/BOHEMIA_THE_FIRST_NOTICE_9_21_26.html is
 *     generated by tools/bohemia_the_first_notice.js. This re-runs the generator
 *     into memory and fails if the file on disk is not what it produces, so the
 *     page he votes on cannot describe a module that has since changed.
 *
 *  F  IT IS REGISTERED WHERE HE VOTES (rule 15, rule 22a), and it is not in the
 *     game (rule 18): no play surface carries this module while the hold is on.
 *
 *   node gates/first_notice_gate.js
 */
'use strict';
const fs = require('fs'), path = require('path'), cp = require('child_process');
const ROOT = path.resolve(__dirname, '..');
const R = (p) => require(path.join(ROOT, p));

const N  = R('engine/bohemia_notice.js');
const PU = R('engine/bohemia_purse.js');
const G  = R('engine/BOHEMIA_faction_graph.json');

let pass = 0, fail = 0;
const ok = (n, c, note) => {
  if (c) pass++;
  else { fail++; console.log('  > FAIL ' + n + (note ? '  [' + note + ']' : '')); }
};

/* *** ONE BLOCKED MEASUREMENT COSTS ONE SECTION, NEVER THE WHOLE PAGE. ***
   Caught by mutating the module: blanking one slot made the notice refuse, which
   is correct, and then this gate THREW on the next line and the other thirty-odd
   checks never ran. A gate that dies on the first red reports a number that is
   not the truth about the build. Same shape PLUMBER's speed gate landed on. */
const section = (name, fn) => {
  try { fn(); }
  catch (e) {
    fail++;
    console.log('  > FAIL ' + name + ' could not be measured  [' + (e && e.message) + ']');
  }
};

/* the facts a notice needs, all of them, so a test can remove exactly one */
const FACTS = () => ({
  service: 'power', at: [75, 5], street: 'freeway', circuit: 24,
  holder: 'Mob', free: false, day: 1, clock: '13:57'
});

/* ---- A. THE FORM IS WHOLE, AND A HOLE IS REFUSED ------------------------- */
section('A the form is whole', () => {
  const n = N.disconnection(FACTS());
  ok('a notice with every fact issues', n.issued, n.reason || '');

  const need = N.slotsOf('disconnection').filter(s => s.need).map(s => s.key);
  const have = need.filter(k => n.slots && n.slots[k]);
  ok('every required slot is filled (' + have.length + ' of ' + need.length + ')',
     have.length === need.length,
     need.filter(k => !(n.slots && n.slots[k])).join(','));

  /* each fact removed on its own must be a refusal, never a quiet blank */
  const drops = {
    service: 'NO_ISSUER', clock: 'NO_CLOCK', circuit: 'NO_ACCOUNT', street: 'NO_ADDRESS'
  };
  Object.keys(drops).forEach(k => {
    const f = FACTS(); delete f[k];
    const r = N.disconnection(f);
    ok('drop ' + k + ' -> refused ' + drops[k], !r.issued && r.reason === drops[k],
       JSON.stringify(r.reason || 'ISSUED ANYWAY'));
  });

  ok('the total is the sum of its own lines',
     n.amounts.total === n.amounts.arrears + n.amounts.current + n.amounts.fee,
     JSON.stringify(n.amounts));

  /* and the alert's five slots, same rule */
  const A = () => ({ service: 'water', hazard: 'h', location: 'l', action: 'a',
                     day: 1, clock: '13:57', untilDays: 1 });
  const a = N.alert(A());
  ok('the alert issues with its five slots', a.issued, a.reason || '');
  ['hazard', 'location', 'action'].forEach(k => {
    const f = A(); delete f[k];
    const r = N.alert(f);
    ok('alert without ' + k + ' is refused',
       !r.issued && r.reason === 'MISSING_SLOT' && r.missing.indexOf(k) >= 0,
       JSON.stringify(r.reason || 'ISSUED ANYWAY'));
  });
  ok('the alert names all five slots and no more',
     N.slotsOf('alert').map(s => s.key).join(',') === 'source,hazard,location,action,expiry');
});

/* ---- B. NOT ONE NUMBER IS TYPED: MOVE HIS ONE AND WATCH IT FOLLOW -------- */
section('B no number is typed', () => {
  const was = PU.PAYOUT.COMPLETE.electricity;
  const before = N.disconnection(FACTS()).amounts;
  PU.PAYOUT.COMPLETE.electricity = 7;
  const after = N.disconnection(FACTS()).amounts;
  PU.PAYOUT.COMPLETE.electricity = was;
  const back = N.disconnection(FACTS()).amounts;

  ok('*** MOVE THE ONE IN HIS OWN TABLE AND THE BILL FOLLOWS IT ***',
     before.arrears === was && after.arrears === 7 && after.fee === 7 &&
     after.total === 14 && back.arrears === was,
     JSON.stringify({ before: before.total, after: after.total, back: back.total }));

  /* and with the table gone entirely it refuses rather than guessing */
  const row = PU.PAYOUT.COMPLETE;
  delete PU.PAYOUT.COMPLETE;
  const r = N.disconnection(FACTS());
  PU.PAYOUT.COMPLETE = row;
  ok('with no ruled price at all it refuses instead of inventing one',
     !r.issued && r.reason === 'NO_AMOUNT', JSON.stringify(r.reason || 'ISSUED ANYWAY'));
  ok('and it recovers the moment the table is back', N.disconnection(FACTS()).issued);
});

/* ---- C. THE HORROR IS MEASURED, AND IT CAN SHRINK ------------------------ */
section('C the horror is measured', () => {
  const n = N.disconnection(FACTS());
  const living = Object.keys(G.factions);
  ok('the valley really has ' + living.length + ' named outfits', living.length > 0);

  ok('with no list to check against it refuses to claim anybody is gone',
     N.unanswered(n, null).known === false);
  ok('and it refuses on a notice that never issued',
     N.unanswered(N.disconnection({}), living).known === false);

  const cold = N.unanswered(n, living);
  ok('every body the notice sends you to is unanswered right now (' +
     cold.unanswered + ' of ' + cold.asks + ')',
     cold.known && cold.asks > 0 && cold.unanswered === cold.asks);

  /* *** THE ANTI-ASSERTION CHECK. Hand it a world where the appeal board exists
     and the count MUST drop. A number that cannot go down is not a measurement. */
  const warm = N.unanswered(n, living.concat([N.ISSUERS.power.appeal]));
  ok('*** PUT THE APPEAL BOARD BACK IN THE WORLD AND THE COUNT DROPS ***',
     warm.unanswered === cold.unanswered - 1,
     JSON.stringify({ cold: cold.unanswered, warm: warm.unanswered }));

  const all = N.unanswered(n, living.concat([
    N.ISSUERS.power.appeal, N.ISSUERS.power.name + ' ' + N.ISSUERS.power.office]));
  ok('and with every body back nothing is unanswered', all.unanswered === 0,
     JSON.stringify(all.unanswered));

  /* not one word of the notice changed while that number moved */
  ok('the words of the notice never mention any of it',
     N.disconnection(FACTS()).en.join('\n') === n.en.join('\n') &&
     !/nobody|no one|abandoned|closed down|long gone/i.test(n.en.join(' ')));
});

/* ---- D. LANGUAGE NEVER GATES REQUIRED INFORMATION ------------------------ */
section('D language never gates', () => {
  const n = N.disconnection(FACTS());
  ok('an issued notice always carries an English issue',
     Array.isArray(n.en) && n.en.length > 0);
  ok('and a Spanish one beside it', Array.isArray(n.es) && n.es.length > 0);

  const digits = (a) => (a.join(' ').match(/\d+/g) || []).sort().join(',');
  const enD = digits(n.en), esD = digits(n.es);
  ok('every number in the Spanish issue is also in the English one',
     esD.split(',').every(d => enD.split(',').indexOf(d) >= 0),
     'en ' + enD + ' / es ' + esD);

  /* the Spanish issue must not be the only place a fact lives: the account, the
     cut day and the total all appear in English */
  const en = n.en.join(' ');
  ok('the account, the cut and the total are all in the English issue',
     en.indexOf(String(FACTS().circuit)) >= 0 &&
     en.indexOf(n.slots.cutAt) >= 0 && en.indexOf(n.slots.total) >= 0);

  /* the alert is English only by design: it is the one that must be read fast */
  ok('the alert carries required information in English', N.alert({
    service: 'water', hazard: 'h', location: 'l', action: 'a', day: 1, clock: '13:57'
  }).en.length > 0);
});

/* ---- E. THE PAGE HE VOTES ON IS NOT STALE -------------------------------- */
section('E the page is not stale', () => {
  const page = path.join(ROOT, 'slices/BOHEMIA_THE_FIRST_NOTICE_9_21_26.html');
  ok('the page exists', fs.existsSync(page));
  if (fs.existsSync(page)) {
    const before = fs.readFileSync(page, 'utf8');
    let ran = true;
    try { cp.execFileSync(process.execPath,
      [path.join(ROOT, 'tools/bohemia_the_first_notice.js')], { cwd: ROOT, stdio: 'pipe' }); }
    catch (e) { ran = false; }
    ok('the generator runs', ran);
    const after = fs.readFileSync(page, 'utf8');
    ok('*** THE PAGE ON DISK IS WHAT THE MODULE SAYS TODAY ***', before === after,
       'regenerating it changed ' + Math.abs(after.length - before.length) + ' bytes');
    ok('and the page carries the notice, not a description of one',
       after.indexOf('NOTICE OF DISCONNECTION') > 0 && after.indexOf('AVISO DE CORTE') > 0 &&
       after.indexOf('EMERGENCY NOTIFICATION') > 0);
    /* A CAP IS NOT A FIXED WIDTH, and the first cut of this check could not tell
       them apart: it read the page's own `max-width:720px` as a 720px element and
       called a phone-shaped page too wide. Only a plain `width:` is a demand. */
    const demands = (after.match(/(^|[^-])\bwidth:\s*(\d+)px/g) || [])
      .map(s => parseInt(s.match(/(\d+)px/)[1], 10));
    ok('it reads on a phone: nothing demands more than 390px of glass',
       demands.every(w => w <= 390), demands.join(','));
  }
});

/* ---- F. REGISTERED WHERE HE VOTES, AND NOT IN THE GAME (rule 18) --------- */
section('F registered and not in the game', () => {
  const reg = R('records/target/BOHEMIA_VOTE_REGISTRY.json');
  const mine = reg.items.filter(i => i.lane === 'world');
  ok('this lane has candidates in the one registry (' + mine.length + ')', mine.length >= 1);
  ok('and each one points at a page that exists',
     mine.every(i => i.show && i.show.how === 'page' &&
       fs.existsSync(path.join(ROOT, 'slices', i.show.src))),
     mine.map(i => i.show && i.show.src).join(','));
  ok('no id of this lane has already been judged',
     mine.every(i => !(reg.verdicts || []).some(v => v.id === i.id)));

  /* RULE 18: the hold is on the play surface. The notice may not be wired into
     anything he plays until the coordinator says the cut holds. */
  const surfaces = ['slices/BOHEMIA_CITY_WORLD.html', 'slices/BOHEMIA_ALPHA_0_9.html',
                    'slices/BOHEMIA_DEMO.html'];
  surfaces.forEach(s => {
    const p = path.join(ROOT, s);
    if (!fs.existsSync(p)) return;
    ok('rule 18: ' + path.basename(s) + ' does not carry this module yet',
       fs.readFileSync(p, 'utf8').indexOf('BohemiaNotice') < 0);
  });

  /* every sentence it makes is an attempt, never a ruling (8/11) */
  ok('everything it makes is tagged draft', N.draft === true &&
     N.disconnection(FACTS()).draft === true &&
     N.alert({ service: 'water', hazard: 'h', location: 'l', action: 'a',
               day: 1, clock: '13:57' }).draft === true);

  /* RULE 20(b) AND THE REFERENCE LAW. The first cut of this check failed on the
     module's OWN SENTENCE saying it cites nothing, because it grepped for the word
     "series". A ruler that cannot tell a citation from a disclaimer measures
     nothing. So it checks for an actual citation instead: a link out, or one of
     the reference games Paolo HAS named, every one of which belongs to another
     department and none of which may be cited here. */
  const src = fs.readFileSync(path.join(ROOT, 'engine/bohemia_notice.js'), 'utf8');
  ok('it links out to nothing', !/https?:\/\//i.test(src));
  ok('rule 20b and the reference law: it cites no game, his or otherwise',
     !/(final fantasy|battle brothers|rogue fable|fallout|pocket city)/i.test(src));
});

console.log('FIRST NOTICE GATE: ' + pass + ' passed, ' + fail + ' failed'
  + '  (the form is whole or it is refused, every number comes off his own table,'
  + ' the count of who is left can go down, and the page he votes on is live)');
process.exit(fail ? 1 : 0);
