#!/usr/bin/env node
/* MANDATE FACE GATE (8/15/26, WORLD lane) — HE CAN SEE THE RUNG, ON THE PAGE HE WALKS.
 *
 * HE MUST BE ABLE TO DIRECT IT, NOT JUST WATCH IT (Paolo 8/12, LOCKED). The ladder he
 * locked on 6/30 shipped as a module and computed perfectly where nobody could reach it,
 * which is the exact failure that cost him the quests: "I CANT DIRECT QUESTS OR CUTSCENES
 * RN." A rung that exists only in engine/ is a rung he meets nowhere and can correct never.
 *
 * SO THIS GATE RUNS THE REAL PAGE IN A REAL BROWSER, taps the button a player taps, and
 * reads the card a player reads. Not the module. The module already has its own gate, and
 * every finding in it was green while the card was invisible.
 *
 * AND IT DRIVES THE LADDER RATHER THAN PHOTOGRAPHING IT. Opening the card and finding words
 * in it proves nothing: the first version of this face read a `QS` global that DOES NOT
 * EXIST on that page, failed silently into an empty object behind a try/catch, and would
 * have shown "0 of 16" forever while looking perfectly healthy. A screenshot would have
 * passed it. So the gate warms factions through the ledger the quest verb actually writes,
 * and requires the number and the rung to MOVE:
 *
 *      0 of 16 -> TERRITORY        nobody is with you yet
 *      7 of 16 -> TERRITORY        close, and still not backed
 *      8 of 16 -> MANDATE          his ~49% crossed, on the surface
 *      turn one -> TERRITORY       and losing favour knocks you straight back down
 *
 * That last line is the one worth having. The rung is DERIVED, never stored, and this is
 * that design being true where he can see it rather than in a unit test.
 *
 * IT ALSO HOLDS THE REFUSALS, because a UI is the easiest place to smuggle in canon nobody
 * ruled. The card must NOT name a faction as owning the ground it is standing on (MAP LAW,
 * and who holds which district is his), and it must NOT put a number on the top rung.
 *
 *   node gates/mandate_face_gate.js
 */
'use strict';
const { settle: SETTLE } = require(__dirname + '/bohemia_settle.js');
const fs = require('fs');
const path = require('path');
const ROOT = path.dirname(__dirname);
process.chdir(ROOT);

const PAGE = 'slices/BOHEMIA_CITY_WORLD.html';
let pass = 0, fail = 0;
const ok = (n, c) => { c ? pass++ : (fail++, console.log('  FAIL: ' + n)); };

function requirePlaywright() {
  const globals = ['/opt/node22/lib/node_modules', '/usr/lib/node_modules',
                   '/usr/local/lib/node_modules'];
  for (const g of globals) { try { return require(path.join(g, 'playwright')); } catch (_e) {} }
  return require('playwright');
}

/* ---- the static half: the tool is the source, not the page -------------------------- */
const TOOL = fs.readFileSync('tools/bohemia_city_mandate_patch.py', 'utf8');
const src = fs.readFileSync(PAGE, 'utf8');

ok('the face is generated by a re-runnable tool, so it survives a rebase instead of being ' +
   'hand-edited into a page four lanes are writing to',
   /MARK = '(.*)'/.test(TOOL) && /ENDMARK = '(.*)'/.test(TOOL));
{
  const mark = (TOOL.match(/^MARK = '(.*)'/m) || [, ''])[1];
  const end = (TOOL.match(/^ENDMARK = '(.*)'/m) || [, ''])[1];
  ok('and its block is on the page exactly once, delimited, so it can be refreshed and ' +
     'never orphaned the way the payday block was',
     src.split(mark).length === 2 && src.split(end).length === 2);
}
ok('the roster is READ off his belonging registry, never typed into the UI -- a hand-typed ' +
   'faction list goes stale the day he adds one',
   /BohemiaBelonging[\s\S]{0,40}RULES/.test(TOOL) &&
   !/\['REMNANTS'|"REMNANTS"\s*,/.test(TOOL));

(async () => {
  let browser;
  try {
    const { chromium } = requirePlaywright();
    browser = await chromium.launch();
    const p = await browser.newPage();
    const errs = [];
    p.on('pageerror', e => errs.push(String(e)));
    await p.goto('file://' + path.join(ROOT, PAGE));
    await SETTLE(p, 3000);

    ok('the STANDING button is really there on the walked page', await p.locator('#rungbtn').count() === 1);

    /* Read the card the way a player does: close whatever card the day opened with, tap,
       read. cardHide is the page's own function, so this uses its real machinery. */
    const read = async () => {
      await p.evaluate(() => { try { cardHide(); } catch (e) {} });
      await p.evaluate(() => document.getElementById('rungbtn').click());
      await SETTLE(p, 150);
      return p.locator('#daycardIn').innerText();
    };
    /* Warm factions through DQ.shared.faction, which is where Runtime._remember puts what
       `@DO faction NAME +n` writes -- the CROSS-QUEST ledger, not a quest's own copy. The
       distinction is the 8/12 fix: a quest's state dies with the quest, and standing read
       from there would evaporate every morning. */
    const warm = (names, v) => p.evaluate(([ns, val]) => {
      DQ.shared.faction = DQ.shared.faction || {};
      ns.forEach(n => { DQ.shared.faction[n] = val; });
    }, [names, v]);

    const day1 = await read();
    ok('day one it says nobody is with you yet, out of his sixteen',
       /0 of 16 factions with you/.test(day1));
    ok('and day one you are on TERRITORY', /TERRITORY/.test(day1));
    ok('it tells you how many it takes, and that is his 49% of his 16 rather than a number ' +
       'anybody picked', /8 of 16/.test(day1));

    await warm(['TRADES', 'CHURCH', 'CARAVANS', 'VOLUNTEERS', 'REDS', 'HOMELESS', 'MOB'], 5);
    const seven = await read();
    ok('warm seven and the CARD MOVES -- proof it is reading the real ledger and not ' +
       'painting a constant', /7 of 16 factions with you/.test(seven));
    ok('and seven is still not backed, because close does not count',
       /TERRITORY/.test(seven) && !/MANDATE/.test(seven));

    await warm(['BLUES'], 2);
    const eight = await read();
    ok('THE EIGHTH FACTION FLIPS THE RUNG ON THE SURFACE HE TAPS: the city backs you',
       /MANDATE/.test(eight) && /8 of 16/.test(eight));
    ok('and the card says what that BUYS, in plain words, because a rung nobody can read is ' +
       'a badge', /can build in a district whose local faction does not love you/i.test(eight));

    await warm(['MOB'], -3);
    const lost = await read();
    ok('LOSE ONE AND YOU ARE KNOCKED STRAIGHT BACK DOWN, visibly -- the rung is derived, ' +
       'never stored, and this is that design being true where he can see it',
       /TERRITORY/.test(lost) && /7 of 16/.test(lost));

    /* ---- the refusals, which a UI is the easiest place to break -------------------- */
    ok('the card does NOT name a faction as holding the ground you stand on -- who owns ' +
       'which district is his canon and MAP LAW says Claude never designs the map',
       /Nobody holds this ground yet/.test(day1) && /yours to set/.test(day1));
    ok('and it puts NO number on the top rung, because "enough done, enough love" is not a ' +
       'share and guessing one off the 49% would be canon nobody ruled',
       /top rung has no number/.test(day1) && !/MAYOR\b[\s\S]{0,40}\d+ of \d+/.test(day1));

    ok('and the page throws nothing while all of that happens',
       errs.length === 0 || (console.log('  (errors: ' + errs.slice(0, 2).join(' | ') + ')'), false));
  } catch (e) {
    fail++;
    console.log('  FAIL: the gate could not drive the real page -- ' + e.message);
  } finally {
    if (browser) await browser.close();
  }

  console.log('MANDATE FACE GATE: ' + pass + ' passed, ' + fail + ' failed  (the rung is on ' +
              'the page he walks, it MOVES when factions warm and demotes when one turns, ' +
              'and it refuses to name a district owner or a number for the top rung)');
  process.exit(fail ? 1 : 0);
})();
