/* BOHEMIA QUEST PLACEMENT — the CANDIDATE FACTORY for "where does this quest happen".
   (7/26/26, WORLD lane, backlog WORLD-1: "Quest NPC placement CANDIDATES for the 9
   live quests: propose per-quest placements with reasons ... never place canon
   yourself".)

   ---------------------------------------------------------------------------
   MAP LAW HELD, EXPLICITLY. Claude never designs map layouts. NOTHING in this file
   invents geography, moves a district, or declares where a quest lives. It reads
   three things that ALREADY EXIST and reports the overlap:
     1. the quest's OWN prose (@LOG / @SAY / @OBJ / @OPT lines it already ships with),
     2. each district's OWN dossier (records/tilespec/BOHEMIA_TILESPEC_*.md — the
        district module's own NOTES + LEGEND, generated by tools/bohemia_tilespec.js),
     3. the ALREADY-GENERATED valley (bohemia_world.js cells + who really owns them).
   The output is a ranked list of CANDIDATES with plain-English reasons for Paolo to
   pick from. Applying a pick is his verdict, never this module's.
   ---------------------------------------------------------------------------

   WHY IT EXISTS. The casting bridge (bohemia_loop.js castTarget) already answers
   "somewhere real" — it drops a quest on the base district of the faction its own
   @ROLE demands. That is correct plumbing and it stays the ANCHOR here. But faction
   bases are an even stride across the district list, and the valley is 70% suburb,
   so today all nine canon quests happen in a generic suburb tract: the flood-tunnel
   quest, the power-skim quest and the smuggling quest all read as the same street.
   This factory surfaces, per quest, the districts whose OWN dossier vocabulary the
   quest's OWN words already match — so Paolo can judge "put the deep-water quest in
   the wash" in one look instead of typing coordinates.

   FACTORY LAW: typed spec (CANDIDATE below) -> generator (candidates()) -> batch
   output (all quests at once) -> kill/approve pipeline (the judge page's PICK /
   NONE OF THESE + .txt export) -> its own regression gate (gates/quest_placement_gate.js).

   DETERMINISTIC: no RNG, no Date, no Math.random. Same seed + same quest + same
   dossiers => byte-identical candidates, forever. Ties break on distance then on
   the district id string, never on iteration order.

   TYPED SPEC — a CANDIDATE is exactly:
     { strategy : 'anchor' | 'setting' | 'nearby'   // how it was derived
     , x, y     : overmap cell coords (ints)
     , id       : 'x,y' district id, as worldMap uses
     , kind     : the district type already generated at that cell
     , owner    : faction id that really holds that cell, or null
     , demanded : the faction the quest's own REQ role demands, or null
     , channel  : 'feed' | 'inperson' (carried from the anchor; the engine's rule)
     , fit      : setting-fit score for that district kind (0 when not setting-driven)
     , terms    : the quest's own words that matched that district's dossier
     , dist     : chebyshev cells from the anchor
     , reasons  : [plain-English strings, no jargon — this is what Paolo reads]
     }

   Runs in node and in the browser (no deps). */
(function (root) {
  'use strict';

  /* ---------- vocabulary ----------------------------------------------------
     STOP: ordinary English glue + the words every dossier shares by construction
     (they are all generated from one template, so 'district', 'tile', 'layer',
     'material' carry zero signal). FORMAT: the .bq format's own keywords, which
     would otherwise make every quest look identical to every other quest. */
  var STOP = ('the and that with this from they have been what when where which will your them then than into over under most '
    + 'very much some just also each only other more like about after before through being were area cell tile tiles code color '
    + 'kind layer solid enter material name district districts real world reference layout circulation layering decisions rulings '
    + 'legend colors thing things every never always still keep make made take does dont cant wont there their here comes come '
    + 'goes went said says tell told know knew back down out up off one two three four five').split(' ');
  var FORMAT = ('quest act faction once role req opt stage log obj talk say end lock noverb gate silence trap complete fail clout '
    + 'quiet notable risky reckless speaker entry show_objective complete_objective learn flag bond posture faction_posture '
    + 'advance_territory knows target true false none').split(' ');

  var STOPSET = {}, FMTSET = {};
  STOP.forEach(function (w) { STOPSET[w] = 1; });
  FORMAT.forEach(function (w) { FMTSET[w] = 1; });

  function tokenize(text) {
    var m = String(text).toLowerCase().match(/[a-z][a-z\-]{3,}/g) || [];
    var out = [];
    for (var i = 0; i < m.length; i++) {
      var w = m[i];
      if (STOPSET[w] || FMTSET[w]) continue;
      out.push(w);
    }
    return out;
  }

  /* The HUMAN half of a .bq: the lines a player actually reads or hears, plus the
     author's own header comments. Directive names, role conditions and @DO effects
     are deliberately excluded — they are machinery, not setting. */
  function questProse(bqText) {
    var out = [], lines = String(bqText).replace(/\r\n/g, '\n').split('\n'), m;
    for (var i = 0; i < lines.length; i++) {
      var s = lines[i].trim();
      if ((m = /^@(?:LOG|SAY)\s+(.*)$/.exec(s))) out.push(m[1].replace(/#\w+/g, ''));
      else if ((m = /^@OBJ\s+\d+\s+"([^"]*)"/.exec(s))) out.push(m[1]);
      else if ((m = /^@OPT\s+"([^"]*)"/.exec(s))) out.push(m[1]);
      else if ((m = /^@OPT\s+\(([^)]*)\)/.exec(s))) out.push(m[1]);
      else if ((m = /^@NOVERB\s+"?(.*?)"?$/.exec(s))) out.push(m[1]);
      else if ((m = /^@QUEST\s+\S+\s+(.*)$/.exec(s))) out.push(m[1]);
      else if (s.charAt(0) === '#') out.push(s.replace(/^#+/, ''));
    }
    return out.join(' ');
  }

  /* dossiers: { districtKind: dossierText }. Returns the corpus stats the fit
     score reads. Pure; the caller decides how the texts were loaded (node reads
     records/tilespec/, the judge page carries them baked). */
  function buildVocab(dossiers) {
    var kinds = Object.keys(dossiers).sort();
    var tf = {}, len = {}, df = {};
    kinds.forEach(function (k) {
      var t = {}, n = 0;
      tokenize(dossiers[k]).forEach(function (w) { t[w] = (t[w] || 0) + 1; n++; });
      tf[k] = t; len[k] = n;
      Object.keys(t).forEach(function (w) { df[w] = (df[w] || 0) + 1; });
    });
    return { kinds: kinds, tf: tf, len: len, df: df, n: kinds.length };
  }

  /* SETTING FIT — how much a quest's own words are THIS district's own words.
     Classic tf-idf cosine-ish overlap: a word that shows up in every dossier
     (idf ~ 0) proves nothing; a word only the wash dossier uses ('tunnel',
     'channel') is the whole signal. Length-normalized so a long dossier cannot
     win by being wordy. Returns every kind, best first. */
  function settingFit(vocab, prose) {
    var qtf = {};
    tokenize(prose).forEach(function (w) { qtf[w] = (qtf[w] || 0) + 1; });
    var words = Object.keys(qtf).sort();
    /* COMMON-WORD FLOOR: a word carried by 40%+ of the dossiers describes the
       valley, not a district ('people', 'block', 'door', 'line'). It cannot
       distinguish anything, so it is not evidence and is dropped outright — not
       merely down-weighted, or thirty weak words outvote one real one. */
    var maxDf = Math.floor(vocab.n * 0.4);
    var out = vocab.kinds.map(function (k) {
      var score = 0, hits = [];
      for (var i = 0; i < words.length; i++) {
        var w = words[i], d = vocab.tf[k][w];
        if (!d) continue;
        if ((vocab.df[w] || 0) > maxDf) continue;
        /* idf SQUARED, deliberately. Plain tf-idf let a pile of merely-uncommon
           words ("people", "against", "whole") outscore the one word that names
           the place ("tunnel", "church", "cable"). Squaring makes the rare word
           the evidence and the common word a rounding error — which is what a
           human means by "this quest is obviously about the wash". */
        var idf = Math.log((vocab.n + 1) / ((vocab.df[w] || 0) + 1));
        var v = idf * idf * Math.min(1 + Math.log(qtf[w]), 3) * Math.min(1 + Math.log(d), 3);
        if (v <= 0) continue;
        score += v; hits.push({ w: w, v: v });
      }
      score = vocab.len[k] ? score / Math.sqrt(vocab.len[k]) : 0;
      hits.sort(function (a, b) { return b.v - a.v || (a.w < b.w ? -1 : 1); });
      return { kind: k, score: score, terms: hits.slice(0, 6).map(function (h) { return h.w; }) };
    });
    out.sort(function (a, b) { return b.score - a.score || (a.kind < b.kind ? -1 : 1); });
    return out;
  }

  function cheb(ax, ay, bx, by) { return Math.max(Math.abs(ax - bx), Math.abs(ay - by)); }

  /* The nearest already-generated cell of `kind` to the anchor, skipping cells
     another quest already claimed. Deterministic: distance, then id string. */
  function nearestOfKind(districts, kind, ax, ay, taken) {
    var best = null;
    for (var i = 0; i < districts.length; i++) {
      var d = districts[i];
      if (d.kind !== kind) continue;
      if (taken && taken[d.id]) continue;
      var dist = cheb(ax, ay, d.pos[0], d.pos[1]);
      if (!best || dist < best.dist || (dist === best.dist && d.id < best.d.id)) best = { d: d, dist: dist };
    }
    return best;
  }

  function pretty(kind) { return String(kind).replace(/_/g, ' '); }
  function list(words) {
    if (!words.length) return '';
    if (words.length === 1) return '"' + words[0] + '"';
    return words.slice(0, -1).map(function (w) { return '"' + w + '"'; }).join(', ')
      + ' and "' + words[words.length - 1] + '"';
  }

  /* ---------- THE GENERATOR --------------------------------------------------
     opts:
       worldMap  — ctx.worldMap (districts[] of {id,pos,kind}) — the REAL valley
       owner     — function(districtId) -> faction id or null (ctx.factions.owner)
       anchor    — ctx.quests.castTarget(Q): where the ENGINE puts it today. Passed
                   IN, never re-derived, so this can never drift from the shipped rule.
       vocab     — buildVocab(dossiers)
       questText — the raw .bq
       demanded  — the faction id the quest's REQ role demands (anchor.faction)
       taken     — { districtId: true } cells earlier quests already claimed
       radius    — 'nearby' search radius in cells (default 10)
     Returns [CANDIDATE, ...], anchor always first. */
  function candidates(opts) {
    var worldMap = opts.worldMap, anchor = opts.anchor, vocab = opts.vocab;
    if (!worldMap || !worldMap.districts || !worldMap.districts.length || !anchor) return [];
    var districts = worldMap.districts;
    var ownerOf = opts.owner || function () { return null; };
    var taken = opts.taken || {};
    var radius = opts.radius == null ? 10 : opts.radius;
    var demanded = opts.demanded || anchor.faction || null;

    var byId = {};
    districts.forEach(function (d) { byId[d.id] = d; });

    var fits = settingFit(vocab, questProse(opts.questText));
    var fitOf = {};
    fits.forEach(function (f) { fitOf[f.kind] = f; });

    var out = [];
    function push(strategy, d, fit, dist, reasons) {
      out.push({
        strategy: strategy, x: d.pos[0], y: d.pos[1], id: d.id, kind: d.kind,
        owner: ownerOf(d.id) || null, demanded: demanded || null,
        channel: anchor.channel || 'feed',
        fit: fit ? Math.round(fit.score * 1000) / 1000 : 0,
        terms: fit ? fit.terms.slice(0, 4) : [],
        dist: dist, reasons: reasons
      });
    }

    // ---- A. THE ANCHOR: exactly where the shipped engine casts it today.
    var aId = anchor.x + ',' + anchor.y;
    var aD = byId[aId] || { id: aId, pos: [anchor.x, anchor.y], kind: (anchor.kind || 'unknown') };
    var aReasons = [
      'WHERE IT IS NOW. The engine already casts this quest here, so this is the '
        + 'live build you are comparing against.',
      demanded
        ? ('This is the ' + demanded + ' base tile, and the quest\'s own required role asks for '
           + demanded + ', so the faction really holds this ground.')
        : ('The quest names no faction, so the engine picks a real district by the quest\'s own id.'),
      'The setting is a ' + pretty(aD.kind) + ' cell at ' + anchor.x + ',' + anchor.y + '.'
    ];
    var aFit = fitOf[aD.kind] || null;
    if (aFit) aReasons.push('Its words match ' + pretty(aD.kind) + ' at a fit of '
      + (Math.round(aFit.score * 100) / 100) + ' (the best-fitting district in the valley scores '
      + (Math.round(fits[0].score * 100) / 100) + ').');
    push('anchor', aD, aFit, 0, aReasons);
    var claimed = {}; claimed[aId] = true;

    // ---- B. BEST SETTING: the district whose OWN dossier owns the quest's OWN words.
    //         Skips the anchor's own kind (never show Paolo the same idea twice) and
    //         any cell another quest already proposed (no two errands on one tile).
    function ownerLine(id) {
      var o = ownerOf(id);
      if (o) return 'That ground is held by ' + o + '.';
      return demanded
        ? ('Nobody holds that ground yet, so putting ' + demanded + ' business there is a claim, '
           + 'not a home game.')
        : 'Nobody holds that ground yet.';
    }

    var yielded = [];   // kinds already handed to another quest this batch
    function firstAvailable(skipKinds, maxDist) {
      for (var i = 0; i < fits.length; i++) {
        var f = fits[i];
        if (f.kind === aD.kind || skipKinds[f.kind]) continue;
        var all = nearestOfKind(districts, f.kind, anchor.x, anchor.y, null);
        if (!all) continue;                       // the valley has no cell of this kind at all
        var free = nearestOfKind(districts, f.kind, anchor.x, anchor.y, mergeTaken(taken, claimed));
        if (!free) { yielded.push(f.kind); continue; }   // every one is spoken for
        if (maxDist != null && free.dist > maxDist) continue;
        return { f: f, near: free };
      }
      return null;
    }

    var skip = {};
    var best = firstAvailable(skip, null);
    if (best) {
      skip[best.f.kind] = true;
      claimed[best.near.d.id] = true;
      var bReasons = [
        /* NO EM DASHES IN ANYTHING PAOLO READS (taste canon). Code comments are code;
           this string is UI copy. */
        'BEST SETTING MATCH. The quest\'s own lines use ' + list(best.f.terms) + ', and those '
          + 'are ' + pretty(best.f.kind) + ' words, straight out of that district\'s own dossier.',
        'It is the nearest ' + pretty(best.f.kind) + ' cell to where the quest sits now: '
          + best.near.dist + ' cells away, at ' + best.near.d.pos[0] + ',' + best.near.d.pos[1] + '.',
        ownerLine(best.near.d.id)
      ];
      if (yielded.length) bReasons.push('A closer fit (' + pretty(yielded[0])
        + ') exists but every cell of it is already proposed for another quest, so this one '
        + 'stepped down rather than stack two errands on one tile.');
      push('setting', best.near.d, best.f, best.near.dist, bReasons);
    }

    // ---- C. SHORT WALK: the best-fitting DIFFERENT setting still close to the faction
    //         the quest itself demands. Falls back to the runner-up anywhere.
    var near2 = firstAvailable(skip, radius);
    if (near2) {
      claimed[near2.near.d.id] = true;
      push('nearby', near2.near.d, near2.f, near2.near.dist, [
        'SHORT WALK. The best-fitting setting within ' + radius + ' cells of where the quest '
          + 'sits now, so the errand stays in the neighbourhood.',
        'A ' + pretty(near2.f.kind) + ' cell ' + near2.near.dist + ' cells out at '
          + near2.near.d.pos[0] + ',' + near2.near.d.pos[1] + ', matching on '
          + list(near2.f.terms) + '.',
        ownerLine(near2.near.d.id)
      ]);
    } else {
      var alt = firstAvailable(skip, null);
      if (alt) {
        claimed[alt.near.d.id] = true;
        push('nearby', alt.near.d, alt.f, alt.near.dist, [
          'RUNNER-UP SETTING. Nothing else that fits sits within ' + radius + ' cells, so this is '
            + 'the second-best match in the whole valley instead.',
          'A ' + pretty(alt.f.kind) + ' cell ' + alt.near.dist + ' cells out at '
            + alt.near.d.pos[0] + ',' + alt.near.d.pos[1] + ', matching on ' + list(alt.f.terms) + '.',
          ownerLine(alt.near.d.id)
        ]);
      }
    }

    return out;
  }

  function mergeTaken(a, b) {
    var out = {}, k;
    for (k in a) if (a[k]) out[k] = true;
    for (k in b) if (b[k]) out[k] = true;
    return out;
  }

  /* BATCH: every quest at once, with a shared `taken` set so two quests never
     propose the same cell (a valley where three errands stack on one tile reads
     as one errand).

     STRONGEST CLAIM FIRST. Some settings are scarce — the valley holds exactly one
     truckstop. Processing in file order would hand it to whichever quest sorts
     first alphabetically; instead quests are processed in order of how strongly
     their own words claim a setting, so the toll-road quest gets the truck stop and
     the busker quest steps down to its next match. Deterministic: score desc, then
     filename. Output is returned in file order regardless. */
  function batch(opts) {
    var taken = {}, out = [];
    var files = Object.keys(opts.quests).sort();
    var strength = {};
    files.forEach(function (file) {
      var q = opts.quests[file];
      var fits = settingFit(opts.vocab, questProse(q.text));
      var anchorKind = q.anchor ? q.anchor.kind : null;
      var top = 0;
      for (var i = 0; i < fits.length; i++) {
        if (fits[i].kind === anchorKind) continue;
        top = fits[i].score; break;
      }
      strength[file] = top;
    });
    var order = files.slice().sort(function (a, b) {
      return strength[b] - strength[a] || (a < b ? -1 : 1);
    });
    order.forEach(function (file) {
      var q = opts.quests[file];
      var cands = candidates({
        worldMap: opts.worldMap, owner: opts.owner, vocab: opts.vocab,
        anchor: q.anchor, questText: q.text, demanded: q.anchor ? q.anchor.faction : null,
        taken: taken, radius: opts.radius
      });
      cands.forEach(function (c) { if (c.strategy !== 'anchor') taken[c.id] = true; });
      out.push({ file: file, questId: q.id, title: q.title, candidates: cands });
    });
    out.sort(function (a, b) { return a.file < b.file ? -1 : a.file > b.file ? 1 : 0; });
    return out;
  }

  var API = { VERSION: '7/26/26', tokenize: tokenize, questProse: questProse,
              buildVocab: buildVocab, settingFit: settingFit, candidates: candidates,
              batch: batch, nearestOfKind: nearestOfKind };

  if (typeof module !== 'undefined' && module.exports) module.exports = API;
  else root.BohemiaQuestPlacement = API;
})(typeof globalThis !== 'undefined' ? globalThis : this);
