// BOHEMIA BETWEEN -- WHAT THE OUTFITS ARE TO EACH OTHER.
//
// GENERATED by tools/bohemia_between.py. EDIT THE TOOL, NEVER THIS FILE.
//
// This module is not about the player. It is the shape of the valley: which
// outfits are at war, which tax which, which run close enough that helping one
// is nearly helping the other. Everything the player does gets bent by it.
//
// PAOLO 8/26: "custom is your own personal faction!!!!!! ... the values arent
// just for you its for how your factions treated ... But, yeah, for the other
// factions." The second half is this file. The other outfits have positions on
// each other that have nothing to do with you, and those positions are the
// reason the same act costs different amounts to different ears.
//
// NOTHING HERE IS INVENTED. Every pair below is copied out of
// engine/BOHEMIA_faction_graph.json, whose own _meta reads "relations are
// directional labels the engine reads for spillover, war state, and AI. All
// canon; nothing invented." Every number below is parsed out of
// engine/bohemia_engine.js FactionCanon.REL_SPEC at build time. Neither was
// typed by hand here, so neither can drift from its source.
//
// THE HOLE IT FILLS, MEASURED: bohemia_commitment.costs() charged every outfit
// that heard about your commitment the identical amount --
//     var lose = stateIndex(state);   // one number, for everybody
// -- so the Remnants, who are at PERMANENT WAR with the Cartel in canon, and
// the Church, who have no canon position on the Cartel at all, both took the
// same thing off you for siding with the Cartel. The game held a canon war and
// the cost engine could not feel it.
//
// IT DOES NOT BYPASS WORD TRAVELS. An outfit at war with the people you just
// sided with still has to FIND OUT. whoHears decides whether it lands; this
// decides how hard. Two organs, composed, each still doing its own job.
(function(root){
  var HASREQ=(typeof module!=='undefined'&&module.exports&&typeof require!=='undefined');

  /* THE CANON PAIRS. 9 directed edges, straight from the graph. */
  var PAIRS = [
  {
    "from": "Caravans",
    "to": "Cartel",
    "label": "preyed-taxed",
    "init": -45
  },
  {
    "from": "Cartel",
    "to": "Caravans",
    "label": "prey-tax",
    "init": -45
  },
  {
    "from": "Cartel",
    "to": "Remnants",
    "label": "permanent-war",
    "init": -80
  },
  {
    "from": "Cartel",
    "to": "Volunteers",
    "label": "hands-off",
    "init": 0
  },
  {
    "from": "Mob",
    "to": "Remnants",
    "label": "professional-respect",
    "init": 20
  },
  {
    "from": "Network",
    "to": "Reds",
    "label": "adjacent",
    "init": 35
  },
  {
    "from": "Reds",
    "to": "Network",
    "label": "adjacent",
    "init": 35
  },
  {
    "from": "Remnants",
    "to": "Cartel",
    "label": "permanent-war",
    "init": -80
  },
  {
    "from": "Remnants",
    "to": "Mob",
    "label": "professional-respect",
    "init": 20
  }
];

  /* THE NUMBERS, PARSED FROM FactionCanon.REL_SPEC. 6 labels.
     `init` is the canon standing on the -100..100 scale that
     engine/bohemia_factions.js uses. Its SIGN is the position and its
     MAGNITUDE is the weight; both are readings of this table, never a second
     table. */
  var SPEC = {
  "adjacent": {
    "init": 35,
    "max": 100,
    "min": -100
  },
  "hands-off": {
    "init": 0,
    "max": 100,
    "min": -20,
    "protects": "target"
  },
  "permanent-war": {
    "init": -80,
    "locked": "war",
    "max": -40,
    "min": -100
  },
  "prey-tax": {
    "init": -45,
    "max": 0,
    "min": -100
  },
  "preyed-taxed": {
    "init": -45,
    "max": 0,
    "min": -100
  },
  "professional-respect": {
    "init": 20,
    "max": 100,
    "min": -10
  }
};

  /* THE PLAIN ENGLISH. draft:true on every one -- ALWAYS MAKE AN ATTEMPT
     (Paolo 8/11): these ship written and playable and he edits them later in
     the WORDS tab. They describe a position canon already took. */
  var WORDS = {
  "adjacent": {
    "draft": true,
    "they": "Different names, near enough the same argument. They do not love each other. They are not going to move against each other either.",
    "word": "THEY RUN CLOSE",
    "you": "You helped somebody they already work beside. It costs you less with them, and it may cost you nothing at all."
  },
  "hands-off": {
    "draft": true,
    "they": "Everybody has agreed, without ever agreeing, not to touch them. It is the one line the valley keeps.",
    "word": "THEY LEAVE THEM ALONE",
    "you": "Nobody is going to hold this against you. There is no side to be on here."
  },
  "permanent-war": {
    "draft": true,
    "they": "They are at war with them. Not a feud, not a bad season. It has been going long enough that nobody alive is trying to finish it, only to survive it.",
    "word": "AT WAR, AND IT DOES NOT END",
    "you": "You just picked the people they bury. Whatever you were worth to them, halve it and then some."
  },
  "prey-tax": {
    "draft": true,
    "they": "They take a cut off them and call it protection. It is not war because war would be expensive, and this pays.",
    "word": "THEY TAX THEM",
    "you": "You helped their livestock. They do not hate you for it. They do lower what you are worth."
  },
  "preyed-taxed": {
    "draft": true,
    "they": "They pay, every time, and there is nothing at the far end of refusing that they have ever come back from.",
    "word": "THEY GET TAXED BY THEM",
    "you": "You helped the people who bleed them. They will not forget which side of that you stood on."
  },
  "professional-respect": {
    "draft": true,
    "they": "Two outfits that know exactly what the other one is, and have both decided that is worth more standing than fighting.",
    "word": "THEY RESPECT THEM",
    "you": "They understand why you did it. That is not approval. It is the reason they are not charging you full price."
  }
};

  /* YOUR OUTFIT. Read from the graph note "Player faction", never typed. */
  var MINE = "Custom";

  /* Ordinal power per act, and the alignment word. Display facts, already
     written in canon, never used to compute a cost. */
  var POWER = {
  "Anarchists": {
    "act1": 6,
    "act3": 4
  },
  "Blues": {
    "act1": 7,
    "act3": 6
  },
  "Caravans": {
    "act1": 10,
    "act3": 8
  },
  "Cartel": {
    "act1": 12,
    "act3": 9
  },
  "Church": {
    "act1": 9,
    "act3": 5
  },
  "Colorful": {
    "act1": 1,
    "act3": 1
  },
  "Custom": {
    "act1": 4,
    "act3": null
  },
  "Homeless": {
    "act1": 2,
    "act3": 2
  },
  "Mob": {
    "act1": 13,
    "act3": 12
  },
  "Network": {
    "act1": 11,
    "act3": 13
  },
  "Reds": {
    "act1": 8,
    "act3": 11
  },
  "Remnants": {
    "act1": 14,
    "act3": 10
  },
  "Trades": {
    "act1": 5,
    "act3": 7
  },
  "Volunteers": {
    "act1": 3,
    "act3": 3
  }
};
  var ALIGN = {
  "Anarchists": "anti-establishment",
  "Blues": "socialist",
  "Caravans": "neutral",
  "Cartel": "predatory",
  "Church": "evangelical",
  "Colorful": "community",
  "Custom": "emergent",
  "Homeless": "underground",
  "La Familia": "identity-supremacist",
  "Mob": "territorial",
  "Network": "psyop",
  "Panthers": "identity-supremacist",
  "Pures": "identity-supremacist",
  "Reds": "capitalist",
  "Remnants": "military",
  "Trades": "neutral",
  "Triads": "identity-supremacist",
  "Volunteers": "nonprofit"
};

  function norm(f){ return String(f||'').toUpperCase().replace(/[\s_]/g,''); }

  /* ---- WHAT ARE THESE TWO TO EACH OTHER? ---------------------------------
     DIRECTIONAL, and it matters: the Cartel 'prey-tax' the Caravans and the
     Caravans are 'preyed-taxed' by the Cartel. Same relationship, two seats,
     and the graph writes both. Asking A about B gets A's seat.
     Returns null when canon says nothing, and NULL IS A REAL ANSWER -- most
     pairs in this valley have no written position and pretending otherwise
     would be inventing canon. */
  function between(a, b){
    var A=norm(a), B=norm(b);
    if(!A || !B || A===B) return null;
    for(var i=0;i<PAIRS.length;i++){
      var p=PAIRS[i];
      if(norm(p.from)===A && norm(p.to)===B) return decorate(p);
    }
    return null;
  }

  /* The same question asked from either seat: is there ANY canon position
     between these two, whichever way it was written down. Used when the
     question is "do these two have history", not "what does A think". */
  function either(a, b){ return between(a,b) || between(b,a); }

  function decorate(p){
    var s = SPEC[p.label] || null;
    var w = WORDS[p.label] || null;
    var init = (s && s.init != null) ? s.init : null;
    return {
      from: p.from, to: p.to, label: p.label,
      init: init,
      /* THE SIGN IS A READING OF init, not a third table. */
      sign: init == null ? 'unknown' : (init < 0 ? 'hostile'
                                      : init > 0 ? 'warm' : 'neutral'),
      war: !!(s && s.locked === 'war'),
      protected: !!(s && s.protects),
      word: w ? w.word : String(p.label).toUpperCase().replace(/-/g,' '),
      note: w ? w.they : null,
      cost: w ? w.you : null,
      draft: w ? !!w.draft : false
    };
  }

  /* EVERY canon position this outfit holds, both seats, for a board he can
     read. Sorted hostile-first because that is the half that gets you killed.

     ONE ROW PER OTHER OUTFIT, and the dedupe is not cosmetic. The graph writes
     BOTH SEATS of the pairs somebody bothered to write twice -- Cartel says
     'prey-tax' about the Caravans and the Caravans say 'preyed-taxed' about
     the Cartel -- so a naive walk lists the Remnants twice on the Cartel's
     board and reads as two separate wars. The outfit's OWN seat wins, because
     a board about them should say what THEY hold, not what is held about them;
     a mirrored row only survives when canon never wrote their side. */
  function ripples(fid){
    var A=norm(fid), out=[], byOther={};
    if(!A) return out;
    for(var i=0;i<PAIRS.length;i++){
      var p=PAIRS[i], row=null;
      if(norm(p.from)===A) row = decorate(p);
      else if(norm(p.to)===A) row = flip(decorate(p));
      if(!row) continue;
      var k = norm(row.to), had = byOther[k];
      if(had && !had.mirrored) continue;      /* their own seat already stands */
      if(had && row.mirrored) continue;       /* neither seat is theirs; keep one */
      if(had){ out.splice(out.indexOf(had), 1); }
      byOther[k] = row;
      out.push(row);
    }
    var rank={hostile:0, unknown:1, neutral:2, warm:3};
    out.sort(function(x,y){
      var d=(rank[x.sign]||1)-(rank[y.sign]||1);
      return d !== 0 ? d : String(x.to).localeCompare(String(y.to));
    });
    return out;
  }

  /* The other seat of an edge written from the far side. The LABEL is not
     mirrored -- 'prey-tax' seen from the prey is still 'prey-tax', that is
     what is being done TO them -- but the from/to swap so the row reads about
     the outfit you asked about. */
  function flip(d){
    return { from:d.to, to:d.from, label:d.label, init:d.init, sign:d.sign,
             war:d.war, protected:d.protected, word:d.word, note:d.note,
             cost:d.cost, draft:d.draft, mirrored:true };
  }

  /* ---- WHAT THIS DOES TO A COST ALREADY ESTABLISHED -----------------------
     `base` is what bohemia_commitment.costs() already decided this hearer
     takes off you. `sided` is the outfit you sided WITH; `hearer` is the
     outfit that found out. The canon position the hearer holds on the sided
     outfit bends the number:

         weighted = max(0, base + round(base * (-init / 100)))

     -80 (permanent war) roughly doubles it. +35 (adjacent) shaves it. The
     only thing chosen here is the SHAPE -- "the canon standing, as a
     proportion" -- and every magnitude comes off REL_SPEC.

     THE FLOOR IS ZERO AND ZERO IS NOT A REWARD. A warm position can take the
     cost to nothing, and "they heard and they did not mind" is a real, visible
     outcome. It never goes negative: paying somebody for helping their
     friends' friends is a REWARD CHANNEL, and inventing one of those is
     Paolo's ruling to make, not a side effect of mine.

     *** AND A CANON POSITION ALWAYS BITES AT LEAST ONE. *** The proportion
     alone has a dead zone and it was found by running it rather than reasoning
     about it: the Cartel TAX the Caravans in canon (init -45), and at base 1
     that is round(0.45) = 0, so the most common case in the game charged
     nothing at all for a hostile position the lore spent a line writing down.
     A relation the engine holds and the player never feels is this lane's
     oldest bug wearing a new coat. So the sign is an INVARIANT, not a hint:
     hostile always takes more than base, warm always takes less (down to
     zero), neutral moves nothing. That is FactionCanon's own lesson --
     "a starting value decays; an invariant holds" -- applied to the cost side.

     Returns the full working, not just a number, so the surface can say WHY
     and so a gate can check the arithmetic instead of trusting it. */
  function weigh(sided, hearer, base){
    var b = base|0;
    var rel = between(hearer, sided);
    var out = { base:b, weighted:b, rel:rel, moved:0, why:null };
    if(!rel || rel.init == null || b <= 0) return out;
    var w = b + Math.round(b * (-rel.init / 100));
    if(rel.init < 0 && w <= b) w = b + 1;    /* hostile always costs more */
    if(rel.init > 0 && w >= b) w = b - 1;    /* warm always costs less */
    if(w < 0) w = 0;
    out.weighted = w;
    out.moved = w - b;
    out.why = rel;
    return out;
  }

  /* ---- YOUR OUTFIT --------------------------------------------------------
     PAOLO 8/26: "custom is your own personal faction!!!!!!" -- and canon says
     so too: the graph's note on Custom reads "Player faction. No preset
     philosophy. Identity emerges from three generations of action."

     Its relations are {} AND THAT IS CORRECT, NOT A GAP. An emergent faction
     has not made its enemies yet. The mechanism is live and empty. The day one
     line goes into that JSON, your outfit has a war and every surface below
     already knows what to do with it. */
  function mine(){ return MINE; }
  function isMine(fid){ return !!MINE && norm(fid) === norm(MINE); }
  function myRipples(){ return MINE ? ripples(MINE) : []; }

  /* Power is an ORDINAL RANK per act (1 = weakest), straight off the graph.
     Returned raw with the act asked for; nothing here converts it to a
     strength, because canon says rank and rank is what it says. */
  function powerOf(fid, act){
    var A=norm(fid);
    for(var k in POWER) if(norm(k)===A)
      return (act>=3 ? POWER[k].act3 : POWER[k].act1);
    return null;
  }
  function alignOf(fid){
    var A=norm(fid);
    for(var k in ALIGN) if(norm(k)===A) return ALIGN[k];
    return null;
  }

  /* Every outfit canon has anything to say about, for a gate to sweep. */
  function keys(){
    var seen={}, out=[];
    for(var k in POWER){ if(!seen[k]){ seen[k]=1; out.push(k); } }
    for(var i=0;i<PAIRS.length;i++){
      if(!seen[PAIRS[i].from]){ seen[PAIRS[i].from]=1; out.push(PAIRS[i].from); }
      if(!seen[PAIRS[i].to]){ seen[PAIRS[i].to]=1; out.push(PAIRS[i].to); }
    }
    return out.sort();
  }

  var API = { PAIRS:PAIRS, SPEC:SPEC, WORDS:WORDS, POWER:POWER, ALIGN:ALIGN,
              between:between, either:either, ripples:ripples, weigh:weigh,
              mine:mine, isMine:isMine, myRipples:myRipples,
              powerOf:powerOf, alignOf:alignOf, keys:keys };
  if(HASREQ) module.exports=API; else root.BohemiaBetween=API;
})(typeof globalThis!=='undefined'?globalThis:this);
