// BOHEMIA SUBURB (canonical, 7/18/26) — Paolo APPROVED cul-de-sacs + the scale.
// Real dimensions at the game scale (TILE=0.75 m, 128 tiles = 96 m per cell):
// a ~14x8 m house body + a 6x6 m front garage + a 6 m driveway to the street, on
// ~16 m lots, lining cul-de-sac streets off the entrance. Cluster-aware (cw,ch) per
// the MERGE LAW: fills the union as ONE connected neighborhood, wall wrapping the
// union, an ENTRANCE per street-facing cell — a GATE only if this community was
// rich enough to buy one (GATED IS RICH, Paolo's bank law, enforced 8/1; an
// ordinary walled suburb opens its street through the wall instead). Homes are exposed as footprints the world
// model floorplans (residential). Loops + garden were graveyarded (7/18 verdict).
// codes: 0 dead-ground 1 road 2 house 3 driveway 4 wall 5 gate 6 garage 10 sidewalk (7=tree and 8=pool are GRAVEYARDED, dead world)
// ACT 1 IS A DEAD WORLD: no vegetation ever (no trees/pools/grass). Backyards are
// dead ground (code 0). Homes NEVER touch the wall — 3-tile dead backyard minimum.
(function(root){
  // THE KIT BINDING (7/26 fix): every other district module binds K up front;
  // this one referenced a bare `K` guarded by `typeof K!=='undefined'`, so in the
  // browser the guard silently swallowed it and the module NEVER registered with
  // the district kit. The whole generic marriage in the CITY app keys off that
  // registry, so the walked district fell back to the legacy prefab stamps -
  // not the canon plot, and not one enterable building in it.
  // AND IT WAS STILL BROKEN IN THE CITY APP (8/3 fix, measured). The binding above
  // was captured AT LOAD TIME, and inside the alpha's CITY blob this module is
  // inlined at line 2950 while the district kit is inlined at 3335 -- the ONLY
  // district of thirty-nine that loads BEFORE the kit. So `BohemiaDistrictKit` did
  // not exist yet, K froze as undefined forever, and the first line of this module
  // that ever actually reached for the kit blew the whole world up
  // ("Cannot read properties of undefined (reading 'layWalks')" out of realizeCell,
  // which took 32 gates red at once). Measured in the running app: 35 districts in
  // BohemiaDistrictKit.types(), and `suburb` is NOT one of them -- the registration
  // at the tail of this file has never run in the CITY app for the same reason.
  // THE FIX IS TO STOP CAPTURING. K() resolves at CALL time, by which point the kit
  // is always up, so load order cannot decide it any more. Registration behaviour is
  // deliberately UNCHANGED (the tail still asks at load time, so it still no-ops in
  // the CITY app) -- newly registering Paolo's spawn district would change what the
  // walked suburb is generated by, and that is a measured change, not a side effect.
  // Recorded: records/BOHEMIA_THE_SUBURB_NEVER_HAD_THE_KIT_8_3_26.md
  var _K = (typeof module!=='undefined') ? require('./bohemia_district_kit.js') : null;
  function K(){
    if(_K) return _K;
    var k=(typeof BohemiaDistrictKit!=='undefined')?BohemiaDistrictKit:(root&&root.BohemiaDistrictKit);
    if(!k) throw new Error('bohemia_suburb: the district kit is not loaded yet');
    return k;
  }

  var SZ=128, TILE=0.75;                                  // tiles/cell, m/tile
  var M=function(m){return Math.round(m/TILE);};          // meters -> tiles
  function rng(seed){var s=(seed>>>0)||1;return function(){s=(s*1103515245+12345)>>>0;return s/4294967296;};}
  function Wd(g){return g[0].length;} function Ht(g){return g.length;}
  function blank(w,h){var g=[];for(var y=0;y<h;y++){var r=[];for(var x=0;x<w;x++)r.push(0);g.push(r);}return g;}
  function inb(g,x,y){return x>=1&&y>=1&&x<Wd(g)-1&&y<Ht(g)-1;}
  function road(g,x,y,w){for(var dy=-w;dy<=w;dy++)for(var dx=-w;dx<=w;dx++){var nx=(x+dx)|0,ny=(y+dy)|0;
    if(inb(g,nx,ny)&&g[ny][nx]!==2&&g[ny][nx]!==6&&g[ny][nx]!==4)g[ny][nx]=1;}}
  function seg(g,x0,y0,x1,y1,w){var n=Math.max(1,Math.max(Math.abs(x1-x0),Math.abs(y1-y0))|0);
    for(var i=0;i<=n;i++)road(g,x0+(x1-x0)*i/n,y0+(y1-y0)*i/n,w);}
  function disc(g,cx,cy,rr){for(var dy=-rr;dy<=rr;dy++)for(var dx=-rr;dx<=rr;dx++)if(dx*dx+dy*dy<=rr*rr)road(g,cx+dx,cy+dy,0);}
  function frame(g,cw){var W=Wd(g),H=Ht(g);
    for(var x=0;x<W;x++){g[0][x]=4;g[H-1][x]=4;}for(var y=0;y<H;y++){g[y][0]=4;g[y][W-1]=4;}
    for(var ci=0;ci<cw;ci++){var gx=(SZ*ci+SZ/2)|0;for(var d=-3;d<=3;d++)g[H-1][gx+d]=5;
      for(var s=1;s<=6;s++)if(inb(g,gx,H-1-s))g[H-1-s][gx]=1;}}
  // Vegas home (top-down): a SHORT driveway (a car apron, 3 tiles long x 4 wide
  // for 2 cars) leads to a garage that is the FRONT CORNER of the house. The
  // house is the bulk; the driveway is tiny. Home faces the street (nx,ny),
  // backyard goes to the wall behind it.
  // GAP = Paolo's law: at worst 3 tiles of backyard AND 3 tiles between neighbors.
  /* DRIVEWAY SIZE. Paolo 7/31, LOCKED, and SUPERSEDING HIS OWN EARLIER RULING THE
     SAME DAY: "REAL DRIVE WAYS ALL OF THEM SHOULD BE 4 X 5 AND BE CONSISTEN TO
     WHERE A GARAGE WOULD BE IN A HOUSE."
     He said "2 tiles wide not three" earlier on 7/31 and "4 x 5" later on 7/31.
     NEWEST DATE WINS. The 2-wide ruling is DEAD, and it is struck HERE, in the
     code it governed, rather than left to rot in an old commit message.
     ALIGNED TO THE GARAGE: dvOff centres the apron on the garage door it serves,
     so the car's path and the door it drives into are one line.
     Law: laws/BOHEMIA_THE_BUILT_WORLD_LAW_7_31_26.md clause D2.
     Gate: gates/suburb_street_gate.js */
  var DRIVE=5, DVW=4, HD=M(9), GARD=M(5), RD=Math.max(2,M(5)>>1), GAP=3;
  // HOUSE FACTORY (Paolo 7/18: "the houses need to be modular, not all the same").
  // Typed models: constant DEPTH (so rows still pack cleanly) but varied WIDTH,
  // garage size, garage side, and STORIES. Two-story homes stamp an inset upper
  // floor (code 9) so they read taller from the top-down world.
  var MODELS=[
    {id:'ranch',   w:M(14), gw:M(5), story:1},
    {id:'twostory',w:M(11), gw:M(5), story:2},
    {id:'compact', w:M(10), gw:M(4), story:1},
    {id:'wide',    w:M(16), gw:M(6), story:1},
    {id:'bigtwo',  w:M(13), gw:M(5), story:2}
  ];
  var MAXW=0; for(var _mi=0;_mi<MODELS.length;_mi++)MAXW=Math.max(MAXW,MODELS[_mi].w);
  var LOTW=MAXW+GAP, SEED_CTX=1;                          // lot stride fits the widest model
  function pickModel(x,y){var h=((x*73856093)^(y*19349663)^(SEED_CTX*2654435761))>>>0;
    return {m:MODELS[h%MODELS.length], gar:(h>>4)&1};}    // deterministic model + garage side per lot
  function isHome(v){return v===2||v===3||v===6||v===9;}
  function home(g,rx,ry,nx,ny){var px=-ny,py=nx;
    var sel=pickModel(rx,ry), HW=sel.m.w, GARW=sel.m.gw, story=sel.m.story;
    var h0=-(HW>>1), garOff=sel.gar?(h0+HW-GARW):h0;      // garage on left OR right front corner
    var dv=[],ga=[],bd=[],up=[],foot=[];
    for(var d=DRIVE+1;d<DRIVE+1+HD;d++)for(var w=h0;w<h0+HW;w++){
      var c=[(rx+nx*d+px*w)|0,(ry+ny*d+py*w)|0]; foot.push(c);
      if(d<DRIVE+1+GARD && w>=garOff && w<garOff+GARW){ga.push(c);continue;}
      var inset=(story===2 && d>=DRIVE+3 && d<DRIVE+HD-1 && w>h0+1 && w<h0+HW-2);
      (inset?up:bd).push(c);}
    var dvOff=garOff+((GARW-DVW)>>1);
    for(var d2=1;d2<=DRIVE;d2++)for(var w2=dvOff;w2<dvOff+DVW;w2++){var c2=[(rx+nx*d2+px*w2)|0,(ry+ny*d2+py*w2)|0];dv.push(c2);foot.push(c2);}
    /* NO BUILDING EVER SITS ON A SIDEWALK (Paolo 7/31, LOCKED, his own caps:
       "houses or buildings should NEVER SIT ON THE SIDEWALK EVER ANYWHERE IN THE
       WORLD"). The walk is laid BEFORE homes now, so a walk cell is already code
       10 when a house asks for it and this check refuses the placement outright --
       the mass cannot go there at all.
       THE DRIVEWAY IS THE ONE EXCEPTION, because a real apron does cross the walk
       to reach the street. So driveway cells are validated separately and accept
       10 as well as bare ground. A MASS never does.
       Law: laws/BOHEMIA_THE_BUILT_WORLD_LAW_7_31_26.md clause D1. */
    var _isDrive={}; for(var _d=0;_d<dv.length;_d++) _isDrive[dv[_d][0]+','+dv[_d][1]]=1;
    for(var i=0;i<foot.length;i++){var c=foot[i];
      if(!inb(g,c[0],c[1])) return false;
      var cur=g[c[1]][c[0]];
      if(_isDrive[c[0]+','+c[1]]){ if(cur!==0&&cur!==10) return false; }  /* apron may cross the walk */
      else if(cur!==0) return false;                                       /* a MASS may not, ever */
    }
    // 3-tile skirt on the two SIDES + the BACK must be clear of any other home
    for(var d3=1;d3<=DRIVE+HD+GAP;d3++)for(var w3=h0-GAP;w3<h0+HW+GAP;w3++){
      var side=(w3<h0||w3>=h0+HW), back=(d3>DRIVE+HD);
      if(!side&&!back)continue;
      var mx=(rx+nx*d3+px*w3)|0,my=(ry+ny*d3+py*w3)|0;
      if(mx<0||my<0||mx>=Wd(g)||my>=Ht(g))continue;
      if(isHome(g[my][mx]))return false;}
    // NEVER let a home touch the wall: 3-tile DEAD backyard to any wall (Paolo 7/18).
    for(var fi=0;fi<foot.length;fi++){var fc=foot[fi];
      for(var wy=-GAP;wy<=GAP;wy++)for(var wx=-GAP;wx<=GAP;wx++){
        var wxx=fc[0]+wx,wyy=fc[1]+wy;
        if(wxx<0||wyy<0||wxx>=Wd(g)||wyy>=Ht(g))continue;
        if(g[wyy][wxx]===4)return false;}}
    dv.forEach(function(c){g[c[1]][c[0]]=3;});ga.forEach(function(c){g[c[1]][c[0]]=6;});
    bd.forEach(function(c){g[c[1]][c[0]]=2;});up.forEach(function(c){g[c[1]][c[0]]=9;});
    /* THE FRONT YARD, AND IT IS THE THING THE SPAWN WAS MISSING. Every house in this
       district sat in a large flat rectangle of one dead-dirt tone with NOTHING in it --
       nine codes in the whole suburb and not one of them a prop. Looked at from the
       player's camera at the spawn, that is most of the screen.
       WHERE: the frontage between the walk and the house, either side of the apron --
       exactly the strip a real front yard occupies. The apron runs through it to the
       garage, which is why the driveway cells are skipped rather than overwritten.
       ONLY OVER BARE GROUND (cur===0): it never takes a walk, a wall, a mass or a
       neighbour's cell, so nothing this adds can break D1 or the 3-tile skirt.
       DETERMINISTIC PER LOT, never per cell (desert_dominance_law, Paolo 7/14: "too much
       diversity with the desert tiles") -- a per-cell roll would salt the debris evenly
       across every yard in the valley, which reads as texture rather than as somewhere
       the wind has been. */
    var _fy=((rx*73856093)^(ry*19349663)^0x5EED)>>>0;
    for(var fd=1;fd<=DRIVE;fd++)for(var fw=h0;fw<h0+HW;fw++){
      if(fw>=dvOff&&fw<dvOff+DVW) continue;                 /* the apron keeps its cells */
      var fx=(rx+nx*fd+px*fw)|0, fy=(ry+ny*fd+py*fw)|0;
      if(!inb(g,fx,fy)||g[fy][fx]!==0) continue;            /* bare ground only */
      g[fy][fx]=11;
      /* DRIFT COLLECTS AT AN EDGE AND IN SOME YARDS, NOT EVENLY IN ALL OF THEM.
         One lot in three has drift at all (the per-lot roll), and within those it stacks
         on the KERB ROW -- fd===1, the row furthest from the house -- because that is
         where a wall or a kerb stops it. An even sprinkle across every yard reads as
         texture; a few yards full of it reads as weather. */
      /* THE KERB ROW IS USUALLY THE SIDEWALK, which this loop skips (bare ground only),
         so "fd===1" put drift almost nowhere -- 12 cells across four whole plots. It goes
         on the OUTER BARE ROWS instead: fd<=2, the yard edge nearest the street, which is
         the same place for the same reason. Measured before and after rather than assumed. */
      if(fd<=2 && (_fy%3)===0 && ((((_fy>>3)+fw*7)&3)!==0)) g[fy][fx]=13;
    }
    return true;}
  // even lot spacing along every road frontage (position-based, not a global counter)
  function fillHomes(g){var W=Wd(g),H=Ht(g);
    for(var y=1;y<H-1;y++)for(var x=1;x<W-1;x++){if(g[y][x]!==1)continue;
      for(var s=0;s<4;s++){var nx=[1,-1,0,0][s],ny=[0,0,1,-1][s];
        if(!inb(g,x+nx*2,y+ny*2)||g[y+ny*2][x+nx*2]!==0)continue;   // frontage opens to buildable land
        var along=(nx!==0)?y:x;                                     // coordinate running along the road
        if((along%LOTW)!==((nx>0||ny>0)?0:(LOTW>>1)))continue;      // stagger the two sides
        home(g,x,y,nx,ny);}}}
  /* THE SIDEWALK (code 10). Paolo 7/31, LOCKED: "Im upset your suburbs dont have
     a 1 grid sidewalk next to the streets".

     He was right, and the reason it hid is worth writing down. The RUN was already
     drawing a kerb band: its renderer asked "is this ground cell next to a road?"
     and laid the walk_kerb tile if so. Measured on the real surface, all 709
     ground-touching-road cells came back walk_kerb, so on that one screen it
     looked handled. But it was a RENDER-TIME TRICK and the world never knew:
     this generator's codes were 0,1,2,3,4,5,6,9 with no sidewalk among them, so
     the CITY drew none, the dossier had no row to tile against, and no gate could
     ever fail. A feature that lives in one renderer's if-statement is not in the
     game. So it is a REAL CELL now and every consumer gets it for free.

     LAST PASS, deliberately: homes and driveways are already stamped, so a
     driveway apron (code 3) keeps its cells and the walk breaks where a car
     crosses it, which is what a real street does. Only dead ground converts. */
  /* ONE BODY, AND IT IS IN THE KIT NOW. This was private to this file, which is exactly
     why D1 was true in one district out of forty: nobody else could call it. K.layWalks is
     the same code, proved byte-identical on 32 blocks / 786,432 cells; this is the caller. */
  function layWalks(g){ return K().layWalks(g,{road:{1:1},walk:10,over:function(c){return c===0;}}); }
  /* THE STREET LIGHT (code 12), 8/21. The district Paolo SPAWNS IN had eleven codes and
     every single one of them lay flat on the ground: road, walk, drive, dirt, gravel,
     debris, and the house masses. Nothing on this plot stood up out of the ground plane
     except the buildings themselves, which is why the spawn reads as a floor plan seen
     from above rather than a street you are standing in. A streetlight is the cheapest
     vertical in any real neighbourhood and the valley already owns the art for it -- the
     blessed V11 dark lamp bodies, banks/BOHEMIA_LAMP_DARK_VARIANTS_7_14_26.txt, three
     variants, approved 7/14 and drawn ZERO times anywhere in the world until today.

     WHERE IT STANDS. Paolo's 7/31 ruling put the walk hard against the kerb ("a 1 grid
     sidewalk next to the streets"), so there is no amenity strip to stand a pole in. Real
     attached-walk residential practice puts the pole at the BACK OF WALK, on the property
     line, and that is what this does: it finds a kerb walk cell, steps one further from
     the road, and stands the pole there if that cell is bare yard or gravel. The walk
     itself is never blocked and a driveway apron is never touched.

     SPACING IS RESEARCHED, NOT INVENTED (8/21, local residential practice): successive
     heads at 200-300 ft, STAGGERED on alternate sides of the street, which puts same-side
     poles at 400-600 ft. TILE=0.75 m, so 250 ft = 76 m = 102 tiles between successive
     heads. On a 128-tile plot that is roughly one head per street, which is why a suburb
     comes out with a handful and not an avenue of them -- the same order as every other
     district that authors a light (trailer 4, apartment 8, town 18).
     DEAD IS DEFAULT: the head is dark. The night glow is the POWER network's business and
     only a live circuit lights one, which is CLUSTERED POWER / LIGHT=TERRITORY, unchanged. */
  var LIGHT_SPACE=204;   /* 500 ft between SAME-SIDE poles; the other kerb is offset by half
                            of that, so SUCCESSIVE heads land ~250 ft apart. That is the
                            researched pair of numbers, and the staggering is what turns one
                            into the other. */
  /* AND IT IS A GREEDY WALK, NOT A MODULO. The first cut of this asked `along % SPACE ===
     phase`, which nominates ONE cell per street and then throws the pole away if that exact
     cell happens to have a driveway, a garage or a house behind it. MEASURED: one light in
     the whole plot. A real crew does not abandon a pole because the target station is
     somebody's drive apron -- it walks on and sets it at the next place it fits. So: collect
     every LEGAL station along each kerb, then walk that list in order and take one whenever
     the spacing has been earned. The number is a target the street has to honour on average,
     not a lottery a cell has to win. */
  function layLights(g){
    var W=Wd(g),H=Ht(g),x,y,i,n=0,d4=[[1,0],[-1,0],[0,1],[0,-1]];
    var ph=(SEED_CTX>>>3)%LIGHT_SPACE, runs={};
    for(y=1;y<H-1;y++)for(x=1;x<W-1;x++){
      if(g[y][x]!==10) continue;                                   /* the kerb walk only */
      for(i=0;i<4;i++){
        var rx=x+d4[i][0], ry=y+d4[i][1];
        if(!inb(g,rx,ry)||(g[ry][rx]!==1&&g[ry][rx]!==5)) continue; /* the road it hugs */
        var bx=x-d4[i][0], by=y-d4[i][1];                          /* BACK OF WALK */
        if(!inb(g,bx,by)) break;
        if(g[by][bx]!==0&&g[by][bx]!==11) break;   /* bare yard or gravel; never a drive,
                                                      a wall, a garage or a house */
        var vert=(d4[i][0]!==0);                   /* the road runs north-south */
        var along=vert?y:x;                        /* the coordinate running along the kerb */
        var line=vert?rx:ry;                       /* WHICH street this kerb belongs to */
        var side=((d4[i][0]+d4[i][1])>0)?0:1;      /* which of the two kerbs this is */
        var key=(vert?'V':'H')+line+':'+side;
        (runs[key]||(runs[key]=[])).push([along,bx,by,side]);
        break;
      }
    }
    for(var k in runs){ var st=runs[k]; st.sort(function(a,b){return a[0]-b[0];});
      /* side 1 starts half a spacing later: that offset IS the stagger */
      var last=-1e9, want=ph+(st[0][3]?(LIGHT_SPACE>>1):0);
      for(i=0;i<st.length;i++){ var e=st[i];
        if(e[0]<want&&last<-1e8) continue;                /* wait for this run's first station */
        if(e[0]-last<LIGHT_SPACE) continue;               /* spacing not earned yet */
        g[e[2]][e[1]]=12; last=e[0]; n++;
      }
    }
    return n;
  }
  function ringRect(g,x0,y0,x1,y1,w){seg(g,x0,y0,x1,y0,w);seg(g,x1,y0,x1,y1,w);seg(g,x1,y1,x0,y1,w);seg(g,x0,y1,x0,y0,w);}
  // WALLED NEIGHBORHOOD — LOTS FIRST (Paolo 7/18, calibrated to 89147/Campana Dr:
  // ~0.15 acre lots, 2-story homes, packed). The developer maximizes LOTS; streets
  // exist to give them driveways. So: homes back onto the perimeter wall on all
  // four sides (a ring of lots), and the INTERIOR is packed with rows of lots
  // served by streets spaced exactly one back-to-back lot-pair apart. Houses are
  // the primary unit; roads serve them; every home keeps its 3-tile yards.
  function placeRow(g,streetY,W,lotw,lo,hi){   // pack houses on BOTH sides of a horizontal street
    for(var lx=lo+((lotw/2)|0); lx<hi; lx+=lotw){
      home(g,lx,streetY-RD,0,-1);              // north side: backyard up, driveway down to the street
      home(g,lx,streetY+RD,0, 1);              // south side: backyard down
    }}
  function placeCol(g,streetX,H,lotw,lo,hi){   // pack houses on BOTH sides of a vertical street
    for(var ly=lo+((lotw/2)|0); ly<hi; ly+=lotw){
      home(g,streetX-RD,ly,-1,0); home(g,streetX+RD,ly,1,0);
    }}
  // houses along one straight ring edge, on BOTH sides (outer backs the wall,
  // inner backs the center), packed every LOTW.
  function placeEdge(g,x0,y0,dx,dy,len,nx,ny,lotw){
    for(var t=(lotw>>1); t<len-2; t+=lotw){ var rx=(x0+dx*t)|0, ry=(y0+dy*t)|0;
      home(g,rx+nx*RD,ry+ny*RD,nx,ny);          // outer side: start just past the road edge
      home(g,rx-nx*RD,ry-ny*RD,-nx,-ny); }}      // inner side
  function placeEdge2(g,x0,y0,dx,dy,len,nx,ny,lotw){   // OUTER side only (backs the wall)
    for(var t=(lotw>>1); t<len-2; t+=lotw){ var rx=(x0+dx*t)|0, ry=(y0+dy*t)|0; home(g,rx+nx*RD,ry+ny*RD,nx,ny); }}
  function ringHomes(g,R,W,H,lotw){
    placeEdge(g,R,R,1,0,W-2*R,0,-1,lotw);        // top edge: outer backs up
    placeEdge(g,R,H-R,1,0,W-2*R,0,1,lotw);       // bottom edge: outer backs down
    placeEdge(g,R,R,0,1,H-2*R,-1,0,lotw);        // left edge: outer backs left
    placeEdge(g,W-R,R,0,1,H-2*R,1,0,lotw);       // right edge: outer backs right
  }
  // evenly space N positions from lo to hi INCLUSIVE (both ends hit), each gap >=LOTW
  function spread(lo,hi){ var m=Math.max(1,Math.floor((hi-lo)/LOTW)), a=[], k;
    for(k=0;k<=m;k++) a.push(Math.round(lo+(hi-lo)*k/m)); return a; }
  // one column of houses backing a SIDE wall, fronting a vertical rail (outer side
  // only). Spread from the rail's TOP end to its BOTTOM end so a house lands in BOTH
  // corners, fed by the existing rail — no extra street (Paolo 7/18: fill the corners).
  function placeColOuter(g,streetX,dir,lo,hi){ var ys=spread(lo,hi);
    for(var k=0;k<ys.length;k++) home(g,(streetX+dir*RD)|0,ys[k],dir,0); }
  // THE BLOCK — the canonical Bohemia suburb (Paolo APPROVED 7/18; the central-court
  // variant was rejected -> graveyard). DENSE, HOUSES-FIRST fill of the whole block:
  // a rail+rung LADDER is the minimum road that serves a full block of lots — two
  // vertical rails near the side walls, horizontal rungs between them. Houses pack
  // EVERY frontage: both sides of every rung (top+bottom wall rows and all interior
  // rows), and the outer side of each rail (left+right wall columns). Nothing is left
  // as empty band; every home keeps its 3-tile dead backyard to the wall.
  /* PUNCH THE ENTRANCE THROUGH A STREET-FACING WALL, and WHAT KIND of entrance
     is the whole point of this function now.

     GATED IS RICH (Paolo's own bank law, in banks/BOHEMIA_GRAPHICS_VERDICTS_
     MASTER_7_16_26.txt and BOHEMIA_REAL_VEGAS_VERDICTS_R2_7_14_26.txt, verbatim:
     "most Vegas communities are walled but NOT gated; gates = boujee/richer
     pre-apocalypse (story fuel post-apocalypse)"). It sat in his approved banks
     unenforced from 7/14 to 8/1 and the generator broke it on every single cell:
     it stamped a GATE (code 5) through every street edge of every district in
     the suburb family, so `suburb`, `gated` and `estate` were the same place
     wearing three names.

     THE REAL VEGAS THIS IS MODELLED ON, and it is regulation rather than taste:
     Clark County's Unified Development Code 30.64.020 REQUIRES the developer to
     install a decorative perimeter wall on a subdivision - so in this valley
     WALLED is very nearly universal and is not a signal of anything. GATED is
     the signal. Nationally the American Housing Survey (2015, the last year it
     asked) put 5.9% of households behind a wall or fence and only 3.4% behind
     controlled access; Vegas sits far above both, but the RATIO is the point and
     the ratio is what his law states. A gate is a thing a richer community
     bought on top of the wall everybody had to build.

     SO THERE ARE TWO ENTRANCES, and they use tiles that already exist:
       GATED   (gated / estate)  code 5 across the aperture: a gate assembly.
       WALLED  (ordinary suburb) code 1 across the aperture: THE STREET SIMPLY
               RUNS THROUGH. The block wall stops, the road continues out to the
               arterial, the wall picks up on the far side. No leaf, no guard
               house, nothing to open - which is exactly what the overwhelming
               majority of Las Vegas tract subdivisions actually look like.
     Same aperture width either way (7 tiles, the road's own 2*RD+1), because the
     difference is what is IN the gap, not how big the gap is.

     POST-APOCALYPSE, this is the "story fuel" half of his ruling and it comes
     free: after the collapse, which neighbourhoods could be SHUT is decided by
     which ones were rich enough to have bought a gate before it. Nothing here
     has to encode that. The map just tells the truth and the story is already in
     it. */
  function punchGate(g,edge,frac,W,H,rails,gated){var i;
    var APERTURE = gated ? 5 : 1;          // 5 = gate assembly, 1 = open street
    if(edge==='S'||edge==='N'){ var gx=Math.min(W-4,Math.max(3,Math.round(W*frac))), gy=(edge==='S')?H-1:0, dir=(edge==='S')?-1:1;
      for(i=-3;i<=3;i++)if(gx+i>0&&gx+i<W-1)g[gy][gx+i]=APERTURE;
      seg(g,gx,gy+dir,gx,(edge==='S')?rails.by:rails.ty,RD);
      return {edge:edge,x:gx,y:gy,gated:!!gated}; }
    var gy2=Math.min(H-4,Math.max(3,Math.round(H*frac))), gx2=(edge==='E')?W-1:0, dir2=(edge==='E')?-1:1;
    for(i=-3;i<=3;i++)if(gy2+i>0&&gy2+i<H-1)g[gy2+i][gx2]=APERTURE;
    seg(g,gx2+dir2,gy2,(edge==='E')?rails.rx:rails.lx,gy2,RD);
    return {edge:edge,x:gx2,y:gy2,gated:!!gated}; }
  // fill the whole union with the packed ladder + houses; entrances only on
  // street edges, and gated ONLY if this community was rich enough to buy one.
  function denseFill(g,W,H,streets,gpe,gated){
    var back=RD+DRIVE+HD, R=back+5, Lx=R, Rx=W-R, Ty=R, By=H-R, i;
    /* DENSITY IS NOT ALLOWED TO PAY FOR THE DRIVEWAY (Paolo 7/31 D2 gave every
       driveway 2 more tiles of length; WALKABLE-LAND says buildings must still
       dominate the plot).
       The row count used to be derived from `back`, which INCLUDES the driveway,
       so lengthening the apron silently pushed the street rows apart and the block
       lost 5 of its 24 homes -- caught because the life sim then ran out of people
       to put on the street at midday. A neighbourhood is not allowed to get thinner
       as a side effect of an apron ruling.
       The rows are spaced by what a lot actually NEEDS back-to-back: two house
       depths plus the 3-tile gap law. The driveway still sits in front of each
       house; it just no longer inflates the spacing between streets. */
    var lotDepth=RD+HD, span=By-Ty, n=Math.max(2, Math.ceil(span/(2*lotDepth+2*GAP))+1);
    var ys=[]; for(i=0;i<n;i++) ys.push(Math.round(Ty+span*i/(n-1)));
    // ROADS FIRST: rails + rungs (a fully connected ladder, no dead ends). No extra
    // stubs poked into the corners (Paolo 7/18: more street to fill a corner is a bad
    // trade) — the corner squares stay dead-yard, served by the existing network.
    seg(g,Lx,ys[0],Lx,ys[n-1],RD); seg(g,Rx,ys[0],Rx,ys[n-1],RD);
    for(i=0;i<n;i++) seg(g,Lx,ys[i],Rx,ys[i],RD);
    var rails={ty:ys[0],by:ys[n-1],lx:Lx,rx:Rx}, gates=[];
    streets.forEach(function(edge){ var cnt=gpe[edge]||1;
      for(var k=0;k<cnt;k++) gates.push(punchGate(g,edge,(k+1)/(cnt+1),W,H,rails,gated)); });
    /* THE WALK GOES DOWN BEFORE THE HOUSES DO (Paolo 7/31, clause D1: "houses or
       buildings should NEVER SIT ON THE SIDEWALK EVER ANYWHERE IN THE WORLD").
       Order is the whole enforcement. Laid AFTER homes -- which is how it shipped
       first -- a house that happened to front the kerb simply kept the cell and the
       walk flowed around it, so a mass could stand on public ground. Laid HERE, the
       kerb strip is already code 10 when home() asks for the land, and home()'s own
       footprint check refuses it. The rule is not a post-hoc audit, it is the
       placement order: you cannot build on the walk because the walk is there first. */
    layWalks(g);
    // THEN houses, packing every frontage — rung rows (interior + wall-backing) AND
    // BOTH sides of each rail: outer backs the side wall, inner FRONTS the rail from
    // the interior, filling the strip the rung houses can't reach (Paolo 7/18: squeeze
    // more in beside the rails).
    for(i=0;i<n;i++) placeRow(g,ys[i],W,LOTW,Lx,Rx);
    placeColOuter(g,Lx,-1,ys[0],ys[n-1]); placeColOuter(g,Lx, 1,ys[0],ys[n-1]);
    placeColOuter(g,Rx, 1,ys[0],ys[n-1]); placeColOuter(g,Rx,-1,ys[0],ys[n-1]);
    /* LAST, ON PURPOSE, and it is the mirror of the walk's argument above. The walk goes
       down FIRST so nothing can build on it; the pole goes down LAST so it cannot take
       land a house, a garage or a driveway wanted. Order is the enforcement, both ways. */
    layLights(g);
    return gates;
  }
  // MODULAR NEIGHBORHOOD (Paolo 7/18): a block knows which of its edges face STREETS.
  // Gates go ONLY on street edges (a corner exits two streets; a 1x1 on one street has
  // one gate on that street). Adjacent same-type cells MERGE into a 2x1/2x2 union: ONE
  // perimeter wall, ONE connected network, gates scaled per street edge (a 2-wide main
  // street gets 2 gates). API: generate(seed, {cw,ch,streets:['S','E']}); the old
  // generate(seed,'ring',cw,ch) still works (defaults to a south street).
  function generate(seed,a,b,c){
    var opts={};
    if(a&&typeof a==='object')opts=a;
    else if(typeof a==='string'){opts.cw=b;opts.ch=c;}
    else {opts.cw=a;opts.ch=b;}
    var cw=opts.cw||1, ch=opts.ch||1, streets=opts.streets||['S'];
    /* IS THIS COMMUNITY GATED? Paolo's bank law: "most Vegas communities are
       walled but NOT gated; gates = boujee/richer". Three district types share
       this generator - suburb, gated, estate - and until 8/1 it was handed NO
       district at all, so all three came out identical and every one of them was
       gated. The world model knows the type; it just was not saying.
       DEFAULT IS UNGATED. A caller that says nothing gets the ordinary walled
       subdivision, which is the overwhelming majority of the real valley, so the
       expensive thing has to be asked for by name. */
    var gated = (opts.gated != null) ? !!opts.gated
              : (opts.district === 'gated' || opts.district === 'estate');
    SEED_CTX=(seed>>>0)||1;
    var g=blank(SZ*cw,SZ*ch), W=Wd(g), H=Ht(g), x, y;
    // ONE perimeter wall around the whole union (the entrance punches through on
    // street edges - a gate if this community bought one, an open street if not)
    for(x=0;x<W;x++){g[0][x]=4;g[H-1][x]=4;} for(y=0;y<H;y++){g[y][0]=4;g[y][W-1]=4;}
    var gpe={N:cw,S:cw,E:ch,W:ch};                              // entrances scale with the edge's length
    var gates=denseFill(g,W,H,streets,gpe,gated);
    var res={g:g,W:W,H:H,cw:cw,ch:ch,streets:streets,gates:gates,gated:gated,
             district:opts.district||null};
    res.houses=homeFootprints(res).length;
    return res;
  }
  // building footprints (house bodies) for the world model: bounding box of each
  function homeFootprints(res){var g=res.g,W=res.W,H=res.H,seen={},out=[];
    var d4=[[1,0],[-1,0],[0,1],[0,-1]], body=function(v){return v===2||v===9;};
    for(var y=1;y<H-1;y++)for(var x=1;x<W-1;x++){if(!body(g[y][x])||seen[x+','+y])continue;
      var st=[[x,y]];seen[x+','+y]=1;var x0=x,y0=y,x1=x,y1=y,two=false;
      while(st.length){var p=st.pop();if(g[p[1]][p[0]]===9)two=true;
        if(p[0]<x0)x0=p[0];if(p[1]<y0)y0=p[1];if(p[0]>x1)x1=p[0];if(p[1]>y1)y1=p[1];
        for(var i=0;i<4;i++){var nx=p[0]+d4[i][0],ny=p[1]+d4[i][1],k=nx+','+ny;
          if(!seen[k]&&nx>=0&&ny>=0&&nx<W&&ny<H&&body(g[ny][nx])){seen[k]=1;st.push([nx,ny]);}}}
      out.push({x:x0,y:y0,w:x1-x0+1,h:y1-y0+1,story:two?2:1});}
    return out;}
  /* THE WALK STARTS AT THE ENTRANCE, AND THE ENTRANCE IS NOT ALWAYS A GATE.
     This began the drivable-network check by scanning for the first code-5 cell
     and calling it the way in. That was true for exactly as long as every
     community was gated, which was the bug: the moment an ordinary walled
     subdivision opened its street instead (GATED IS RICH, Paolo's bank law),
     `start` came back null and every one of the valley's 2,582 ordinary suburbs
     reported its roads DISCONNECTED - not because they were, but because the
     function could not find a door it recognised.
     The entrance list the generator returns is the honest source: it says where
     every way in is and what kind each one is. The code-5 scan survives only as
     a fallback for a caller that hands over a bare grid with no result object. */
  function roadConnected(res){var g=res.g,W=res.W,H=res.H,start=null,total=0;
    if(res.gates&&res.gates.length){ var e0=res.gates[0]; if(e0&&e0.x!=null) start=[e0.x,e0.y]; }
    for(var y=0;y<H;y++)for(var x=0;x<W;x++){var c=g[y][x];if(c===1||c===5||c===3||c===6){total++;if(!start&&c===5)start=[x,y];}}
    if(!start)return false;var seen={},st=[start];seen[start[0]+','+start[1]]=1;var reach=0;
    while(st.length){var p=st.pop();reach++;for(var i=0,d=[[1,0],[-1,0],[0,1],[0,-1]];i<4;i++){var nx=p[0]+d[i][0],ny=p[1]+d[i][1],k=nx+','+ny;
      if(seen[k]||nx<0||ny<0||nx>=W||ny>=H)continue;var cc=g[ny][nx];if(cc===1||cc===5||cc===3||cc===6){seen[k]=1;st.push([nx,ny]);}}}
    return reach/total>0.9;}
  var PALETTE={
    /* CODE 0 IS A REAL TILE, NOT A VOID (8/4). Its legend names it and the plot draws
       it, but it had no colour here -- so every judging surface painted it MAGENTA,
       which is both a lie about the game and a PURPLE RESERVATION breach. */
    0: '#463f30',1:'#33333c',2:'#8a8478',3:'#3f3f47',4:'#6b6152',5:'#c79a3f',6:'#6b6b74',9:'#9a938a',11:'#9b968a',13:'#7c7263',10:'#57575f',12:'#4a463f'};
  // TILE SPEC (the "note section" for tiling): code -> name, kind, ACT-1 dead-world material.
  // ACT 1 is a DEAD suburb: NO vegetation ever — dead-dirt yards, no trees/pools/grass.
  var LEGEND={
    0:{name:'dead-ground (yard)', kind:'ground',    act1:'dead-dirt front/back yard, no grass, cracked'},
    /* street:true = a PUBLIC RIGHT OF WAY, so D1 demands a walk beside it. Code 3 (the
       driveway apron) deliberately has no such flag: D1's own text lets the apron cross
       the walk, and that is what keeps 1,928 legal garage-to-apron adjacencies legal. */
    1:{name:'road',               kind:'drive',      street:true, act1:'cracked residential street asphalt (car-drivable)'},
    2:{name:'house',              kind:'building',   act1:'single-story stucco tract house, faded, dark windows', enter:'house floorplan (residential): living + kitchen up front, bedrooms/bath off a hall, door to the garage'},
    3:{name:'driveway',           kind:'drive',      act1:'cracked concrete driveway apron (drivable to garage)'},
    4:{name:'wall',               kind:'fence',      act1:'block perimeter wall / side fence, tan stucco, chipped'},
    /* GATED IS RICH (Paolo's bank law, enforced 8/1): code 5 appears ONLY on a
       `gated` or `estate` district. An ordinary walled `suburb` opens its
       perimeter and lets the STREET (code 1) run through instead - same
       aperture, no gate assembly - which is what ~98% of this valley is. */
    5:{name:'gate',               kind:'gate',       act1:'gated-community entrance assembly off the arterial: sliding leaf, call box, kerb returns - only on a gated/estate community, never an ordinary walled suburb'},
    6:{name:'garage',             kind:'building',   act1:'front-corner garage, steel roll door, dented', enter:'garage interior: 1-2 car bays, junk shelves, a door into the house'},
    /* THE FRONT YARD IS GRAVEL, WHICH IS THE MOST LAS VEGAS THING ABOUT A LAS VEGAS
       YARD AND THE ONE THAT SURVIVES A DEAD WORLD. This valley has paid people to tear
       lawns out since the early 2000s (the water authority's turf-removal rebate is the
       most successful programme of its kind in the country), so the default front yard
       here is DECORATIVE ROCK, not grass. Rock does not die: ten years on it is still
       rock, bleached, drifted into the low corners, weeds gone to nothing in the joints.
       This is NOT the graveyarded code 7. That was a TREE, and ACT 1 IS A DEAD WORLD --
       no vegetation ever. Gravel is not vegetation; it is the ground the vegetation was
       replaced with, twenty years before the lights went out. */
    11:{name:'gravel yard',       kind:'ground',     act1:'decorative desert gravel over weed fabric, the rock that replaced a lawn a long time before anybody left'},
    /* WHAT A DECADE LEAVES ON A FRONT YARD. Named with "debris" on purpose: the hazard
       classifier reads the LEGEND, so this lands in AMPLIFIES by derivation and the
       district he SPAWNS IN finally has ground that does something to a body. Not solid
       -- you walk through drift, you do not walk around it (PROP SOLIDITY IS PER TILE). */
    13:{name:'yard debris / drift',kind:'prop', solid:false, act1:'blown debris drifted against the kerb and the wall -- paper, a bin on its side, what the wind kept moving'},
    10:{name:'sidewalk',           kind:'walk',       act1:'cracked concrete sidewalk, one grid wide, hugging the kerb; weeds in the joints, no vegetation'},
    /* THE ONLY THING ON THIS PLOT THAT STANDS UP AND IS NOT A BUILDING. Named
       'street light' so the city page's ONE lamp rule -- legend name reads as a light
       standard -> draw the approved lamp body -- finds it the same way it finds the
       'streetlight' on the arterial and the 'pole light' in forty-three other districts.
       A pole blocks a body's cell, so it takes the kind default solid:true. */
    12:{name:'street light',      kind:'prop',       act1:'a residential street light on its pole at the back of walk, cobra head dark, the pole scuffed at knee height where the kerb takes it'},
    9:{name:'house upper floor',  kind:'building',   act1:'2-story house upper mass (taller top-down read)', enter:'the house floorplan upper story (bedrooms), reached by interior stairs'}
  };
  var NOTES={
    summary:'Walled tract-home neighborhood — cul-de-sac streets off the entrance, homes with front-garage driveways, packed lots, dead-dirt yards. WALLED always; GATED only if the community was rich enough to buy a gate (suburb = open street through the wall, gated/estate = a gate assembly).',
    reference:['Vegas suburb: ~14x8m house body + 6x6m front garage + 6m driveway on ~16m lots; ~85-90% single-family by land area; curvilinear cul-de-sacs, walled, few entries',
      'WALLED IS MANDATORY, GATED IS BOUGHT: Clark County Unified Development Code 30.64.020 requires a developer-installed decorative perimeter wall on a subdivision, so a wall signals nothing in this valley - every tract has one. A GATE is the thing a richer community paid for on top of it, and access gates carry their own 18ft setback from the property line on a collector or arterial.',
      'The American Housing Survey (2015, the last year it asked) put 5.9% of US households behind a wall or fence and 3.4% behind controlled access. Vegas sits far above both in absolute terms; the RATIO is what Paolo ruled and what the generator now builds - measured on the canon seed at 1.9% gated across 2,631 residential cells.'],
    layout:['Cul-de-sac streets branch off the entrance gate; homes line them on packed ~0.15-acre lots.',
      'Each home: a short driveway apron -> a front-corner garage -> the house body; 2-story homes add an upper-floor mass (code 9).',
      'A perimeter block wall; dead-dirt yards — NO vegetation ever in act 1.',
      'Cluster-aware: fills a cw x ch union as ONE connected neighborhood (snaps into 1x2 / 2x2).'],
    circulation:'Street-aware: ENTRANCES only on street edges (a corner exits two streets); roads reach every lot from the entrance (roadConnected). Driveways (code 3) + roads (code 1) are the drivable surface. GATED IS RICH: a gated/estate community gets a GATE ASSEMBLY (code 5) in the aperture; an ordinary walled suburb gets the STREET ITSELF (code 1) running through a gap in the block wall - same 7-tile aperture, different thing standing in it.',
    layering:'GROUND plane: roads, the one-grid SIDEWALK hugging every street (10), driveways, dead-dirt yards, gravel yards (11) (flat, walk/drive). PROP: yard debris drift (13, walk THROUGH) and the STREET LIGHT (12, solid, the one vertical on this plot that is not a building - it stands at the BACK OF WALK on the property line, never on the walk itself). STRUCTURES (¾ front face, solid): the house (2, ENTERABLE -> floorplan) and its garage (6, ENTERABLE -> car bays + a door into the house); the perimeter wall (4). The 2-story mass (9) is the same house drawing UP a second story (its footprint is the ground-floor cell; the upper story is height, reached inside by stairs). PORTAL: the neighborhood gate (5). Key layering: a house occupies its footprint cells (block) and rises with a front face toward the street; you enter via the front door or drive into the garage — outside shell becomes inside rooms.',
    decisions:['Every home has a proper street -> driveway -> front-garage (Paolo ruling).',
      'Every street wears a ONE-GRID SIDEWALK on both sides (code 10), broken only where a driveway crosses it (Paolo 7/31, LOCKED). A real cell in the generator, not a render-time band, so the city and the dossier see it too.',
      'Driveways are exactly 2 tiles wide x 3 long (Paolo 7/31, LOCKED).',
      'STREET LIGHTS (code 12) at the BACK OF WALK, 250 ft (102 tiles) between successive heads, STAGGERED on alternate kerbs -- researched local-residential practice (200-300 ft successive, 400-600 ft same side), not an invented number. The walk is attached to the kerb by Paolo 7/31, so there is no amenity strip and the pole goes on the property line behind it. Heads are DARK; the night glow belongs to the POWER network and only a live circuit lights one (CLUSTERED POWER / LIGHT=TERRITORY).',
      'MODULARITY LAW: must snap into 1x2 / 2x2, connected.',
      'Loops + garden-curve variants GRAVEYARDED (7/18 verdict) — THE BLOCK packed grid is the one canonical suburb block.']
  };
  /* UNCHANGED ON PURPOSE: still asked at LOAD time, so in the CITY app (where this
     module is inlined before the kit) it still no-ops exactly as it does today. */
  var _k0=null; try{ _k0=K(); }catch(e){}
  if(_k0&&_k0.register) _k0.register('suburb', { generate:generate, body:function(c){return c===2||c===9;}, category:'residential', palette:PALETTE, legend:LEGEND, notes:NOTES });

  var API={generate:generate,homeFootprints:homeFootprints,roadConnected:roadConnected,palette:PALETTE,legend:LEGEND,notes:NOTES,SZ:SZ,TILE:TILE};
  if(typeof module!=='undefined')module.exports=API;
  root.BohemiaSuburb=API;
})(typeof window!=='undefined'?window:(typeof globalThis!=='undefined'?globalThis:this));
