/* BOHEMIA TILE BANK -- THE LATE LOADER. Generated by tools/bohemia_city_chunk_tile_bank.py.
   Chunk 1 is a blocking tag in the page and carries every bank NAME. These are the
   sprites, 26.1 MB of them, and nothing on screen needs them to exist. They are pulled
   here rather than declared as <script defer> tags because a deferred tag still
   DOWNLOADS during the parse -- measured on a 3 Mbit phone, that put 26 MB in the pipe
   alongside the 1.75 MB the world was waiting for, and turned a five-second wait into
   twenty-nine.
   IN ORDER AND ONE AT A TIME: every chunk after the first MUTATES the banks chunk 1
   declared (Object.assign, push, TP_TILES[fam]=...), so out-of-order execution is not
   a slower world, it is a wrong one.
   AND NOT UNTIL THERE IS A WORLD. Waiting on pixels rather than on a timer or a load
   event: a canvas that has drawn a city has dozens of colours in it, a blank or
   single-fill one has a handful. If the world somehow never draws, the art loads
   anyway after 20 seconds -- late art is a disappointment, no art is a bug. */
(function(){
  var CHUNKS=["BOHEMIA_CITY_TILES_02.js", "BOHEMIA_CITY_TILES_03.js", "BOHEMIA_CITY_TILES_04.js", "BOHEMIA_CITY_TILES_05.js", "BOHEMIA_CITY_TILES_06.js", "BOHEMIA_CITY_TILES_07.js", "BOHEMIA_CITY_TILES_08.js", "BOHEMIA_CITY_TILES_09.js", "BOHEMIA_CITY_TILES_READY.js"];
  var i=0, going=false;
  function next(){
    if(i>=CHUNKS.length) return;
    var s=document.createElement("script");
    s.src=CHUNKS[i++];
    s.async=false;
    s.onload=next; s.onerror=next;
    document.head.appendChild(s);
  }
  function go(){ if(going)return; going=true; next(); }
  var tries=0;
  (function poll(){
    if(going) return;
    try{
      var c=document.getElementById("cv");
      if(c && c.width && c.height){
        var d=c.getContext("2d").getImageData(0,0,Math.min(c.width,120),Math.min(c.height,120)).data;
        var seen={}, n=0;
        for(var k=0;k<d.length;k+=4){ if(d[k+3]>8){ var v=(d[k]<<16)|(d[k+1]<<8)|d[k+2];
          if(!seen[v]){ seen[v]=1; if(++n>8) break; } } }
        if(n>8){ go(); return; }
      }
    }catch(e){}
    if(++tries*100 >= 20000){ go(); return; }
    setTimeout(poll,100);
  })();
})();
