/* BOHEMIA TILE BANK -- run after the last chunk lands. Generated by tools/bohemia_city_chunk_tile_bank.py.
   The page baked its Image objects at parse time, when the late banks were still
   empty; this is what tells it to bake them again and redraw. */
if (typeof __tilesArrived === "function") __tilesArrived();
else if (window.__tilesArrived) window.__tilesArrived();
