#!/usr/bin/env python3
"""
BOHEMIA QUESTBOOK LAW INDEX (7/26/26) - make the 240-file questbook MACHINE-READABLE
so a quest cook can never again "write in the style" instead of USING the corpus.

WHY THIS EXISTS (the failure it answers, recorded honestly): the S10-S21 batch was
written from CLAUDE.md's summary craft bullets and two addenda. The four masters -
1,527 craft findings, 693 flaw findings, 1,276 ports, 176 dissected dialogue nodes,
distilled out of 152 studied quests across 240 files - were never opened. Paolo
caught it. The art side already had REUSE-FIRST (a factory must document which bank
it opened, and the claimed reuse must actually open it); the quest side had no
equivalent, so skipping the corpus cost nothing and nobody noticed.

WHAT IT BUILDS
  records/BOHEMIA_QUESTBOOK_LAW_INDEX.json   the machine copy (the gate reads this)
  records/BOHEMIA_QUESTBOOK_LAW_INDEX.md     the human copy (Paolo reads this)

Every law gets a stable citable id:
  Q001.W4     craft law W4 of study #1        (CRAFT master)
  Q017.X2     flaw finding 2 of study #17     (FLAWS master, carries its >> LAW)
  Q001.P5     port 5 of study #1              (PORTS master, the build queue)
  Q001.N2     dissected dialogue node 2       (CONVERSATIONS master)

The parsers are deliberately dumb and total: they read the masters' own shapes and
never invent. A study that does not parse is REPORTED, never silently dropped.

  python3 tools/bohemia_questbook_index.py
"""
import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) or '.'
os.chdir(REPO)
QB = 'questbook'
OUT_JSON = 'records/BOHEMIA_QUESTBOOK_LAW_INDEX.json'
OUT_MD = 'records/BOHEMIA_QUESTBOOK_LAW_INDEX.md'

MASTERS = {
    'craft': ('BOHEMIA_CRAFT_MASTER_7_16_26.txt', 'W'),
    'flaws': ('BOHEMIA_FLAWS_MASTER_7_16_26.txt', 'X'),
    'ports': ('BOHEMIA_PORTS_MASTER_7_16_26.txt', 'P'),
    'convos': ('BOHEMIA_CONVERSATIONS_MASTER_7_16_26.txt', 'N'),
}

STUDY_RE = re.compile(r'^###\s+#(\d+)\s+(.*?)\s*$')
# craft:  "  W1  TITLE"      flaws: "  X  TITLE"
# ports:  "  ->  W1 (title"  convos: "  @  NODE NAME"
ENTRY_RE = {
    'craft': re.compile(r'^\s{2}W(\d+)\s+(.*?)\s*$'),
    'flaws': re.compile(r'^\s{2}X\s+(.*?)\s*$'),
    'ports': re.compile(r'^\s{2}->\s+(.*?)\s*$'),
    'convos': re.compile(r'^\s{2}@\s+(.*?)\s*$'),
}


def parse_master(kind):
    """-> {studyNum: {'title':..., 'entries':[{'id','title','body'}]}}"""
    fname, letter = MASTERS[kind]
    path = os.path.join(QB, fname)
    studies, cur, entry = {}, None, None
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        m = STUDY_RE.match(line)
        if m:
            cur = int(m.group(1))
            studies.setdefault(cur, {'title': m.group(2), 'entries': []})
            entry = None
            continue
        if cur is None:
            continue
        m = ENTRY_RE[kind].match(line)
        if m:
            n = len(studies[cur]['entries']) + 1
            num = m.group(1) if kind == 'craft' else str(n)
            title = m.group(2) if kind == 'craft' else m.group(1)
            entry = {'id': 'Q%03d.%s%s' % (cur, letter, num), 'title': title.strip(), 'body': ''}
            studies[cur]['entries'].append(entry)
            continue
        if entry is not None and line.strip():
            entry['body'] = (entry['body'] + ' ' + line.strip()).strip()
    return studies


def main():
    index = {'_meta': {
        'what': 'Machine-readable law index over the BOHEMIA questbook corpus. '
                'Every citable id resolves to a real finding in a real master file. '
                'Generated by tools/bohemia_questbook_index.py; never hand-edited.',
        'why': 'QUEST STUDY LAW (7/26/26): a .bq quest must CITE the corpus laws it '
               'applies, and gates/quest_study_gate.js proves the citation is real.',
    }, 'studies': {}, 'laws': {}}

    parsed = {k: parse_master(k) for k in MASTERS}
    all_nums = sorted(set().union(*[set(p) for p in parsed.values()]))
    for n in all_nums:
        title = ''
        for k in ('craft', 'ports', 'flaws', 'convos'):
            if n in parsed[k] and parsed[k][n]['title']:
                title = parsed[k][n]['title']
                break
        index['studies']['Q%03d' % n] = {'n': n, 'title': title,
                                         'counts': {k: len(parsed[k].get(n, {'entries': []})['entries'])
                                                    for k in MASTERS}}
        for k in MASTERS:
            for e in parsed[k].get(n, {'entries': []})['entries']:
                index['laws'][e['id']] = {'study': 'Q%03d' % n, 'studyTitle': title,
                                          'kind': k, 'title': e['title'], 'body': e['body'],
                                          'source': MASTERS[k][0]}

    os.makedirs('records', exist_ok=True)
    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(index, f, indent=1, sort_keys=True)

    lines = ['# BOHEMIA QUESTBOOK LAW INDEX (generated, never hand-edited)', '',
             'Every id here is CITABLE from a `.bq` quest and is machine-verified by',
             '`gates/quest_study_gate.js`. Regenerate with `python3 tools/bohemia_questbook_index.py`.',
             '', '- studies: %d' % len(index['studies']),
             '- citable laws: %d' % len(index['laws']), '']
    for k in MASTERS:
        lines.append('- %s laws (%s): %d' % (k, MASTERS[k][1],
                     sum(1 for v in index['laws'].values() if v['kind'] == k)))
    lines.append('')
    for sid in sorted(index['studies']):
        s = index['studies'][sid]
        lines.append('### %s  %s' % (sid, s['title']))
        for lid in sorted(l for l in index['laws'] if index['laws'][l]['study'] == sid):
            law = index['laws'][lid]
            lines.append('- `%s` **%s** %s' % (lid, law['title'], law['body'][:180]))
        lines.append('')
    open(OUT_MD, 'w', encoding='utf-8').write('\n'.join(lines))
    print('questbook index: %d studies, %d citable laws -> %s' %
          (len(index['studies']), len(index['laws']), OUT_JSON))
    for k in MASTERS:
        print('  %-7s %5d laws  (%s)' % (k, sum(1 for v in index['laws'].values()
                                                if v['kind'] == k), MASTERS[k][0]))


main()
