#!/usr/bin/env python3
"""BOHEMIA CITY BARKS -- the 244 lines finally reach a surface somebody sees.

*** THE MEASUREMENT THAT FORCED THIS, AND IT IS THE WORST ONE YET. ***
`linesFor` is called ZERO TIMES in slices/BOHEMIA_CITY_WORLD.html -- the frame
the player is actually looking at when they tap RUN. Measured in a browser, not
inferred: the module is inlined there with all 244 barks and all 19 reaction
buckets present and correct, and nothing in that surface has ever asked it for a
line.

HOW IT HID FOR THREE DAYS. The game is split across two frames and I had the
wrong one the whole time:
  BOHEMIA_RUN_CURRENT.html   SIM, RUN, reactionCtx, witnessResolution, the
                             person card (#idcard/#says) -- and the RUN tab does
                             NOT show it. It is parked in a hidden panel so
                             postMessage still finds it.
  BOHEMIA_CITY_WORLD.html    DAY, DQ, the wake card, pplPeople/pplAt/peoplePass,
                             the people you can actually walk past -- THIS is
                             what p-city shows, and this is the game.
So the mouth I built, the reactions I wired, and the gate that proves them all
live in the frame nobody opens. Every one of those gates is honestly green about
a surface the player never reaches. THIRD TIME THIS WEEK, and the biggest.

WHAT THIS DOES. The residents already walking the streets get to speak. A person
near you occasionally says one of his lines, in a bubble over their head, and
then shuts up. That is all. It is the single highest-return thing the corpus
says a one-person team can do:
  Q043.W4 AMBIENT BANTER AS CHARACTERIZATION -- "the cast comes alive through
  OVERHEARD relationships, not just quests -- cheap, high-impact life (a
  solo-dev-friendly technique)."
OVERHEARD is the word. Not opened in a card. Overheard, while you walk past.

WHAT IT ASKS FOR, and every field is something the city already knows about that
person -- nothing is invented and nothing new is tracked:
  role/act   BohemiaAgents.whereAt(p, minute) -- the sim's own words
  faction    the person's own
  when       night / heat / market / brownout, from pplCtx() and the clock
So the lookup lands on the specific buckets rather than falling through to the
generic ones, which is what made a 58-bucket table fire four buckets before.

LAWS IT OBEYS:
  120 BPM -- a bark starts on a beat and holds for a whole number of beats.
  READING SPEED -- the hold is derived from the line's own length at 14 cps with
    the same floor and ceiling bohemia_stage.js uses for the cutscenes (833ms /
    7s), because subtitle timing is a solved problem and guessing insults it.
  ONE MOUTH AT A TIME -- a street where four people talk at once is noise, not
    life. One bark on screen, ever.
  MECHANISM-MINE / CONTENTS-PAOLO'S -- not one word is written here. Every line
    comes out of BohemiaPeople.LINES, which is the WORDS tab's table, which he
    edits.

*** LANE NOTE, SAID OUT LOUD: THIS IS PEOPLE-LANE CODE INSIDE THE CITY LANE'S
FILE. *** It is additive -- one function and one call after peoplePass -- and it
touches no city logic, no render maths and no existing draw. It is here because
the people are here. CITY lane: if you want it moved, it is one block between two
markers and this tool regenerates it.

REUSE CHECK: cooks no pixels and opens no bank. It draws a rounded rect and text
with the canvas 2D API in the surface's own palette, and every word comes from
engine/bohemia_people.js.

  python3 tools/bohemia_city_barks_patch.py
Gate: gates/city_barks_gate.js
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CITY = os.path.join(ROOT, 'slices', 'BOHEMIA_CITY_WORLD.html')

BEGIN = '/* ===== BOHEMIA CITY BARKS (generated by tools/bohemia_city_barks_patch.py) ===== */'
END = '/* ===== END BOHEMIA CITY BARKS ===== */'

# WHERE THE BLOCK GOES vs WHERE THE CALL GOES, and the first cut got it wrong.
# I anchored the whole block on the peoplePass CALL SITE -- which is inside the
# draw function -- so every `function barkHold(...)` was a nested declaration and
# `barkHold is not defined` came straight back from the browser. Declarations go
# at TOP LEVEL, next to the people functions they belong with; only the one-line
# call goes in the draw.
DECL_ANCHOR = 'function peoplePass(ox, oy, C) {'
# THE ONE LINE ADDED INSIDE peoplePass: record WHERE each body was actually
# blitted, so a bark can only ever come out of a person the renderer really
# drew. Placed next to the existing drewFaces push, which is the same idea the
# facing gate already relies on.
DREW_ANCHOR = ("      drewFaces.push({ id: p.id, dir: dir, "
               "home: (fx === p.home[0] && fy === p.home[1]) });")
DREW_ADD = "\n      BARK_DREW.push({ p: p, at: [fx, fy] });   /* __CITY_BARKS__ */"
ANCHOR = '  peoplePass(ox,oy,C);\n'
CALL = '  try{ barkPass(ox,oy,C); }catch(_e){}   /* __CITY_BARKS__ */\n'

BLOCK = BEGIN + r'''
/* ---- THE STREET HAS A MOUTH ------------------------------------------------
   engine/bohemia_people.js has carried 244 written lines and 66 reactions since
   8/12 and this surface has never once called linesFor(). The lines were real,
   the gates were green, and they were in the other frame. This is the call.

   NOTHING IS AUTHORED HERE. Every string comes out of his LINES table (the same
   rows the WORDS tab edits), chosen by facts the city already knows about that
   person. If he rewrites a line in WORDS, the street says the new one. */
var BARK = { p: null, text: '', until: 0, at: null, beat: -1, next: 0 };
var BARK_SEEN = {};                 /* who has spoken recently, so it moves around */
var BARK_DREW = [];                 /* filled by peoplePass: who is ON SCREEN */

/* READING SPEED, the same numbers the cutscenes use (bohemia_stage.js): 14
   characters per second, never under 833ms, never over 7s. Netflix ships 20cps
   for adults and 17 for children with a 5/6s floor; 14 is the conservative end
   of the general 12-14 band, which is right for a line you read while walking
   and are not expecting. Then QUANTIZED UP to a whole beat -- 120 BPM law. */
function barkHold(text){
  var ms = Math.max(833, Math.min(7000, (String(text).length / 14) * 1000));
  return Math.ceil(ms / 500) * 500;
}

/* WHAT THIS PERSON IS, in the sim's own vocabulary. role:act keys were written
   against bohemia_agents.js's exact words, so they only fire if we ask with the
   same words -- which is the whole reason the bark table has a role:act axis. */
function barkOpts(p){
  var o = {};
  try {
    var b = BohemiaAgents.whereAt(p, T.min | 0);
    if (b) { o.at = b.what || b.where || null; }
  } catch (_e) {}
  try { o.faction = p.faction || null; } catch (_e) {}
  /* SITUATION, from the same context the population module already builds. */
  try {
    var c = pplCtx(p);
    if (c.dark) o.when = 'night';
    else if (!c.powered) o.when = 'brownout';
    else if ((T.min | 0) > 11 * 60 && (T.min | 0) < 16 * 60) o.when = 'heat';
  } catch (_e) {}
  return o;
}

/* WHO SPEAKS. Close enough to overhear, outdoors, not the player's own cell,
   and not the same person twice in a row -- a street where one man monologues
   is worse than silence. */
function barkPick(){
  var best = null, bestD = 99;
  try {
    /* *** ONLY SOMEBODY YOU CAN SEE. *** The first cut scanned the population
       and picked the nearest person, which at 06:00 is somebody ASLEEP INSIDE A
       HOUSE two tiles away: the line resolved correctly, the bubble drew over a
       roof, and nothing was on screen to attach it to. Overhearing through
       masonry is wrong and a speech bubble over nobody is a visible bug.
       peoplePass already records every body it actually blitted, so THAT is the
       list. If the renderer did not draw them, they do not speak -- the two can
       never disagree, because it is one list. */
    var drew = BARK_DREW;
    for (var i = 0; i < drew.length; i++) {
      {
        var p = drew[i].p, at = drew[i].at;
        if (!at) continue;
        if (at[0] === hx && at[1] === hy) continue;      /* OCCUPANCY: that is you */
        /* *** NOBODY TALKS THROUGH A WALL. *** Caught by looking: at 06:00 the
           whole block is HOME, the nearest person was two tiles away and INSIDE
           A HOUSE, and the bark fired for somebody who is not drawn. A bubble
           over a roof is nonsense and overhearing through masonry is worse. The
           population module already answers this -- placeFor() returns 'home'
           for somebody who stayed in -- so ask it rather than inventing a test.
           This is also why the street goes quiet at night, which is correct:
           laws say nobody patrols the dark, and an empty street should sound
           empty. */
        var d = Math.abs(at[0] - hx) + Math.abs(at[1] - hy);
        if (d > 7) continue;                              /* earshot, not telepathy */
        if (BARK_SEEN[p.key || p.id] && d >= bestD) continue;
        if (d < bestD) { best = { p: p, at: at, d: d }; bestD = d; }
      }
    }
  } catch (_e) { return null; }
  return best;
}

function barkTick(now){
  if (BARK.p && now < BARK.until) return;
  if (BARK.p) { BARK.p = null; BARK.next = now + 1500; return; }   /* a breath after */
  /* *** ELAPSED TIME, NOT A BEAT MULTIPLE. *** The first cut said
     `if (beat % 8) return;` -- look every four seconds -- which is correct on a
     surface that redraws every frame and USELESS here. This city is
     I-MOVE-YOU-MOVE: it draws when the player acts, so the odds of a draw
     landing exactly on a beat divisible by eight are small, and measured over
     forty walked steps NOBODY EVER SPOKE. The clock has to be a deadline the
     next draw can be LATE for, never an instant it has to hit.
     Still quantized where it counts: the HOLD is a whole number of beats. */
  if (now < (BARK.next || 0)) return;
  BARK.next = now + 4000;
  var beat = Math.floor(now / 500);
  BARK.beat = beat;
  var pick = barkPick();
  if (!pick) return;
  var lines;
  try { lines = BohemiaPeople.linesFor(pick.p, barkOpts(pick.p)); } catch (_e) { return; }
  if (!lines || !lines.length) return;
  var k = pick.p.key || pick.p.id || 'x';
  var idx = Math.abs(((beat * 2654435761) ^ String(k).length) >>> 0) % lines.length;
  BARK.p = pick.p; BARK.at = pick.at; BARK.text = lines[idx];
  BARK.until = now + barkHold(BARK.text);
  BARK_SEEN[k] = 1;
  if (Object.keys(BARK_SEEN).length > 24) BARK_SEEN = {};
}

/* THE BUBBLE. Drawn in the surface's own palette, above their head, clamped so
   it never leaves the screen -- a line you cannot read is a line that did not
   happen (the whole lesson of 8/14). */
function barkPass(ox, oy, C){
  /* peoplePass filled BARK_DREW this frame; consume it, then clear for the next. */
  barkTick(typeof performance !== 'undefined' ? performance.now() : Date.now());
  if (!BARK.p || !BARK.text || !BARK.at) return;
  var sx = ox + BARK.at[0] * C, sy = oy + BARK.at[1] * C;
  if (sx < -C * 4 || sy < -C * 6 || sx > cv.width + C * 4 || sy > cv.height + C * 4) return;
  /* *** THE CITY'S 2D CONTEXT IS `g`, NOT `ctx`. *** The first cut opened with
     `var g = ctx;` -- which is BOTH a reference to something this frame does not
     have AND a shadow of the real one -- so barkPass threw on its first line,
     every single call, and the try/catch around the call swallowed it in
     silence. Everything upstream measured perfectly: a body was drawn, a person
     was picked, a real line came back. Nothing reached the screen.
     A CAUGHT EXCEPTION IN A DRAW PATH IS A FEATURE THAT SILENTLY DOES NOTHING,
     and that is worse than a crash, because a crash gets fixed. */
  var gg = g;
  gg.save();
  gg.font = '11px ui-monospace,monospace';
  var txt = String(BARK.text);
  var maxW = Math.min(210, cv.width - 16);
  /* wrap on words, never mid-word */
  var words = txt.split(' '), lines = [], cur = '';
  for (var i = 0; i < words.length; i++) {
    var t = cur ? cur + ' ' + words[i] : words[i];
    if (gg.measureText(t).width > maxW && cur) { lines.push(cur); cur = words[i]; }
    else cur = t;
  }
  if (cur) lines.push(cur);
  var lh = 14, padX = 7, padY = 6;
  var w = 0;
  for (var j = 0; j < lines.length; j++) w = Math.max(w, gg.measureText(lines[j]).width);
  w += padX * 2;
  var h = lines.length * lh + padY * 2;
  var bx = Math.max(4, Math.min(cv.width - w - 4, sx + C / 2 - w / 2));
  var by = Math.max(4, sy - h - C * 0.9);
  gg.globalAlpha = 0.92;
  gg.fillStyle = '#0d0b07';
  gg.strokeStyle = '#2a2114';
  gg.lineWidth = 1;
  if (gg.roundRect) { gg.beginPath(); gg.roundRect(bx, by, w, h, 4); gg.fill(); gg.stroke(); }
  else { gg.fillRect(bx, by, w, h); gg.strokeRect(bx, by, w, h); }
  gg.globalAlpha = 1;
  gg.fillStyle = '#cdbd8a';
  gg.textBaseline = 'top';
  for (var m = 0; m < lines.length; m++) gg.fillText(lines[m], bx + padX, by + padY + m * lh);
  gg.restore();
}
''' + END


def main():
    if not os.path.exists(CITY):
        sys.exit('FAIL: ' + CITY + ' not found')
    s = open(CITY, encoding='utf-8').read()

    # 1. the block. REPLACE, NEVER APPEND (8/11: an insert tool run twice is a
    #    duplication tool). Running this ten times leaves the file identical.
    i = s.find(BEGIN)
    if i >= 0:
        j = s.find(END, i)
        if j < 0:
            sys.exit('REFUSING TO WRITE: the bark block has an opening marker and no closing one.')
        s = s[:i] + BLOCK + s[j + len(END):]
    else:
        n = s.count(DECL_ANCHOR)
        if n != 1:
            sys.exit('REFUSING TO WRITE: the peoplePass declaration resolves %d times, not 1.' % n)
        s = s.replace(DECL_ANCHOR, BLOCK + '\n' + DECL_ANCHOR, 1)
    if CALL not in s:
        n = s.count(ANCHOR)
        if n != 1:
            sys.exit('REFUSING TO WRITE: cannot place the bark call; anchor resolves %d times.' % n)
        s = s.replace(ANCHOR, ANCHOR + CALL, 1)

    # the one line inside peoplePass that records what was drawn
    if DREW_ADD.strip() not in s:
        n = s.count(DREW_ANCHOR)
        if n != 1:
            sys.exit('REFUSING TO WRITE: the drewFaces anchor resolves %d times, not 1.' % n)
        s = s.replace(DREW_ANCHOR, DREW_ANCHOR + DREW_ADD, 1)
    # and peoplePass must start each frame with an empty list
    START = 'function peoplePass(ox, oy, C) {'
    if 'BARK_DREW = [];   /* __CITY_BARKS__ */' not in s:
        s = s.replace(START, START + '\n  BARK_DREW = [];   /* __CITY_BARKS__ */', 1)

    open(CITY, 'w', encoding='utf-8').write(s)
    print('CITY BARKS: block %s, call %s' % ('replaced' if i >= 0 else 'inserted', 'present'))
    print('  city : %.1f MB' % (os.path.getsize(CITY) / 1e6))


if __name__ == '__main__':
    main()
