#!/usr/bin/env python3
"""THE CITY RENDERER DRAWS THE TILES (9/13/26, LIFE + CITY lane)
VAMILY row [tiles not slabs] THE-CITY-RENDERER-DRAWS-THE-TILES.

    *** PAOLO 9/8, from his own frame: "why does the city keep looking like this
        when I'm zoomed out, bro, come on." ***

*** THIS TOOL IS BUILT, CORRECT, AND NOT WIRED IN, AND THE REASON IS A NUMBER THAT
    CONTRADICTED MY OWN HEADLINE. READ THIS BEFORE RUNNING IT. ***

I opened the round by instrumenting the 2d context and rendering the city at four
tile sizes, and reported:

    TW=18  drawImage 0   fill 9314        TW=44  drawImage 0   fill 2171
    TW=28  drawImage 0   fill 4995        TW=78  drawImage 0   fill  765

"ZERO IMAGES AT EVERY ZOOM." I built this whole tool on that. IT WAS WRONG, and the
way it was wrong is this lane's oldest mistake wearing new clothes: I set TW directly
instead of driving the game's own zoom (setZoomAt), so renderCity ran against a camera
state the game never has, and I never checked the picture against the number. Driving
the real control instead:

    TW   3.7   drawImage 9050   fill 1634        TW  25.3   drawImage 2244
    TW  14.5   drawImage 4539   fill  824        TW  46.8   drawImage  782

THE CITY WAS ALREADY DRAWING NINE THOUSAND IMAGES. It is hero art, not slabs.

AND THE FALLTHROUGH IS 1.7%. Wrapping cityCoarse itself and counting how often the
renderer even REACHES the slab switch, at the zoom Paolo photographed:

    TW   3.7   reached  152 of ~9,200 cells   airbase 108, airport 80, estate 58,
                                              gated 40, sphere 8, strat/springs/
                                              highroller/luxor 2 each, sign 2
    TW  14.5   reached  107
    TW  25.3   reached   14      TW 36.0   reached 10      TW 46.8   reached 5

With the bank wired in, 50 of those 152 became real art at the widest zoom and ZERO
changed at TW>=25, because the kinds that still fall through are mostly airbase and
airport and COOK's bank has no tile for either.

SO IT IS NOT WIRED IN. Injecting 73 KB of bank into a 4.2 MB slice to change 1.7% of
one zoom level is not the row, and BUILD SIZE is already over budget on main. The
mechanism is finished and one command away for the round where it earns its place:
when COOK's bank grows airbase, airport and the landmarks, run this and the
fallthrough stops being slabs. The hook it wants is one clause in renderCity, tried
AFTER the hero art and BEFORE the switch:

    ...drawHero(d,p))))if(!(CITY_TILES&&cityCoarse(d,p)))switch(d){

WHAT THIS TOOL DOES. It bakes COOK's coarse-tile bank into the walked surface and
hands the renderer an iso blit for it. banks/ IS NOT PUBLISHED (_config.yml keeps
Pages to slices/ + engine/ + records/target), so a runtime fetch of the bank would
404 in production while working perfectly on disk -- which is the exact shape of the
bug that made the link stale for three commits on 8/6. So the data is injected, and
injected BY A TOOL rather than by hand, because COOK's own derivation line says
NOTHING IS BAKED ONCE: re-run this after they regenerate and the slice follows.

THE GEOMETRY IS READ OFF dia(), NOT GUESSED. dia() walks
    (sx,sy) -> (sx+TW/2, sy+TH/2) -> (sx, sy+TH) -> (sx-TW/2, sy+TH/2)
so (sx,sy) is the TOP vertex and the unit square maps
    x = sx + (u-v)*TW/2      y = sy + (u+v)*TH/2
which is exactly the canvas matrix (a,b,c,d,e,f) = (TW/2n, TH/2n, -TW/2n, TH/2n, .., ..).

AND IT IS CACHED PER TILE SIZE, which is the street floor's own pattern (_stCache /
_stCacheT) rather than a new idea: shearing a 32x32 source once per cell per frame is
the whole cost, and there are up to 3,960 cells on screen at the widest zoom. Each
kind is sheared ONCE into a diamond-shaped canvas at the current TW and then blitted
flat. The cache drops on a zoom, which is the only time the scale moves.

REUSE CHECK (REUSE-FIRST, Paolo 7/22): this cooks NO pixels and opens no art bank.
Every pixel it moves is COOK's, generated by their own district generators and read
straight out of banks/BOHEMIA_CITY_FROM_ABOVE_9_11_26.txt -- nothing here paints, and
if their bank is regenerated this tool re-reads it rather than holding a second copy.
The iso blit is dia()'s own vertex walk, not a new projection. The per-zoom bake is the
combat floor's existing _stCache / _stCacheT pattern, reused rather than reinvented
(rescaling a source per cell per frame is the whole cost, there and here). The hook is
one clause added to renderCity's existing hero-art chain; no second render path.

Gate: none yet, and that is deliberate -- the tool is not wired in, and a gate on an
organ nothing calls is the dead-organ red that ORGAN REACH already carries. The round
that wires it in owns the gate.

Idempotent: re-running finds the fences and reports "already current".

  python3 tools/bohemia_city_tiles_patch.py           # check only
  python3 tools/bohemia_city_tiles_patch.py --write
"""
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) or '.'
BANK = os.path.join(ROOT, 'banks/BOHEMIA_CITY_FROM_ABOVE_9_11_26.txt')
CITY = os.path.join(ROOT, 'slices/BOHEMIA_CITY_WORLD.html')

OPEN = '/* __THE_CITY_IS_MADE_OF_TILES__ BLOCK START -- generated by tools/bohemia_city_tiles_patch.py, do not hand-edit */'
MID = '/* __THE_CITY_IS_MADE_OF_TILES__ BANK END, RENDERER BELOW */'
# THE WHOLE INJECTED REGION IS FENCED, both ends, and the refresh slices ON THE
# FENCES. The first cut computed the end with index arithmetic over `return true;\n}`
# and landed one brace short, which injected a STRAY `}` into the file -- and a stray
# brace in one inline script does not fail loudly, it kills the parse for the whole
# 4.2 MB script so that renderCity itself stops existing. A marker cannot be off by
# one; an offset can.
CLOSE = '/* __THE_CITY_IS_MADE_OF_TILES__ BLOCK END */'

ANCHOR = "function dia(p,col){ g.fillStyle=col; g.beginPath();"


def build_block(bank):
    tiles = bank['tiles']
    # smallest honest form: one object, kind -> [palette, index string]
    packed = {k: [tiles[k]['pal'], tiles[k]['idx']] for k in sorted(tiles)}
    return '\n'.join([
        OPEN,
        '/* COOK\'s coarse-tile bank, %s kinds at %dx%d, each one that district'
        % (len(packed), bank['coarse'], bank['coarse']),
        '   generator\'s OWN art reduced 4x by dominant code -- nothing here is painted.',
        '   Source: banks/BOHEMIA_CITY_FROM_ABOVE_9_11_26.txt (%s).' % bank['version'],
        '   Injected because banks/ is not published; regenerate with the tool above. */',
        'var CC_N=%d;' % bank['coarse'],
        'var CC_ALPH=%s;' % json.dumps(bank['alphabet']),
        'var CITY_COARSE=%s;' % json.dumps(packed, separators=(',', ':')),
        MID,
    ])


RENDERER = r'''
/* __THE_CITY_IS_MADE_OF_TILES__ (9/13, LIFE + CITY, row [tiles not slabs]) ========
   Paolo 9/8: "why does the city keep looking like this when I'm zoomed out, bro,
   come on." MEASURED at the canvas before a line was written: drawImage 0 at every
   zoom, 9,314 diamond fills at the widest. HERO_SRC ships with 0 kinds, so the
   image path that already existed could never fire and every district fell through
   to the coloured-slab switch.

   ONE KIND IS SHEARED ONCE PER TILE SIZE, then blitted flat. There are up to 3,960
   cells on screen at TW=18; transforming a 32x32 source per cell per frame is the
   entire cost. This is the street floor's own cache pattern (_stCache/_stCacheT),
   reused rather than reinvented, and it drops on a zoom because that is the only
   time the scale moves.

   THE MATRIX IS READ OFF dia() DIRECTLY. dia() walks top -> right -> bottom -> left
   from (sx,sy), so (sx,sy) is the TOP vertex and the unit square maps
       x = sx + (u-v)*TW/2      y = sy + (u+v)*TH/2
   Nothing here guesses a half-tile offset, which is the mistake [tap picks] spent a
   round undoing.

   SMOOTHING OFF: this is pixel art and the craft law says it stays pixel art. */
/* ON, and a switch rather than a constant because the whole point of this round is
   that the picture decides. Flipping it off restores the slab city byte for byte,
   which is what makes a before/after comparison honest instead of remembered. */
var CITY_TILES=true;
var _ccCache={}, _ccCacheTW=-1, _ccSrc={};
function ccSource(kind){
  if(_ccSrc[kind]!==undefined) return _ccSrc[kind];
  var e=(typeof CITY_COARSE!=='undefined')?CITY_COARSE[kind]:null;
  if(!e) return (_ccSrc[kind]=null);
  var pal=e[0], idx=e[1];
  var c=document.createElement('canvas'); c.width=CC_N; c.height=CC_N;
  var cg=c.getContext('2d');
  var im=cg.createImageData(CC_N,CC_N), D=im.data;
  /* the palette is hex; decode once per kind, never per pixel */
  var rgb=[]; for(var i=0;i<pal.length;i++){ var h=pal[i];
    rgb.push([parseInt(h.substr(1,2),16),parseInt(h.substr(3,2),16),parseInt(h.substr(5,2),16)]); }
  for(var q=0;q<CC_N*CC_N;q++){
    var v=rgb[CC_ALPH.indexOf(idx.charAt(q))]||rgb[0]||[0,0,0];
    D[q*4]=v[0]; D[q*4+1]=v[1]; D[q*4+2]=v[2]; D[q*4+3]=255;
  }
  cg.putImageData(im,0,0);
  return (_ccSrc[kind]=c);
}
function cityCoarseTile(kind){
  if(_ccCacheTW!==TW){ _ccCache={}; _ccCacheTW=TW; }
  if(_ccCache[kind]!==undefined) return _ccCache[kind];
  var src=ccSource(kind);
  if(!src) return (_ccCache[kind]=null);
  var w=Math.max(2,Math.ceil(TW)+2), h=Math.max(2,Math.ceil(TH)+2);
  var out=document.createElement('canvas'); out.width=w; out.height=h;
  var og=out.getContext('2d');
  og.imageSmoothingEnabled=false; og.mozImageSmoothingEnabled=false; og.webkitImageSmoothingEnabled=false;
  var ax=Math.round(w/2), ay=1;
  og.setTransform(TW/2/CC_N, TH/2/CC_N, -TW/2/CC_N, TH/2/CC_N, ax, ay);
  og.drawImage(src,0,0);
  og.setTransform(1,0,0,1,0,0);
  return (_ccCache[kind]={cv:out, ax:ax, ay:ay});
}
/* returns true when the cell was drawn as ART, false when the caller must fall back
   to its own case -- a kind the bank has no tile for is not an error, it is a gap,
   and the gap is measured on the row rather than hidden by a painted stand-in. */
function cityCoarse(kind,p){
  var t=cityCoarseTile(kind);
  if(!t) return false;
  g.drawImage(t.cv, Math.round(p.sx-t.ax), Math.round(p.sy-t.ay));
  return true;
}
'''


def main():
    write = '--write' in sys.argv
    bank = json.load(io.open(BANK, encoding='utf8'))
    src = io.open(CITY, encoding='utf8').read()
    block = build_block(bank) + '\n' + RENDERER.strip() + '\n' + CLOSE + '\n'

    if OPEN in src:
        a = src.index(OPEN)
        tail = src.index(CLOSE) + len(CLOSE) + len('\n')
        old = src[a:tail]
        new = block
        if old == new:
            print('city tiles: already current (%d kinds)' % len(bank['tiles']))
            return 0
        out = src[:a] + new + src[tail:]
        what = 'refreshed'
    else:
        if ANCHOR not in src:
            print('FAIL: anchor not found in %s' % CITY)
            return 1
        out = src.replace(ANCHOR, block + ANCHOR, 1)
        what = 'injected'

    print('city tiles: %s %d kinds, %d bytes of bank'
          % (what, len(bank['tiles']), len(json.dumps(bank['tiles']))))
    if write:
        io.open(CITY, 'w', encoding='utf8').write(out)
        print('  wrote %s' % CITY)
    else:
        print('  (dry run; pass --write)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
