#!/usr/bin/env python3
"""
BOHEMIA RUN PERSON FACTS (7/31/26) — THE RUN'S STREET EMPTIES AT MIDDAY TOO.

HE PLAYS THE RUN. That is this lane's standing rule and it is why this tool
exists at all: on 7/31 the CITY tab learned that the Mojave clears a street
between 11:00 and 16:00 and the RUN did not, so the two surfaces agreed on the
HEAD-COUNT and disagreed on the DAY. One city, two renderers, two different
afternoons.

THE BACKLOG SAID THIS WAS BLOCKED, AND THE BACKLOG WAS WRONG. It said the fix
was five lines in bohemia_agents.js (an opts.personFor hook that would let a
caller supply `kind` and `shift` to makeAgent), which is WORLD's module and not
this lane's to write. That framing was the mistake. kind and shift are WHEN and
WHAT KIND -- agents.js's half, correctly, and nothing here wants them. What the
run was missing is WHICH PLACE UNDER A CONDITION, which is bohemia_population's
half, and a caller can apply its own half to its own agents without WORLD's file
changing by one character. It did not change. The split this lane wrote down on
7/31 turned out to be the unblock, not the obstacle.

WHAT IT DOES, in the run's own dev source:

  1. builds one PERSON RECORD per agent the run already materialised, through
     BohemiaPopulation.peopleForAgents -> personFields (ONE DERIVATION POINT)
     then the overrides layer, in that order, so the run can never draw a body
     that a mass edit has not been applied to;
  2. rewrites each agent's `sched` through shiftEdges (the personal morning) and
     conditionSchedule (heat, dark, wet), both of which are this module's;
  3. re-applies both whenever BohemiaPopulation.rulesVersion() moves, so a bulk
     edit made after boot reaches bodies that are already walking;
  4. records what the DRAW actually painted in window.__RUN_PPL_DRAWN.

IT IS NOT A DRAW-TIME LIE, AND THAT WAS NAMED AS A WRONG ANSWER BEFORE IT WAS
AVOIDED. The run's sim reads agent.sched through whereAt() on EVERY tick
(bohemia_agents.js step()), so a conditioned block makes the body genuinely walk
to its own door and go inside. Hiding people in the draw while the sim still
walks them down the street would have been the cheap version and it stays
forbidden.

WHAT IT DELIBERATELY DOES NOT DO: it does not touch `role`. agents.js picks the
archetype from its own hash and keeps it. This lane's law is that agents.js owns
WHEN and WHAT KIND and this module owns WHICH PLACE, WHICH CONDITIONS, WHICH
EDGES. Overriding role here would merge the two modules, which is the one thing
the split exists to prevent.

WHAT IT CANNOT DO YET, STATED RATHER THAN FAKED: the run has no weather and no
per-cell power reading, so ctx ships {} -- a clear, unpowered day, which is 88%
of the valley by the CLUSTERED POWER law and the honest default. When the run
gains weather, the ctx object here is the one line that has to learn about it.

REUSE CHECK: cooks ZERO pixels and opens no bank. Every function it calls
already existed (BohemiaPopulation.peopleForAgents / shiftEdges /
conditionSchedule / rulesVersion, BohemiaAgents.agentsForBlock). Nothing is
created; a schedule the agent module already built is conditioned in place.

TASTE CHECK: produces no candidates and reaches Paolo's thumbs with nothing.

PATCHES THE DEV SOURCE, NOT THE BUILD. slices/BOHEMIA_RUN_CURRENT.html is
GENERATED by tools/build_run_slice.js; patching it would be erased by the very
next build.

Idempotent AND re-appliable: strips its own previous injection by delimiter and
puts the current version back. Refuses outright if a delimiter has gone missing,
because half a strip is worse than no strip.

  python3 tools/bohemia_run_person_facts_patch.py && node tools/build_run_slice.js
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) or '.'
os.chdir(REPO)
SRC = 'slices/BOHEMIA_RUN_SLICE_7_26_26.html'

OPEN_ = '/* ==== RUN PERSON FACTS (7/31) ==== */'
CLOSE = '/* ==== /RUN PERSON FACTS ==== */'

run = open(SRC, encoding='utf8').read()

# ---- strip a previous injection, all of them, by delimiter ------------------
if OPEN_ in run:
    if CLOSE not in run:
        sys.exit('RUN PERSON FACTS: opening delimiter present with no close. '
                 'Refusing to guess where the old block ended.')
    n_open, n_close = run.count(OPEN_), run.count(CLOSE)
    if n_open != n_close:
        sys.exit('RUN PERSON FACTS: %d open vs %d close delimiters. Refusing.'
                 % (n_open, n_close))
    run = re.sub(re.escape(OPEN_) + r'.*?' + re.escape(CLOSE) + r'\n?', '', run,
                 flags=re.S)
    print('  (previous RUN PERSON FACTS injection stripped; re-applying)')

# ---- 1. condition the agents the run just built ----------------------------
ANCHOR_1 = """    var _agents = BohemiaAgents.agentsForBlock(seed, feet, [], fpOf,
      (_rate!=null) ? {occupiedRate:_rate} : {});
"""
if run.count(ANCHOR_1) != 1:
    sys.exit('RUN PERSON FACTS: agentsForBlock anchor not found exactly once '
             '(%d). The run source moved; fix the anchor, do not loosen it.'
             % run.count(ANCHOR_1))

BLOCK_1 = OPEN_ + """
    /* WHO THEY ARE, not just how many. The zone map above answers HOW MANY
       people live on this block; this answers what each of them is like, and
       then rewrites their day with their own conditions on it.

       THE SPLIT, because it is the whole reason this is legal from here:
       bohemia_agents.js owns WHEN and WHAT KIND (it just picked every role and
       built every schedule above, and none of that is touched).
       bohemia_population.js owns WHICH PLACE, WHICH CONDITIONS, WHICH EDGES.
       Conditioning a schedule the agent module built is this module's own half
       applied to this surface's own agents - no fork, no second sim, no change
       to WORLD's file.

       AND THE SIM REALLY WALKS IT: step() reads agent.sched through whereAt()
       every tick, so at 13:00 these bodies path to their own doors and go
       inside. Nothing is hidden at draw time. */
    try{ if(typeof BohemiaPopulation!=='undefined' && BohemiaPopulation.conditionAgents){
      var _zone=null;
      try{ if(WORLD) _zone=BohemiaPopulation.zoneAt(WORLD, POWERMAP, CELL[0], CELL[1], SEED); }catch(_ez){}
      /* ctx is EMPTY ON PURPOSE: the run has no weather and no per-cell power
         reading yet, so this is a clear unpowered day - 88% of the valley by
         the CLUSTERED POWER law. When the run gains weather this object is the
         one line that learns about it. */
      RUN_PEOPLE = BohemiaPopulation.peopleForAgents(_agents, CELL[0], CELL[1], SEED, _zone);
      RUN_PPL_CTX = {};
      BohemiaPopulation.conditionAgents(_agents, RUN_PEOPLE, RUN_PPL_CTX);
      RUN_RULES_V = BohemiaPopulation.rulesVersion();
    } }catch(_ep){ RUN_PEOPLE=null; }
""" + CLOSE + "\n"

run = run.replace(ANCHOR_1, ANCHOR_1 + BLOCK_1)

# ---- 2. state + the re-apply a mass edit needs ------------------------------
ANCHOR_2 = "var FACES={}, _APOS={}, NPC_LOOK_SEED=0x5eed;\nfunction updateFaces(){\n  if(!SIM) return;\n"
if run.count(ANCHOR_2) != 1:
    sys.exit('RUN PERSON FACTS: updateFaces anchor not found exactly once (%d).'
             % run.count(ANCHOR_2))

BLOCK_2 = OPEN_ + """
/* A MASS EDIT MADE AFTER BOOT HAS TO REACH BODIES THAT ARE ALREADY WALKING.
   Paolo's 7/29 condition on the people was that editing them in bulk must
   actually work, and a surface that conditions once at build time would keep
   serving pre-edit days forever. rulesVersion() is an integer that moves on
   any mutation, so this is a compare-and-skip on the frame path, not work. */
var RUN_PEOPLE=null, RUN_PPL_CTX=null, RUN_RULES_V=-1;
function reconditionPeople(){
  if(!SIM || !RUN_PEOPLE) return 0;
  try{
    /* re-derive through the overrides layer FIRST - an edit changes what a
       person IS, and the conditions are read off that. */
    RUN_PEOPLE = BohemiaPopulation.peopleForAgents(SIM.agents, CELL[0], CELL[1], SEED,
                   RUN_PEOPLE.length? RUN_PEOPLE[0].zone : null);
    var n = BohemiaPopulation.conditionAgents(SIM.agents, RUN_PEOPLE, RUN_PPL_CTX||{});
    RUN_RULES_V = BohemiaPopulation.rulesVersion();
    return n;
  }catch(_e){ return 0; }
}
""" + CLOSE + "\n"

ANCHOR_2_NEW = (BLOCK_2 + "var FACES={}, _APOS={}, NPC_LOOK_SEED=0x5eed;\n"
                "function updateFaces(){\n  if(!SIM) return;\n"
                + OPEN_ + "\n"
                "  if(typeof BohemiaPopulation!=='undefined' && RUN_PEOPLE &&\n"
                "     RUN_RULES_V!==BohemiaPopulation.rulesVersion()) reconditionPeople();\n"
                + CLOSE + "\n")
run = run.replace(ANCHOR_2, ANCHOR_2_NEW)

# ---- 3. record what the DRAW actually painted -------------------------------
# VERIFY ON THE REAL SURFACE, and the sharper half of it: a gate that calls the
# helper instead of reading the render is a gate that cannot fail. This lane
# already shipped one of those and had to sabotage its own draw to find out.
ANCHOR_3 = """                      ring:null, fb:['#8f7a56','#5f7486','#9a8452','#7a5a4a','#6a7a6a'][(a.seed>>>0)%5] }); } }
"""
if run.count(ANCHOR_3) != 1:
    sys.exit('RUN PERSON FACTS: body-push anchor not found exactly once (%d).'
             % run.count(ANCHOR_3))

BLOCK_3 = OPEN_ + """
      /* WHAT WAS PAINTED, not what a helper says would be painted. A gate that
         asks a helper instead of reading the render passed 18/18 with the draw
         deliberately sabotaged - this lane shipped that mistake once, on 7/31.
         This is the neighbour bodies that actually went into the paint list
         this frame, by id, and it is what the gate reads.

         THE ID LIST IS THE USEFUL HALF. The run's viewport is about four tiles
         either side of you (CELL 44 on a ~390px canvas), so standing in your
         own doorway on a 128-tile block the honest painted count is usually
         ZERO and a "bodies thin at midday" assertion read here would be noise.
         What the render CAN prove from any vantage is that it never paints
         somebody the sim says is indoors - which is exactly the surface-
         disagrees-with-the-sim bug this whole lane exists to prevent. */
      try{ window.__RUN_PPL_DRAWN = bodies.length;
           window.__RUN_PPL_IDS = bodies.map(function(_b){ return _b.id; }); }catch(_ed){}
""" + CLOSE + "\n"

# the paint object carries the id it was built from, so the list above is read
# OFF THE PAINT LIST rather than recomputed from the cull - recomputing the same
# condition next to the loop would be the helper trap wearing a different hat.
# This one edit lives OUTSIDE the delimiters (it is a field on an existing
# object, not a block), so it is made idempotent by checking for itself rather
# than by the strip above.
ANCHOR_3B = "        bodies.push({ sx:nsx, sy:nsy, set:lk?lk[fa.d]:null, frame:fa.moving?fa.f:null,"
DONE_3B = "        bodies.push({ id:a.id, sx:nsx, sy:nsy, set:lk?lk[fa.d]:null, frame:fa.moving?fa.f:null,"
if run.count(DONE_3B) == 1:
    pass                                   # already carries its id
elif run.count(ANCHOR_3B) == 1:
    run = run.replace(ANCHOR_3B, DONE_3B)
else:
    sys.exit('RUN PERSON FACTS: body-push object anchor not found exactly once '
             '(%d plain, %d already-idd).' % (run.count(ANCHOR_3B), run.count(DONE_3B)))

run = run.replace(ANCHOR_3, ANCHOR_3 + BLOCK_3)

# ---- 4. a test hook, so a gate can drive the day ---------------------------
ANCHOR_4 = """RESOLVER.register('neighbours','PEOPLE', function(){
"""
if run.count(ANCHOR_4) != 1:
    sys.exit('RUN PERSON FACTS: resolver anchor not found exactly once (%d).'
             % run.count(ANCHOR_4))

BLOCK_4 = OPEN_ + """
/* THE HOOK A GATE DRIVES THE DAY WITH. Stepping the sim to a wall-clock minute
   is the only way to assert "the street empties at 13:00" on the real surface,
   and the run's own boot already does exactly this (buildSim(450) warms it to
   ~07:30 "so the street is already living"). No new simulation: it calls
   SIM.step(), which is the same tick the game runs. */
window.__RUN_PEOPLE = {
  ready: function(){ return !!(SIM && RUN_PEOPLE); },
  count: function(){ return SIM ? SIM.agents.length : 0; },
  outdoors: function(){ return SIM ? SIM.outAgents().length : 0; },
  drawn: function(){ return window.__RUN_PPL_DRAWN; },
  minute: function(){ return SIM ? (SIM.turn % 1440) : -1; },
  facts: function(){ return RUN_PEOPLE ? RUN_PEOPLE.map(function(p){
    return {id:p.id, ns:p.ns, archetype:p.archetype, heatTol:p.heatTol,
            earlyBy:p.earlyBy, nightOut:p.nightOut, darkStay:p.darkStay}; }) : null; },
  /* run the clock to a minute of the day and report what the sim did */
  runTo: function(min){
    if(!SIM) return null;
    var guard=0;
    while((SIM.turn%1440)!==(min|0) && guard++ < 3000) SIM.step();
    updateFaces(); draw();
    return {minute:SIM.turn%1440, outdoors:SIM.outAgents().length, drawn:window.__RUN_PPL_DRAWN};
  },
  recondition: function(){ return reconditionPeople(); }
};
""" + CLOSE + "\n"

run = run.replace(ANCHOR_4, BLOCK_4 + ANCHOR_4)

open(SRC, 'w', encoding='utf8').write(run)
print('RUN PERSON FACTS applied to %s:' % SRC)
print('  - one person record per agent (personFields -> overrides), namespace "run"')
print('  - every day shifted on its morning edge and conditioned for heat/dark')
print('  - a bulk edit re-reaches bodies already walking (rulesVersion compare)')
print('  - the DRAW records what it painted (window.__RUN_PPL_DRAWN)')
print('  - window.__RUN_PEOPLE lets a gate drive the clock on the real surface')
print('  next: node tools/build_run_slice.js')
