#!/usr/bin/env node
/* THE HAZARD SHEET (8/18/26, WORLD lane) — the batch output half of the factory.
 *
 * FACTORY LAW: typed spec, generator, BATCH OUTPUT, kill/approve pipeline, own gate. The
 * spec and the generator are engine/bohemia_hazard.js; the gate is gates/hazard_gate.js;
 * this is the batch output — records/BOHEMIA_THE_FLOOR_CAN_KILL_YOU_8_18_26.md, the sheet
 * that says which ground in this valley does what to a body standing on it.
 *
 * GENERATED, LIKE THE DOSSIERS, FOR THE SAME REASON. tools/bohemia_tilespec.js exists
 * because a hand-written note section drifts from the code it describes within days. A
 * hand-written hazard list would be worse: it would be a SECOND membership table sitting
 * beside the derived one, and the day they disagreed the file would win the argument in
 * everybody's head while the game did something else. Rerun this; never hand-edit it.
 *
 * REUSE CHECK: cooks no pixels and opens no bank. It reads the district registry through
 * engine/bohemia_district_kit.js and the classification through engine/bohemia_hazard.js,
 * and it re-implements neither.
 *
 *   node tools/bohemia_hazard_sheet.js
 */
const fs = require('fs'), path = require('path');
const ROOT = path.dirname(__dirname);
require(path.join(ROOT, 'engine/bohemia_world.js'));      // registers every generator
const K = require(path.join(ROOT, 'engine/bohemia_district_kit.js'));
const H = require(path.join(ROOT, 'engine/bohemia_hazard.js'));

const OUT = path.join(ROOT, 'records', 'BOHEMIA_THE_FLOOR_CAN_KILL_YOU_8_18_26.md');
const sweep = H.sweep(K);
const types = K.types();

const rows = [];
for (const d of Object.keys(sweep).sort())
  for (const c of Object.keys(sweep[d]).map(Number).sort((a, b) => a - b)) {
    const L = K.get(d).legend[c];
    rows.push({ d, c, cls: sweep[d][c], name: L.name, kind: L.kind, act1: L.act1 || '' });
  }
const byClass = {};
rows.forEach(r => (byClass[r.cls] = byClass[r.cls] || []).push(r));

/* HOW MUCH OF THE VALLEY EACH CLASS ACTUALLY COVERS — generated one cell per district so
   the number is a measurement of the generators rather than a guess. It is NOT a dial and
   it is not a target: it is what the world already does, which is the whole point. */
function tileShare(d) {
  try {
    const r = K.get(d).generate(1, { streets: ['S'], cw: 1, ch: 1 });
    const tot = r.g.length * r.g[0].length;
    const hit = {};
    for (const row of r.g) for (const v of row) {
      const cl = sweep[d][v];
      if (cl) hit[cl] = (hit[cl] || 0) + 1;
    }
    const out = {};
    for (const cl in hit) out[cl] = hit[cl] / tot;
    return out;
  } catch (e) { return null; }
}

let md = '';
md += '# THE FLOOR CAN DO SOMETHING TO YOU — the hazard sheet (8/18/26, WORLD lane)\n\n';
md += 'GENERATED by `node tools/bohemia_hazard_sheet.js` from `engine/bohemia_hazard.js` +\n';
md += 'the district registry. **Do not hand-edit.** A second membership table kept by hand\n';
md += 'is a table that will one day disagree with the game and win the argument anyway.\n\n';
md += '> Paolo 8/17, LOCKED: **"THE WORLD HAS TO FEEL MORE ALIVE."**\n';
md += '> `laws/BOHEMIA_ADDENDUM_THE_RF4_LIFT_8_17_26.md` §5 routes that order to WORLD and\n';
md += '> says why: it is TILE TYPES with combat-readable properties, not combat code.\n';
md += '> Its closing line is the brief: *a room only feels alive if the floor can do\n';
md += '> something to you.*\n\n';

md += '## NOBODY INVENTED A HAZARD AND NOBODY PLACED ONE\n\n';
md += 'Sixty-two district generators have been authoring real Mojave ground for weeks —\n';
md += 'drained pools, talus aprons, leachate ponds, standing pit water, ballast, crusted\n';
md += 'sludge. **Nothing had ever told the game any of it was dangerous.** So this is a\n';
md += 'READING of ground that already existed, produced by a rule run against each\n';
md += "district's own LEGEND. Author a drained pool into a new district next month and it\n";
md += 'is lethal ground that afternoon, with no edit anywhere. The gate proves that by\n';
md += 'mutating a legend and watching the class follow, in both directions.\n\n';

md += '**' + types.length + ' registered district types swept → ' + rows.length +
      ' hazard tiles in ' + Object.keys(sweep).length + ' districts.**\n\n';
md += '| class | what the floor does (his words) | tiles | districts |\n|---|---|---|---|\n';
['KILLS', 'AMPLIFIES', 'DISABLES', 'FAVOURS', 'DENIES'].forEach(cl => {
  const r = byClass[cl] || [];
  const ds = new Set(r.map(x => x.d));
  md += '| **' + cl + '** | ' + H.CLASSES[cl].says + ' | ' + r.length + ' | ' + ds.size + ' |\n';
});
md += '\n';

md += '## WHAT THE VALLEY ACTUALLY CONTAINS\n\n';
['KILLS', 'DISABLES', 'AMPLIFIES'].forEach(cl => {
  const r = byClass[cl] || [];
  if (!r.length) return;
  const rule = H.ruleFor(cl);
  md += '### ' + cl + ' — ' + H.CLASSES[cl].says + '\n\n';
  md += '_' + rule.why + '_\n\n';
  md += '| district | code | tile | kind | the act-1 material it was authored as |\n';
  md += '|---|---|---|---|---|\n';
  r.forEach(x => {
    md += '| ' + x.d + ' | ' + x.c + ' | **' + x.name + '** | ' + x.kind + ' | ' +
          x.act1.replace(/\|/g, '/') + ' |\n';
  });
  md += '\n';
});

md += '## HOW MUCH OF A CELL IT IS (measured, one generated cell per district)\n\n';
md += 'Not a dial and not a target — **what the generators already do.** How common each\n';
md += 'class SHOULD be is his call and that table ships empty.\n\n';
md += '| district | class | share of the cell |\n|---|---|---|\n';
Object.keys(sweep).sort().forEach(d => {
  const sh = tileShare(d);
  if (!sh) { md += '| ' + d + ' | — | (cell would not generate standalone) |\n'; return; }
  const keys = Object.keys(sh).sort();
  if (!keys.length) { md += '| ' + d + ' | — | 0% in a standalone cell |\n'; return; }
  keys.forEach(cl => {
    md += '| ' + d + ' | ' + cl + ' | ' + (sh[cl] * 100).toFixed(2) + '% |\n';
  });
});
md += '\n';

md += '## THE TWO CLASSES THAT SHIP EMPTY, AND WHY EACH ONE IS EMPTY\n\n';
md += '- **FAVOURS THEM** (cursed floor heals undead) — act one has no undead, and ACT ONE\n';
md += '  ONLY (7/28) forbids me designing the ones that might. The class is DEFINED so\n';
md += '  combat can read it; the day he rules what a cursed floor favours it is one entry,\n';
md += '  not a system.\n';
md += '- **DENIES** (standing on a body prevents resurrection) — **not a tile at all.** It\n';
md += '  is a predicate over OCCUPANCY, so no legend sweep could ever populate it. It ships\n';
md += '  as `deniesOn()`, which answers from a body.\n\n';

md += '## WHAT I REFUSED TO CLASSIFY, AND WHY\n\n';
md += "A classifier's refusals are as much a claim as its picks, and an unrecorded refusal\n";
md += 'is indistinguishable from an oversight.\n\n';
H.UNCLASSIFIED.forEach(u => { md += '- **' + u.tile + '** — ' + u.why + '\n'; });
md += '\n';

md += '## THE GAPS THIS FOUND IN THE WORLD ITSELF — ALL FOUR NOW CLOSED (8/20)\n\n';
md += 'Kept rather than deleted, because a gap that was closed and a gap that was never\n';
md += 'real look identical once the text is gone, and two of these were closed by finding\n';
md += 'out the diagnosis was wrong rather than by doing the work it asked for.\n\n';
md += '1. **~~THE VALLEY HAS NO WALKABLE RUBBLE FIELD.~~ CLOSED — and it was never true.**\n';
md += '   The rubble was declared walk-through in the legends all along and the walked\n';
md += '   surface was discarding all 48 such declarations one line before they reached him\n';
md += '   (the PROP OCCUPANCY fix, 8/18). Re-measured 8/20: **14 walkable loose-ground tiles**\n';
md += '   — 7 ground-layer, 7 walk-through props, all AMPLIFIES. The 9 that still block are a\n';
md += '   scrap pile, a debris rack, a screen tower: things that SHOULD block.\n';
md += '2. **~~THE REAL LETHAL DROPS ARE MODELLED AS WALLS.~~ CLOSED 8/20** —\n';
md += '   records/BOHEMIA_A_HOLE_IS_NOT_A_WALL_8_20_26.md. All four are VOIDS now (a third\n';
md += '   occupancy state: does not block, cannot be walked into), 2,405 cells in the valley.\n';
md += '   THE DIAGNOSIS ABOVE WAS INCOMPLETE: making them voids was necessary and was not the\n';
md += '   hard part. The sweep admitted a tile only if a body could STAND on it, so all four\n';
md += '   matched the KILLS rule BY NAME and were classified as nothing — and a body knocked\n';
md += '   into a hole is by definition somewhere it could not have walked.\n';
md += '3. **~~ONE CODE, TWO THINGS.~~ CLOSED 8/20.** The gypsum dome shell is code 15 now\n';
md += '   (360 cells, still solid, still not lethal) and 7 is the bench lip alone. The KILLS\n';
md += "   rule's `/dome shell/i` veto still exists and is finally FREE: it used to throw away\n";
md += '   the lip along with the roof.\n';
md += '4. **~~THE WALKED SURFACE KNOWS FEWER DISTRICTS THAN THE ENGINE DOES.~~ CLOSED.**\n';
md += "   Re-measured on the running page 8/20: the city world's kit registers **" +
      types.length + " of the engine's " + types.length + "** types.\n";
md += '   The 9 district types in the valley it cannot build are either a\n';
md += '   different code path (suburb, estate and gated go through __subGrid — 2,582 cells of\n';
md += '   suburb build fine) or the landmark names reserved for Paolo. The number in this\n';
md += '   line was wrong twice before it was counted: it said 35, then 57.\n\n';
md += '**AND THE ONE THIS FEATURE HAD NOT REACHED AT ALL, now also closed:** every hazard\n';
md += 'above is OUTDOORS, and every fight in this game happens indoors. Interiors carried no\n';
md += 'terrain whatsoever until 8/20 — see records/BOHEMIA_THE_FLOOR_INDOORS_8_20_26.md and\n';
md += 'engine/bohemia_interior_ground.js, which invents no vocabulary: its materials are named\n';
md += 'so the rules above classify them with no new rule.\n\n';

md += '## THE ART ASK (hazard tile forms — ART lane, per §6 of the lift)\n\n';
md += 'The law says ART supplies pixels **once the types exist**. They exist as of today.\n';
md += 'What the floor needs to SHOW, so the readout can be retired (§2.6: never explain\n';
md += 'something the floor could have shown):\n\n';
md += '- a **drop** that reads as a drop from above — a rim, a shadow line, a floor at a\n';
md += '  different value. Drained pool, splash pool, treatment basin.\n';
md += '- **loose ground** that reads as loose — broken, unmatched, no two pieces alike.\n';
md += '  Talus, ballast, debris fill, crusted sludge.\n';
md += '- **standing liquid** that reads as wet without reading as clean. Leachate, pit\n';
md += '  water, coolant, shallows.\n\n';
md += 'All three at the 45 DEGREE ART LAW, act-1 dead. Three forms, not nineteen: the\n';
md += 'nineteen tiles already have their own materials — what is missing is the one visual\n';
md += 'mark that says *this ground is different*, readable at walking zoom.\n\n';

md += '---\n';
md += '**Spec + generator:** `engine/bohemia_hazard.js` · **Gate:** `gates/hazard_gate.js` ';
md += '(68 checks) · **On the surface:** `tools/bohemia_city_hazard_patch.py`\n';

fs.writeFileSync(OUT, md);
console.log('HAZARD SHEET: wrote ' + path.relative(ROOT, OUT));
console.log('    ' + rows.length + ' hazard tiles in ' + Object.keys(sweep).length +
            ' districts, swept from ' + types.length + ' registered types');
