#!/usr/bin/env python3
"""
BOHEMIA RUN PEOPLE (7/29/26) — *** NOT WIRED YET. DO NOT ASSUME IT WORKS. ***

STATUS: WRITTEN, APPLIED, MEASURED, AND BACKED OUT. The tool is correct as far
as it goes and the modules load cleanly in the run (population + powergrid both
live, zero page errors, the zone map answers for the real cell). What is NOT
solved is the LAST MILE, and it is written down here rather than shipped
half-working:

  MEASURED: calling agentsForBlock directly in the booted run with the floored
  rate returns 12 agents. The SIM the run actually boots with has 1. So the
  rate is not reaching the sim on the boot path, and the cause is not yet
  found. Candidates ruled OUT: CELL and HOME_CELL do match at boot (verified),
  and the save-restore call site at ~2046 is a different path that only runs on
  load. Candidate NOT yet ruled out: buildSim running before feet/doorOf are
  populated, its try/catch swallowing the failure, and an earlier SIM surviving.

  THE RULE THAT SENT IT BACK: shipping a wiring that measures wrong is worse
  than shipping nothing, and "it loads without errors" is not the same as "it
  works". The CITY tab's version IS verified and shipped; this one is not.

NEXT SESSION: instrument buildSim itself (log _rate and _agents.length from
inside it), find why the boot SIM ignores the option, then re-apply and prove
it with a gate that boots the run and asserts a cluster block and an empty
block differ. Do not ship it on "the modules load".

WHAT IT DOES WHEN IT WORKS: the run's neighbours obey Paolo's zone map.

HE PLAYS THE RUN. That is the lesson of 7/28, recorded in the backlog as the
day's whole point, and it applies here: the CITY tab got the zone map on 7/29
and the run did not, which means the two surfaces were describing two different
cities. Same seed, same corner of the valley, different number of people.

WHAT WAS WRONG, measured in the run's own source: buildSim() calls

    BohemiaAgents.agentsForBlock(seed, feet, [], fpOf)

with no options, so every block in the valley fell back to the module's flat
OCCUPIED_RATE=0.30 - the placeholder whose own source comment says "how dead
Vegas is (90%? 50%?) is Paolo's canon ruling, [PENDING Paolo]". He RULED it on
7/29 (laws/BOHEMIA_ADDENDUM_HOW_MANY_PEOPLE_7_29_26.md): the population is the
valley's FOOD CARRYING CAPACITY, and it lands as clusters AND no man's lands
AND random spread. A flat 30% everywhere is exactly the thing that ruling
replaced.

WHAT THIS CHANGES, and it is deliberately almost nothing: ONE ARGUMENT. The run
now passes an occupiedRate computed by engine/bohemia_population.js for the
cell you are standing on. Walk into a cluster and the block is full; walk into
a no man's land and it is empty; and it is the SAME answer the CITY tab gives
for that cell, because both ask the same module.

  - no new sim, no second census: agentsForBlock ALREADY accepted opts.occupiedRate
  - no change to bohemia_agents.js, which is the WORLD lane's (ENGINE SYNC LAW)
  - no change to how anybody walks, looks or is scheduled
  - the run keeps its own bodies and its own renderer

REUSE CHECK: cooks ZERO pixels and opens no bank. It changes one number that an
existing function already took as a parameter. Nothing is created.

TASTE CHECK: produces no candidates and reaches Paolo's thumbs with nothing.

PATCHES THE DEV SOURCE, NOT THE BUILD. slices/BOHEMIA_RUN_CURRENT.html is
GENERATED by tools/build_run_slice.js; patching it would be erased by the very
next build. The guard goes in slices/BOHEMIA_RUN_SLICE_7_26_26.html where the
builder carries it forward - the same lesson the touch-guard tool learned.

Idempotent (marker RUN PEOPLE).

  python3 tools/bohemia_run_people_patch.py && node tools/build_run_slice.js
"""
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) or '.'
os.chdir(REPO)
SRC = 'slices/BOHEMIA_RUN_SLICE_7_26_26.html'

run = open(SRC, encoding='utf8').read()
if 'RUN PEOPLE' in run:
    print('run people already applied. no-op.')
    sys.exit(0)

# ---- 1) load the shared census module the same way every other engine module
#         is loaded here: a script tag, next to the overmap it depends on ------
ANCHOR_SRC = '<script src="../engine/bohemia_overmap_bridge.js"></script>'
if run.count(ANCHOR_SRC) != 1:
    print('FAILED: overmap bridge script tag not unique.')
    sys.exit(1)
run = run.replace(ANCHOR_SRC, ANCHOR_SRC +
                  '\n<!-- RUN PEOPLE (7/29): Paolo\'s zone map, the same module the CITY tab\n'
                  '     asks, so both surfaces describe ONE city. Gate: zone_map_gate.js -->\n'
                  '<script src="../engine/bohemia_powergrid.js"></script>\n'
                  '<script src="../engine/bohemia_population.js"></script>', 1)

# ---- 2) the one argument ----------------------------------------------------
OLD = """    var seed = (SEED ^ (CELL[0]*73856093) ^ (CELL[1]*19349663)) >>> 0;
    var _agents = BohemiaAgents.agentsForBlock(seed, feet, [], fpOf);"""
NEW = """    var seed = (SEED ^ (CELL[0]*73856093) ^ (CELL[1]*19349663)) >>> 0;
    /* RUN PEOPLE (7/29): HOW MANY of them there are is Paolo's zone map, not a
       flat rate. agentsForBlock already took opts.occupiedRate and the run was
       never passing it, so every block in the valley used the module's
       OCCUPIED_RATE=0.30 placeholder - the one whose own comment says the real
       number is "[PENDING Paolo]". He ruled it: the population IS the valley's
       food carrying capacity, landing as clusters AND no man's lands AND
       random spread (BOHEMIA_ADDENDUM_HOW_MANY_PEOPLE_7_29_26).
       The rate comes from the SHARED module, so this block holds exactly as
       many people as the CITY tab says it holds. One city, two renderers. */
    var _rate = null;
    try{ if(typeof BohemiaPopulation!=='undefined' && WORLD)
      _rate = BohemiaPopulation.occupiedRateFor(WORLD, POWERMAP, CELL[0], CELL[1],
                                                SEED, feet.length||6); }catch(_e){}
    /* YOUR OWN BLOCK ALWAYS HAS NEIGHBOURS, and this is not a fudge of the zone
       map - it is the run's own stated invariant. Its lineman code says, in its
       own words, "He is your neighbour, one door down. Nothing closer is
       possible." Act 1 opens on that relationship. Measured after wiring the
       zone map: the start cell came out 'spread' at a 0.5% rate, which is ZERO
       households on a 23-home block - correct for the valley at large and fatal
       for the one block the game opens on.
       So the PLAYER'S CELL gets a FLOOR and every other cell in the valley gets
       the zone map exactly. Walk one block over and the real distribution takes
       back over immediately.
       THE FLOOR IS 6 HOUSEHOLDS, MEASURED NOT GUESSED: occupancy is a per-house
       hash roll, so a floor of 3 came out as ONE household on the real block -
       right on average, useless in practice. 6 lands 4-6 doors with somebody
       behind them, which is a street with neighbours on it and still nothing
       like the flat 30% (7+ houses) this replaced. */
    var _here = (typeof CELL!=='undefined' && HOME_CELL &&
                 CELL[0]===HOME_CELL[0] && CELL[1]===HOME_CELL[1]);
    if(_here){ var _floor = 6/Math.max(1,feet.length); if(_rate==null||_rate<_floor) _rate=_floor; }
    var _agents = BohemiaAgents.agentsForBlock(seed, feet, [], fpOf,
      (_rate!=null) ? {occupiedRate:_rate} : {});"""
if run.count(OLD) != 1:
    print('FAILED: buildSim anchor not unique.')
    sys.exit(1)
run = run.replace(OLD, NEW, 1)

# ---- 3) the power map, because a cluster is a place that HAS POWER ----------
# The run never built one; the zone map needs it to know which neighbourhoods
# earned a settlement. Built once, from the same seed, exactly as the CITY tab
# builds it - and if the powergrid module is not present the zone map simply
# falls back to farm/water adjacency rather than throwing.
ANCHOR_W = 'var WORLD = CTX.worldMap && CTX.worldMap.real;'
if run.count(ANCHOR_W) != 1:
    print('FAILED: WORLD anchor not unique.')
    sys.exit(1)
run = run.replace(ANCHOR_W, ANCHOR_W + """
/* RUN PEOPLE (7/29): the 12% CLUSTERED POWER map. A cluster is EARNED by having
   power or backing onto farm/water ground (his rule), so the zone map needs
   this to answer. Built from the same seed the whole game boots on, so the
   run's idea of which circuits are live is the CITY tab's idea. */
var POWERMAP = null;
try{ var _PG = (typeof BohemiaPowergrid!=='undefined') ? BohemiaPowergrid
             : (typeof BOH_POWERGRID!=='undefined') ? BOH_POWERGRID : null;
     if(_PG && WORLD) POWERMAP = _PG.powerMap(WORLD.overmap || WORLD, SEED);
}catch(_e){ POWERMAP = null; }""", 1)

open(SRC, 'w', encoding='utf8').write(run)
print('RUN PEOPLE applied to the dev source:')
print('  - engine/bohemia_population.js loaded (the shared census)')
print('  - buildSim passes the zone map\'s occupiedRate for THIS cell')
print('  - the 12% power map built so clusters can be earned')
print('  NOW RUN: node tools/build_run_slice.js')
