#!/usr/bin/env python3
"""BOHEMIA -- THE CROWD BOARD (7/31/26). Idempotent alpha patch.

Paolo 7/31: "WE HAVE 11 months of forward motion work we need to complete.
Do what you have to do next and know what comes after."

WHY THIS EXISTS. BOH_PERSONLOOK shipped a pure function: id -> a body and an
outfit, deterministic, no dice. That is a mechanism nobody can see. VERIFY ON
THE REAL SURFACE (7/18) says an unlooked-at feature is not a feature, and the
question it raises is a question only Paolo can answer -- do a dozen strangers
built from his one rig and his 221 garments read as HIS PEOPLE, or as one man
in twelve coats. He cannot answer that from a module. He answers it from a
board with twelve people on it.

WHAT IT DOES. Adds THE CROWD to the CHARACTER panel, under the wardrobe:
twelve citizens generated by BOH_PERSONLOOK, drawn THROUGH drawChar -- the real
render path, the same one that draws him -- by installing each person's dials
and worn outfit, drawing, and putting his own look back. NEW CROWD walks to the
next page of twelve.

THE SIDE-DOOR TRAP, avoided on purpose. The shuffle-fit bug (7/31) was exactly
this shape: a probe called buildFrame directly, passed, and the live canvas
never changed because HD_CACHE keyed off a hash that did not include the thing
that changed. So the crowd calls drawChar, not buildFrame, and every person's
look goes through frameLookHash -- which now carries bodyVar AND G_WORN, so
twelve people get twelve cache entries instead of one shared stale frame.

REUSE CHECK: no new graphic pixels are cooked here. It draws nothing itself.
Bodies come from his one painted rig via the six existing dials; clothes come
from window.GARMENTS, the 221 pieces Paolo already approved. This file contains
no art, no garment names, and no palette.

RIG CHECK (RIG IS LAW, Paolo 7/26/26): no joints, no parts, no pixels, and it
never opens the rig package -- it hands DIAL VALUES to the existing render path
and lets that path do the warping, which is the whole point of ONE RIG. Its only
rig-touching act is calling drawChar, the same entry point the character box uses.
(An earlier draft of this header said the word BAKED in prose. It was a name-drop:
this file never reads the rig package. Corrected, because a citation is a claim
the machine can check.)
  built on: drawChar
  joints: none named
  parts: none

STILL, NOT ANIMATED, and that is a decision: twelve animated bodies would mean
12 x 24 buckets of HD_CACHE churn on his phone every frame to answer a
still-frame question (is this body right, is this outfit right). The board
redraws when the crowd changes or the facing changes, so AUTO-SPIN still turns
all twelve.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
ALPHA = ROOT / 'slices' / 'BOHEMIA_ALPHA_0_9.html'
src = ALPHA.read_text()
orig = src

# ---------------------------------------------------------------- 1. MARKUP
MARKUP_ANCHOR = '      <div id="wardrobe"></div>\n'
MARKUP = (
    '      <div class="row"><b>THE CROWD</b><span class="mini">every person is a '
    'different person &mdash; one rig, one closet, no two alike</span></div>\n'
    '      <div class="row"><button id="crowdNew" class="opt">&#8635; NEW CROWD</button>'
    '<span id="crowdStat" class="mini" style="margin-left:6px"></span></div>\n'
    '      <div id="crowdBoard" style="display:flex;flex-wrap:wrap;gap:4px;'
    'justify-content:center;margin:4px auto;max-width:min(94vw,440px)"></div>\n'
)
if 'id="crowdBoard"' not in src:
    if MARKUP_ANCHOR not in src:
        sys.exit('CROWD PATCH: wardrobe host not found -- alpha markup moved')
    src = src.replace(MARKUP_ANCHOR, MARKUP_ANCHOR + MARKUP, 1)

# ---------------------------------------------------------------- 2. RENDERER
JS_ANCHOR = "  /* --- JUDGE ALL: \"i want to judge all the animations in bulk now\" ------- */"
JS = r'''  /* --- THE CROWD: BOH_PERSONLOOK, on a surface he can look at -----------
     Twelve citizens from the one rig and the approved closet. Each is drawn
     through drawChar (the REAL path, cache and all) by installing that
     person's dials + worn outfit, drawing, then putting Paolo's own look
     back. Never buildFrame: a direct call is the side door that made SHUFFLE
     FIT look like it worked when it did not. */
  (function(){
    var HOST = 'crowdBoard', N = 12, page = 0, lastDir = null, lastPage = -1;
    /* his painted pieces are the PLAYER'S clothes. A citizen wears what
       PERSONLOOK gave them, otherwise the whole street shows up in his hoodie.
       Hair stays -- that is body, not wardrobe. */
    var PD_OFF = ['shirt','jacket','pants','shoes','hat','glasses'];

    function render(force){
      var host = document.getElementById(HOST);
      if (!host || !window.BOH_PERSONLOOK) return;
      var panel = document.getElementById('p-char');
      if (!panel || !panel.classList.contains('on')) return;
      if (!force && lastDir === G.dir && lastPage === page) return;
      lastDir = G.dir; lastPage = page;

      var pool = window.GARMENTS || [];
      if (host.childElementCount !== N) {
        host.innerHTML = '';
        for (var i = 0; i < N; i++) {
          var cell = document.createElement('div');
          cell.style.cssText = 'line-height:0;position:relative';
          var cv = document.createElement('canvas');
          cv.width = 56; cv.height = 56;
          cv.style.cssText = 'width:66px;height:66px;image-rendering:pixelated;background:#141118;border:1px solid #241c12;border-radius:3px';
          cell.appendChild(cv); host.appendChild(cell);
        }
      }

      /* SAVE HIS LOOK. Everything below is borrowed and given back. */
      var keepVar  = G.bodyVar, keepWorn = window.G_WORN, keepEq = G.equipped;
      var drawn = 0;
      try {
        for (var k = 0; k < N; k++) {
          var id = 'crowd:' + page + ':' + k;
          var look = window.BOH_PERSONLOOK.lookFor(id, pool);
          var eq = {}; for (var p in keepEq) eq[p] = keepEq[p];
          for (var q = 0; q < PD_OFF.length; q++) eq[PD_OFF[q]] = '';
          G.bodyVar = look.body; window.G_WORN = look.worn; G.equipped = eq;
          var cv = host.children[k].firstChild;
          try { drawChar(cv, G.dir, 'idle', 0); drawn++; } catch (e) {}
        }
      } finally {
        G.bodyVar = keepVar; window.G_WORN = keepWorn; G.equipped = keepEq;
      }
      var st = document.getElementById('crowdStat');
      if (st) st.textContent = drawn + ' people · page ' + (page + 1) +
        ' · ' + pool.filter(function(g){ return g.st === 'canon'; }).length + ' garments in play';
    }

    var nb = document.getElementById('crowdNew');
    if (nb) nb.onclick = function(){ page++; render(true); };
    window.crowdTick = function(){ render(false); };
    window.crowdRefresh = function(){ render(true); };
    setTimeout(function(){ render(true); }, 900);
  })();

'''
if 'window.crowdTick' not in src:
    if JS_ANCHOR not in src:
        sys.exit('CROWD PATCH: JUDGE ALL anchor not found -- alpha script moved')
    src = src.replace(JS_ANCHOR, JS + JS_ANCHOR, 1)

# ---------------------------------------------------------------- 3. LOOP HOOK
LOOP_ANCHOR = "    G.showSkel=_sk;}\n"
LOOP_HOOK = "    G.showSkel=_sk;\n    if(window.crowdTick)window.crowdTick();}\n"
if 'window.crowdTick)window.crowdTick' not in src:
    if LOOP_ANCHOR not in src:
        sys.exit('CROWD PATCH: character loop anchor not found')
    src = src.replace(LOOP_ANCHOR, LOOP_HOOK, 1)

if src == orig:
    print('CROWD PATCH: already applied, nothing to do')
else:
    ALPHA.write_text(src)
    print('CROWD PATCH: applied (markup + renderer + loop hook)')
