#!/usr/bin/env python3
"""BOHEMIA OPENING -- the cold open stops being a tab and becomes the first
thing that happens to you.

THE DEMO PLAN SAYS THIS IN TWO SEPARATE ROWS AND NEITHER WAS DONE.
records/BOHEMIA_THE_DEMO_PLAN_8_4_26.md, THE CRITICAL PATH:
  "7. THE FIRST FIVE MINUTES: an opening that needs zero explanation -- the
      scripted-scene runtime (PEOPLE 0sc) playing a minimal cold open, or a
      clean wake-up-and-go if the cold open isn't ready."
  "10. THE COLD OPEN SCENE (PEOPLE 0sc scripted-scene runtime + RUN consumes...)"
The runtime shipped 8/9. The scene shipped. The CUTSCENE tab shipped and is
gated 40 claims deep. AND THE RUN NEVER CONSUMED IT -- measured, the run source
has ZERO references to the scene runtime and boots straight into wakeInBed(),
which is the plan's own FALLBACK. So the demo's first five minutes has been the
fallback this whole time while the real opening sat one tab away.

THIS IS THE SAME DISEASE AS THE BARKS, THREE DAYS RUNNING: the work exists, the
gates are green, and it is not in the surface he taps. Built, gated, unreachable.

WHERE IT GOES, AND WHY NOT IN THE RUN. The scene draws the family with drawChar
over Paolo's painted rig wearing FAMILY_CAST's wardrobe -- the rig and the cast
live in the ALPHA, not in the run frame, and porting them into the run would
mean a second body pipeline (ENGINE SYNC LAW says no). The alpha owns the RUN
tab as an iframe, so the opening plays OVER that frame in the alpha and reveals
the run when it ends. Nothing in the run's own logic is touched, which also
keeps this inside the PEOPLE lane's boundary.

*** IT PLAYS HIS DIRECTED VERSION, NOT THE SHIPPED ONE. *** DIR['scene:<id>'] is
what the DIRECT tab writes when he changes a line, a speaker, an order or a
beat. The opening reads that first and falls back to canon. So HE MUST BE ABLE
TO DIRECT IT (8/12) closes its loop here: what he edits in DIRECT is literally
what the game opens with, on his phone, on the next run.

WHEN IT PLAYS: first time the RUN tab opens on a device, and only with NO SAVE
(bohemia.save.v1). A returning player never sees it again, and SKIP is on screen
from the first frame because he is going to watch this a hundred times.

IT REPLACES, IT NEVER APPENDS (the 8/11 CHARACTER lane lesson: "an insert tool
run twice is a duplication tool"). Everything lives between markers and is
swapped whole; running it ten times leaves the file identical to running it once.

REUSE CHECK: cooks no pixels. Draws entirely through BohemiaStorySurface +
BohemiaColdOpenSet (12 tiles Paolo approved out of the interior pool) and
cutPaintBody, which are already inlined in the alpha by
tools/bohemia_cutscene_tab_patch.py. No new art, no new bank.

  python3 tools/bohemia_opening_patch.py
Gate: gates/opening_gate.js
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = os.path.join(ROOT, 'slices', 'BOHEMIA_ALPHA_0_9.html')

PANEL_BEGIN = '<!-- ===== BOHEMIA OPENING OVERLAY (generated) ===== -->'
PANEL_END = '<!-- ===== END BOHEMIA OPENING OVERLAY ===== -->'

# *** FOLDED IN 8/20 FROM THE LIVE ALPHA, NOT AUTHORED HERE. ***
# The RUN lane's __THE_COLD_OPEN_CLEARS_THE_TOOLBAR__ fix lives inside the JS
# region below -- it is what stops this banner covering the PHONE, which is
# where the day's job arrives. This tool replaces the region WHOLE, so
# re-running it after their commit deleted 47 lines of their work. The body is
# now the LIVE region, theirs included, so a re-run REPRODUCES the file instead
# of reverting somebody. If you change the opening, change it HERE, and leave
# their block alone.
JS_BEGIN = '<!-- ===== BOHEMIA OPENING (generated by tools/bohemia_opening_patch.py) ===== -->'
JS_END = '<!-- ===== END BOHEMIA OPENING ===== -->'

# The run panel is a bare iframe; the overlay is a sibling inside the same panel
# so it covers the run exactly and nothing else on the page.
PANEL = PANEL_BEGIN + '''
      <div id="openWrap" style="display:none;position:absolute;inset:0;z-index:40;background:#070906;
           flex-direction:column;align-items:center;justify-content:center">
        <canvas id="openCv" width="360" height="470"
          style="max-width:100%;max-height:74%;display:block;image-rendering:pixelated"></canvas>
        <div id="openCap" style="min-height:56px;width:92%;max-width:420px;margin-top:10px;padding:8px 10px;
             font:13px/1.5 ui-monospace,monospace;color:#e8dfc8;text-align:center"></div>
        <button id="openSkip" style="position:absolute;top:10px;right:10px;padding:6px 12px;
                border:1px solid #3a2f1c;border-radius:4px;background:rgba(12,10,7,.8);
                color:#9a8a5e;font:11px ui-monospace,monospace;letter-spacing:1px">SKIP</button>
      </div>
      <div id="openInvite" style="display:none;position:absolute;left:0;right:0;top:0;z-index:39;
           padding:9px 12px;background:linear-gradient(#0d0b07,rgba(13,11,7,.94));
           border-bottom:1px solid #2a2114;font:12px/1.45 ui-monospace,monospace;color:#cdbd8a">
        <div style="color:#d8b45a;letter-spacing:2px;font-size:11px">DAY 1 BEGINS BEFORE THE DAY</div>
        <div style="margin-top:3px;color:#8d8168">The family, the table, ten years ago.</div>
        <div style="margin-top:7px;display:flex;gap:7px">
          <button id="openWatch" style="padding:5px 12px;border:1px solid #d8b45a;border-radius:4px;
                  background:#d8b45a;color:#191308;font:11px ui-monospace,monospace;letter-spacing:1px">&#9654; WATCH</button>
          <button id="openNot" style="padding:5px 12px;border:1px solid #3a2f1c;border-radius:4px;
                  background:transparent;color:#8d8168;font:11px ui-monospace,monospace;letter-spacing:1px">NOT NOW</button>
        </div>
      </div>
''' + PANEL_END

JS = JS_BEGIN + '''
<script>
/* ---- THE OPENING. The cold open, in the game, before the day. ---------------
   The CUTSCENE tab is a viewing room. This is the door. Same runtime, same set,
   same bodies -- the only new thing here is WHEN it happens and what it hands
   you to afterwards.

   IT PLAYS WHAT HE DIRECTED. openScene() reads DIR['scene:<id>'] before canon,
   so a line he retyped in DIRECT is the line the game opens with. That is the
   whole point of the 8/12 law and it was only half done while the opening was
   a tab nobody's run ever entered. */
var OPEN_SEEN_KEY = 'bohemia.opening.seen.v1';
var OPEN_PLAYER = null, OPEN_RUNNING = false;

/* THE ONE SCENE THE GAME OPENS WITH. Not "whatever is selected in the CUTSCENE
   tab" -- the opening is a fixed thing, found by the scene's own act/order
   rather than by index, so adding a scene to the catalogue cannot silently
   change what the game starts with. */
function openWhich(){
  var all = (typeof BOHEMIA_CUTSCENES !== 'undefined') ? BOHEMIA_CUTSCENES : [];
  for(var i=0;i<all.length;i++){
    var s = all[i] && all[i].scene;
    if(s && (s.id === 'act1_cold_open' || /cold_open/.test(String(s.id||'')))) return all[i];
  }
  return all[0] || null;
}
function openScene(){
  var c = openWhich(); if(!c) return null;
  return openDirected(c.scene);
}
/* HIS VERSION FIRST. DIR is the DIRECT tab's store; it only has a row for a
   scene he has actually touched, so canon is the honest default. Pulled out of
   openScene so EVERY scene the sequence plays gets his edits, not only the
   first one -- the day this played a second scene, a version that only
   respected DIRECT for the opener would have quietly shipped canon over the
   top of his rewrites. */
function openDirected(sc){
  if(!sc) return null;
  try { if(typeof DIR !== 'undefined' && DIR && DIR['scene:' + sc.id]) return DIR['scene:' + sc.id]; }
  catch(_e){}
  return sc;
}
function openSceneById(id){
  var all = (typeof BOHEMIA_CUTSCENES !== 'undefined') ? BOHEMIA_CUTSCENES : [];
  for(var i=0;i<all.length;i++) if(all[i] && all[i].scene && all[i].scene.id === id)
    return openDirected(all[i].scene);
  return null;
}

/* ---- THE OPENING IS A SEQUENCE, NOT A SCENE -----------------------------
   *** HIS LAW CALLS IT ONE UNBROKEN SEQUENCE AND THIS PLAYED ONE THIRD OF IT. ***
   laws/BOHEMIA_ADDENDUM_ACT1_OPENING_VISION_7_19_26.md: "The pieces fuse into
   one unbroken sequence: 1. NIGHT RAID ... 2. THE GRIEF DINNER ... 3. THE
   BURIAL ON THE RIDGE (tutorial ends here)." This runner played scene 1 and
   called openDone, so beats 2 and 3 have never happened in the played game --
   they existed only as chips in a dev tab.

   A scene says what follows it, in its own handoff beat, and this now READS
   that instead of assuming there is nothing after.

   *** AND A HANDOFF IT CANNOT HONOUR STOPS THE SEQUENCE, IT NEVER SKIPS IT. ***
   The cold open hands off to COMBAT (the raid, where the sibling is taken).
   MEASURED 8/19: startColdOpen has exactly ONE occurrence in the alpha, its own
   definition, and ZERO callers -- so the raid has never been played from
   anywhere, which is why the death the whole opening is built on does not
   happen in the played game. Advancing past a combat handoff would seat the
   family at the grief dinner mourning somebody the player never saw die, which
   is worse than stopping. So the sequence pauses at a handoff it cannot make,
   and openContinue() is the published seam for whoever wires the fight to
   resume it -- the same courtesy COMBAT did this lane by exposing
   startColdOpen(onEnd) for the scene to name. */
function openNext(sc){
  if(!sc || !sc.beats) return null;
  for(var i=0;i<sc.beats.length;i++){
    var b = sc.beats[i];
    if(b && b.kind === 'handoff') return b;
  }
  return null;
}
/* resume the authored sequence after whatever the handoff went out to. Safe to
   call with nothing pending; safe to call twice. */
function openContinue(fromId){
  var sc = fromId ? openSceneById(fromId) : (OPEN_PLAYER && OPEN_PLAYER.scene);
  var h = openNext(sc);
  if(!h) return false;
  /* `then` is what plays when a handoff COMES BACK; `scene` is what a
     scene-to-scene handoff goes straight to. The first cut read only `scene`,
     so resuming from the raid looked at a handoff whose target was COMBAT,
     found nothing to chain, and ended the opening -- the grief dinner would
     never have played after the fight. It went unnoticed because until this
     turn the raid had never run at all, so the resume path had never been
     reached. A returns:true handoff that names nothing to return to is a
     sequence that stops on success. */
  var want = h.then || (h.to === 'scene' ? h.scene : null);
  if(!want) return false;
  var nxt = openSceneById(want);
  if(!nxt) return false;
  return openPlay(nxt);
}

/* *** A FRESH PLAYER ALREADY HAS A SAVE, AND THAT IS NOT A BUG. *** The first
   cut of this gated on "no bohemia.save.v1" and never fired once. Measured on
   the real alpha: the RUN frame preloads on a 2.5s timer, boots, and writes an
   auto-save labelled "auto:start" at beat 0 / turn 0 before anybody has touched
   anything. So THE PRESENCE OF A SAVE IS NOT EVIDENCE OF PROGRESS, and any lane
   that reads the key as "has this person played?" is reading it wrong.
   What actually means "mid-story" is a save with something IN it. */
function openHasProgress(){
  try {
    var raw = localStorage.getItem('bohemia.save.v1');
    if(!raw) return false;
    var list = JSON.parse(raw);
    if(!list || !list.length) return false;
    for(var i=0;i<list.length;i++){
      var s = list[i]; if(!s) continue;
      if(String(s.label||'') !== 'auto:start') return true;   /* they saved, or slept, or died */
      if((s.beat|0) > 0 || ((s.engine && s.engine.turn)|0) > 0) return true;
    }
  } catch(_e){ return false; }
  return false;
}

/* WHO GETS TO SEE IT. Once per device, and never over a day already in progress
   -- somebody mid-story is not at the beginning, and being shown the beginning
   would read as a bug rather than as drama. */
function openShould(){
  try { if(localStorage.getItem(OPEN_SEEN_KEY)) return false; } catch(_e){ return false; }
  if(openHasProgress()) return false;
  return !!(typeof BohemiaStorySurface !== 'undefined' && openWhich());
}
function openMarkSeen(){ try{ localStorage.setItem(OPEN_SEEN_KEY,'1'); }catch(_e){} }

function openCaption(s, ended){
  var cap=document.getElementById('openCap'); if(!cap) return;
  if(ended || (s && s.ended)){ cap.textContent=''; return; }
  var L = s && s.line;
  if(!L || !L.text){
    cap.innerHTML='<span style="color:#6f6552;letter-spacing:2px">'+
      (((s && s.scene && s.scene.when) ? String(s.scene.when).toUpperCase() : null) || ((s && s.era==='pre_collapse') ? 'BEFORE' : 'TEN YEARS LATER'))+'</span>';
    return;
  }
  cap.innerHTML='<span style="color:#9a8a5e;font-size:11px;letter-spacing:1px">'+
    (typeof cutSpeakerName==='function' ? cutSpeakerName(L.speaker) : String(L.speaker||''))+
    '</span><br>'+String(L.text).replace(/&/g,'&amp;').replace(/</g,'&lt;');
}

/* THE HANDOFF. However it ends -- played out, skipped, or thrown -- the player
   ends up in the day. An opening that can strand somebody on a black screen is
   worse than no opening, so every exit runs through here exactly once. */
function openDone(){
  if(!OPEN_RUNNING) return;
  OPEN_RUNNING=false;
  openMarkSeen();
  try{ if(OPEN_PLAYER && OPEN_PLAYER.stop) OPEN_PLAYER.stop(); }catch(_e){}
  var w=document.getElementById('openWrap'); if(!w) return;
  w.style.transition='opacity .45s'; w.style.opacity='0';
  setTimeout(function(){ w.style.display='none'; w.style.opacity='1'; w.style.transition=''; }, 460);
}

/* *** IT MUST NOT PLAY BEHIND THE SPLASH, AND IT WAS. *** Caught by LOOKING at
   the render rather than by asking the DOM: the overlay said display:flex, the
   canvas had pixels in it, the captions advanced BEFORE -> the mother's line ->
   the daughter's line, every check green -- and the screenshot was the TAP TO
   ENTER screen, because #front is position:fixed z-index:200 and sits over
   everything. The opening was burning through where nobody could see it.
   VERIFY ON THE REAL SURFACE (7/18) means look at the pixels a person sees, not
   the pixels you addressed. So: if the front screen is still up, wait for it.
   Raising the overlay above the splash would have been the wrong fix -- the
   splash is the door and the opening happens after you walk through it. */
function openFrontUp(){
  var f=document.getElementById('front');
  return !!f && getComputedStyle(f).display !== 'none';
}
/* *** THE RUN TAB DOES NOT SHOW THE RUN PANEL. *** Paolo 7/28, "Can you put the
   city in the run tab?" -- the switcher routes `run` to p-city and leaves the
   run iframe parked in a hidden p-run so postMessage still finds it. The first
   cut of this put the overlay in p-run, which NEVER gets the on class, so it
   computed display:flex inside a display:none parent: every DOM check passed,
   the canvas really was painting, and its bounding box was 0x0. Only the
   screenshot showed the truth.
   So the overlay MOVES to whatever panel is actually live at play time, rather
   than trusting any panel id. If the routing changes again this follows it. */
function openHost(){
  var on=document.querySelector('.panel.on');
  return on || document.getElementById('p-city') || document.getElementById('p-run');
}
function openStart(){
  if(OPEN_RUNNING || !openShould()) return;
  var w=document.getElementById('openWrap'), cv=document.getElementById('openCv');
  if(!w || !cv || typeof cutBoot!=='function') return;
  if(openFrontUp()){
    /* poll rather than hook the splash's own click: another lane owns that
       handler and a second listener on it is a boundary crossing waiting to
       break. Cheap, self-cancelling, and it cannot be got wrong by a reorder. */
    var tries=0;
    var iv=setInterval(function(){
      if(!openFrontUp()){ clearInterval(iv); openStart(); return; }
      if(++tries > 600) clearInterval(iv);        /* five minutes, then give up */
    }, 500);
    return;
  }
  OPEN_RUNNING=true;
  var host=openHost();
  if(host && w.parentElement!==host){
    if(getComputedStyle(host).position==='static') host.style.position='relative';
    host.appendChild(w);
  }
  w.style.display='flex';
  var cap=document.getElementById('openCap');
  if(cap) cap.innerHTML='<span style="color:#6f6552">...</span>';
  /* cutBoot bakes the family once and caches the frames; reusing them is the
     difference between an opening that starts in a second and one that makes a
     demo player stare at a black rectangle while six rigs rebuild. */
  cutBoot(function(){
    var sc=openScene();
    if(!sc){ openDone(); return; }
    openPlay(sc);
  });
}

/* ---- WHAT A SCENE HANDS OFF TO ------------------------------------------
   Returns true if it has taken responsibility for what happens next. False
   means nothing follows and the opening is over -- the caller ends it, so a
   handoff this cannot honour can never silently look like a finished sequence.

   *** THE RAID HAD NO CALLER FOR TWELVE DAYS. *** startColdOpen(onEnd) has been
   sitting in the alpha since 8/8 with exactly one occurrence -- its own
   definition. The family-defense encounter is the combat tutorial, the raid, and
   the scene the sibling is killed in, and it had never been played from
   anywhere: the game went warm dinner -> cut -> "get to the back door" -> you
   wake up on day 1 and get a job. The death the whole opening is built on did
   not happen, which made the grief dinner mourn nothing and the burial bury
   nobody.

   IT DOES NOT INVENT A HANDOFF PATH. cityEncounterIn() has done this exact
   dance for weeks -- show the combat panel, make sure the frame exists, wait for
   it, then start the encounter -- and its own comment says why a second one
   would be wrong: "A second handoff path is the duplicate-system mistake this
   repo keeps paying for." So this mirrors that shape, calls the function COMBAT
   published for the scene to name, and switches the surface with showTabPanel,
   which is the alpha's own public switcher.

   IT FAILS SAFE. No seam, no tab, or a throw anywhere in it, and this returns
   false so the opening simply ends the way it did yesterday. The demo can never
   be worse off than before this existed. */
function openHandoff(h, fromId){
  if(!h) return false;
  if(h.to === 'scene' && h.scene){
    var nxt = openSceneById(h.scene);
    if(!nxt) return false;
    return openPlay(nxt);
  }
  if(h.to === 'combat' && h.call) return openRaid(h, fromId);
  return false;
}

/* the fight is not a cutscene, so the overlay stands down for it and the
   sequence resumes when the encounter settles. */
function openRaid(h, fromId){
  var fn = (typeof window !== 'undefined') ? window[h.call] : null;
  if(typeof fn !== 'function') return false;
  if(typeof showTabPanel !== 'function') return false;
  openHideOverlay();
  openMarkSeen();               /* he has seen the opening; it must not replay */
  OPEN_RUNNING = false;
  var resumed = false;
  function resume(){
    if(resumed) return; resumed = true;
    try{ showTabPanel('run'); }catch(_e){}
    setTimeout(function(){
      try{ if(!openContinue(fromId)) openDone(); }catch(_e){ openDone(); }
    }, 500);
  }
  try {
    showTabPanel('combat');
    /* the frame may not exist yet; clicking the tab is what builds it, and the
       generic data-src promoter runs off the same click. Same order
       cityEncounterIn uses, for the same reason. */
    var tab = document.querySelector('.tab[data-p=combat]');
    if(!document.getElementById('combatFrame') && tab) tab.click();
    var fr = document.getElementById('combatFrame');
    var go = function(){ try{ fn(resume); }catch(_e){ resume(); } };
    if(!fr) { go(); return true; }
    if(fr.contentDocument && fr.contentDocument.readyState === 'complete') setTimeout(go, 250);
    else fr.addEventListener('load', function(){ setTimeout(go, 250); });
    return true;
  } catch(_e){ return false; }
}

/* fade the overlay WITHOUT ending the sequence. openDone does this and also
   marks the opening finished; the raid needs only the first half. */
function openHideOverlay(){
  var w=document.getElementById('openWrap'); if(!w) return;
  try{ if(OPEN_PLAYER && OPEN_PLAYER.stop) OPEN_PLAYER.stop(); }catch(_e){}
  w.style.transition='opacity .45s'; w.style.opacity='0';
  setTimeout(function(){ w.style.display='none'; w.style.opacity='1'; w.style.transition=''; }, 460);
}

/* PLAY ONE SCENE OF THE SEQUENCE. Pulled out of openStart so the second and
   third beats are played by exactly the same code as the first -- a sequence
   whose later scenes go through a different path is a sequence where only the
   first one is really tested. */
function openPlay(sc){
  var cv=document.getElementById('openCv');
  if(!sc || !cv) { openDone(); return false; }
  try{ if(OPEN_PLAYER && OPEN_PLAYER.stop) OPEN_PLAYER.stop(); }catch(_e){}
  OPEN_RUNNING=true;
  var w=document.getElementById('openWrap');
  if(w) w.style.display='flex';
  OPEN_PLAYER=new BohemiaStorySurface.Story({
    canvas:cv, set:BohemiaColdOpenSet, scene:sc, runtime:BohemiaScene,
    stage:BOH_STAGE, floorplan:BOH_FLOORPLAN,
    paintBody:cutPaintBody, speak:cutVoice,
    playerSex:(typeof G!=='undefined' && G && G.sex) ? G.sex : 'male',
    onBeat:function(r,s){ openCaption(s); },
    /* THE SEQUENCE DECIDES WHAT HAPPENS AT THE END, NOT THE SCENE. If the
       scene that just finished names another SCENE, play it. If it hands off
       to something this runner cannot call -- the raid -- stop here rather
       than skipping to a grief dinner for a death nobody watched. */
    onEnd:function(s){
      openCaption(s,true);
      var h=openNext(sc);
      setTimeout(function(){ if(!openHandoff(h, sc.id)) openDone(); }, 900);
    }
  });
  if(typeof CUT_FRAMES!=='undefined' && CUT_FRAMES) OPEN_PLAYER.frames=CUT_FRAMES;
  OPEN_PLAYER.loadTiles(function(){
    function go(){ try{ OPEN_PLAYER.start(); }catch(_e){ openDone(); } }
    if(OPEN_PLAYER.frames && Object.keys(OPEN_PLAYER.frames).length) go();
    else OPEN_PLAYER.bake(go);
  });
  return true;
}

/* *** IT INVITES, IT DOES NOT AMBUSH -- AND THAT IS A DESIGN FIX, NOT A TEST FIX.
   The first cut auto-played the moment the RUN tab was tapped. It worked, and it
   was wrong twice over:
     FOR HIM -- the alpha is a SIXTEEN TAB dev surface and he taps RUN a hundred
       times a day. A forty-second scene seizing the screen because he changed
       tabs is a thing you learn to dread, and there was no moment where the
       story chose to start; it just took over while the run was still loading.
     FOR EVERYTHING ELSE -- it trampled every gate that drives the run. Measured:
       NAV CLUSTER "the canvas is 101px of a 150px viewport" (my overlay had the
       screen), VOICE SURFACES "30 utterances for 7 distinct lines" and VOICE
       "three utterances needed to check voice identity" (my scene was talking
       over their count). Three other lanes' gates, red, because of me.
   A small card, out of the layout flow, that OFFERS the opening. Still the first
   thing on the run surface for a fresh player, still zero explanation, and now
   the story starts because somebody chose to start it. */
function openInviteShow(){
  if(!openShould()) return;
  var host=openHost(), inv=document.getElementById('openInvite');
  if(!host || !inv) return;
  if(openFrontUp()){
    var tries=0, iv=setInterval(function(){
      if(!openFrontUp()){ clearInterval(iv); openInviteShow(); return; }
      if(++tries>600) clearInterval(iv);
    }, 500);
    return;
  }
  if(getComputedStyle(host).position==='static') host.style.position='relative';
  if(inv.parentElement!==host) host.appendChild(inv);
  /* __THE_COLD_OPEN_CLEARS_THE_TOOLBAR__ -- CLEAR THE CITY'S TOOLBAR.
     This banner used to sit at top:0 of the panel and the walked city's own
     toolbar is a few pixels down inside the iframe, so the banner covered
     MUSIC, save, the builder drawer and PHONE. On DAY 1 the wake card says
     "Something came in on your phone overnight" and shows the unread badge --
     and the phone was underneath this. The job comes in on the phone.
     The offset is REPORTED BY THE CITY, never hardcoded: the shell cannot read
     into the iframe on file:// (opaque origins, which is how every gate runs),
     and the height is the city's business anyway.
     BEFORE THE CITY EXISTS THERE IS NOTHING TO CLEAR, so the banner opens where
     it always did and drops to the reported line the instant the city says where
     its chrome is. That is not a guessed toolbar height -- it is the honest
     statement that an empty panel has no toolbar to cover.
     THE FIRST CUT HELD THE BANNER BACK UNTIL THE REPORT ARRIVED AND THAT WAS
     WRONG: measured, the report lands 8.5 SECONDS after the RUN tap, because the
     city is a 2.3MB document that has to boot. So the story hook sat invisible
     for eight seconds and opening_gate went red on "TAPPING RUN WITH NO DAY IN
     PROGRESS OFFERS THE OPENING" -- correctly. Making a beat wait on another
     document's load is a regression even when the pixels end up right. */
  inv.dataset.want='1';
  if(CITY_BUSY){ inv.style.display='none'; return; }
  inv.style.top=(typeof CITY_CHROME_TOP==='number'?CITY_CHROME_TOP:0)+'px';
  inv.style.display='block';
}
/* var, NOT let: openInviteShow above runs from a tab handler that can fire
   before this line is reached, and a top-level let would throw out of the
   temporal dead zone into a listener nobody is catching. Same trap that ate
   LANDED on 8/11 and CITYSAVE in the standalone check. */
var CITY_CHROME_TOP=null, CITY_BUSY=false;
function cityChromeIn(d){
  if(!d||!d.bohemiaCityChrome) return false;
  var m=d.bohemiaCityChrome, t=m.top;
  if(typeof t!=='number'||!(t>=0)) return true;
  CITY_CHROME_TOP=t; CITY_BUSY=!!m.busy;
  var inv=document.getElementById('openInvite');
  if(!inv) return true;
  /* reposition a banner that is already up: fonts land late, and the phone
     staying covered for the first second is still the phone being covered. */
  inv.style.top=t+'px';
  /* AND STAND DOWN while the city has a surface open, then come back when it
     closes. He never loses the invitation, he just never reads it through the
     phone he was told to check. */
  if(inv.dataset.want==='1') inv.style.display=CITY_BUSY?'none':'block';
  return true;
}
window.addEventListener('message',function(ev){ try{ cityChromeIn(ev&&ev.data); }catch(_e){} });
function openInviteHide(){
  var inv=document.getElementById('openInvite');
  /* __THE_COLD_OPEN_CLEARS_THE_TOOLBAR__ -- answered means answered: clear the want flag too, or a
     later chrome report raises a banner he already dismissed. */
  if(inv){ inv.dataset.want='0'; inv.style.display='none'; }
}

(function(){
  var sk=document.getElementById('openSkip');
  if(sk) sk.addEventListener('click', function(e){ e.stopPropagation(); openDone(); });
  var w=document.getElementById('openWatch');
  if(w) w.addEventListener('click', function(e){ e.stopPropagation(); openInviteHide(); openStart(); });
  var n=document.getElementById('openNot');
  /* NOT NOW is a real answer and it is remembered. Asking twice is the same
     ambush in a politer voice, and the CUTSCENE tab is where it lives forever. */
  if(n) n.addEventListener('click', function(e){ e.stopPropagation(); openInviteHide(); openMarkSeen(); });
  /* THE TRIGGER. The run frame is lazy-loaded when the RUN tab is tapped (and
     preloaded on a timer), so this hangs off the same tap rather than off page
     load -- otherwise it would sit over the splash for somebody who came to
     look at CLOTHES. */
  var t=document.getElementById('tabs'); if(!t) return;
  var rt=t.querySelector('.tab[data-p=run]');
  if(rt) rt.addEventListener('click', function(){ setTimeout(openInviteShow, 60); });
})();
</script>
''' + JS_END


def swap(text, begin, end, block, what):
    """REPLACE, NEVER APPEND. Idempotent by construction."""
    i = text.find(begin)
    if i >= 0:
        j = text.find(end, i)
        if j < 0:
            sys.exit('REFUSING TO WRITE: %s has an opening marker and no closing one.' % what)
        return text[:i] + block + text[j + len(end):], True
    return text, False


def main():
    src = open(ALPHA, encoding='utf-8').read()
    before = src
    n_before = src.count('\n')

    src, had_panel = swap(src, PANEL_BEGIN, PANEL_END, PANEL, 'the overlay')
    if not had_panel:
        anchor = '<div class="panel" id="p-run">'
        n = src.count(anchor)
        if n != 1:
            sys.exit('REFUSING TO WRITE: the run panel anchor resolves %d times, not 1.' % n)
        # the overlay is absolutely positioned, so the panel must be a containing block
        old = anchor
        new = '<div class="panel" id="p-run" style="position:relative">\n' + PANEL + '\n      '
        src = src.replace(old, new, 1)

    src, had_js = swap(src, JS_BEGIN, JS_END, JS, 'the opening script')
    if not had_js:
        # AFTER the cutscene tab, always: it needs cutBoot, cutPaintBody, cutVoice,
        # BohemiaStorySurface and BohemiaColdOpenSet to already be defined, and it
        # needs DIR, which the DIRECT tab declares.
        anchor = '<!-- ===== END BOHEMIA DIRECT TAB ===== -->'
        n = src.count(anchor)
        if n != 1:
            sys.exit('REFUSING TO WRITE: the DIRECT tab end marker resolves %d times, not 1. '
                     'The opening must be emitted after both the CUTSCENE and DIRECT blocks.' % n)
        src = src.replace(anchor, anchor + '\n' + JS, 1)

    # *** THIS TOOL ATE ANOTHER LANE'S WORK, AND THE HEADER'S OWN BOAST IS WHY. ***
    # "IT REPLACES, IT NEVER APPENDS ... everything lives between markers and is
    # swapped whole" is exactly right for MY content and exactly wrong the moment
    # somebody else edits inside my region. On 8/20 the RUN lane's
    # __THE_COLD_OPEN_CLEARS_THE_TOOLBAR__ fix -- the one that stopped this very
    # banner covering the PHONE, which is where the day's job arrives -- lived
    # inside the overlay block. Re-running this after a rebase silently deleted
    # 47 lines of it. Caught by reading `git diff --stat` on a tree I had just
    # been told was green.
    #   A WHOLE-REGION REPLACE IS A DELETE PLUS AN INSERT, and the delete half
    #   does not know whose lines it is taking.
    # The tool's own content is fixed, so a NET LOSS OF LINES can only be
    # somebody else's edit inside the region. That is now a refusal, not a
    # surprise. Second time a patch tool in this lane has done this (8/17, 2,607
    # lines of the FACTIONS lane), and the first time the guard was added to the
    # tool that did it rather than to all of them.
    grew = src.count('\n') - n_before
    if grew < 0:
        sys.exit('REFUSING TO WRITE: this would REMOVE %d lines from the alpha.\n'
                 '  A whole-region replace cannot tell your lines from somebody '
                 'else\'s.\n'
                 '  Somebody has edited INSIDE the opening markers -- diff the '
                 'region, fold their\n'
                 '  change into PANEL/JS in this file, and run again.' % -grew)

    if src == before:
        print('OPENING: already exactly this. Nothing written.')
        return
    open(ALPHA, 'w', encoding='utf-8').write(src)
    print('OPENING: overlay %s, script %s, %+d lines'
          % ('replaced' if had_panel else 'inserted',
             'replaced' if had_js else 'inserted', grew))
    print('  alpha : %.1f MB' % (os.path.getsize(ALPHA) / 1e6))


if __name__ == '__main__':
    main()
