#!/usr/bin/env python3
"""
THE LAST LINK IN THE FIRST MORNING WAS THE DARKEST BUTTON ON THE SCREEN
(8/25/26, RUN lane. Backlog row P0-MORNING, third and final patch.)

THE COLD HAND -- a probe that presses the loudest control on screen, never reads,
and cannot press through a modal -- now gets four taps deep on a cold boot:

    1. WATCH     the opening        gold, score 89
    2. GET UP    the wake card      score 43
    3. PHONE     the ringing chip   gold, score 90   (fixed an hour ago)
    4. ???

and stalled, because the button that TAKES THE JOB is `.mapgo` -- background
#2a2418, a dark chip built for the map's small "GO" link. On the phone's own
screen it is quieter than the wallpaper. Every other thing on that screen is text.

THE JOB IS THE ONLY REASON THE PHONE OPENS ON DAY ONE. `LIVE.offer` is true for
exactly one state -- a job has come in and has not been taken -- and in that state
TAKE IT is not one option among several, it is the single thing the screen exists
to let him do. It should look like it.

So it wears the same solid fill the opening's WATCH button and the ringing phone
chip already wear (#d8b45a on #191308). THAT IS NOW THE SENTENCE THE WHOLE FIRST
MORNING IS WRITTEN IN, and he has pressed it twice before he gets here:

    WATCH -> GET UP -> [gold] PHONE -> [gold] TAKE IT

Norman's rule is that a signifier has to be learnable; the same fill in the same
role three times is how it gets learned, and it beats any amount of copy telling
him where to press.

*** IT IS ONLY LOUD IN THE STATE THAT DESERVES IT. *** `.mapgo` is untouched --
the map's GO links stay the quiet chips they were designed as. Only `.lv-take`,
which exists solely inside `if(LIVE.offer)`, gets the fill, so the phone goes back
to being calm the moment the job is his.

*** AND THIS EDITS THE SOURCE, NOT THE BUILD. *** slices/BOHEMIA_CURRENT_SLICE.html
is GENERATED by tools/build_current_slice.js from
slices/BOHEMIA_SOCIAL_PHONE_DEMO_7_20_26.html. I edited the generated file once
already, on a different job, and the CURRENT SLICE gate caught it with
"regenerating changes nothing" going FALSE. BEFORE EDITING A FILE, ASK WHO
GENERATES IT. Run build_current_slice.js after this.

REUSE CHECK: no graphic pixels cooked -- a CSS rule reusing the fill already
declared on #openWatch in the alpha and on #phonebtn.ring in the city, so no
banks/ lookup applies.

Idempotent (marker __TAKE_IT_IS_THE_YES__).
"""
import os
import sys

SRC = 'slices/BOHEMIA_SOCIAL_PHONE_DEMO_7_20_26.html'
MARK = '__TAKE_IT_IS_THE_YES__'

OLD = """.lv-take{margin-top:8px;margin-left:0;display:inline-block}"""

NEW = """/* """ + MARK + """ (8/25) -- THE YES LOOKS LIKE THE YES.
   A cold hand that presses the loudest control on screen and never reads got
   WATCH -> GET UP -> PHONE and then stalled here, because TAKE IT inherited
   .mapgo (#2a2418, the map's small quiet GO link) and was the darkest thing on
   its own screen. LIVE.offer is true for exactly one state -- a job has come in
   and has not been taken -- and in that state this is not one option among
   several, it is the only reason the phone is open.
   THE FILL IS NOT NEW: it is the opening's WATCH button and the ringing phone
   chip, so by the time he reaches it he has pressed it twice and the language is
   learned. .mapgo itself is untouched, so the map's GO links stay quiet, and this
   goes quiet too the moment the job is his. */
.lv-take{margin-top:8px;margin-left:0;display:inline-block;
  background:#d8b45a;border-color:#d8b45a;color:#191308;
  padding:7px 14px;font-size:11px;letter-spacing:2px}
.lv-take:active{background:#c8a44a;color:#0d0a04}"""


def main():
    if not os.path.exists(SRC):
        sys.exit('FAIL: ' + SRC + ' not found')
    s = open(SRC, encoding='utf8').read()
    if MARK in s:
        print('NOOP: the yes already looks like the yes')
        return
    for needle, why in (('lv-take" onclick="phoneTake()"', 'the button that takes the job'),
                        ('if(LIVE.offer){', 'the one state it appears in')):
        if needle not in s:
            sys.exit('FAIL: %s is missing (%s)' % (needle, why))
    n = s.count(OLD)
    if n != 1:
        sys.exit('FAIL: the .lv-take rule matched %d times, expected 1' % n)
    open(SRC, 'w', encoding='utf8').write(s.replace(OLD, NEW, 1))
    print('PATCHED %s -- now run: node tools/build_current_slice.js' % SRC)


if __name__ == '__main__':
    main()
