#!/usr/bin/env python3
"""
SIDE DOORS IN THE DISTRICT HE ACTUALLY STANDS IN (8/3/26).

Paolo, third time asking: "id dint see the side door."

I fixed the geometry. I fixed the draw order. I wired his 7/10 edge-on art. Then I
measured coverage and reported "commercial 22/22, farm 10/10" and called it done.

HE SPAWNS IN THE SUBURB. The suburb is generated by a COMPLETELY SEPARATE BRANCH of
the cell realizer (m.sub, its own front-door rule from 7/27) and my east/west pass only
touched the generic KIT branch (m.kit). So in the ONE district he walks around in, there
were ZERO side doors, and my gate was green because it swept the whole valley and found
plenty of them in districts he has never visited.

THE REAL LESSON, and it is going in the law: A MEASUREMENT THAT IS NOT TAKEN WHERE HE
IS STANDING IS NOT A MEASUREMENT OF WHAT HE SEES. "22 of 22 buildings" is worthless if
the 22 are somewhere he will never walk. The gate now asserts side doors exist IN THE
SPAWN DISTRICT specifically, not merely somewhere in a 96x96 valley.

WHAT THIS DOES: the same rule the kit branch already got, ported into the suburb branch
in the suburb's own vocabulary (codes: 2 house, 6 garage, 9 upper floor, 3 driveway,
1 road, 10 sidewalk, 0 dead ground).

    A DOOR GOES WHERE THE HOUSE MEETS GROUND A PERSON CAN STAND ON.
    South approach  -> the front-door plate (7/27 rule, untouched).
    East / west     -> his edge-on sliver on that side, one per contiguous
                       VERTICAL run, topmost tile of the run takes it.

The 7/27 rule stays exactly as approved for the FRONT door; this only adds the sides,
which had nothing at all. Every side door faces a cell a person can stand on, so none
of them is the 7/27 bug (a door onto a lot with no way to reach it).

REUSE CHECK: cooks no graphic pixels and embeds no new bytes. It sets the same
c.doorW / c.doorE flags the kit branch sets, drawn by the ewDoorPass already in the
renderer out of the JAMB_WI / JAMB_EI arrays that came from
banks/BOHEMIA_DOOR_EW_BANK_7_10_26.txt. Same 368 strips, same bank, same draw.

Idempotent: re-running finds the marker and reports NOOP.
"""
import base64
import re
import sys

ALPHA = 'slices/BOHEMIA_ALPHA_0_9.html'
MARKER = '__SUBURB_EW_DOORS__'

ANCHOR = """        const gh=(Math.imul(gx,73856093)^Math.imul(gy,19349663))>>>0, pick=gh%20;
        c.artPool_face=doorHere?'hdoor':(pick<14?'hwall':(pick<19?'hwindow':'hboarded'));
      }
    }
    return c;
  }"""

NEW = """        const gh=(Math.imul(gx,73856093)^Math.imul(gy,19349663))>>>0, pick=gh%20;
        c.artPool_face=doorHere?'hdoor':(pick<14?'hwall':(pick<19?'hwindow':'hboarded'));
      }
      /* """ + MARKER + """ -- THE DISTRICT HE ACTUALLY STANDS IN.
         Paolo, third time: "id dint see the side door." The east/west door pass went
         into the generic KIT branch. He spawns in the SUBURB, which is this branch --
         a completely separate realizer with its own 7/27 front-door rule -- so the one
         district he walks around in had ZERO side doors while the gate reported
         "commercial 22/22, farm 10/10" and went green. A measurement that is not taken
         where he is standing is not a measurement of what he sees.
         Same rule as the kit branch, in the suburb's own codes: a door goes where the
         house meets ground a person can stand on. The 7/27 FRONT door rule above is
         untouched; this only adds the sides, which had nothing at all. */
      const isBody=(v)=>(v===2||v===6||v===9);
      const canStand=(v)=>(v===0||v===1||v===3||v===10);
      if(isBody(v)){
        const upV=(ly>0)?m.sub[(ly-1)*FN+lx]:0;
        const wV=(lx>0)?m.sub[ly*FN+(lx-1)]:0, eV=(lx<FN-1)?m.sub[ly*FN+(lx+1)]:0;
        const upW=(ly>0&&lx>0)?m.sub[(ly-1)*FN+(lx-1)]:0;
        const upE=(ly>0&&lx<FN-1)?m.sub[(ly-1)*FN+(lx+1)]:0;
        if(canStand(wV)&&!(isBody(upV)&&canStand(upW))) c.doorW=true;
        if(canStand(eV)&&!(isBody(upV)&&canStand(upE))) c.doorE=true;
        if((c.doorW||c.doorE)&&typeof window!=='undefined')
          window.__SUB_EW_DOORS=(window.__SUB_EW_DOORS||0)+1;
      }
    }
    return c;
  }"""


def main():
    alpha = open(ALPHA, encoding='utf8', errors='ignore').read()
    m = re.search(r"CITY_B64\s*=\s*['\"`]([A-Za-z0-9+/=]{5000,})", alpha)
    if not m:
        print('FAIL: CITY_B64 not found'); return 1
    city = base64.b64decode(m.group(1)).decode('utf8', errors='ignore')
    if MARKER in city:
        print('NOOP: the suburb already has side doors'); return 0
    if city.count(ANCHOR) != 1:
        print('FAIL: the suburb facade branch is not where this tool expects it (%d)'
              % city.count(ANCHOR)); return 1
    if 'function ewDoorPass(' not in city:
        print('FAIL: the E/W draw pass is missing -- run the ewdoor patch first'); return 1

    city = city.replace(ANCHOR, NEW, 1)
    if city.count(MARKER) != 1:
        print('FAIL: post-edit marker count %d' % city.count(MARKER)); return 1

    out = base64.b64encode(city.encode('utf8')).decode('ascii')
    open(ALPHA, 'w', encoding='utf8').write(alpha[:m.start(1)] + out + alpha[m.end(1):])
    print('wrote %s' % ALPHA)
    print('  suburb houses now carry east/west doors -- the district he spawns in')
    return 0


if __name__ == '__main__':
    sys.exit(main())
