/* ============================================================================
   THE INSIDE OF A POLICE STATION  (WORLD, 10/10/26)
   row [the valley has no inside]

   TWO REAL FLOORPLANS, SIDE BY SIDE, BOTH GENERATED BY THE GAME'S OWN INTERIOR
   GENERATOR AT THE SAME FOOTPRINT AND THE SAME SEED. Nothing is drawn by hand
   and nothing is arranged: these are the two answers the game currently gives
   for the same building.

   LEFT is what the engine says a police station is: a hall, a reception, an
   office, a records room and a bath.
   RIGHT is WHAT THE GAME ACTUALLY BUILDS TODAY, because the thing that builds
   the rooms holds an older copy of the table and reads `institutional`: an
   office, a service room, a bath, AND TWO HOSPITAL WARDS.

   THE ROW SAID THE VALLEY HAS NO INSIDE AND THIS LANE WROTE THE ROW. It has had
   one since 7/26. What it has is the table twice, and the copies disagree on six
   districts -- the police station, the fire station, the school, the campus, the
   bus terminal and the sign -- every disagreement collapsing a specific grammar
   into the generic one.

   REFERENCE CHECK
   COMPARED TO: AH-01 (the analog horror bible), TG-02 (how a flat tone reads at
   a small size), CB-06 (the valley's own grain, ours, measured and gated),
   CB-03 (a Vegas block from the air) and BLDG-05 (how a real building's plan
   reads: served space off a corridor, service against the back wall).

   STRUCTURAL RULES TAKEN:
     * BLDG-05 -- a real plan is rooms off a spine with the doors on the spine,
       and that is what the generator makes, so the composition is its own.
     * TG-02 -- three tones inside a panel (floor, wall, door) so a plan still
       reads at this size; the wards are marked, nothing else is.
     * CB-06 / CB-03 -- the valley's own tones, flat, no outlines added.
     * AH-01 -- ordinary frame, ONE THING WRONG. Two floorplans side by side is
       the ordinary part, the thing any architect's drawing set prints. THE
       WRONG THING IS THAT THEY ARE THE SAME BUILDING: the police station in
       this valley has two hospital wards in it, and it has had them for as long
       as anybody has been able to walk inside, and nobody noticed because the
       rooms are generated and nobody reads the labels.

   NOT SHIPPED TO A PLAY SURFACE (rule 18): a picture for the VOTE tab.

     node tools/bohemia_the_insides_cook_10_10_26.js
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const REPO = path.resolve(__dirname, '..');
let IN = require(path.join(REPO, 'engine/bohemia_insides.js')); IN = IN.BOH_INSIDES || IN;
const FP = require(path.join(REPO, 'engine/bohemia_floorplan.js'));

const W = 44, H = 28, SEED = 1337, SCALE = 3, GAP = 2;

const PALETTE = {
  0: '#0a0a0c',   /* the sheet */
  1: '#2a2823',   /* floor you can stand on */
  2: '#c9bb86',   /* wall */
  3: '#e86a3a',   /* a door */
  4: '#7fb0c9'    /* a ward: a hospital room in a police station */
};
const LEGEND = {
  0: 'the sheet', 1: 'floor you can stand on', 2: 'wall', 3: 'a door',
  4: 'a hospital ward, in a police station'
};

function blank(w, h, f) { const g = []; for (let y = 0; y < h; y++) g.push(new Array(w).fill(f)); return g; }

/* draw a plan into a w x h box, marking the cells of any room whose role is in `mark` */
function drawPlan(p, mark) {
  const img = blank(p.W, p.H, 1);
  const wardCells = new Set();
  (p.rooms || []).forEach((r, i) => {
    if (mark.indexOf(r.role) < 0) return;
    for (let y = r.y; y < r.y + r.h; y++) for (let x = r.x; x < r.x + r.w; x++) wardCells.add(y + ',' + x);
  });
  for (let y = 0; y < p.H; y++) for (let x = 0; x < p.W; x++) {
    const c = p.grid[y][x], g = c && c.g;
    if (g === 'wall') img[y][x] = 2;
    else if (g === 'door') img[y][x] = 3;
    else img[y][x] = wardCells.has(y + ',' + x) ? 4 : 1;
  }
  return img;
}

function main() {
  /* ---- REFUSALS, before a pixel ---------------------------------------- */
  const drift = Object.keys(IN.DRIFT.disagree);
  if (drift.indexOf('policestation') < 0) {
    console.log('REFUSED: the police station is not one of the drifted districts any more. '
      + 'This picture is two answers to one building; if the two tables agree about it, '
      + 'there is one answer and the picture is about nothing.');
    process.exit(1);
  }
  const right = IN.proveAnInside('civic', W, H, SEED);
  const wrong = IN.proveAnInside('institutional', W, H, SEED);
  if (!right.known || !wrong.known) {
    console.log('REFUSED: the interior generator did not answer, so there is nothing real to draw.');
    process.exit(1);
  }
  if (wrong.rooms.indexOf('ward') < 0) {
    console.log('REFUSED: the institutional grammar no longer makes a ward, so the thing this '
      + 'picture exists to show -- a hospital room in a police station -- is not happening.');
    process.exit(1);
  }
  if (right.rooms.indexOf('ward') >= 0) {
    console.log('REFUSED: the civic grammar makes a ward too, so the two sides are not different '
      + 'and the picture would be claiming a difference that is not there.');
    process.exit(1);
  }
  if (right.floor < 100 || wrong.floor < 100) {
    console.log('REFUSED: a plan came back with ' + Math.min(right.floor, wrong.floor)
      + ' floor cells. The row this corrects said the valley has no inside; a picture '
      + 'arguing otherwise needs a real one.');
    process.exit(1);
  }

  /* ---- THE TWO PLANS, SAME FOOTPRINT, SAME SEED ------------------------- */
  const pRight = FP.generate(SEED, W, H, { zone: 'civic' });
  const pWrong = FP.generate(SEED, W, H, { zone: 'institutional' });
  if (pRight.W !== pWrong.W || pRight.H !== pWrong.H) {
    console.log('REFUSED: the two plans came back different sizes (' + pRight.W + 'x' + pRight.H
      + ' and ' + pWrong.W + 'x' + pWrong.H + '), so they are not the same building and the '
      + 'comparison is not honest.');
    process.exit(1);
  }
  const imgR = drawPlan(pRight, ['ward']);
  const imgW = drawPlan(pWrong, ['ward']);

  const SW = 2 * pRight.W + 3 * GAP, SH = pRight.H + 2 * GAP;
  const sheet = blank(SW, SH, 0);
  [imgR, imgW].forEach((im, i) => {
    const ox = GAP + i * (pRight.W + GAP), oy = GAP;
    for (let y = 0; y < pRight.H; y++) for (let x = 0; x < pRight.W; x++) sheet[oy + y][ox + x] = im[y][x];
  });

  let wardCells = 0;
  for (let y = 0; y < SH; y++) for (let x = 0; x < SW; x++) if (sheet[y][x] === 4) wardCells++;
  if (!wardCells) {
    console.log('REFUSED: not one ward cell reached the sheet, so the blue that the whole '
      + 'picture turns on is not in it.');
    process.exit(1);
  }

  /* ---- WRITE ------------------------------------------------------------ */
  const doc = {
    id: 'WORLD_THE_INSIDES', made: '10/10/26', lane: 'world',
    row: '[the valley has no inside]', draft: true,
    measured: {
      footprint: [pRight.W, pRight.H], seed: SEED,
      engineSays: { zone: 'civic', rooms: right.rooms, floor: right.floor, wall: right.wall, door: right.door },
      theGameBuilds: { zone: 'institutional', rooms: wrong.rooms, floor: wrong.floor, wall: wrong.wall, door: wrong.door },
      wardCellsOnTheSheet: wardCells,
      drift: Object.keys(IN.DRIFT.disagree).concat(IN.DRIFT.missingFromTheApp).sort(),
      noGrammarYet: IN.NO_GRAMMAR_YET.owesOne.districts.length
    }
  };
  fs.writeFileSync(path.join(REPO, 'banks/BOHEMIA_THE_INSIDES_10_10_26.txt'), JSON.stringify(doc));
  fs.writeFileSync(path.join(REPO, 'banks/_insides_grid.json'),
    JSON.stringify({ g: sheet, pal: PALETTE, leg: LEGEND, w: SW, h: SH }));

  fs.writeFileSync(path.join(REPO, 'records/target/BOHEMIA_THE_INSIDES.json'), JSON.stringify({
    _readme: 'WORLD [the valley has no inside] 10/10: the valley\'s insides as one table. '
      + 'Written by tools/bohemia_the_insides_cook_10_10_26.js from engine/bohemia_insides.js -- '
      + 'do not hand edit. THE ROW WAS WRONG AND THIS LANE WROTE IT: the valley has had an inside '
      + 'since 7/26 (engine/bohemia_floorplan.js, the INTERIOR-MATCHES-EXTERIOR LAW, a 62-district '
      + 'room-grammar table). What is wrong is that THE TABLE EXISTS TWICE -- DISTGEN in the engine '
      + 'and IN_ZONE in the CITY app -- and the copies disagree on six districts, every '
      + 'disagreement collapsing a specific grammar into the generic `institutional`, so a POLICE '
      + 'STATION IS GENERATED WITH TWO HOSPITAL WARDS IN IT. No second copy of the table is made '
      + 'here: the rows below are read from the live DISTGEN by the gate.',
    version: 'BOHEMIA_THE_INSIDES_v1', built: '2026-10-10',
    theTableExistsTwice: IN.DRIFT,
    districtsWithNoGrammarYet: IN.NO_GRAMMAR_YET,
    whatAnInsideIs: {
      from: IN.SRC_FP,
      aCityHallFootprint: right,
      whatAPoliceStationGetsToday: wrong
    },
    measured: doc.measured
  }, null, 1));

  console.log('wrote banks/BOHEMIA_THE_INSIDES_10_10_26.txt and records/target/BOHEMIA_THE_INSIDES.json');
  console.log('  *** THE VALLEY HAS AN INSIDE AND HAS SINCE 7/26; THE TABLE THAT PICKS THE ROOMS EXISTS TWICE ***');
  console.log('  one ' + pRight.W + 'x' + pRight.H + ' building, one seed, two answers:');
  console.log('    the engine says    civic          ' + right.rooms.join(' / '));
  console.log('    the game builds    institutional  ' + wrong.rooms.join(' / '));
  console.log('  six districts disagree: ' + doc.measured.drift.join(', '));
  console.log('  and ' + IN.NO_GRAMMAR_YET.owesOne.districts.length + ' live districts owe a grammar, '
    + 'four of them the Strip\'s own casinos');
}

main();
