#!/usr/bin/env python3
"""BOHEMIA CUTSCENE TAB -- put the cold open where Paolo can watch it.

WHY. engine/bohemia_scene.js has played the Act 1 cold open correctly since 8/9
and gates/scene_gate.js proves it beat by beat -- headless, in a terminal.
It appeared in ZERO slices. NAME THE TAB: a thing he cannot reach does not
exist to him. This wires the runtime, the approved set, the scene canon and the
surface into the alpha as the CUTSCENE tab.

IT REPLACES, IT NEVER APPENDS. The CHARACTER lane learned this the hard way on
8/11: "an insert tool run twice is a duplication tool -- anything editing
shipped code must REPLACE, not ADD" (they shipped two `var FAMILY_CAST` and it
measured fine because the later declaration won). So everything this writes
lives between two markers and is swapped whole on every run. Running it ten
times leaves the file identical to running it once.

WHAT IT INLINES, ALL VERBATIM (ENGINE SYNC LAW -- one canonical body per
module; a copy that can drift is a second body):
  engine/bohemia_scene.js            the beat runtime
  engine/bohemia_coldopen_set.js     12 approved tiles out of the interior pool
  engine/bohemia_story_surface.js    the room
  records/BOHEMIA_SCENE_ACT1_COLD_OPEN.json   the authored canon
gates/coldopen_gate.js re-reads all four off disk and fails if the inlined copy
has drifted by one byte.

ONE-LINK LAW: this ships INSIDE the alpha. No new URL, ever.

  python3 tools/bohemia_story_tab_patch.py
Gate: gates/coldopen_gate.js
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = os.path.join(ROOT, 'slices', 'BOHEMIA_ALPHA_0_9.html')

BEGIN = '<!-- ===== BOHEMIA CUTSCENE TAB (generated by tools/bohemia_story_tab_patch.py) ===== -->'
END = '<!-- ===== END BOHEMIA CUTSCENE TAB ===== -->'

PANEL_BEGIN = '<!-- ===== CUTSCENE PANEL (generated) ===== -->'
PANEL_END = '<!-- ===== END CUTSCENE PANEL ===== -->'

PANEL = PANEL_BEGIN + '''
    <div class="panel" id="p-cutscene">
      <div id="cutWrap" style="max-width:420px;margin:6px auto 0;padding:0 8px">
        <canvas id="cutCv" width="360" height="470"
          style="width:100%;height:auto;display:block;background:#0a0806;border:1px solid #241c12;border-radius:4px;image-rendering:pixelated"></canvas>
        <div id="cutCap" style="min-height:66px;margin-top:7px;padding:8px 10px;border:1px solid #241c12;border-radius:4px;background:#100c07;font:13px/1.5 ui-monospace,monospace;color:#e8dfc8"></div>
        <div class="row" style="margin-top:7px;gap:6px;display:flex;align-items:center;flex-wrap:wrap">
          <button id="cutPlay" class="opt">&#9654; PLAY THE OPEN</button>
          <button id="cutAgain" class="opt">&#8635; AGAIN</button>
          <span id="cutState" class="mini" style="flex:1;text-align:right"></span>
        </div>
        <div class="mini" style="margin-top:6px;line-height:1.55">
          The opening of the game. One cut carries ten years.
          Every line is a draft you can rewrite in the WORDS tab.
        </div>
      </div>
    </div>
''' + PANEL_END


def read(p):
    with open(os.path.join(ROOT, p), 'r', encoding='utf-8') as f:
        return f.read()


GLUE = r'''
/* ---- THE ALPHA SIDE OF THE CUTSCENE TAB ------------------------------------
   The surface module never touches a global. Everything it needs from this
   file arrives through ONE injected function, and that function is written
   here because this is where the rig lives.

   THE BODIES ARE THE GAME'S BODIES. Not a lookalike cast drawn for a cutscene:
   drawChar over Paolo's painted rig, wearing FAMILY_CAST's wardrobe, aged on
   the 8/11 age axis. If he changes a garment in CLOTHES, the family at the
   table changes with it.

   ONE REBUILD PER BODY, MEASURED. rebuildFromRig + cache clear costs ~19ms;
   another clip off an already-installed rig costs ~0.6ms. So every frame a
   member needs is taken while that member's rig is installed, and the player's
   body is put back afterwards -- these are GLOBALS, and leaving the child rig
   installed would silently reshape every other surface in the game. */
/* *** PAOLO 8/11 ON v1: "glitchy". *** He was describing THIS. v1 trimmed every
   animation frame to ITS OWN painted bounds, so a body whose arm swings two
   pixels wider on frame 3 got a two-pixel-wider canvas -- and since the surface
   plants a sprite by its own width and height, the whole person jumped sideways
   six times a second. The animation was fine; the CROP was moving.
   The bounds are now measured across EVERY frame of a clip and the same box is
   cut out of all of them, so the body sits still and only the pixels inside it
   move. A shared crop is the difference between an animation and a seizure. */
function cutBounds(list){
  var x0=1e9,y0=1e9,x1=-1,y1=-1;
  list.forEach(function(cv){
    try{
      var g=cv.getContext('2d'), d=g.getImageData(0,0,cv.width,cv.height).data;
      for(var y=0;y<cv.height;y++)for(var x=0;x<cv.width;x++){
        if(d[(y*cv.width+x)*4+3]>8){ if(x<x0)x0=x; if(x>x1)x1=x; if(y<y0)y0=y; if(y>y1)y1=y; } }
    }catch(e){}
  });
  return (x1<0)?null:{x:x0,y:y0,w:x1-x0+1,h:y1-y0+1};
}
function cutCrop(cv,b){
  if(!b) return cv;
  var t=document.createElement('canvas'); t.width=b.w; t.height=b.h;
  try{ t.getContext('2d').drawImage(cv,b.x,b.y,b.w,b.h,0,0,b.w,b.h); }catch(e){ return cv; }
  return t;
}
function cutPaintBody(role, age, dir, clips, phases){
  var m=null;
  if(role && window.FAMILY_CAST) for(var i=0;i<FAMILY_CAST.length;i++) if(FAMILY_CAST[i].role===role) m=FAMILY_CAST[i];
  var keepW=window.G_WORN, keepD=G.bodyVar, keepA=G.age, out={};
  try{
    if(m){ window.G_WORN=m.worn; G.bodyVar=m.dials; G.age=m.age||'adult'; }
    else { G.age = age || 'adult'; }      /* the PLAYER, in the player's own fit */
    rebuildFromRig(); try{HD_CACHE.map.clear();}catch(e){}
    clips.forEach(function(cl){
      var raw=[];
      for(var p=0;p<phases;p++){
        var cv=document.createElement('canvas'); cv.width=112; cv.height=112;
        try{ drawChar(cv, dir, cl, p/phases); }catch(e){}
        raw.push(cv);
      }
      var b=cutBounds(raw);                 /* ONE box for the whole clip */
      out[cl]=raw.map(function(cv){ return cutCrop(cv,b); });
    });
  } finally {
    window.G_WORN=keepW; G.bodyVar=keepD; G.age=keepA;
    try{ rebuildFromRig(); }catch(e){}
    try{ HD_CACHE.map.clear(); }catch(e){}
  }
  return out;
}

/* speaker -> the draft name the CHARACTER lane gave them. A caption that says
   "sibling_lost" is a debug readout, not a scene. */
function cutSpeakerName(role){
  var map={mother:'MOTHER',father:'FATHER',sibling_older:'BROTHER',sibling_lost:'SISTER'};
  var k=map[role];
  if(k && window.FAMILY_CAST) for(var i=0;i<FAMILY_CAST.length;i++) if(FAMILY_CAST[i].role===k) return FAMILY_CAST[i].name;
  return (role||'').toUpperCase().replace(/_/g,' ');
}

/* HIS SQUIGGLE VOICES, ON THE COLD OPEN. The engine is engine/bohemia_voice.js
   and the six voices he approved on 8/11 are in
   records/BOHEMIA_VOICE_VERDICT_8_11_26.txt. Routed through the alpha's own
   bus() so the effects slider still owns the level -- routing voices anywhere
   else is the drift the one-bus rule exists to stop. A speaker keeps the SAME
   voice every time because speakerVoice() hashes the role, which is the whole
   point of the feature: you learn to recognise people. */
function cutVoice(role, text, windowMs){
  try{
    if(typeof BOH_VOICE==='undefined' || !text) return;
    /* THE SAME BUS THE VOICE JUDGE USES, RESOLVED THE SAME WAY. The first cut
       called the alpha's bus() helper -- which is declared INSIDE another
       closure and is NOT on window, so `typeof bus` was 'undefined', cutVoice
       returned on line two, and the cutscene played silent AGAIN with a working
       engine three hundred lines away. A gate claim now counts the calls, which
       is the only reason this was caught rather than shipped twice.
       Never MUS.MAST: that is the MUSIC master and MUS.stop() ducks it to zero. */
    if(typeof MUS==='undefined') return;
    MUS.audio(); if(!MUS.AC) return;
    var d = window.__SFXBUS || MUS.OUT || MUS.MAST || MUS.AC.destination;
    if(!d) return;
    var pool = (window.__VOICES_APPROVED && window.__VOICES_APPROVED.length)
      ? window.__VOICES_APPROVED : null;
    var v = BOH_VOICE.speakerVoice('coldopen:'+role, pool);
    /* HOW LONG THE VOICE PLAYS vs HOW LONG THE TEXT IS UP -- his 8/12 note. The
       babble emits one letter per 1/rate seconds, so a 51-letter line at rate
       10.7 runs 4.8s; under a one-second caption it talked straight over the
       next beat. The caption's length is set by READING SPEED and the spoken
       line is trimmed on whole words to fit inside it. */
    var say = (windowMs && BOH_STAGE) ? BOH_STAGE.voiceFit(text, windowMs, v.rate)
                                      : BOH_VOICE.opener(text);
    if(say) BOH_VOICE.say(say, v, MUS.AC, d, null);
  }catch(e){}
}

var CUTSCENE=null, CUT_READY=false;
function cutBoot(done){
  if(CUT_READY){ if(done)done(); return; }
  var cv=document.getElementById('cutCv'); if(!cv) return;
  var st=document.getElementById('cutState');
  if(st) st.textContent='building the family...';
  CUTSCENE=new BohemiaStorySurface.Story({
    canvas:cv, set:BohemiaColdOpenSet, scene:BOHEMIA_COLD_OPEN, runtime:BohemiaScene,
    stage:BOH_STAGE, floorplan:BOH_FLOORPLAN,
    paintBody:cutPaintBody,
    speak:cutVoice,
    onBeat:function(r,s){ cutCaption(s); },
    onEnd:function(s){ cutCaption(s, true); }
  });
  CUTSCENE.loadTiles(function(){
    CUTSCENE.bake(function(){
      CUT_READY=true;
      CUTSCENE.draw();
      if(st) st.textContent='ready';
      if(done)done();
    });
  });
}
function cutCaption(s, ended){
  var cap=document.getElementById('cutCap'), st=document.getElementById('cutState');
  if(!cap) return;
  if(ended || s.ended){
    var h=s.handoff;
    cap.innerHTML='<b style="color:#d8b45a">THE OPEN ENDS HERE.</b><br>'+
      (h? 'Hands off to the tutorial fight ('+h.encounter+').' : 'Scene complete.')+
      ' <span style="color:#8d8168">The family-defense fight is COMBAT\'s, and who is saved is Paolo\'s ruling, not drawn here.</span>';
    if(st) st.textContent='done';
    /* if COMBAT has landed its half on this build, take the handoff for real */
    if(s.handoff && s.handoff.call && typeof window[s.handoff.call]==='function'){
      try{ window[s.handoff.call](function(){}); }catch(e){}
    }
    return;
  }
  if(st) st.textContent='beat '+s.beatNo;
  var L=s.line;
  if(!L || !L.text){ cap.innerHTML='<span style="color:#6f6552">'+
      (s.era==='pre_collapse'?'before':'ten years later')+'</span>'; return; }
  cap.innerHTML='<span style="color:#9a8a5e;font-size:11px;letter-spacing:1px">'+
    cutSpeakerName(L.speaker)+(L.draft?' <span style="color:#6f6552">&middot; draft, edit in WORDS</span>':'')+
    '</span><br>'+L.text.replace(/&/g,'&amp;').replace(/</g,'&lt;');
}
(function(){
  var t=document.getElementById('tabs'); if(!t) return;
  var tab=t.querySelector('.tab[data-p=cutscene]');
  if(tab) tab.addEventListener('click', function(){ cutBoot(); });
  var p=document.getElementById('cutPlay');
  if(p) p.addEventListener('click', function(){ cutBoot(function(){ CUTSCENE.start(); }); });
  var a=document.getElementById('cutAgain');
  if(a) a.addEventListener('click', function(){ cutBoot(function(){ CUTSCENE.start(); }); });
})();
'''


def main():
    alpha = read('slices/BOHEMIA_ALPHA_0_9.html')

    scene_rt = read('engine/bohemia_scene.js')
    set_js = read('engine/bohemia_coldopen_set.js')
    stage_js = read('engine/bohemia_stage.js')
    floor_js = read('engine/bohemia_floorplan.js')
    surface = read('engine/bohemia_story_surface.js')
    canon = read('records/BOHEMIA_SCENE_ACT1_COLD_OPEN.json')
    json.loads(canon)                                   # it must be legal before it ships

    block = (BEGIN + '\n<script>\n'
             '/* INLINED VERBATIM from engine/bohemia_scene.js -- gates/coldopen_gate.js\n'
             '   fails if this copy drifts one byte from the canonical module. */\n'
             + scene_rt +
             '\n/* INLINED VERBATIM from engine/bohemia_coldopen_set.js */\n'
             + set_js +
             '\n/* INLINED VERBATIM from engine/bohemia_floorplan.js -- the SAME room\n'
             '   generator the walked world uses. This is what makes the cutscene stand\n'
             '   in the actual house rather than in a hand-typed rectangle. */\n'
             + floor_js +
             '\n/* INLINED VERBATIM from engine/bohemia_stage.js -- the plumbing: reading\n'
             '   speed, room, furniture, occupancy, camera. */\n'
             + stage_js +
             '\n/* INLINED VERBATIM from engine/bohemia_story_surface.js */\n'
             + surface +
             '\n/* THE AUTHORED SCENE, verbatim from records/BOHEMIA_SCENE_ACT1_COLD_OPEN.json.\n'
             '   It lives in records/ because it is Paolo canon, not engine code. */\n'
             'var BOHEMIA_COLD_OPEN = ' + canon.strip() + ';\n'
             + GLUE +
             '\n</script>\n' + END)

    # 1) THE SCRIPT BLOCK -- replaced whole, never appended
    if BEGIN in alpha and END in alpha:
        alpha = re.sub(re.escape(BEGIN) + r'[\s\S]*?' + re.escape(END), lambda m: block, alpha, count=1)
        where = 'replaced'
    else:
        anchor = '<script>(function(){var t=document.getElementById("tabs");if(!t)return;'
        i = alpha.index(anchor)
        alpha = alpha[:i] + block + '\n' + alpha[i:]
        where = 'inserted'

    # 2) THE TAB
    if 'data-p="cutscene"' not in alpha:
        alpha = alpha.replace('<div class="tab" data-p="words">WORDS</div>',
                              '<div class="tab" data-p="words">WORDS</div>'
                              '<div class="tab" data-p="cutscene">CUTSCENE</div>', 1)

    # 3) THE PANEL -- also replaced whole
    if PANEL_BEGIN in alpha and PANEL_END in alpha:
        alpha = re.sub(re.escape(PANEL_BEGIN) + r'[\s\S]*?' + re.escape(PANEL_END),
                       lambda m: PANEL, alpha, count=1)
    else:
        anchor = '<div class="panel" id="p-words">'
        j = alpha.index(anchor)
        k = alpha.index('</div>', alpha.index('</iframe>', j)) + len('</div>')
        alpha = alpha[:k] + '\n    ' + PANEL + alpha[k:]

    with open(ALPHA, 'w', encoding='utf-8') as f:
        f.write(alpha)

    print('CUTSCENE TAB: script block %s (%.0f KB)' % (where, len(block) / 1024.0))
    print('  tab      : %d' % alpha.count('data-p="cutscene"'))
    print('  panel    : %d' % alpha.count('id="p-cutscene"'))
    print('  runtime  : %d' % alpha.count('root.BohemiaScene = API'))
    print('  stage    : %d' % alpha.count('root.BOH_STAGE = API'))
    print('  floorplan: %d' % alpha.count('const BOH_FLOORPLAN='))
    print('  set      : %d' % alpha.count('root.BohemiaColdOpenSet = API'))
    print('  surface  : %d' % alpha.count('root.BohemiaStorySurface = API'))
    print('  canon    : %d' % alpha.count('var BOHEMIA_COLD_OPEN ='))
    print('  alpha    : %.1f MB' % (len(alpha) / 1048576.0))


if __name__ == '__main__':
    main()
