#!/usr/bin/env python3
"""
BOHEMIA BANK LAW INDEX (7/28/26) - Paolo's rulings are not only in /laws. They
are buried in the BANKS, in fields nothing reads.

THIS TOOL EXISTS BECAUSE THE SAME FAILURE HAPPENED THREE TIMES IN ONE DAY.

  1. banks/BOHEMIA_PERIMETER_WALL_POOL_7_14_26.txt has said "wall height min 2
     tiles" in its own `law` field since 7/14. The wall was drawn flat on the
     ground for ten days.
  2. banks/BOHEMIA_REAL_VEGAS_VERDICTS_R2_7_14_26.txt has a `paolo_laws` block
     that says "per-cell wall shuffle BANNED". The game picked the wall tile with
     a per-cell hash.
  3. The same file's cap meant nine of his thirteen approved border walls had
     never been drawn at all.

Every one of those was a written Paolo ruling, in the repo, with no machine
reading it. laws/ is indexed by BOHEMIA_CANON_INDEX; the banks were not indexed
by anything, and a `law` field inside a 2MB JSON blob is invisible to a human and
to every gate.

WHAT THIS DOES: sweeps banks/ (and records/), pulls every `law`, `paolo_law(s)`,
`ruling`, `paolo_direction` and `status` field out of every JSON block at any
depth, and writes records/BOHEMIA_BANK_LAW_INDEX.md - one readable page of every
ruling that lives in a bank, with the file it came from. gates/banklaw_gate.py
then requires the index to be CURRENT and requires every ruling to be marked
either ENFORCED BY a named gate or UNENFORCED on purpose, so a new bank cannot
quietly add a rule nobody checks.

  python3 tools/bohemia_bank_law_index.py
"""
import glob
import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) or '.'
os.chdir(REPO)
OUT = 'records/BOHEMIA_BANK_LAW_INDEX.md'
FIELDS = ('law', 'paolo_law', 'paolo_laws', 'ruling', 'paolo_direction', 'status')
NOISE = re.compile(r'^(NS|EW|N|S|E|W|up|down|ok)$', re.I)


def blocks(text):
    """every top-level JSON object in a file that may hold several."""
    dec = json.JSONDecoder()
    i = 0
    while i < len(text):
        j = text.find('{', i)
        if j < 0:
            return
        try:
            obj, end = dec.raw_decode(text, j)
        except Exception:
            i = j + 1
            continue
        i = end
        yield obj


def harvest(obj, out, depth=0):
    if depth > 6:
        return
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k in FIELDS and isinstance(v, str) and not NOISE.match(v.strip()):
                out.append((k, v.strip()))
            elif k in FIELDS and isinstance(v, dict):
                for k2, v2 in v.items():
                    if isinstance(v2, str):
                        out.append((k + '.' + k2, v2.strip()))
            else:
                harvest(v, out, depth + 1)
    elif isinstance(obj, list):
        for x in obj[:120]:
            harvest(x, out, depth + 1)


rows = []
for path in sorted(glob.glob('banks/*.txt') + glob.glob('banks/*.json') +
                   glob.glob('records/*.txt') + glob.glob('records/*.json')):
    try:
        text = open(path, encoding='utf8', errors='replace').read()
    except Exception:
        continue
    found = []
    for obj in blocks(text):
        harvest(obj, found)
    seen = set()
    for field, value in found:
        k = (field, value)
        if k in seen:
            continue
        seen.add(k)
        rows.append((path, field, value))

body = ["# BOHEMIA — BANK LAW INDEX",
        "",
        "Every ruling that lives inside a BANK or a RECORD rather than in `/laws`.",
        "",
        "Generated by `python3 tools/bohemia_bank_law_index.py`. Regenerate it the same",
        "turn any bank lands, exactly like BOHEMIA_CANON_INDEX for the laws directory.",
        "",
        "WHY THIS FILE EXISTS: on 7/28 the same failure surfaced three times in one day —",
        "a Paolo ruling sitting in a bank's own `law` field, in the repo, obeyed by",
        "nothing. The perimeter wall bank had said \"wall height min 2 tiles\" since 7/14",
        "and the wall was drawn flat. A `paolo_laws` block said \"per-cell wall shuffle",
        "BANNED\" and the game shuffled per cell. A rule inside a 2MB JSON blob is",
        "invisible to a human and to every gate, so it may as well not exist.",
        "",
        "BEFORE TOUCHING ANY ART PATH, READ THIS PAGE.",
        "",
        "`ENFORCED BY` is filled in by hand and checked by `gates/banklaw_gate.py`: every",
        "row is either enforced by a named gate or explicitly marked UNENFORCED, so a new",
        "bank cannot quietly add a rule nobody checks.",
        "",
        "| # | source | field | ruling |",
        "|---|--------|-------|--------|"]
for n, (path, field, value) in enumerate(rows, 1):
    v = value.replace('|', '\\|').replace('\n', ' ')
    if len(v) > 420:
        v = v[:417] + '...'
    body.append('| %d | `%s` | `%s` | %s |' % (n, path, field, v))
body += ["", "TOTAL: %d rulings across %d files." %
         (len(rows), len(set(r[0] for r in rows))), ""]

os.makedirs('records', exist_ok=True)
open(OUT, 'w', encoding='utf8').write('\n'.join(body) + '\n')
print('wrote %s — %d rulings from %d files' % (OUT, len(rows), len(set(r[0] for r in rows))))
