#!/usr/bin/env node
/* ============================================================================
   BOHEMIA -- MODS: THE DRAFT RANGE COLUMN (MODS lane, 10/10/26)
   Row [range column], rule 22. The reference merge checks a value's TYPE, never
   its SIZE, so a knife that hits for minus 5 loads. This computes, from the
   values the data files ALREADY hold, a draft min and max for every numeric
   field of every table, and lists the limits the wiki itself states (rules.json).
   DRAFT: TUNING can overwrite any row. A value outside the range is a WARNING,
   never a block. Nothing here is loaded by the game.
   Usage: node tools/bohemia_mods_ranges_draft.js [--write]
     --write  writes banks/BOHEMIA_MODS_RANGES_DRAFT_10_10_26.json (draft:true)
   ============================================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const BB = path.join(__dirname, '..', 'records', 'target', 'bb');
const OUT = path.join(__dirname, '..', 'banks', 'BOHEMIA_MODS_RANGES_DRAFT_10_10_26.json');
const isRow = x => x && typeof x === 'object' && !Array.isArray(x);

function tablesOf(j) {
  const t = {};
  for (const [k, v] of Object.entries(j)) {
    if (k.startsWith('_')) continue;
    if (Array.isArray(v) && v.length && v.every(isRow)) t[k] = v;
    else if (isRow(v) && Object.keys(v).length > 8 && Object.values(v).every(isRow)) t[k] = Object.values(v);
  }
  return t;
}
function rangesOf(rows) {
  const f = {};
  for (const r of rows) for (const [k, v] of Object.entries(r)) {
    if (typeof v !== 'number' || !isFinite(v)) continue;
    const e = f[k] || (f[k] = { min: Infinity, max: -Infinity, n: 0, integer: true });
    e.min = Math.min(e.min, v); e.max = Math.max(e.max, v); e.n++;
    if (!Number.isInteger(v)) e.integer = false;
  }
  return f;
}
const ranges = {};
let fields = 0, tables = 0, neverNeg = 0, constant = 0, thin = 0;
for (const file of fs.readdirSync(BB).filter(f => f.endsWith('.json')).sort()) {
  const j = JSON.parse(fs.readFileSync(path.join(BB, file), 'utf8'));
  const T = file === 'rules.json' ? {} : tablesOf(j);   /* rules.json is a values file: its limits are listed as STATED below, not guessed */
  for (const [name, rows] of Object.entries(T)) {
    const R = rangesOf(rows);
    const out = {};
    for (const [k, e] of Object.entries(R)) {
      out[k] = { min: e.min, max: e.max, rows_with_a_value: e.n, of_rows: rows.length, whole_numbers: e.integer, never_negative_in_the_base: e.min >= 0 };
      fields++; if (e.min >= 0) neverNeg++; if (e.min === e.max) constant++; if (e.n < 5) thin++;
    }
    if (Object.keys(out).length) { (ranges[file] = ranges[file] || {})[name] = out; tables++; }
  }
}
/* the limits the wiki itself states, read from rules.json (each carries its own quote) */
const rules = JSON.parse(fs.readFileSync(path.join(BB, 'rules.json'), 'utf8'));
const stated = [];
(function walk(o, p) {
  if (isRow(o)) for (const [k, v] of Object.entries(o)) {
    if (/(^|_)(min|max|floor|cap|clamp)(_|$)/.test(k) && isRow(v) && ('value' in v || 'min' in v || 'max' in v)) stated.push({ at: 'rules.json ' + (p + '.' + k).replace(/^\./, ''), limit: 'value' in v ? v.value : { min: v.min, max: v.max }, quote: String(v.quote || '').slice(0, 100) });
    walk(v, p + '.' + k);
  } else if (Array.isArray(o)) o.slice(0, 60).forEach((x, i) => walk(x, p + '[' + i + ']'));
})(rules, '');
const doc = { _readme: ['DRAFT. NOT IN THE GAME. MODS [range column] 10/10.', 'Each numeric field of each table: the smallest and largest value any base row holds. A mod value outside it is a WARNING, never a block.', 'TUNING owns every row and can overwrite it. Generated by tools/bohemia_mods_ranges_draft.js from records/target/bb; re-run it after any data change.'], draft: true, stated_by_the_wiki: stated, ranges };
const summary = { files: Object.keys(ranges).length, tables, fields, neverNegative: neverNeg, constantFields: constant, thinFields: thin, statedLimits: stated.length };
module.exports = { doc, summary, ranges };
if (require.main === module) {
  console.log(JSON.stringify(summary));
  console.log('weapons.rows.damage_min', JSON.stringify(ranges['weapons.json'].rows.damage_min));
  stated.forEach(s => console.log('  stated: ' + s.at + ' = ' + JSON.stringify(s.limit)));
  if (process.argv.includes('--write')) { fs.writeFileSync(OUT, JSON.stringify(doc, null, 1) + '\n'); console.log('wrote ' + path.relative(path.join(__dirname, '..'), OUT)); }
}
