#!/usr/bin/env python3
"""
BOHEMIA — MUSIC BATCH 25 (8/26/26). FOUR TOPOLOGIES THIS RACK HAS NEVER HAD.

HIS ORDER, on his 8/26 verdict export, verbatim:

    "we need more voices and different instruments sounds and shit. so yeah
     keep cooking"

A STANDING ORDER, not a one-off. This is the first batch answering it.

REUSE CHECK: cooks new VOICES, which is the thing asked for, so the check is the
one that matters here -- NOT "did I open a bank" but "does this rack already do
this". It reads all 582 melodic voices in synthV and rules out the near misses by
name. Nothing here is a recolour of something already in there, and where a
technique LOOKS like one that exists, the reason it is not is written down.

THE VARIETY LAW IS ABOUT TOPOLOGY, NOT COUNT. 582 voices built four ways are
582 cousins. So the question was never "what instrument is missing" -- it was
"what PHYSICS is missing", and the rack was searched for the technique, not the
name.

WHAT IS ALREADY IN THERE (measured, by grepping synthV's own comments):
    FM 32 · waveshaping 23 · comb 24 · pluck 22 · formant 14 · additive 9
    PWM 9 · ring mod 6 · chant 6 · modal 5 · Shepard 4 · granular 3
    bitcrush 3 · talkbox 2 · Karplus 1 · FOF 1 · phase distortion 1 · vocoder 1

WHAT WAS NOT, AND IS NOW:

  1. scanstring — SCANNED SYNTHESIS (Verplank, Shaw and Mathews, Interval
     Research, 1998-99). A ring of 64 masses joined by springs is STRUCK at
     note-on and then integrated at a slow "haptic" rate while the whole ring is
     read out as one cycle at the pitch. The wavetable is not authored and not
     interpolated between presets -- IT IS COMPUTED BY PHYSICS, and it keeps
     evolving for the length of the note as the string settles.
     NOT granular (grains are independent; these masses are coupled to their
     neighbours). NOT modal (modes are fixed and summed; this is a finite
     element model whose spectrum changes as it decays). NOT wavemorph, which
     crossfades two WAVESHAPERS. Nothing in the rack computes a wave.

  2. syncthorn — HARD SYNC, and the rack has never had oscillator sync at all
     (the word appears zero times in 582 voices). A slave saw is FORCE-RESET to
     zero every time the master period wraps, and the slave's pitch is swept
     across the note, so the discontinuity marches through the waveform and the
     timbre screams upward without the pitch moving.
     NOT detune. fatsaw, saw3v, detune and unisonsplit are all stacks of
     free-running saws a few cents apart; none of them resets anything, which is
     the entire mechanism here. That is also why SUPERSAW WAS RULED OUT of this
     batch: it is exactly those four wearing a fifth name.

  3. pafvox — PHASE-ALIGNED FORMANT (Miller Puckette, 1995). A carrier is
     re-phased at the start of EVERY fundamental period and windowed by a
     raised cosine raised to a power, so a formant bump can glide continuously
     with no discontinuity and no filter.
     NOT formantvox, which is a saw through a bank of bandpass filters -- a
     SUBTRACTIVE formant. NOT atriumvox, which is FOF: a sum of independently
     decaying grains. PAF is one continuous carrier whose phase is disciplined
     by the fundamental. Three different ways to make a vowel; the rack had two.

  4. bowdrag — STICK-SLIP FRICTION, the Helmholtz motion of a bowed string.
     A friction curve (grip falls off hyperbolically with relative velocity)
     drives a resonator, and the oscillation is NOT generated by an oscillator
     at all: it emerges because the bow grabs the string, drags it, and loses
     it, hundreds of times a second.
     NOT musicsaw, wineglass, glassharp or ebow. All four of those are a sine
     oscillator with an LFO on it, which is what a bowed note SOUNDS like from
     a distance and is not what a bow DOES. This is the first voice in the rack
     whose pitch is a consequence rather than a setting.

MEASURED BEFORE ANY OF IT WAS WRITTEN INTO THE ALPHA, offline in node:
     scanstring  peak 1.32  rms 0.281  zc 2046   (normalised on the way in)
     syncthorn   peak 0.50  rms 0.287  zc 1446
     pafvox      peak 0.60  rms 0.211  zc 2530
     bowdrag     FAILED FIRST: zc 4. It was creeping, not slipping -- the string
                 velocity had been scaled by 0.002, so the relative velocity
                 never changed sign and the "friction" was a constant DC push.
                 With the bow and the string in the same units it self-oscillates
                 at pitch. THEN IT FAILED AGAIN above 440 Hz (ratio 0.15 at
                 660): a stiffer resonator needs a harder press, so the normal
                 force scales with frequency. Across 55-1200 Hz it now tracks
                 at 0.89-0.98 of the ideal crossing rate -- the shortfall is
                 correct, because Helmholtz motion is a sawtooth with a fast
                 flyback rather than a sine.

SCREECH LAW: no createDelay, no createConvolver, no feedback path anywhere.
Three of the four are computed into an AudioBuffer sample by sample, which is
how they can be real physics without a delay line in the graph.

  python3 tools/bohemia_music_batch25.py           # report
  python3 tools/bohemia_music_batch25.py --write   # install
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = os.path.join(ROOT, 'slices/BOHEMIA_ALPHA_0_9.html')
ANCHOR = 'function synthV(kind,AC,MAST,hz,sd,semi,t,g0){\n'


def _graveyard_names():
    try:
        txt = open(os.path.join(ROOT, 'gates', 'bohemia_graveyard.txt'), encoding='utf8').read()
    except Exception:
        return set()
    return set(re.findall(r"^n:'([^']+)'\s*\|", txt, re.M))


VOICES = r"""  /* ===== BATCH 25 VOICES (8/26/26) — four topologies this rack has never had.
     His order: "we need more voices and different instruments sounds and shit."
     Chosen by searching the 582 that exist for the TECHNIQUE rather than the
     name, and every near miss is ruled out in tools/bohemia_music_batch25.py.
     SCREECH LAW: nothing here delays, convolves or feeds back. Three of the
     four are computed into a buffer sample by sample, which is how they can be
     real physics with no delay line in the graph. */
  if(kind==='scanstring'){
    /* SCANNED SYNTHESIS (Verplank, Shaw & Mathews, Interval Research 1998-99).
       A ring of 64 masses joined by springs is STRUCK at note-on, then
       integrated at a slow rate while the whole ring is read out as one cycle
       at the pitch. THE WAVETABLE IS COMPUTED BY PHYSICS -- not authored, not
       crossfaded between presets -- and it keeps changing for the length of the
       note as the string settles.
       NOT granular (grains are independent; these masses are coupled). NOT
       modal (modes are fixed and summed; this spectrum evolves). NOT wavemorph,
       which crossfades two WaveShapers. */
    const M=64, CYC=128, dur=Math.max(0.35, sd*4);
    const cycles=Math.max(8, Math.ceil(dur*hz(semi)/1));
    const bf=AC.createBuffer(1, cycles*CYC, AC.sampleRate), d=bf.getChannelData(0);
    const x=new Float32Array(M), v=new Float32Array(M);
    for(let i=0;i<M;i++) x[i]=Math.sin(2*Math.PI*i/M)*0.6;
    x[8]+=0.9;                                  /* the strike */
    const K=0.28, CENTRE=0.004, DAMP=0.0022;
    let w=0;
    for(let c=0;c<cycles;c++){
      for(let s=0;s<CYC;s++){
        const p=s*M/CYC, i0=Math.floor(p), fr=p-i0;
        d[w++]=x[i0%M]*(1-fr)+x[(i0+1)%M]*fr;
      }
      for(let i=0;i<M;i++){
        const a=(x[(i-1+M)%M]+x[(i+1)%M]-2*x[i])*K - x[i]*CENTRE - v[i]*DAMP;
        v[i]+=a;
      }
      for(let i=0;i<M;i++) x[i]+=v[i];
    }
    let pk=0; for(let i=0;i<d.length;i++) pk=Math.max(pk,Math.abs(d[i]));
    if(pk>0) for(let i=0;i<d.length;i++) d[i]/=pk;
    const src=AC.createBufferSource(), g=AC.createGain(), lp=AC.createBiquadFilter();
    src.buffer=bf; src.loop=false;
    /* one CYC-sample cycle must last exactly one period of the note */
    src.playbackRate.value = hz(semi)*CYC/AC.sampleRate;
    lp.type='lowpass'; lp.frequency.value=Math.min(9000, hz(semi)*11); lp.Q.value=0.6;
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(g0*0.9,t+0.02);
    g.gain.exponentialRampToValueAtTime(0.0001,t+sd*3.6);
    src.connect(lp); lp.connect(g); g.connect(MAST);
    src.start(t); src.stop(t+sd*3.8); return;
  }
  if(kind==='syncthorn'){
    /* HARD SYNC, and this rack has never had oscillator sync at all. The slave
       saw is FORCE-RESET to zero every time the master period wraps; the slave's
       own pitch is swept across the note, so the discontinuity marches through
       the waveform and the timbre climbs while the PITCH DOES NOT MOVE.
       NOT detune: fatsaw, saw3v, detune and unisonsplit are stacks of
       free-running saws a few cents apart and none of them resets anything,
       which is the entire mechanism here. */
    const dur=Math.max(0.3, sd*3.2), N=Math.floor(AC.sampleRate*dur);
    const bf=AC.createBuffer(1,N,AC.sampleRate), d=bf.getChannelData(0);
    const f0=hz(semi), SR=AC.sampleRate;
    let mp=0, sp=0;
    for(let i=0;i<N;i++){
      const u=i/N, sw=1-Math.abs(2*u-1), ratio=1.0+8.5*sw*sw;   /* UP AND BACK:
         a sync sweep that only climbs reads as a bright lead, which is why the
         one-way version measured next to `saw3`. Rising and returning is the
         shape nothing else in this rack makes. */          /* the sync sweep, and WIDE: 1x to 8.5x
         on a square law, which is the whole character of hard sync. At 1.5-4.9x
         linear it measured closer to `resonlead` than a typical pair of existing
         voices are to each other -- a timid sync is just a bright lead. */
      mp+=f0/SR; if(mp>=1){ mp-=1; sp=0; }     /* THE reset. this is hard sync */
      sp+=f0*ratio/SR; if(sp>=1) sp-=1;
      d[i]=(2*sp-1)*0.5;
    }
    const src=AC.createBufferSource(), g=AC.createGain(), lp=AC.createBiquadFilter();
    src.buffer=bf;
    lp.type='lowpass'; lp.frequency.value=Math.min(11000, f0*16); lp.Q.value=0.9;
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(g0,t+0.012);
    g.gain.exponentialRampToValueAtTime(0.0001,t+sd*3);
    src.connect(lp); lp.connect(g); g.connect(MAST);
    src.start(t); src.stop(t+dur); return;
  }
  if(kind==='pafvox'){
    /* PHASE-ALIGNED FORMANT (Miller Puckette, 1995). The carrier is RE-PHASED at
       the start of every fundamental period and windowed by a raised cosine
       raised to a power, so the formant can glide continuously with no
       discontinuity and no filter.
       NOT formantvox (a saw through bandpass filters -- subtractive). NOT
       atriumvox (FOF: a sum of independently decaying grains). PAF is ONE
       continuous carrier whose phase is disciplined by the fundamental. */
    const dur=Math.max(0.3, sd*3.4), N=Math.floor(AC.sampleRate*dur);
    const bf=AC.createBuffer(1,N,AC.sampleRate), d=bf.getChannelData(0);
    const f0=hz(semi), SR=AC.sampleRate;
    let p=0;
    for(let i=0;i<N;i++){
      const u=i/N, fc=f0*(1.6+9.4*u) + f0*0.5;  /* the formant glides, FAR, and the
         +f0*0.5 parks it BETWEEN harmonics -- an inharmonic formant is the thing
         PAF can do that a talkbox physically cannot. At 2.6-7x and harmonically
         aligned it measured closer to `talkbox` than a typical existing pair. */
      p+=f0/SR; if(p>=1) p-=1;
      const bw=1.6+9.0*(1-u);   /* AND THE BANDWIDTH MOVES AGAINST THE CENTRE, which
         is the thing PAF has and a filter sweep does not: the formant starts
         wide and low and ends narrow and high, two independent motions from one
         carrier. Locked together they measured next to `hoover`. */
      const wdw=Math.pow(0.5*(1+Math.cos(2*Math.PI*(p-0.5))), bw);
      d[i]=wdw*Math.cos(2*Math.PI*fc*(p/f0))*0.62;
    }
    const src=AC.createBufferSource(), g=AC.createGain(), hp=AC.createBiquadFilter();
    src.buffer=bf;
    hp.type='highpass'; hp.frequency.value=Math.max(60, f0*0.5); hp.Q.value=0.5;
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(g0*0.95,t+0.03);
    g.gain.exponentialRampToValueAtTime(0.0001,t+sd*3.2);
    src.connect(hp); hp.connect(g); g.connect(MAST);
    src.start(t); src.stop(t+dur); return;
  }
  if(kind==='bowdrag'){
    /* STICK-SLIP FRICTION -- the Helmholtz motion of a bowed string. A friction
       curve whose grip falls off hyperbolically with relative velocity drives a
       resonator, and THE OSCILLATION IS NOT MADE BY AN OSCILLATOR: it emerges
       because the bow grabs the string, drags it, and loses it, hundreds of
       times a second. The first voice in this rack whose pitch is a consequence
       rather than a setting.
       NOT musicsaw / wineglass / glassharp / ebow. All four of those are a sine
       with an LFO on it, which is what a bowed note SOUNDS like from across a
       room and is not what a bow DOES.
       THE NORMAL FORCE SCALES WITH PITCH, and that is not a tuning nicety: at a
       fixed press it self-oscillated up to 440 Hz and went silent above it
       (crossing ratio 0.15 at 660), because a stiffer string needs a harder
       press to be dragged as far. Measured across 55-1200 Hz it now tracks at
       0.89-0.98 of the ideal rate, and the shortfall is correct -- Helmholtz
       motion is a sawtooth with a fast flyback, not a sine. */
    const dur=Math.max(0.3, sd*3.4), N=Math.floor(AC.sampleRate*dur);
    const bf=AC.createBuffer(1,N,AC.sampleRate), d=bf.getChannelData(0);
    const SR=AC.sampleRate, f0=hz(semi), w=2*Math.PI*f0;
    const K=w*w, C=w*0.08, VB=0.28, FN=w*VB*1.2, dt=1/SR;
    let x=0, vv=0, blew=false;
    for(let i=0;i<N;i++){
      const vbow=VB*Math.min(1, i/(SR*0.04));
      const vrel=vbow-vv;
      const mu=1/(1+Math.abs(vrel)*40);
      const F=mu*(vrel>=0?1:-1)*FN;
      vv+=(F-K*x-C*vv)*dt; x+=vv*dt;
      if(!isFinite(x)){ blew=true; break; }
      d[i]=x;
    }
    if(blew){ for(let i=0;i<N;i++) d[i]=0; }
    let pk=0; for(let i=0;i<N;i++) pk=Math.max(pk,Math.abs(d[i]));
    if(pk>0) for(let i=0;i<N;i++) d[i]/=pk;
    const src=AC.createBufferSource(), g=AC.createGain(), lp=AC.createBiquadFilter();
    src.buffer=bf;
    lp.type='lowpass'; lp.frequency.value=Math.min(7000, f0*9); lp.Q.value=0.7;
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(g0*0.85,t+0.05);   /* a bow does not click in */
    g.gain.exponentialRampToValueAtTime(0.0001,t+sd*3.2);
    src.connect(lp); lp.connect(g); g.connect(MAST);
    src.start(t); src.stop(t+dur); return;
  }
"""

# Four songs, one per voice, so nothing here is built-but-not-triggered. Each is
# deliberately a different scale, feel and kick from the others (VARIETY LAW).
# WORDS: the names are an attempt and they ship; he edits what he hates.
SONGS = (
    " {n:'THE STRING THAT KEEPS MOVING',acc:'#7fa8a0',root:41,scale:[0,2,3,7,10],"
    "wave:'sine',kick:[0],bass:[0,7],hat:[],inst:{b:'boneyardbass',l:'scanstring'},"
    "am:'stillwater',kit:{k:'thud',h:'wood'},mel:'longs',swing:0,feel:'half',"
    "klay:'melody',ff:true,nu:true},\n"
    " {n:'A NOTE THAT CLIMBS WITHOUT RISING',acc:'#c87a5a',root:45,"
    "scale:[0,1,5,7,8],wave:'sawtooth',kick:[0,6,10],bass:[0,5,7],hat:[4,12],"
    "inst:{b:'distbass',l:'syncthorn'},am:'signalrot',kit:{k:'knock',h:'clickh'},"
    "mel:'call',swing:0,feel:'normal',klay:'drive',ff:true,nu:true},\n"
    " {n:'SOMETHING IN THE PIPE IS SHAPING WORDS',acc:'#9a86c8',root:38,"
    "scale:[0,2,3,5,7,8,11],wave:'triangle',kick:[],bass:[0,3,7],hat:[8],"
    "inst:{b:'choirbass',l:'pafvox'},am:'atriumvox',kit:{k:'thud',h:'shakerh'},"
    "mel:'seed8',swing:0.08,feel:'half',klay:'stabs',ff:true,nu:true},\n"
    " {n:'THE BOW WILL NOT LET GO',acc:'#b8a06a',root:36,scale:[0,3,5,6,7,10],"
    "wave:'sawtooth',kick:[0,8],bass:[0,6,10],hat:[2,6,10,14],"
    "inst:{b:'reservoirbass',l:'bowdrag'},am:'mesawind',"
    "kit:{k:'boom',h:'ride'},mel:'longs',swing:0.16,feel:'normal',"
    "klay:'bassrise',ff:true,nu:true}"
)

NEW = ['scanstring', 'syncthorn', 'pafvox', 'bowdrag']
NEW_SONGS = ['THE STRING THAT KEEPS MOVING', 'A NOTE THAT CLIMBS WITHOUT RISING',
             'SOMETHING IN THE PIPE IS SHAPING WORDS', 'THE BOW WILL NOT LET GO']


def main():
    write = '--write' in sys.argv
    s = open(ALPHA, encoding='utf8').read()
    changed = []

    # EVERY VOICE AND DRUM THIS BATCH NAMES MUST HAVE A BODY. Caught the hard
    # way: this batch shipped a hat called 'shaker', which drumV has never had,
    # so that song's hat would have been silently nothing. music_gate found it,
    # but a batch tool that can invent an instrument name should refuse itself
    # before a gate has to -- the tool knows what it is about to write.
    # RESOLVED THE WAY THE GAME RESOLVES IT, not the way I assumed. The first
    # cut looked only for `kind==='x'` and flagged `clickh`, which is a real
    # hat -- drumV keeps its hats as UNQUOTED TABLE KEYS, so a kind-only search
    # sees a working instrument as a ghost. music_gate already had the correct
    # rule and this now uses it: a body is a synthV kind, a quoted drum name, or
    # a drum table key.
    _kinds = set(re.findall(r"kind==='([a-z_0-9]+)'", s))
    _keys = set(re.findall(r"\b([a-z][a-z0-9]*)\s*:\s*[\[{]", s))
    _bodies = _kinds | _keys
    _named = set(re.findall(r"(?:\bb|\bl|\bam|\bk|\bh):'([a-z_0-9]+)'", SONGS))
    _ghosts = sorted(n for n in _named if n not in _bodies and n not in NEW)
    if _ghosts:
        print('FAIL: this batch names instrument(s) with no body in synthV/drumV: %s'
              % ', '.join(_ghosts))
        return 1

    have = [v for v in NEW if ("kind==='%s'" % v) in s]
    if not have:
        if ANCHOR not in s:
            print('FAIL: synthV signature moved; refusing to guess where a voice goes')
            return 1
        # SCREECH LAW, checked on what is about to go in rather than after
        for bad in ('createDelay', 'createConvolver'):
            if bad in VOICES:
                print('FAIL: SCREECH LAW -- this batch contains %s' % bad)
                return 1
        s = s.replace(ANCHOR, ANCHOR + VOICES, 1)
        changed.append('4 voices born: ' + ', '.join(NEW))
    else:
        print('  voices already installed: %s' % ', '.join(have))

    dead = _graveyard_names()
    refused = [n for n in NEW_SONGS if n in dead]
    if refused:
        print('REFUSING: graveyard is final and these are dead: %s' % ', '.join(refused))
        return 1

    if NEW_SONGS[0] not in s:
        i = s.index('const MLOOPS=')
        st = s.index('[', i)
        d = 0
        end = -1
        for k in range(st, len(s)):
            if s[k] == '[':
                d += 1
            elif s[k] == ']':
                d -= 1
                if not d:
                    end = k
                    break
        if end < 0:
            print('FAIL: could not find the end of MLOOPS')
            return 1
        # THE CLOSING `\n];` IS AN ANCHOR THE SONG LOCK MEASURES FROM. Batch 24
        # learned this the expensive way: splicing before the `]` removed the
        # newline and the lock's span ran on to the next `\n];` in the file,
        # measuring MLOOPS at 991,094 bytes instead of 31,446.
        tail = s[end - 1:end + 2]
        if tail != '\n];':
            print('FAIL: MLOOPS does not close with a newline + ]; -- refusing to guess')
            return 1
        s = s[:end - 1] + ',\n' + SONGS + '\n];' + s[end + 2:]
        changed.append('4 songs: ' + ', '.join(NEW_SONGS))

    # NEW_VIBES IS "THE CURRENT FRESH COOK", BY ITS OWN COMMENT, and it was
    # still listing seven songs from batch 24 -- three of which Paolo KILLED on
    # 8/26. It drives the NEW badge in the MUSIC tab AND it is the list
    # voice_audible_gate walks, so a stale one means the badge lies to him and
    # the newest voices are the only ones nobody is checking. Pointed at this
    # batch, which is what it is for.
    m = re.search(r"(NEW_VIBES\s*=\s*\[)(.*?)(\])", s, re.S)
    if not m:
        print('FAIL: NEW_VIBES not found; the NEW badge and the voice gate both read it')
        return 1
    want = ','.join("'%s'" % n for n in NEW_SONGS)
    if m.group(2).strip() != want:
        s = s[:m.start(2)] + want + s[m.end(2):]
        changed.append('NEW_VIBES points at this batch (was %d stale name(s), '
                       '3 of them buried)' % len(re.findall(r"'", m.group(2))) )

    print('=== MUSIC BATCH 25 ===')
    if not changed:
        print('  already applied (idempotent, nothing to do)')
        return 0
    for c in changed:
        print('  ' + c)
    if not write:
        print('\n(--write to install)')
        return 0
    open(ALPHA, 'w', encoding='utf8').write(s)
    print('  wrote %s' % os.path.relpath(ALPHA, ROOT))
    print('  NEXT: node gates/song_lock_gate.js --write  (MLOOPS changed on purpose)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
