#!/usr/bin/env python3
"""BOHEMIA STORY TAB -- put the cold open where Paolo can watch it.

WHY. engine/bohemia_scene.js has played the Act 1 cold open correctly since 8/9
and gates/scene_gate.js proves it beat by beat -- headless, in a terminal.
It appeared in ZERO slices. NAME THE TAB: a thing he cannot reach does not
exist to him. This wires the runtime, the approved set, the scene canon and the
surface into the alpha as the STORY tab.

IT REPLACES, IT NEVER APPENDS. The CHARACTER lane learned this the hard way on
8/11: "an insert tool run twice is a duplication tool -- anything editing
shipped code must REPLACE, not ADD" (they shipped two `var FAMILY_CAST` and it
measured fine because the later declaration won). So everything this writes
lives between two markers and is swapped whole on every run. Running it ten
times leaves the file identical to running it once.

WHAT IT INLINES, ALL VERBATIM (ENGINE SYNC LAW -- one canonical body per
module; a copy that can drift is a second body):
  engine/bohemia_scene.js            the beat runtime
  engine/bohemia_coldopen_set.js     12 approved tiles out of the interior pool
  engine/bohemia_story_surface.js    the room
  records/BOHEMIA_SCENE_ACT1_COLD_OPEN.json   the authored canon
gates/coldopen_gate.js re-reads all four off disk and fails if the inlined copy
has drifted by one byte.

ONE-LINK LAW: this ships INSIDE the alpha. No new URL, ever.

  python3 tools/bohemia_story_tab_patch.py
Gate: gates/coldopen_gate.js
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = os.path.join(ROOT, 'slices', 'BOHEMIA_ALPHA_0_9.html')

BEGIN = '<!-- ===== BOHEMIA STORY TAB (generated by tools/bohemia_story_tab_patch.py) ===== -->'
END = '<!-- ===== END BOHEMIA STORY TAB ===== -->'

PANEL_BEGIN = '<!-- ===== STORY PANEL (generated) ===== -->'
PANEL_END = '<!-- ===== END STORY PANEL ===== -->'

PANEL = PANEL_BEGIN + '''
    <div class="panel" id="p-story">
      <div id="storyWrap" style="max-width:420px;margin:6px auto 0;padding:0 8px">
        <canvas id="storyCv" width="360" height="470"
          style="width:100%;height:auto;display:block;background:#0a0806;border:1px solid #241c12;border-radius:4px;image-rendering:pixelated"></canvas>
        <div id="storyCap" style="min-height:66px;margin-top:7px;padding:8px 10px;border:1px solid #241c12;border-radius:4px;background:#100c07;font:13px/1.5 ui-monospace,monospace;color:#e8dfc8"></div>
        <div class="row" style="margin-top:7px;gap:6px;display:flex;align-items:center;flex-wrap:wrap">
          <button id="storyPlay" class="opt">&#9654; PLAY THE OPEN</button>
          <button id="storyAgain" class="opt">&#8635; AGAIN</button>
          <span id="storyState" class="mini" style="flex:1;text-align:right"></span>
        </div>
        <div class="mini" style="margin-top:6px;line-height:1.55">
          The first fifteen seconds of the game. One cut carries ten years.
          Every line here is a draft you can rewrite in the WORDS tab.
        </div>
      </div>
    </div>
''' + PANEL_END


def read(p):
    with open(os.path.join(ROOT, p), 'r', encoding='utf-8') as f:
        return f.read()


GLUE = r'''
/* ---- THE ALPHA SIDE OF THE STORY TAB ------------------------------------
   The surface module never touches a global. Everything it needs from this
   file arrives through ONE injected function, and that function is written
   here because this is where the rig lives.

   THE BODIES ARE THE GAME'S BODIES. Not a lookalike cast drawn for a cutscene:
   drawChar over Paolo's painted rig, wearing FAMILY_CAST's wardrobe, aged on
   the 8/11 age axis. If he changes a garment in CLOTHES, the family at the
   table changes with it.

   ONE REBUILD PER BODY, MEASURED. rebuildFromRig + cache clear costs ~19ms;
   another clip off an already-installed rig costs ~0.6ms. So every frame a
   member needs is taken while that member's rig is installed, and the player's
   body is put back afterwards -- these are GLOBALS, and leaving the child rig
   installed would silently reshape every other surface in the game. */
function storyTrim(cv){
  try{
    var g=cv.getContext('2d'), d=g.getImageData(0,0,cv.width,cv.height).data;
    var x0=cv.width,y0=cv.height,x1=-1,y1=-1;
    for(var y=0;y<cv.height;y++)for(var x=0;x<cv.width;x++){
      if(d[(y*cv.width+x)*4+3]>8){ if(x<x0)x0=x; if(x>x1)x1=x; if(y<y0)y0=y; if(y>y1)y1=y; } }
    if(x1<0) return cv;
    var t=document.createElement('canvas'); t.width=x1-x0+1; t.height=y1-y0+1;
    t.getContext('2d').drawImage(cv,x0,y0,t.width,t.height,0,0,t.width,t.height);
    return t;
  }catch(e){ return cv; }
}
function storyPaintBody(role, age, dir, clips, phases){
  var m=null;
  if(role && window.FAMILY_CAST) for(var i=0;i<FAMILY_CAST.length;i++) if(FAMILY_CAST[i].role===role) m=FAMILY_CAST[i];
  var keepW=window.G_WORN, keepD=G.bodyVar, keepA=G.age, out={};
  try{
    if(m){ window.G_WORN=m.worn; G.bodyVar=m.dials; G.age=m.age||'adult'; }
    else { G.age = age || 'adult'; }      /* the PLAYER, in the player's own fit */
    rebuildFromRig(); try{HD_CACHE.map.clear();}catch(e){}
    clips.forEach(function(cl){
      out[cl]=[];
      for(var p=0;p<phases;p++){
        var cv=document.createElement('canvas'); cv.width=112; cv.height=112;
        try{ drawChar(cv, dir, cl, p/phases); }catch(e){}
        out[cl].push(storyTrim(cv));
      }
    });
  } finally {
    window.G_WORN=keepW; G.bodyVar=keepD; G.age=keepA;
    try{ rebuildFromRig(); }catch(e){}
    try{ HD_CACHE.map.clear(); }catch(e){}
  }
  return out;
}

/* speaker -> the draft name the CHARACTER lane gave them. A caption that says
   "sibling_lost" is a debug readout, not a scene. */
function storySpeakerName(role){
  var map={mother:'MOTHER',father:'FATHER',sibling_older:'BROTHER',sibling_lost:'SISTER'};
  var k=map[role];
  if(k && window.FAMILY_CAST) for(var i=0;i<FAMILY_CAST.length;i++) if(FAMILY_CAST[i].role===k) return FAMILY_CAST[i].name;
  return (role||'').toUpperCase().replace(/_/g,' ');
}

var STORY=null, STORY_READY=false;
function storyBoot(done){
  if(STORY_READY){ if(done)done(); return; }
  var cv=document.getElementById('storyCv'); if(!cv) return;
  var st=document.getElementById('storyState');
  if(st) st.textContent='building the family...';
  STORY=new BohemiaStorySurface.Story({
    canvas:cv, set:BohemiaColdOpenSet, scene:BOHEMIA_COLD_OPEN, runtime:BohemiaScene,
    paintBody:storyPaintBody,
    onBeat:function(r,s){ storyCaption(s); },
    onEnd:function(s){ storyCaption(s, true); }
  });
  STORY.loadTiles(function(){
    STORY.bake(function(){
      STORY_READY=true;
      STORY.draw();
      if(st) st.textContent='ready';
      if(done)done();
    });
  });
}
function storyCaption(s, ended){
  var cap=document.getElementById('storyCap'), st=document.getElementById('storyState');
  if(!cap) return;
  if(ended || s.ended){
    var h=s.handoff;
    cap.innerHTML='<b style="color:#d8b45a">THE OPEN ENDS HERE.</b><br>'+
      (h? 'Hands off to the tutorial fight ('+h.encounter+').' : 'Scene complete.')+
      ' <span style="color:#8d8168">The family-defense fight is COMBAT\'s, and who is saved is Paolo\'s ruling, not drawn here.</span>';
    if(st) st.textContent='done';
    /* if COMBAT has landed its half on this build, take the handoff for real */
    if(s.handoff && s.handoff.call && typeof window[s.handoff.call]==='function'){
      try{ window[s.handoff.call](function(){}); }catch(e){}
    }
    return;
  }
  if(st) st.textContent='beat '+s.beatNo;
  var L=s.line;
  if(!L || !L.text){ cap.innerHTML='<span style="color:#6f6552">'+
      (s.era==='pre_collapse'?'before':'ten years later')+'</span>'; return; }
  cap.innerHTML='<span style="color:#9a8a5e;font-size:11px;letter-spacing:1px">'+
    storySpeakerName(L.speaker)+(L.draft?' <span style="color:#6f6552">&middot; draft, edit in WORDS</span>':'')+
    '</span><br>'+L.text.replace(/&/g,'&amp;').replace(/</g,'&lt;');
}
(function(){
  var t=document.getElementById('tabs'); if(!t) return;
  var tab=t.querySelector('.tab[data-p=story]');
  if(tab) tab.addEventListener('click', function(){ storyBoot(); });
  var p=document.getElementById('storyPlay');
  if(p) p.addEventListener('click', function(){ storyBoot(function(){ STORY.start(); }); });
  var a=document.getElementById('storyAgain');
  if(a) a.addEventListener('click', function(){ storyBoot(function(){ STORY.start(); }); });
})();
'''


def main():
    alpha = read('slices/BOHEMIA_ALPHA_0_9.html')

    scene_rt = read('engine/bohemia_scene.js')
    set_js = read('engine/bohemia_coldopen_set.js')
    surface = read('engine/bohemia_story_surface.js')
    canon = read('records/BOHEMIA_SCENE_ACT1_COLD_OPEN.json')
    json.loads(canon)                                   # it must be legal before it ships

    block = (BEGIN + '\n<script>\n'
             '/* INLINED VERBATIM from engine/bohemia_scene.js -- gates/coldopen_gate.js\n'
             '   fails if this copy drifts one byte from the canonical module. */\n'
             + scene_rt +
             '\n/* INLINED VERBATIM from engine/bohemia_coldopen_set.js */\n'
             + set_js +
             '\n/* INLINED VERBATIM from engine/bohemia_story_surface.js */\n'
             + surface +
             '\n/* THE AUTHORED SCENE, verbatim from records/BOHEMIA_SCENE_ACT1_COLD_OPEN.json.\n'
             '   It lives in records/ because it is Paolo canon, not engine code. */\n'
             'var BOHEMIA_COLD_OPEN = ' + canon.strip() + ';\n'
             + GLUE +
             '\n</script>\n' + END)

    # 1) THE SCRIPT BLOCK -- replaced whole, never appended
    if BEGIN in alpha and END in alpha:
        alpha = re.sub(re.escape(BEGIN) + r'[\s\S]*?' + re.escape(END), lambda m: block, alpha, count=1)
        where = 'replaced'
    else:
        anchor = '<script>(function(){var t=document.getElementById("tabs");if(!t)return;'
        i = alpha.index(anchor)
        alpha = alpha[:i] + block + '\n' + alpha[i:]
        where = 'inserted'

    # 2) THE TAB
    if 'data-p="story"' not in alpha:
        alpha = alpha.replace('<div class="tab" data-p="words">WORDS</div>',
                              '<div class="tab" data-p="words">WORDS</div>'
                              '<div class="tab" data-p="story">STORY</div>', 1)

    # 3) THE PANEL -- also replaced whole
    if PANEL_BEGIN in alpha and PANEL_END in alpha:
        alpha = re.sub(re.escape(PANEL_BEGIN) + r'[\s\S]*?' + re.escape(PANEL_END),
                       lambda m: PANEL, alpha, count=1)
    else:
        anchor = '<div class="panel" id="p-words">'
        j = alpha.index(anchor)
        k = alpha.index('</div>', alpha.index('</iframe>', j)) + len('</div>')
        alpha = alpha[:k] + '\n    ' + PANEL + alpha[k:]

    with open(ALPHA, 'w', encoding='utf-8') as f:
        f.write(alpha)

    print('STORY TAB: script block %s (%.0f KB)' % (where, len(block) / 1024.0))
    print('  tab      : %d' % alpha.count('data-p="story"'))
    print('  panel    : %d' % alpha.count('id="p-story"'))
    print('  runtime  : %d' % alpha.count('root.BohemiaScene = API'))
    print('  set      : %d' % alpha.count('root.BohemiaColdOpenSet = API'))
    print('  surface  : %d' % alpha.count('root.BohemiaStorySurface = API'))
    print('  canon    : %d' % alpha.count('var BOHEMIA_COLD_OPEN ='))
    print('  alpha    : %.1f MB' % (len(alpha) / 1048576.0))


if __name__ == '__main__':
    main()
