#!/usr/bin/env python3
"""BOHEMIA DIRECT TAB -- the controls, so he can direct instead of watch.

Paolo 8/12: "Bro this is the same fucking problem we had with the questing shit!
I CANT DIRECT QUESTS OR CUTSCENES RN WTF IS WRONG WITH YOU."

He is right and it is the second time. WORDS (8/11) let him change what somebody
SAYS. It did not let him change who is in a scene, what order it happens in,
where it happens, whether a beat exists at all, or where a choice leads -- which
is the entire job of a director. He watched two cutscenes, had structural notes
about both, and his only channel was typing a paragraph at me and waiting.

AND IT PUT THE QUESTIONS BACK. The turn before this one ended with "does the
father live?", which is a structural decision I had no way to receive except as
an answer. EVERYTHING IS A THUMB (8/9) banned the approvals queue; the queue came
back because the INSTRUMENT was missing. This is the instrument: he adds the
father himself and presses play.

WHAT IT GIVES HIM, over cutscenes AND quests, in one tab:
  SEE      every beat / stage / line in order, in plain words
  ADD      a line, a person, a wait, a cut, a choice
  DELETE   any of them
  MOVE     any of them up or down
  RETARGET who speaks, who is present, where a choice goes
  RELOCATE which building and which room the scene stands in
  PLAY     what HE built, immediately, not a preview of a plan
  KEEP     saved to the device, survives a reload, exports as .txt

ONE-LINK LAW: it ships inside the alpha. IT REPLACES, IT NEVER APPENDS -- the
whole block lives between markers and is swapped whole, so running this ten
times leaves the file identical to running it once.

  python3 tools/bohemia_direct_tab_patch.py
Law:  laws/BOHEMIA_ADDENDUM_HE_MUST_BE_ABLE_TO_DIRECT_8_12_26.md
Gate: gates/direct_gate.js
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = os.path.join(ROOT, 'slices', 'BOHEMIA_ALPHA_0_9.html')

BEGIN = '<!-- ===== BOHEMIA DIRECT TAB (generated by tools/bohemia_direct_tab_patch.py) ===== -->'
END = '<!-- ===== END BOHEMIA DIRECT TAB ===== -->'
PANEL_BEGIN = '<!-- ===== DIRECT PANEL (generated) ===== -->'
PANEL_END = '<!-- ===== END DIRECT PANEL ===== -->'

PANEL = PANEL_BEGIN + '''
    <div class="panel" id="p-direct">
      <div id="dirWrap" style="max-width:460px;margin:6px auto 0;padding:0 8px">
        <div class="mini" style="line-height:1.55;margin-bottom:7px">
          Change anything. Add people, cut lines, move beats around, put it in a different
          room. Press PLAY and you are watching what you just built. It saves on this phone.
        </div>
        <div class="row" id="dirMode" style="gap:6px;display:flex;flex-wrap:wrap"></div>
        <div class="row" id="dirPick" style="gap:6px;display:flex;flex-wrap:wrap;margin-top:6px"></div>
        <div id="dirWhere" style="margin-top:7px"></div>
        <div id="dirAdd" style="margin-top:7px"></div>
        <div id="dirList" style="margin-top:8px"></div>
        <div class="row" style="margin-top:9px;gap:6px;display:flex;align-items:center;flex-wrap:wrap">
          <button id="dirPlay" class="opt" style="background:#d8b45a;color:#191308;border-color:#d8b45a;font-weight:700">&#9654; PLAY WHAT I BUILT</button>
          <button id="dirExport" class="opt">EXPORT .TXT</button>
          <button id="dirReset" class="opt">UNDO ALL MINE</button>
        </div>
        <div id="dirStage" style="margin-top:9px;display:none">
          <canvas id="dirCv" width="360" height="470"
            style="width:100%;height:auto;display:block;background:#0a0806;border:1px solid #241c12;border-radius:4px;image-rendering:pixelated"></canvas>
          <div id="dirCap" style="min-height:60px;margin-top:7px;padding:8px 10px;border:1px solid #241c12;border-radius:4px;background:#100c07;font:13px/1.5 ui-monospace,monospace;color:#e8dfc8"></div>
        </div>
        <div class="mini" id="dirNote" style="margin-top:8px;line-height:1.55"></div>
      </div>
    </div>
''' + PANEL_END


def read(p):
    with open(os.path.join(ROOT, p), 'r', encoding='utf-8') as f:
        return f.read()


# ------------------------------------------------------------------ quests
def parse_bq(path, rel):
    """The parts of a .bq a DIRECTOR changes: stage logs, objectives, spoken
    lines, and the CHOICES with where they lead. Deliberately not a full parser
    -- a director does not need @DO effects, and pretending to edit something
    that does not round-trip would be worse than not showing it."""
    lines = open(path, encoding='utf-8').read().split('\n')
    out, node, stage, title, qid = [], None, None, None, None
    for i, raw in enumerate(lines):
        m = re.match(r'^@QUEST\s+(\S+)\s+(.*?)\s*$', raw)
        if m:
            qid, title = m.group(1), m.group(2); continue
        m = re.match(r'^@STAGE\s+(\d+)', raw)
        if m:
            stage = m.group(1); continue
        m = re.match(r'^@TALK\s+(\S+)(.*)$', raw)
        if m:
            node = m.group(1)
            sp = re.search(r'speaker=(\S+)', m.group(2))
            out.append({'kind': 'node', 'node': node, 'who': sp.group(1) if sp else '',
                        'text': node, 'line': i + 1})
            continue
        m = re.match(r'^\s*@SAY\s+(.*?)\s*$', raw)
        if m:
            t = re.sub(r'\s+#[a-z_]+\s*$', '', m.group(1))
            out.append({'kind': 'say', 'node': node, 'who': '', 'text': t, 'line': i + 1})
            continue
        m = re.match(r'^\s*@OPT\s+(.*?)\s*$', raw)
        if m:
            body = m.group(1)
            q = re.match(r'"([^"]*)"', body)
            p = re.match(r'\(([^)]*)\)', body)
            txt = q.group(1) if q else (('(' + p.group(1) + ')') if p else None)
            goto = re.search(r'->\s*(\S+)', body)
            if txt:
                out.append({'kind': 'choice', 'node': node, 'who': 'YOU', 'text': txt,
                            'goto': goto.group(1) if goto else '', 'line': i + 1})
            continue
        m = re.match(r'^\s*@LOG\s+(.*?)\s*$', raw)
        if m:
            out.append({'kind': 'journal', 'node': ('stage ' + stage) if stage else '',
                        'who': '', 'text': m.group(1), 'line': i + 1})
            continue
        m = re.match(r'^@OBJ\s+(\d+)\s+"([^"]*)"', raw)
        if m:
            out.append({'kind': 'objective', 'node': 'obj ' + m.group(1), 'who': '',
                        'text': m.group(2), 'line': i + 1})
    return {'file': rel, 'id': qid, 'title': title or os.path.basename(path), 'rows': out}


GLUE = r'''
/* ---- THE DIRECTOR --------------------------------------------------------
   Paolo 8/12: "I CANT DIRECT QUESTS OR CUTSCENES RN." This is the answer.
   Everything here edits a LOCAL copy, keyed by scene/quest id, saved to the
   device. Nothing a lane shipped is overwritten -- his version wins on his
   phone and EXPORT is how it becomes canon. That way he can wreck a scene at
   two in the morning and nothing in the repo moves until he says so. */
var DIR_KEY='bohemia_direct_v1';
var DIR = {};   try { DIR = JSON.parse(localStorage.getItem(DIR_KEY)||'{}'); } catch(e){ DIR={}; }
function dirSave(){ try{ localStorage.setItem(DIR_KEY, JSON.stringify(DIR)); }catch(e){} }
var DIR_MODE='cutscene', DIR_I=0, DIR_PLAYER=null;

/* the cast a scene can draw on. Read off FAMILY_CAST so the CHARACTER lane owns
   who exists and this owns nothing. */
function dirCast(){
  var out=[{role:'player', label:'YOU'}];
  var map={MOTHER:'mother',FATHER:'father',BROTHER:'sibling_older',SISTER:'sibling_lost'};
  if(window.FAMILY_CAST) FAMILY_CAST.forEach(function(m){
    if(map[m.role]) out.push({role:map[m.role], label:m.name+' ('+m.role.toLowerCase()+')'});
  });
  return out;
}
function dirSpeakerLabel(role){
  if(role==='player') return 'YOU';
  var c=dirCast().filter(function(x){return x.role===role;})[0];
  return c?c.label:String(role||'').toUpperCase().replace(/_/g,' ');
}

/* ---- WHAT HE IS EDITING RIGHT NOW ---- */
function dirScenes(){ return BOHEMIA_CUTSCENES; }
function dirCur(){
  if(DIR_MODE==='cutscene'){
    var s=dirScenes()[DIR_I]; if(!s) return null;
    var id='scene:'+s.scene.id;
    if(!DIR[id]) DIR[id]=JSON.parse(JSON.stringify(s.scene));
    return {id:id, title:s.title, data:DIR[id], shipped:s.scene};
  }
  var q=BOHEMIA_QUESTS[DIR_I]; if(!q) return null;
  var qid='quest:'+q.id;
  if(!DIR[qid]) DIR[qid]=JSON.parse(JSON.stringify(q));
  return {id:qid, title:q.title, data:DIR[qid], shipped:q};
}
function dirEdited(){ var c=dirCur(); if(!c) return false;
  return JSON.stringify(c.data)!==JSON.stringify(c.shipped); }

/* ---- CHIPS ---- */
function dirChip(label,on,fn,extra){
  var b=document.createElement('button'); b.className='opt'; b.textContent=label;
  if(on){ b.style.background='#d8b45a'; b.style.color='#191308'; b.style.borderColor='#d8b45a'; }
  if(extra) b.style.cssText+=extra;
  b.onclick=fn; return b;
}
function dirRenderChips(){
  var m=document.getElementById('dirMode'); m.innerHTML='';
  m.appendChild(dirChip('CUTSCENES', DIR_MODE==='cutscene', function(){ DIR_MODE='cutscene'; DIR_I=0; dirRender(); }));
  m.appendChild(dirChip('QUESTS', DIR_MODE==='quest', function(){ DIR_MODE='quest'; DIR_I=0; dirRender(); }));
  var p=document.getElementById('dirPick'); p.innerHTML='';
  var list = DIR_MODE==='cutscene' ? dirScenes().map(function(s){return s.title;})
                                   : BOHEMIA_QUESTS.map(function(q){return q.title;});
  list.forEach(function(t,i){ p.appendChild(dirChip(t, i===DIR_I, function(){ DIR_I=i; dirRender(); })); });
}

/* ---- WHERE IT HAPPENS (cutscene only) ---- */
var DIR_ZONES=['residential','retail','office','civic','institutional','warehouse','landmark','leisure'];
var DIR_ROLES={residential:['living','kitchen','bed','bath'],retail:['shopfloor','checkout','stockroom','office'],
  office:['lobby','office','meeting','breakroom'],civic:['hall','reception','office','records'],
  institutional:['ward','office','service'],warehouse:['floor_open','dock','office'],
  landmark:['atrium','gallery','service'],leisure:['concourse','counter','kitchen','locker']};
function dirWhere(){
  var host=document.getElementById('dirWhere'); host.innerHTML='';
  if(DIR_MODE!=='cutscene') return;
  var c=dirCur(); if(!c) return;
  var pl=c.data.place=c.data.place||{zone:'residential',role:'living',seed:7,w:24,h:16,kit:'dining'};
  var row=document.createElement('div'); row.className='row';
  row.style.cssText='gap:6px;display:flex;flex-wrap:wrap;align-items:center';
  var lab=document.createElement('b'); lab.textContent='WHERE'; lab.style.cssText='font-size:11px;letter-spacing:1px;color:#9a8a5e';
  row.appendChild(lab);
  function sel(opts,val,fn){
    var s=document.createElement('select');
    s.style.cssText='font:11px ui-monospace,monospace;background:#191308;color:#c8b98a;border:1px solid #3a3020;border-radius:4px;padding:5px 7px';
    opts.forEach(function(o){ var op=document.createElement('option'); op.value=o; op.textContent=o; if(o===val)op.selected=true; s.appendChild(op); });
    s.onchange=function(){ fn(s.value); }; return s;
  }
  row.appendChild(sel(DIR_ZONES, pl.zone, function(v){ pl.zone=v; pl.role=(DIR_ROLES[v]||['room'])[0]; dirSave(); dirRender(); }));
  row.appendChild(sel(DIR_ROLES[pl.zone]||['room'], pl.role, function(v){ pl.role=v; dirSave(); dirRender(); }));
  row.appendChild(dirChip('◀ HOUSE', false, function(){ pl.seed=Math.max(1,(pl.seed|0)-1); dirSave(); dirRender(); }));
  var sd=document.createElement('span'); sd.className='mini'; sd.textContent='seed '+pl.seed; row.appendChild(sd);
  row.appendChild(dirChip('HOUSE ▶', false, function(){ pl.seed=(pl.seed|0)+1; dirSave(); dirRender(); }));
  host.appendChild(row);
}

/* ---- ADD ---- */
function dirAddRow(){
  var host=document.getElementById('dirAdd'); host.innerHTML='';
  var c=dirCur(); if(!c) return;
  var row=document.createElement('div'); row.className='row';
  row.style.cssText='gap:6px;display:flex;flex-wrap:wrap;align-items:center';
  var lab=document.createElement('b'); lab.textContent='ADD'; lab.style.cssText='font-size:11px;letter-spacing:1px;color:#9a8a5e';
  row.appendChild(lab);
  if(DIR_MODE==='cutscene'){
    var beats=c.data.beats;
    function ins(b){ var at=Math.max(0,beats.length-1); beats.splice(at,0,b); dirSave(); dirRender(); }
    row.appendChild(dirChip('+ LINE', false, function(){
      ins({kind:'say', id:'d'+beats.length, speaker:dirCast()[1]?dirCast()[1].role:'mother',
           text:'New line.', draft:true, why:'added in DIRECT by Paolo'}); }));
    dirCast().forEach(function(p){
      row.appendChild(dirChip('+ '+p.label, false, function(){
        ins({kind:'actor', id:'d'+beats.length, actor:p.role,
             at:(p.role==='player'?'table_seat_player':null), age:(p.role==='player'?'adult':null),
             why:'added in DIRECT by Paolo'}); }));
    });
    row.appendChild(dirChip('+ PAUSE', false, function(){
      ins({kind:'wait', id:'d'+beats.length, beats:4, why:'added in DIRECT by Paolo'}); }));
    row.appendChild(dirChip('+ TIME CUT', false, function(){
      ins({kind:'cut', id:'d'+beats.length, from:'pre_collapse', to:'post_collapse',
           keepFraming:true, why:'added in DIRECT by Paolo'}); }));
  } else {
    var rows=c.data.rows;
    row.appendChild(dirChip('+ LINE', false, function(){
      rows.push({kind:'say', node:rows.length?rows[rows.length-1].node:'', who:'', text:'New line.'});
      dirSave(); dirRender(); }));
    row.appendChild(dirChip('+ CHOICE', false, function(){
      rows.push({kind:'choice', node:rows.length?rows[rows.length-1].node:'', who:'YOU', text:'New choice.', goto:''});
      dirSave(); dirRender(); }));
    row.appendChild(dirChip('+ JOURNAL', false, function(){
      rows.push({kind:'journal', node:'', who:'', text:'New journal entry.'});
      dirSave(); dirRender(); }));
  }
  host.appendChild(row);
}

/* ---- THE LIST. Every row: what it is, who, the words, and the four verbs. --- */
function dirRenderList(){
  var host=document.getElementById('dirList'); host.innerHTML='';
  var c=dirCur(); if(!c) return;
  var items = DIR_MODE==='cutscene' ? c.data.beats : c.data.rows;
  items.forEach(function(it,i){
    var box=document.createElement('div');
    box.style.cssText='border:1px solid #241c12;border-radius:5px;margin-bottom:6px;background:#120e08';
    var head=document.createElement('div');
    head.style.cssText='display:flex;gap:6px;align-items:center;padding:6px 8px;flex-wrap:wrap';
    var kind=(DIR_MODE==='cutscene')?it.kind:it.kind;
    var k=document.createElement('span');
    k.style.cssText='font-size:9px;letter-spacing:1px;border:1px solid #3a3020;border-radius:3px;padding:1px 5px;color:#8d8168';
    k.textContent=(kind==='say'?'LINE':kind==='actor'?'PERSON':kind==='wait'?'PAUSE':
                   kind==='cut'?'TIME CUT':kind==='choice'?'CHOICE':kind==='journal'?'JOURNAL':
                   kind==='objective'?'OBJECTIVE':kind==='node'?'SCENE':kind.toUpperCase());
    head.appendChild(k);
    var num=document.createElement('span'); num.className='mini'; num.textContent=(i+1); head.appendChild(num);

    /* WHO -- a real picker, because retargeting a line is directing */
    if(DIR_MODE==='cutscene' && (kind==='say'||kind==='actor')){
      var who=document.createElement('select');
      who.style.cssText='font:11px ui-monospace,monospace;background:#191308;color:#c8b98a;border:1px solid #3a3020;border-radius:4px;padding:4px 6px';
      dirCast().forEach(function(p){
        var op=document.createElement('option'); op.value=p.role; op.textContent=p.label;
        if((it.speaker||it.actor)===p.role) op.selected=true; who.appendChild(op); });
      who.onchange=function(){ if(kind==='say') it.speaker=who.value; else it.actor=who.value; dirSave(); dirRender(); };
      head.appendChild(who);
    } else if(it.who||it.node){
      /* A QUEST'S SPEAKERS ARE ROLES CAST AT RUNTIME (the lineman, the fixer),
         never the family, so offering DENISE for them would be nonsense. The
         node is shown instead, which is what a director actually needs to see. */
      var w=document.createElement('span'); w.className='mini';
      w.textContent=(it.who||'')+(it.node?(' · '+it.node):''); head.appendChild(w); }

    var sp=document.createElement('span'); sp.style.flex='1'; head.appendChild(sp);
    function vb(t,fn){ var b=document.createElement('button'); b.className='opt';
      b.style.cssText='padding:3px 7px;line-height:1'; b.textContent=t; b.onclick=fn; return b; }
    head.appendChild(vb('▲', function(){ if(i>0){ items.splice(i-1,0,items.splice(i,1)[0]); dirSave(); dirRender(); } }));
    head.appendChild(vb('▼', function(){ if(i<items.length-1){ items.splice(i+1,0,items.splice(i,1)[0]); dirSave(); dirRender(); } }));
    head.appendChild(vb('✕', function(){ items.splice(i,1); dirSave(); dirRender(); }));
    box.appendChild(head);

    /* THE WORDS, editable in place */
    if(it.text!=null && kind!=='actor' && kind!=='node'){
      var ta=document.createElement('textarea');
      ta.style.cssText='width:100%;font:13px/1.5 ui-monospace,monospace;background:#0e0b06;color:#e8dfc8;border:0;border-top:1px solid #1d1710;padding:7px 9px;resize:vertical;min-height:38px;display:block';
      ta.value=it.text;
      ta.oninput=function(){ it.text=ta.value; if(kind==='say'&&DIR_MODE==='cutscene') it.draft=true; dirSave(); };
      box.appendChild(ta);
    }
    if(kind==='wait'){
      var wr=document.createElement('div'); wr.style.cssText='padding:5px 8px;display:flex;gap:6px;align-items:center';
      wr.appendChild(vb('−', function(){ it.beats=Math.max(1,(it.beats|0)-1); dirSave(); dirRender(); }));
      var bl=document.createElement('span'); bl.className='mini'; bl.textContent=(it.beats|0)+' beats ('+((it.beats|0)*0.5).toFixed(1)+'s)';
      wr.appendChild(bl);
      wr.appendChild(vb('+', function(){ it.beats=(it.beats|0)+1; dirSave(); dirRender(); }));
      box.appendChild(wr);
    }
    /* WHERE A CHOICE GOES -- the one bit of quest routing a director must have */
    if(kind==='choice'){
      var gr=document.createElement('div'); gr.style.cssText='padding:5px 8px;display:flex;gap:6px;align-items:center;flex-wrap:wrap';
      var gl=document.createElement('span'); gl.className='mini'; gl.textContent='goes to'; gr.appendChild(gl);
      var gs=document.createElement('select'); gs.className='dirGoto';
      gs.style.cssText='font:11px ui-monospace,monospace;background:#191308;color:#c8b98a;border:1px solid #3a3020;border-radius:4px;padding:4px 6px';
      var nodes=[''].concat(c.data.rows.filter(function(r){return r.kind==='node';}).map(function(r){return r.node;}));
      nodes.push('END');
      nodes.forEach(function(n){ var op=document.createElement('option'); op.value=n; op.textContent=n||'(nowhere yet)';
        if(n===it.goto) op.selected=true; gs.appendChild(op); });
      gs.onchange=function(){ it.goto=gs.value; dirSave(); };
      gr.appendChild(gs); box.appendChild(gr);
    }
    host.appendChild(box);
  });
}

/* ---- PLAY WHAT HE BUILT ---- */
function dirPlay(){
  var c=dirCur(); if(!c) return;
  var stage=document.getElementById('dirStage');
  var note=document.getElementById('dirNote');
  if(DIR_MODE!=='cutscene'){
    stage.style.display='none';
    note.innerHTML='Quests do not play in here yet — edit and EXPORT, and they land as canon. '+
      'The <b>CUTSCENE</b> tab is where scenes play.';
    return;
  }
  stage.style.display='block';
  cutBoot(function(){
    if(DIR_PLAYER) DIR_PLAYER.stop();
    DIR_PLAYER=new BohemiaStorySurface.Story({
      canvas:document.getElementById('dirCv'), set:BohemiaColdOpenSet,
      scene:c.data, runtime:BohemiaScene, stage:BOH_STAGE, floorplan:BOH_FLOORPLAN,
      paintBody:cutPaintBody, speak:cutVoice,
      onBeat:function(r,s){ dirCaption(s); }, onEnd:function(s){ dirCaption(s,true); }
    });
    if(CUT_FRAMES) DIR_PLAYER.frames=CUT_FRAMES;
    DIR_PLAYER.loadTiles(function(){
      function go(){ DIR_PLAYER.start(); document.getElementById('dirStage').scrollIntoView({behavior:'smooth',block:'center'}); }
      if(DIR_PLAYER.frames && Object.keys(DIR_PLAYER.frames).length) go(); else DIR_PLAYER.bake(go);
    });
  });
}
function dirCaption(s,ended){
  var cap=document.getElementById('dirCap'); if(!cap) return;
  if(ended||s.ended){ cap.innerHTML='<b style="color:#d8b45a">END.</b> That is your version. EXPORT it and it becomes canon.'; return; }
  var L=s.line;
  cap.innerHTML = (L&&L.text)
    ? '<span style="color:#9a8a5e;font-size:11px;letter-spacing:1px">'+dirSpeakerLabel(L.speaker)+'</span><br>'+
      L.text.replace(/&/g,'&amp;').replace(/</g,'&lt;')
    : '<span style="color:#6f6552">'+(s.era==='pre_collapse'?'before':'after')+'</span>';
}

/* ---- EXPORT ---- */
function dirExport(){
  var out=['BOHEMIA -- DIRECTED BY PAOLO',''], n=0;
  Object.keys(DIR).forEach(function(k){
    var shipped=null;
    if(k.indexOf('scene:')===0) BOHEMIA_CUTSCENES.forEach(function(s){ if('scene:'+s.scene.id===k) shipped=s.scene; });
    else BOHEMIA_QUESTS.forEach(function(q){ if('quest:'+q.id===k) shipped=q; });
    if(shipped && JSON.stringify(DIR[k])===JSON.stringify(shipped)) return;
    n++;
    out.push('=== '+k+' ===');
    var d=DIR[k];
    if(d.beats){
      if(d.place) out.push('  WHERE  '+d.place.zone+' / '+d.place.role+' / house seed '+d.place.seed);
      d.beats.forEach(function(b,i){
        var s='  '+String(i+1).padStart(3,' ')+'  '+b.kind.toUpperCase();
        if(b.actor) s+='  '+b.actor;
        if(b.speaker) s+='  '+b.speaker;
        if(b.kind==='wait') s+='  '+(b.beats|0)+' beats';
        out.push(s);
        if(b.text) out.push('        "'+b.text+'"');
      });
    } else if(d.rows){
      d.rows.forEach(function(r,i){
        out.push('  '+String(i+1).padStart(3,' ')+'  '+r.kind.toUpperCase()+(r.node?('  ['+r.node+']'):'')+
                 (r.goto?('  -> '+r.goto):''));
        if(r.text) out.push('        "'+r.text+'"');
      });
    }
    out.push('');
  });
  out.splice(1,0, n?(n+' thing(s) changed. Everything not listed is untouched.'):'Nothing changed yet.','');
  var blob=new Blob([out.join('\n')],{type:'text/plain'});
  var a=document.createElement('a'); a.href=URL.createObjectURL(blob);
  a.download='BOHEMIA_DIRECTED.txt'; a.click();
}

function dirRender(){
  dirRenderChips(); dirWhere(); dirAddRow(); dirRenderList();
  var note=document.getElementById('dirNote');
  var c=dirCur();
  note.innerHTML = c ? ('<b>'+c.title+'</b> · '+
    (DIR_MODE==='cutscene'?c.data.beats.length+' beats':c.data.rows.length+' lines')+
    (dirEdited()?' · <span style="color:#d8b45a">you changed this</span>':' · as shipped')) : '';
}

(function(){
  var t=document.getElementById('tabs'); if(!t) return;
  var tab=t.querySelector('.tab[data-p=direct]');
  if(tab) tab.addEventListener('click', function(){ dirRender(); });
  var p=document.getElementById('dirPlay'); if(p) p.addEventListener('click', dirPlay);
  var e=document.getElementById('dirExport'); if(e) e.addEventListener('click', dirExport);
  var r=document.getElementById('dirReset'); if(r) r.addEventListener('click', function(){
    var c=dirCur(); if(!c) return; DIR[c.id]=JSON.parse(JSON.stringify(c.shipped)); dirSave(); dirRender(); });
})();
'''


def main():
    alpha = read('slices/BOHEMIA_ALPHA_0_9.html')

    # every canon quest, parsed to the parts a director changes
    quests = []
    bqdir = os.path.join(ROOT, 'quests', 'bq')
    if os.path.isdir(bqdir):
        for f in sorted(os.listdir(bqdir)):
            if f.endswith('.bq'):
                quests.append(parse_bq(os.path.join(bqdir, f), 'quests/bq/' + f))

    block = (BEGIN + '\n<script>\n'
             '/* THE CANON QUESTS, parsed to the parts a DIRECTOR changes: stage logs,\n'
             '   objectives, spoken lines, and the choices with where they lead.\n'
             '   Generated by tools/bohemia_direct_tab_patch.py. */\n'
             'var BOHEMIA_QUESTS = ' + json.dumps(quests, ensure_ascii=False) + ';\n'
             + GLUE + '\n</script>\n' + END)

    if BEGIN in alpha and END in alpha:
        alpha = re.sub(re.escape(BEGIN) + r'[\s\S]*?' + re.escape(END), lambda m: block, alpha, count=1)
        where = 'replaced'
    else:
        anchor = '<!-- ===== END BOHEMIA CUTSCENE TAB ===== -->'
        i = alpha.index(anchor) + len(anchor)
        alpha = alpha[:i] + '\n' + block + alpha[i:]
        where = 'inserted'

    if 'data-p="direct"' not in alpha:
        alpha = alpha.replace('<div class="tab" data-p="cutscene">CUTSCENE</div>',
                              '<div class="tab" data-p="cutscene">CUTSCENE</div>'
                              '<div class="tab" data-p="direct">DIRECT</div>', 1)

    if PANEL_BEGIN in alpha and PANEL_END in alpha:
        alpha = re.sub(re.escape(PANEL_BEGIN) + r'[\s\S]*?' + re.escape(PANEL_END),
                       lambda m: PANEL, alpha, count=1)
    else:
        anchor = '<!-- ===== END CUTSCENE PANEL ===== -->'
        i = alpha.index(anchor) + len(anchor)
        alpha = alpha[:i] + '\n    ' + PANEL + alpha[i:]

    with open(ALPHA, 'w', encoding='utf-8') as f:
        f.write(alpha)

    rows = sum(len(q['rows']) for q in quests)
    print('DIRECT TAB: script block %s (%.0f KB)' % (where, len(block) / 1024.0))
    print('  tab    : %d' % alpha.count('data-p="direct"'))
    print('  panel  : %d' % alpha.count('id="p-direct"'))
    print('  quests : %d (%d directable rows)' % (len(quests), rows))
    print('  alpha  : %.1f MB' % (len(alpha) / 1048576.0))


if __name__ == '__main__':
    main()
