#!/usr/bin/env python3
"""BOHEMIA — wire the identity layer into the run surface (7/31/26, PEOPLE lane).

WHAT THIS DOES, in one sentence: the 28 scheduled bodies on the block stop being
bodies. Walk up to one and the one button says TALK TO THE SCAVENGER; tapping it
opens the run's existing dialogue sheet showing that specific person's own face,
their house, their job, where they are in their day, and whether you have met
them before. HANG OUT is not deleted — it moves inside the conversation, which is
where hanging out with somebody belongs once you know who they are.

AND YOU HAVE TO ASK (Paolo 7/31, LOCKED — laws/BOHEMIA_ADDENDUM_YOU_HAVE_TO_ASK_
7_31_26.md): the card says YOU HAVE NOT ASKED where a name would be, and there is
an "Ask their name" button. Tap it and they are named — on the card, on the one
action button, and forever after, across saves. "I hate how in other games you
know everyone's name off the bat and I think it's complete bullshit."

WHY A PATCH TOOL AND NOT AN EDIT:
  The run slice is the RUN lane's file and this is the PEOPLE lane. Under the
  parallel-sessions law the safe way to touch another lane's surface is a tool
  that reproduces its change deterministically on top of whatever main has, so a
  rebase is `git checkout --ours <file>` + re-run, never a hand merge. That rule
  is written in the handoff in blood: hand-resolving this exact file ate a
  megabyte of somebody's work on 7/30.

  IT PATCHES THE DEV SOURCE, NOT THE BUILT FILE. slices/BOHEMIA_RUN_CURRENT.html
  is generated by tools/build_run_slice.js and says so; patching it would be
  erased by the next build (the SOUNDS lane's bug #3 on 7/29). This edits
  slices/BOHEMIA_RUN_SLICE_7_26_26.html and then runs the builder.

REUSE CHECK: this tool cooks ZERO new pixels, and the reuse-first gate is right to
  ask, because the code it injects calls drawImage. Everything it draws already
  existed and was already approved.
  LOOKED AT: the alpha's own run cast (BOHEMIA_RUN_CAST, baked at alpha 5703-5740
  from Paolo's rig + his canon wardrobe) — its `looks[]` bodies and its
  index-aligned `portraits.looks[]` faces; and the run's existing dialogue sheet
  (#talk / #spkface / #says / #opts) with its existing CSS variables.
  USED: both, unchanged. The portrait is Paolo's already-baked 64x64 face, drawn
  at the index the identity layer resolves — no new face, no new body, no new
  colour. The card is laid out in the sheet's own type and the run's own palette
  variables (--surface / --line / --ink / --dim / --faint / --gold), so nothing
  here introduces a colour either.
  COOKED NOTHING: no banks/ file is written, no image is generated, no tile is
  produced. The only art decision this tool makes is WHICH of six already-approved
  bodies each person wears — and the whole point of the change is that three of
  those six were never being reached at all.

IDEMPOTENT, MARKER-BOUNDED: every block is fenced by a PEOPLE:<name> marker pair.
A re-run RESTORES each fenced region to the original text first, then re-patches,
so running it twice is byte-identical to running it once and running it on a
fresh checkout of main works the same. A wrapper you insert is a wrapper you
delete whole — the 7/29 orphaned-`})();` lesson. Every anchor must resolve
EXACTLY ONCE or the tool refuses to write anything at all.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'slices', 'BOHEMIA_RUN_SLICE_7_26_26.html')


def restore(text, name, original='', mine=None):
    """Replace a marker-bounded block with what was there before it (default:
    nothing, for blocks that were pure insertions).

    AND REFUSE IF SOMEBODY ELSE'S CODE HAS MOVED INSIDE OUR FENCE. Not
    theoretical: it happened. On 8/1 another lane anchored its RUN PERSON FACTS
    block on a line inside PEOPLE:WORKERS, so the pair came to span 29 lines that
    were not ours, and a re-run DELETED THEM SILENTLY -- taking RUN_PEOPLE with
    it and turning run_people_gate from 45/0 to 34/5. A tool that exists to make
    cross-lane edits safe was doing the exact opposite.
    THE TEST IS EXACT, not a heuristic: `mine` is the very text this block
    inserts, so any substantial line inside the fence that is not in it belongs
    to somebody else. (The first version of this guard looked for banner comments
    and flagged this file's OWN block headers - a checker that cannot tell a
    mention from a use is the broken one.)"""
    pat = re.compile(
        r'[ \t]*(?:/\*|<!--)\s*PEOPLE:' + name + r'\s*(?:\*/|-->).*?'
        r'(?:/\*|<!--)\s*/PEOPLE:' + name + r'\s*(?:\*/|-->)[ \t]*(?:\n|(?=\S))?',
        re.S)

    def sub(m):
        if mine:
            ours = set(l.strip() for l in mine.split('\n'))
            for line in m.group(0).split('\n'):
                t = line.strip()
                if len(t) > 3 and t not in ours:
                    sys.exit('REFUSING TO WRITE: a line inside the PEOPLE:%s fence '
                             'is not ours, so restoring would delete somebody '
                             'else\'s code. Re-anchor the block so its markers do '
                             'not span foreign code.\n  %s\n' % (name, t[:90]))
        return original
    return pat.sub(sub, text)


def once(text, anchor, what):
    n = text.count(anchor)
    if n != 1:
        sys.exit('REFUSING TO WRITE: anchor for %s resolves %d times, not 1.\n  %r'
                 % (what, n, anchor[:90]))


# ---------------------------------------------------------------------------
# 1. THE ENGINE MODULE. The builder inlines <script src="../engine/X.js"> as the
#    byte-identical body of that file, so this is also how it reaches the alpha.
# ---------------------------------------------------------------------------
A_SCRIPT = '<script src="../engine/bohemia_agents.js"></script>\n'
B_SCRIPT = """<!-- PEOPLE:SCRIPT -->
<script src="../engine/bohemia_people.js"></script>
<!-- /PEOPLE:SCRIPT -->
"""

# ---------------------------------------------------------------------------
# 2. THE CARD'S LOOK. It rides inside the existing dialogue sheet rather than
#    being a second surface: one sheet, one place conversations happen.
# ---------------------------------------------------------------------------
A_CSS = '  #opts button:active{ background:#31280f; }\n'
B_CSS = """/* PEOPLE:CSS */
  /* THE IDENTITY CARD. Deliberately NOT a debug panel: it is the top of the
     dialogue sheet, in the sheet's own type, because a person you can read is a
     person and a table of fields is a spreadsheet. */
  #seat{ font-family:var(--mono); font-size:9px; letter-spacing:1.3px;
    color:var(--faint); text-transform:uppercase; margin-top:3px; }
  #idcard{ display:none; margin:0 0 12px; padding:10px 0 0; border-top:1px solid var(--line); }
  #idcard .r{ display:flex; gap:10px; align-items:baseline; margin-bottom:6px; }
  #idcard .k{ font-family:var(--mono); font-size:8.5px; letter-spacing:1.2px;
    color:var(--faint); text-transform:uppercase; flex:none; width:82px; }
  #idcard .v{ font-size:13px; color:var(--ink); line-height:1.35; }
  #idcard .r.unnamed .v{ color:var(--dim); font-style:italic; }
/* /PEOPLE:CSS */
"""

# ---------------------------------------------------------------------------
# 3. THE CARD'S SLOT, inside the dialogue sheet the run already has.
# ---------------------------------------------------------------------------
A_DOM = ('    <div class="spkrow"><canvas id="spkface" width="64" height="64">'
         '</canvas><div id="spk"></div></div>\n')
B_DOM = """    <!-- PEOPLE:DOM -->
    <div class="spkrow"><canvas id="spkface" width="64" height="64"></canvas>
      <div><div id="spk"></div><div id="seat"></div></div></div>
    <div id="idcard"></div>
    <!-- /PEOPLE:DOM -->
"""

# ---------------------------------------------------------------------------
# 4. THE VERB. The neighbour branch used to be an anonymous HANG OUT. It becomes
#    TALK, and HANG OUT becomes an option INSIDE the talk — the one-button law is
#    untouched (still exactly one verb) and RUN's hour-long hangout still exists
#    and still costs an hour.
# ---------------------------------------------------------------------------
A_VERB = """    /* a neighbour standing near you: a block of time spent with somebody */
    if(SIM){ var outs=SIM.outAgents();
      for(var i=0;i<outs.length;i++){ var a=outs[i];
        if(reaches(a.loc.x,a.loc.y))
          return { verb:'hangout', label:'HANG OUT (1 HOUR)',
                   act:function(){ spendTime('HANGOUT','You spent an hour with a neighbour.'); } };
      } }
"""
B_VERB = """    /* PEOPLE:VERB */
    /* A NEIGHBOUR STANDING NEAR YOU IS A PERSON, NOT A TIME SINK. This branch
       used to be an anonymous HANG OUT (1 HOUR): you spent an hour with "a
       neighbour" and never learned which one. It is TALK now, and the hour is
       still on the table — it is an option inside the conversation, which is
       where hanging out with somebody belongs once you know who they are. */
    if(SIM){ var outs=SIM.outAgents();
      for(var i=0;i<outs.length;i++){ var a=outs[i];
        if(reaches(a.loc.x,a.loc.y)){
          var who=personFor(a);
          return { verb:'talk', label:BohemiaPeople.addressOf(who),
                   act:(function(ag){ return function(){ openPerson(ag); }; })(a) };
        }
      } }
    /* /PEOPLE:VERB */
"""

# ---------------------------------------------------------------------------
# 5. THE RUNTIME. Sits next to closeTalk() because it reuses the same sheet.
# ---------------------------------------------------------------------------
A_RUNTIME = """function closeTalk(){
  TALKEL.style.display='none';
  RUN.phase = (RT && RT.state.done) ? 'resolved' : 'street';
  afterTalk();
}
"""
B_RUNTIME = """/* PEOPLE:RUNTIME */
/* ===========================================================================
   THE PEOPLE ON THE BLOCK ARE PEOPLE (7/31, PEOPLE lane).
   engine/bohemia_people.js derives WHO a scheduled body is from the same three
   numbers the body itself is derived from, so the identity survives the sim
   being thrown away and rebuilt on every save load. Everything below is
   RENDERING: not one fact on this card is invented here, and the NAME row says
   NOT NAMED YET because the named cast is Paolo's and its table ships empty.
   =========================================================================== */
var PEOPLE_MET = BohemiaPeople.makeLedger(null);   /* rides in the save blob */
var PERSON_OPEN = null;
/* THE BLOCK'S OWN SEED, set by buildSim. NOT the world SEED (which is 7 for the
   whole valley) — keying people off that would hand house 3's second resident
   the same identity in every cell there is. */
var PEOPLE_SEED = 0;
/* THE BLOCK SEED FOR ANY CELL, by the same mix buildSim uses. */
function blockSeedFor(cx,cy){ return (SEED ^ (cx*73856093) ^ (cy*19349663)) >>> 0; }
/* WHOSE BLOCK NAMES THEM: a person is identified by where they LIVE, never by
   where they happen to be standing. A worker at the clinic is the same person as
   the neighbour in their own yard, so their key comes from their HOME cell - or
   you would ask somebody their name at work and be a stranger to them at home. */
function seedOfPerson(agent){
  return (agent && agent.visiting && agent.fromCell)
    ? blockSeedFor(agent.fromCell[0], agent.fromCell[1]) : PEOPLE_SEED;
}
function personFor(agent){
  var roster = (SIM && SIM.agents) ? SIM.agents : [agent];
  var sizes = {};
  roster.forEach(function(r){ var h=BohemiaPeople.seatOf(r).house; sizes[h]=(sizes[h]||0)+1; });
  var seed = seedOfPerson(agent);
  var key = BohemiaPeople.keyOf(seed, agent);
  return BohemiaPeople.personOf(seed, agent,
    { householdSize: sizes[BohemiaPeople.seatOf(agent).house],
      asked: PEOPLE_MET.asked(key) });
}
/* THE DAY YOU ARE ON. The meeting ledger remembers world-days, never wall-clock:
   a save has to mean the same thing on a device in another timezone (saveBlob's
   own rule), and the sim turn IS the world minute. */
function worldDay(){ return Math.floor((SIM?SIM.turn:0)/1440); }
/* OPENING a conversation is a meeting. RE-DRAWING the card after you ask their
   name is not, and counting it as one made asking somebody their name inflate how
   often you had met them - caught by the gate, on the real surface. */
function openPerson(agent){
  var who = personFor(agent);
  if(!who) return;
  /* meet() returns the record as it now stands, so the very meeting that makes
     it no longer the first time still reads FIRST TIME. */
  PEOPLE_MET.meet(who.key, worldDay());
  drawPerson(agent);
}
function drawPerson(agent){
  var who = personFor(agent);
  if(!who) return;
  var met = PEOPLE_MET.get(who.key);
  PERSON_OPEN = who;
  RUN.phase='talking'; TALKEL.style.display='flex';
  SPK.textContent = BohemiaPeople.headingOf(who);
  var seat=document.getElementById('seat');
  if(seat) seat.textContent = BohemiaPeople.seatLineOf(who);
  /* THE FACE IS THE BODY. portraits.looks[i] is baked as the face of looks[i]
     (one index, one person), and the walking body is drawn with
     looks[agent.seed % n] — so the same seed here IS the person you walked up
     to, and the body on the street is not touched at all. */
  var slot=document.getElementById('spkface');
  if(slot){
    var n = (CAST && CAST.portraits && CAST.portraits.looks.length) || 0;
    var pf = n ? CAST.portraits.looks[(who.lookSeed>>>0) % n] : null;
    var c2=slot.getContext('2d'); c2.imageSmoothingEnabled=false;
    c2.clearRect(0,0,slot.width,slot.height);
    if(pf){ slot.style.display='block'; c2.drawImage(pf,0,0,slot.width,slot.height); }
    else slot.style.display='none';
  }
  var card=document.getElementById('idcard');
  card.style.display='block'; card.innerHTML='';
  BohemiaPeople.cardFor(who, agent, SIM?SIM.turn:0, met).forEach(function(row){
    var d=document.createElement('div');
    d.className = 'r' + (row.label==='NAME' && !who.name ? ' unnamed' : '');
    var k=document.createElement('div'); k.className='k'; k.textContent=row.label;
    var v=document.createElement('div'); v.className='v'; v.textContent=row.value;
    d.appendChild(k); d.appendChild(v); card.appendChild(d);
  });
  /* WHAT THEY SAY IS EMPTY AND STAYS EMPTY. This lane builds the mouth, not the
     words (doctrine section 6); LINES is Paolo's table and people_gate fails if
     anything fills it. An empty conversation is honest; a placeholder line
     becomes canon by shipping. */
  SAYS.innerHTML='';
  BohemiaPeople.linesFor(who).forEach(function(s){
    var p=document.createElement('p'); p.textContent=s; SAYS.appendChild(p); });
  OPTS.innerHTML='';
  /* YOU HAVE TO ASK (Paolo 7/31, LOCKED). "Nobody will have a name unless you
     talk to them and ask them for their name... I hate how in other games you
     know everyone's name off the bat." So this is the only door to a name, and
     the game remembers you walked through it: re-opening the card, walking away
     and coming back, and loading a save all show them named from here on. */
  if(!BohemiaPeople.nameOf(who)){
    var ask=document.createElement('button');
    ask.id='pplask'; ask.textContent='Ask their name';
    ask.addEventListener('click', function(){
      PEOPLE_MET.ask(who.key, worldDay());
      autoSave('asked');
      drawPerson(agent);          /* they are named from this second onward */
    });
    OPTS.appendChild(ask);
  }
  var hang=document.createElement('button');
  hang.id='pplhang'; hang.textContent='Hang out for an hour';
  hang.addEventListener('click', function(){
    closePerson();
    spendTime('HANGOUT','You spent an hour with '+
      (BohemiaPeople.nameOf(who) ? BohemiaPeople.nameOf(who).split(' ')[0]
                                 : 'the '+BohemiaPeople.headingOf(who).toLowerCase())+'.');
  });
  OPTS.appendChild(hang);
  var go=document.createElement('button');
  go.id='pplleave'; go.className='sil'; go.textContent='Leave them to it';
  go.addEventListener('click', closePerson);
  OPTS.appendChild(go);
  autoSave('met');            /* the meeting is remembered the moment it happens */
}
function closePerson(){
  PERSON_OPEN=null;
  var card=document.getElementById('idcard'); if(card) card.style.display='none';
  var seat=document.getElementById('seat'); if(seat) seat.textContent='';
  TALKEL.style.display='none';
  RUN.phase = (RT && RT.state.done) ? 'resolved' : 'street';
  refresh(); draw();
}
/* THE QUEST'S OWN closeTalk, which now also puts the card away: the two kinds
   of conversation share one sheet, so whichever one closes it has to leave it
   clean for the other. */
function closeTalk(){
  TALKEL.style.display='none';
  var _c=document.getElementById('idcard'); if(_c) _c.style.display='none';
  var _s=document.getElementById('seat'); if(_s) _s.textContent='';
  RUN.phase = (RT && RT.state.done) ? 'resolved' : 'street';
  afterTalk();
}
/* /PEOPLE:RUNTIME */
"""

# ---------------------------------------------------------------------------
# 6. THE MEMORY SURVIVES THE SAVE. Additive: an old save with no `met` key loads
#    into an empty ledger, which is what migrate-forward-never-reject means. No
#    SAVE_ENV_VERSION bump — nothing about an existing save became invalid.
# ---------------------------------------------------------------------------
A_SAVE = "           doors:JSON.parse(JSON.stringify(DOORST)),\n"
B_SAVE = ("           doors:JSON.parse(JSON.stringify(DOORST)),\n"
          "           /* PEOPLE:SAVE */met:PEOPLE_MET.serialize(),/* /PEOPLE:SAVE */\n")

A_LOAD = "    DOORST=b.run.doors||{};\n"
B_LOAD = """    DOORST=b.run.doors||{};
    /* PEOPLE:LOAD */
    /* WHO YOU HAVE MET SURVIVES THE LOAD. The bodies do not survive it — the
       block below rebuilds every agent from the seed — which is exactly why the
       ledger is keyed by DERIVED identity and never by an agent object. */
    PEOPLE_MET = BohemiaPeople.makeLedger(b.run.met || null);
    /* /PEOPLE:LOAD */
"""

# name / where it goes / what it becomes / what UNDOING it restores / label.
# The undo column is the one that matters: a block that only ADDED text undoes
# to nothing, and a block that REPLACED text has to put the original back or a
# second run duplicates it.
# ---------------------------------------------------------------------------
# 7. THE BLOCK'S SEED, NOT THE WORLD'S. Caught by the gate's own first real-
#    surface run: `SEED` is the whole valley (it is literally 7), while the
#    people on a cell are built from a per-cell mix of it. Keying identity off
#    SEED would give house 3's second resident the SAME KEY in every cell in the
#    valley — one identity worn by hundreds of strangers, and a meeting ledger
#    that "remembers" people you have never met. The block seed is the one that
#    made these bodies, so it is the one that names them.
# ---------------------------------------------------------------------------
A_SEED = "    var seed = (SEED ^ (CELL[0]*73856093) ^ (CELL[1]*19349663)) >>> 0;\n"
B_SEED = (A_SEED +
          "    /* PEOPLE:SEED */PEOPLE_SEED = seed;   /* whose block this is */"
          "/* /PEOPLE:SEED */\n")

# ---------------------------------------------------------------------------
# 8. THE BODY IS THE PERSON'S BODY. Measured 7/31 over 528 bodies on 40 blocks:
#    `agent.seed % 6` only ever produces 0, 2 or 4, so THREE OF THE SIX TOWNSFOLK
#    LOOKS THE ALPHA BAKES HAVE NEVER BEEN DRAWN. The cause is dead low bits in
#    bohemia_agents.hash (a float64 multiply past 2^53); the fix lives in
#    bohemia_people.mix32 because changing that hash would reshuffle every
#    household in the valley. Here the body just asks the identity layer which
#    look it wears — the same number the portrait uses, so they agree.
# ---------------------------------------------------------------------------
A_LOOK = "        var lk=lookFor(a.seed);\n"
B_LOOK = """        /* PEOPLE:LOOK */var lk=lookFor(personFor(a).lookSeed);/* /PEOPLE:LOOK */
"""

# ---------------------------------------------------------------------------
# 9. WHAT THE GATE READS. window.__RUN is the run's existing report-never-act
#    debug surface; people_gate.js drives the page through the same buttons
#    Paolo taps and reads the world back through here.
# ---------------------------------------------------------------------------
A_DBG = ("  verb: function(){ return VERB ? { verb:VERB.verb, label:VERB.label } "
         ": null; },\n")
B_DBG = A_DBG + """  /* PEOPLE:DBG */
  /* WHO IS ON THIS BLOCK, as the identity layer sees them. Reports, never acts. */
  people: function(){
    if(!SIM) return null;
    var out = SIM.agents.map(function(a){
      var p = personFor(a);
      return { key:p.key, id:a.id, role:p.role, tier:p.tier, name:BohemiaPeople.nameOf(p),
               asked:PEOPLE_MET.asked(p.key),
               heading:BohemiaPeople.headingOf(p), seat:BohemiaPeople.seatLineOf(p),
               lookSeed:p.lookSeed, outside:(a.loc.mode==='out'),
               x:a.loc.x, y:a.loc.y, house:p.household.house,
               card:BohemiaPeople.cardFor(p, a, SIM.turn, PEOPLE_MET.get(p.key)) };
    });
    return { turn:SIM.turn, day:worldDay(), n:out.length,
             namesKnown:PEOPLE_MET.namesKnown(), met:PEOPLE_MET.serialize(), looks:(CAST&&CAST.portraits)?CAST.portraits.looks.length:0,
             open:PERSON_OPEN?PERSON_OPEN.key:null, people:out };
  },
  /* THE VALLEY IS BIGGER THAN ONE BLOCK, and a gate that can only ever see the
     cell the game opens on cannot check the other 2,303. This calls the run's
     OWN loadCell - the same function the edge-crossing uses when you walk off
     the block - so what the gate sees is what a player who walked there sees.
     Reports after acting; it is a test hook and people_gate is its only caller. */
  gotoCell: function(cx,cy){
    try{ loadCell(cx,cy); buildSim(450); refresh(); draw();
      return { at:CELL.slice(), name:CELLNAME }; }catch(_e){ return null; }
  },
  /* /PEOPLE:DBG */
"""

A_SIM = """    var _agents = BohemiaAgents.agentsForBlock(seed, feet, [], fpOf,
      (_rate!=null) ? {occupiedRate:_rate} : {});
"""
B_SIM = """    /* PEOPLE:WORKERS */
    /* THE OTHER END OF THE COMMUTE (PEOPLE lane 8/1). Everyone whose job is a
       named district already walked out of their gate and LEFT THE WORLD; the
       site they work at stood empty all day while the sim insisted they were
       there. workersForPlot is jobsNear run backwards: the SAME people, from the
       neighbouring blocks that actually send them, materialised where they were
       always supposed to be. It invents nobody \u2014 walk to the solar farm at noon
       and the neighbour whose name you asked is standing in it.
       rateFor hands the run's own zone-map occupancy into the neighbours it
       re-derives, or the person at work would be a different person from the one
       at home.
       THIS FENCE STOPS AT `var _agents`, deliberately: another lane's RUN PERSON
       FACTS block anchors immediately after that line, and a fence that spanned
       it would delete their code on every re-run. The rest of this change is the
       PEOPLE:JOIN block, below theirs. */
    var _rateFor = function(cx,cy){
      if(HOME_CELL && cx===HOME_CELL[0] && cy===HOME_CELL[1]){
        var f=6/Math.max(1,feet.length); var r=_zoneRate(cx,cy);
        return (r==null||r<f)?f:r; }
      return _zoneRate(cx,cy);
    };
    var _agents = BohemiaAgents.agentsForBlock(seed, feet, [], fpOf,
      (_rate!=null) ? {occupiedRate:_rate} : {});
    /* /PEOPLE:WORKERS */
"""

# ---------------------------------------------------------------------------
# 8b. THE JOIN, which lands AFTER the other lane's RUN PERSON FACTS section so
#     neither fence ever spans the other's code.
# ---------------------------------------------------------------------------
A_JOIN = """    SIM = BohemiaAgents.makeSim({ g:G, W:T, H:T }, feet, _agents,
"""
B_JOIN = """    /* PEOPLE:JOIN */
    /* a cell nobody LIVES on gets no households at all - the census has always
       said so and the generator used to disagree with it on 52 of 58 cells */
    if(WORLD && !BohemiaAgents.RESIDENTIAL[(WORLD.at(CELL[0],CELL[1])||{}).district]) _agents=[];
    if(WORLD){ try{
      _agents = _agents.concat(
        BohemiaAgents.workersForPlot(WORLD, CELL[0], CELL[1], 3, {rateFor:_rateFor}));
    }catch(_e){} }
    SIM = BohemiaAgents.makeSim({ g:G, W:T, H:T }, feet, _agents,
    /* /PEOPLE:JOIN */
"""
A_RATE = """    var _rate = null;
"""
B_RATE = """    /* PEOPLE:RATEFN */
    /* the zone-map rate, as ONE function, because both this cell and every
       neighbour a commuter comes from have to be generated at the same one. */
    function _zoneRate(cx,cy){
      try{ if(typeof BohemiaPopulation!=='undefined' && WORLD)
        return BohemiaPopulation.occupiedRateFor(WORLD, POWERMAP, cx, cy,
                 SEED, feet.length||6); }catch(_e){}
      return null;
    }
    /* /PEOPLE:RATEFN */
    var _rate = null;
"""

BLOCKS = [
    ('SCRIPT',  A_SCRIPT,  A_SCRIPT + B_SCRIPT, '',        'engine module'),
    ('CSS',     A_CSS,     A_CSS + B_CSS,       '',        'card css'),
    ('DOM',     A_DOM,     B_DOM,               A_DOM,     'dialogue sheet'),
    ('VERB',    A_VERB,    B_VERB,              A_VERB,    'neighbour verb'),
    ('RUNTIME', A_RUNTIME, B_RUNTIME,           A_RUNTIME, 'talk runtime'),
    ('SAVE',    A_SAVE,    B_SAVE,              '',        'save blob'),
    ('LOAD',    A_LOAD,    B_LOAD,              '',        'save loader'),
    ('SEED',    A_SEED,    B_SEED,              '',        'block seed'),
    ('LOOK',    A_LOOK,    B_LOOK,              A_LOOK,    'body look'),
    ('RATEFN',  A_RATE,    B_RATE,              '',        'zone rate fn'),
    ('WORKERS', A_SIM,     B_SIM,               A_SIM,     'workers at their sites'),
    ('JOIN',    A_JOIN,    B_JOIN,              A_JOIN,    'workers join the sim'),
    ('DBG',     A_DBG,     B_DBG,               '',        'debug surface'),
]


def main():
    src = open(SRC, encoding='utf-8').read()

    for name, _anchor, after, undo, _what in BLOCKS:        # UNDO FIRST, ALWAYS
        src = restore(src, name, undo, after)
    for _n, anchor, _after, _undo, what in BLOCKS:
        once(src, anchor, what)
    for _n, anchor, after, _undo, _w in BLOCKS:
        src = src.replace(anchor, after)

    open(SRC, 'w', encoding='utf-8').write(src)
    print('patched %s' % os.path.relpath(SRC, ROOT))

    r = subprocess.run(['node', os.path.join(ROOT, 'tools', 'build_run_slice.js')],
                       cwd=ROOT, capture_output=True, text=True)
    sys.stdout.write(r.stdout)
    sys.stderr.write(r.stderr)
    if r.returncode:
        sys.exit('build_run_slice.js failed')


if __name__ == '__main__':
    main()
