#!/usr/bin/env python3
"""
BOHEMIA CITY STANDING PATCH -- THE WALL ON THE WALKED SURFACE, AND THE STALE
ENGINE COPY THAT WAS HIDING THE WHOLE FACTION LAYER.  (8/15/26, FACTIONS lane)

Law:  laws/BOHEMIA_ADDENDUM_THE_WALL_AND_WHO_FINDS_OUT_8_15_26.md
Gate: gates/standing_gate.js

REUSE CHECK (REUSE-FIRST, Paolo 7/22): this cooks no graphic pixels. The
mechanisms it wires are all pre-existing and NONE of them is rebuilt here --
BOH_RESOLVE.makeCeiling (approved 7/26), BohemiaCommitment (generated by
tools/bohemia_commitment.py), BohemiaTies (8/12), BohemiaBelonging (8/12). The
patch is wiring, not cooking.

============================================================================
THE THING THIS TURN ACTUALLY FOUND, AND IT IS BIGGER THAN THE FEATURE
============================================================================
Building the wall meant asking a question nobody had asked on the real surface:
HOW MANY PEOPLE IN THE CITY ACTUALLY RUN WITH ANYBODY?

The answer was ZERO. Not few. None, ever, anywhere in the valley.

Measured, not reasoned: 166 people across 40 locations, then all 56 people
standing on all 14 faction bases in turn. Zero affiliated every time.

THE CAUSE, and it is two failures stacked so neither one showed:

  1. THE CITY CARRIES A 7/29 SNAPSHOT OF engine/bohemia_agents.js. Not the
     canonical body -- a copy pasted in on 7/29 under a banner that reads
     "(CITY PEOPLE, 7/29) ... inlined VERBATIM". It was verbatim on 7/29. The
     faction half of that module (factionOf, normalizeBases, jobCell,
     AFFILIATED_RATE, REACH_CELLS) was written on 8/11, THIRTEEN DAYS LATER,
     and the snapshot never moved. So on the walked surface
     BohemiaAgents.factionOf was not a function.

  2. THIS LANE'S OWN BRIDGE SWALLOWED THE EVIDENCE. ctFactionOf was written
     `try { return BohemiaAgents.factionOf(...) } catch(_e){ return null; }`.
     A bare catch returning null turned "this module is thirteen days stale"
     into "nobody in Las Vegas runs with anybody", silently, forever. No page
     error, no red gate, no symptom except a row that never appeared.

AND THE GATES AGREED WITH ME INSTEAD OF WITH THE GAME. walked_surface_gate's
part C proves the card renders a Church member's canon correctly -- by STUBBING
window.ctFactionOf to return 'Church'. Every faction claim this lane has made
about the walked surface was true about a stub. A test that mocks the one thing
that is broken cannot see that it is broken, and that is the failure mode to
remember: I mocked the dependency instead of asserting it existed.

THE FIX IS BOTH HALVES:
  - RESYNC the agents block from its canonical body (ENGINE SYNC LAW: one
    canonical body per module). Measured after: 14 of 56 affiliated across 7
    different outfits, zero page errors.
  - MAKE THE BRIDGE LOUD. A missing dependency now throws once with a sentence
    saying what is stale, instead of answering null a thousand times.

============================================================================
WHAT ELSE IS WIRED
============================================================================
THE WALL. bohemia_standing on the person card: where the wall is, what it is
blocking, what passes it, and -- before you press anything -- which other
outfits will hear about it and how it will reach them.

THE CARD WAS ALSO LYING, and the gate caught it rather than a person: with 5
acts done, an uncommitted player was told "1 MORE TO COUNTED". One more does
nothing; COUNTED is not for sale at any quantity of the same act. The rung line
now defers to the wall.

THE ADAPTER WAS DROPPING A DECLARED FACT. ctAgent minted job:{kind:'scav'} for
everybody, throwing away the workDir/workDist bearing personFields has carried
since the 7/31 address book. Passed through now -- no new data, the record's own
field, in the shape bohemia_ties and bohemia_agents already read.
"""
import os
import sys
import json

CITY = 'slices/BOHEMIA_CITY_WORLD.html'
MARKER = '__CITY_STANDING__'
MODULES = ['engine/bohemia_resolve.js', 'engine/bohemia_commitment.js']

AGENTS_HEAD = '// BOHEMIA AGENTS — the people factory'
AGENTS_TAIL = "})(typeof window!=='undefined'?window:(typeof globalThis!=='undefined'?globalThis:this));"


# ---------------------------------------------------------------- 1. RESYNC
def resync_agents(src):
    """REPLACE THE 7/29 SNAPSHOT WITH ITS CANONICAL BODY (ENGINE SYNC LAW).

    Bounded by the module's own first line and its own IIFE close, both of which
    the canonical file also has, so this is a body swap and not a line-number
    guess. Idempotent: if the block already IS canon, nothing happens."""
    canon = open('engine/bohemia_agents.js', encoding='utf-8').read().rstrip('\n')
    i = src.find(AGENTS_HEAD)
    if i < 0:
        sys.exit('FAIL: could not find the agents block head in the city')
    j = src.find(AGENTS_TAIL, i)
    if j < 0:
        sys.exit('FAIL: could not find the agents block tail in the city')
    j += len(AGENTS_TAIL)
    old = src[i:j]
    if old == canon:
        return src, 0
    if 'factionOf' in old:
        # already resynced by somebody else, or the snapshot moved on: do not
        # stomp a body that already has the faction half.
        return src, 0
    return src[:i] + canon + src[j:], len(canon) - len(old)


# ------------------------------------------------- 2. THE BRIDGE GOES LOUD
OLD_FAC = """function ctFactionOf(p){
  var bases = ctBases();
  if(!bases || typeof BohemiaAgents === 'undefined') return null;
  try { return BohemiaAgents.factionOf(ctAgent(p), ctCell(), bases); } catch(_e){ return null; }
}"""

NEW_FAC = """function ctFactionOf(p){
  var bases = ctBases();
  if(!bases || typeof BohemiaAgents === 'undefined') return null;
  /* """ + MARKER + """ -- A BARE CATCH HERE COST THIS LANE THREE DAYS.
     This used to be `try { ... } catch(_e){ return null; }`. The city carried a
     7/29 snapshot of bohemia_agents whose faction half did not exist yet, so
     factionOf was not a function, so the catch answered null -- for every
     person, in every cell, for thirteen days. Measured: 166 people across 40
     locations, zero affiliated. Nobody in Las Vegas ran with anybody and
     nothing anywhere went red, because a swallowed TypeError looks exactly
     like an honest 'they run with nobody'.
     NULL IS A REAL ANSWER HERE -- most of the valley belongs to no outfit --
     which is precisely why it must never also be the error answer. A missing
     dependency now says so, once, in a sentence. */
  if(typeof BohemiaAgents.factionOf !== 'function'){
    if(!ctFactionOf.__warned){ ctFactionOf.__warned = 1;
      console.error('BOHEMIA: BohemiaAgents.factionOf is missing -- the inlined '
        + 'agents body is stale against engine/bohemia_agents.js. Re-run '
        + 'tools/bohemia_city_commitment_patch.py. Until then NOBODY has a faction '
        + 'and that is a bug, not a world.'); }
    return null;
  }
  /* WHOSE CELL DECIDES IT: THEIRS. This passed ctCell() -- the PLAYER's cell --
     so a person's allegiance was a fact about where I happened to be standing,
     and walking one cell east could change who somebody runs with. Found by the
     gate the same turn: a real Keeper resolved to an outfit while I stood on a
     base and to nobody once I walked over to him.
     Their own cell comes off their own home, which the person record has
     carried all along. Same vocabulary as ctCell (fine coords / FN), so the two
     can never mean different grids. */
  var pc = (p && p.home) ? [Math.floor(p.home[0]/FN), Math.floor(p.home[1]/FN)] : ctCell();
  return BohemiaAgents.factionOf(ctAgent(p), pc, bases);
}"""


# --------------------------------------- 3. THE ADAPTER STOPS DROPPING WORK
OLD_AGENT = """function ctAgent(p){
  var parts=String(p.id).split(':');
  var h=(parseInt(parts[parts.length-1],10)||0)+1;
  return { id:'H'+h+'-1', seed:p.scheduleSeed>>>0, role:p.archetype,
           home:{building:h-1,bedRoom:0}, job:{kind:'scav'}, sched:p.sched };
}"""

NEW_AGENT = """function ctAgent(p){
  var parts=String(p.id).split(':');
  var h=(parseInt(parts[parts.length-1],10)||0)+1;
  /* """ + MARKER + """ -- WHERE THEY WORK WAS BEING THROWN AWAY. personFields has
     carried workDir + workDist on every person since the 7/31 address book
     ("a bearing and a distance, not a district name ... naming the workplace is
     the surface's job"). This adapter marked all of them lone scavengers, which
     deleted a declared fact and cost two things at once: bohemia_ties lost its
     WORK focus, and bohemia_agents.factionOf lost its second origin -- the 8/11
     ruling that you run with whoever your LIVING depends on, not just whoever
     is nearest your bed.
     NOTHING IS INVENTED HERE. These are the record's own fields, handed over in
     the shape both modules already read. A person with no bearing stays a
     scavenger, which is the honest answer and not a gap. */
  /* AND THE BEARING IS RESOLVED INTO A PLACE. personFields says it outright --
     "naming the workplace is the surface's job because only the surface knows
     what is actually there" -- so this surface does it. Their own overmap cell
     plus the declared bearing IS the workplace, and two people who walk to the
     same one now share it however far apart they live. Left as a bearing it was
     relative to each worker, which gave 27 affiliated people 26 different
     workplaces and a social graph with almost no edges in it. */
  var CTW={N:[0,-1],E:[1,0],S:[0,1],W:[-1,0],NE:[1,-1],SE:[1,1],SW:[-1,1],NW:[-1,-1]};
  var site=null;
  if(p.workDir && p.home){
    var v=CTW[p.workDir]||[0,0];
    site=(Math.floor(p.home[0]/FN)+v[0]*p.workDist)+','
        +(Math.floor(p.home[1]/FN)+v[1]*p.workDist);
  }
  return { id:'H'+h+'-1', seed:p.scheduleSeed>>>0, role:p.archetype,
           home:{building:(p.home?p.home[0]+','+p.home[1]:h-1), bedRoom:0},
           job: site
                  ? {kind:'site', district:(p.nx+':'+p.ny), site:site,
                     dir:p.workDir, dist:p.workDist}
                  : {kind:'scav', district:null, dir:null, dist:null},
           sched:p.sched };
}"""


# --------------------------------------------------------- 4. THE CARD ROWS
OLD_RUNG = """      if(bar.rung) body += ctRow('YOU ARE', bar.rung.word
        + (bar.next ? (' \\u00b7 '+bar.next.more+' MORE TO '+bar.next.rung.word) : ''));
      var why = BohemiaBelonging.noActBecause(bRule, bState.st);"""

NEW_RUNG = """      /* """ + MARKER + """ -- THE RUNG LINE WAS PROMISING WHAT THE WALL FORBIDS.
         With five acts done and nothing committed it read "1 MORE TO COUNTED".
         One more does nothing: COUNTED is not for sale at any quantity of the
         same act. The ladder half cannot see the wall half, so the wall answers
         first and the ladder only speaks when there is actually road left. */
      var ctWall = null, ctGave = BohemiaBelonging.gaveOf(bState.sv, ctFid);
      /* function-scoped on purpose: the button block below is outside this if,
         and a commitment is offered on the same ground rule as the act rather
         than on a second number invented for it. */
      var ctOnGround = bState.ground ? bState.ground.on : true;
      if(typeof BohemiaCommitment !== 'undefined'){
        var cSt = BohemiaCommitment.stateOf(bState.sv, ctFid);
        ctWall = BohemiaCommitment.wallOf(cSt, ctGave);
      }
      if(bar.rung) body += ctRow('YOU ARE', bar.rung.word
        + ((bar.next && (!ctWall || !ctWall.atWall))
             ? (' \\u00b7 '+bar.next.more+' MORE TO '+bar.next.rung.word) : ''));
      if(ctWall && ctWall.state !== 'none') body += ctRow('HOW FAR IN', ctWall.word);
      if(ctWall && ctWall.atWall && ctWall.blocks){
        body += ctRow('THE WALL', 'TURNING UP GETS YOU NO FURTHER THAN '
          + ctWall.reaches + '. ' + ctWall.blocks + ' IS NOT FOR SALE.');
        if(ctWall.passNote) body += ctRow('TO PASS IT', ctWall.passNote);
        body = ctHearRows(body, ctFid);
      } else if(ctWall && ctWall.blocks && ctWall.room !== Infinity){
        body += ctRow('THE WALL', ctWall.room + ' MORE AND TURNING UP STOPS WORKING');
      }
      var why = BohemiaBelonging.noActBecause(bRule, bState.st);"""


# ------------------------------------------------------------ 5. THE BUTTON
OLD_BTNS = """  if(ctBtn) body+='<button id="ctask">'+ctBtn+'</button>';
  if(ctAct) body+='<button id="ctgive">'+ctAct.label+'</button>';
  body+='<button id="ctgo">Leave them to it</button>';"""

NEW_BTNS = """  if(ctBtn) body+='<button id="ctask">'+ctBtn+'</button>';
  if(ctAct) body+='<button id="ctgive">'+ctAct.label+'</button>';
  /* """ + MARKER + """ -- THE COMMITMENT. Offered only at the wall, and only on
     their ground: saying you are with somebody is said in front of people, and
     the reach rule that already governs the act governs this too rather than a
     second number invented here. */
  if(ctWall && ctWall.atWall && ctWall.passWord && ctOnGround)
    body+='<button id="ctcommit">'+ctWall.passWord+'</button>';
  body+='<button id="ctgo">Leave them to it</button>';"""

OLD_WIRE2 = """  var give=document.getElementById('ctgive');
  if(give) give.addEventListener('click',function(){"""

NEW_WIRE2 = """  /* """ + MARKER + """ */
  var commit=document.getElementById('ctcommit');
  if(commit) commit.addEventListener('click',function(){
    var sv=ctBelongSave();
    var cur=BohemiaCommitment.stateOf(sv, ctFid);
    var r=BohemiaCommitment.commit(cur, BohemiaBelonging.gaveOf(sv, ctFid));
    if(r.moved) BohemiaCommitment.setState(sv, ctFid, r.state);
    advance(60);
    ctDraw(); render();
  });
  var give=document.getElementById('ctgive');
  if(give) give.addEventListener('click',function(){"""


# ------------------------------------------ 6. WHO WILL HEAR, AND THE ROSTER
HEAR_ANCHOR = "function ctIntroName(intro, asked){"
HEAR = r'''/* ''' + MARKER + r''' -- WHO WILL HEAR ABOUT IT, BEFORE YOU PRESS.
   A consequence you find out about afterwards is a trap. A consequence printed
   on the card next to the button is a decision, and that difference is the whole
   distance between hardcore and unfair.

   THE ROSTER IS THE VALLEY, NOT THE BLOCK -- AND NOT A WINDOW ROUND THE PLAYER.
   News about a commitment does not stop at the edge of the screen, and the nine
   neighbourhoods ctEveryone() returns hold four people.
   THE FIRST VERSION WALKED PLUS-OR-MINUS TEN NEIGHBOURHOODS AROUND hx,hy AND
   CACHED THAT. The gate caught it immediately: stand near the edge of the map
   when the cache is built and the "valley" is 119 people with one affiliated
   body in it, so the same commitment has different consequences depending on
   where you happened to be standing the first time you looked. THE VALLEY DOES
   NOT MOVE, so the walk is now the whole fixed grid from a fixed origin.
   Built ONCE, lazily, on the first card that actually reaches a wall -- which
   is rare -- and cached, keyed to the population module's own RULES VERSION so
   a mass edit invalidates it rather than leaving a stale social graph behind. */
var CT_VALLEY = null, CT_VALLEY_V = null;
function ctValleyRoster(){
  var v = (typeof BohemiaPopulation!=='undefined' && BohemiaPopulation.rulesVersion)
            ? BohemiaPopulation.rulesVersion() : 0;
  if(CT_VALLEY && CT_VALLEY_V === v) return CT_VALLEY;
  var NB=BohemiaPopulation.NB, out=[];
  /* the whole valley: om.n cells a side, NB cells to a neighbourhood. */
  var span=Math.ceil((om && om.n ? om.n : 96)/NB);
  for(var ny=0; ny<span; ny++) for(var nx=0; nx<span; nx++){
    var list=pplPeople(nx,ny);
    for(var i=0;i<list.length;i++){
      var a=ctAgent(list[i]), ph=list[i].home;
      /* THEIR cell, from THEIR home, in the same fine/FN vocabulary ctCell uses.
         nx/ny would have been the neighbourhood grid, which is a different grid
         entirely -- and passing it here would have quietly given the valley a
         different set of allegiances than the card shows. */
      try { a.faction = BohemiaAgents.factionOf(a,
              [Math.floor(ph[0]/FN), Math.floor(ph[1]/FN)], ctBases()); }
      catch(_e){ a.faction = null; }
      a.__id = list[i].id;
      out.push(a);
    }
  }
  CT_VALLEY = out; CT_VALLEY_V = v;
  return out;
}
function ctHearRows(body, fid){
  if(typeof BohemiaCommitment==='undefined' || typeof BohemiaTies==='undefined') return body;
  var heard;
  try { heard = BohemiaCommitment.whoHears(fid, ctValleyRoster(), ctCell(), {ties:BohemiaTies}); }
  catch(_e){ return body; }
  if(!heard.length){
    body += ctRow('WHO WILL HEAR', 'NOBODY. NO OUTFIT IN THIS VALLEY HAS A LINE TO THEM.');
    return body;
  }
  var fact=[], rumour=[];
  for(var i=0;i<heard.length;i++){
    var l=BohemiaCommitment.landing(heard[i]);
    (l.key==='direct'?fact:rumour).push(heard[i].faction);
  }
  if(fact.length)   body += ctRow('WILL HEAR IT AS FACT', fact.join(', '));
  if(rumour.length) body += ctRow('WILL HEAR A RUMOUR', rumour.join(', '));
  /* WHICH SHARED SETTING LEAKED IT. Every bridge across a faction line runs
     through a roof or a job site -- that is a theorem of the foci, not a roll --
     so naming the room is always possible and always the interesting half. */
  var via = heard[0].via==='home' ? 'SOMEBODY THEY SHARE A ROOF WITH'
                                  : 'SOMEBODY THEY WORK BESIDE';
  body += ctRow('IT GETS OUT THROUGH', via);
  return body;
}

function ctIntroName(intro, asked){'''


def main():
    if not os.path.exists(CITY):
        sys.exit('FAIL: ' + CITY + ' not found')
    s = open(CITY, encoding='utf-8').read()
    if MARKER in s:
        print('NOOP: ' + MARKER + ' already present')
        return

    s, delta = resync_agents(s)
    if delta:
        print('ENGINE SYNC: agents block resynced from canon (%+d bytes)' % delta)
        print('  the 7/29 snapshot had no factionOf -- NOBODY in the city had a faction')
    else:
        print('ENGINE SYNC: agents block already current')

    bodies = []
    for m in MODULES:
        if not os.path.exists(m):
            sys.exit('FAIL: missing module ' + m)
        bodies.append('/* ==== engine/' + os.path.basename(m) + ' ==== */\n'
                      + open(m, encoding='utf-8').read())

    # the two organs go in beside the three this lane already inlined
    inject_at = '/* ==== engine/bohemia_introductions.js ==== */'
    if inject_at not in s:
        sys.exit('FAIL: could not find the factions module block to inject beside')
    s = s.replace(inject_at, '\n'.join(bodies) + '\n' + inject_at, 1)

    for old, new, what in ((OLD_FAC, NEW_FAC, 'the faction bridge'),
                           (OLD_AGENT, NEW_AGENT, 'the agent adapter'),
                           (HEAR_ANCHOR, HEAR, 'the who-will-hear rows'),
                           (OLD_RUNG, NEW_RUNG, 'the rung/wall rows'),
                           (OLD_BTNS, NEW_BTNS, 'the commit button'),
                           (OLD_WIRE2, NEW_WIRE2, 'the commit wiring')):
        if old not in s:
            sys.exit('FAIL: could not find ' + what)
        s = s.replace(old, new, 1)

    open(CITY, 'w', encoding='utf-8').write(s)
    print('CITY STANDING: the wall is on the walked surface')
    for m in MODULES:
        print('  + ' + m)


if __name__ == '__main__':
    main()
