/* bohemia_inject_phone.js — regenerate the PHONE tab inside the alpha slice.
   IDEMPOTENT: strips any prior phone injection, then re-injects fresh from the
   canonical sources (engine/bohemia_bq.js + bohemia_quest_runtime.js +
   bohemia_loop.js + slices/phone/phone_app.js + slices/phone/phone.css). Run this
   after any of those change so the alpha's phone stays in sync (ENGINE SYNC LAW:
   the alpha embed is GENERATED from the canonical bodies, never hand-edited).

   Usage:  node tools/bohemia_inject_phone.js            (default target)
           node tools/bohemia_inject_phone.js path.html  (explicit target)
   The phone is purely additive: a PHONE tab, a #p-phone panel, and a scoped
   script/style block of NEW globals. It never touches the alpha's own engine/tabs. */
'use strict';
var fs = require('fs');

var TARGET = process.argv[2] || 'slices/BOHEMIA_ALPHA_0_9.html';
var MARK = '<!-- ===== PHONE (generated by tools/bohemia_inject_phone.js) ===== -->';

function read(p){ return fs.readFileSync(p, 'utf8'); }

function strip(html){
  // remove the injected block (any phone marker -> just before </body></html>)
  var mi = html.indexOf('<!-- ===== PHONE');
  if (mi >= 0){
    while (mi > 0 && html.charAt(mi - 1) === '\n') mi--;   // absorb leading newline(s)
    var end = html.indexOf('</body></html>', mi);
    if (end >= 0) html = html.slice(0, mi) + html.slice(end);
  }
  // remove the tab + panel we added
  html = html.replace('\n    <div class="tab" data-p="phone">PHONE</div>', '');
  html = html.replace('<div class="panel" id="p-phone"><div id="phoneApp"></div></div>\n    ', '');
  return html;
}

function inject(html){
  var tabAnchor = '<div class="tab" data-p="city">CITY</div>';
  if (html.indexOf(tabAnchor) < 0) throw new Error('CITY tab anchor not found');
  html = html.replace(tabAnchor, tabAnchor + '\n    <div class="tab" data-p="phone">PHONE</div>');

  var panelAnchor = '<div class="panel on" id="p-char">';
  if (html.indexOf(panelAnchor) < 0) throw new Error('p-char panel anchor not found');
  html = html.replace(panelAnchor, '<div class="panel" id="p-phone"><div id="phoneApp"></div></div>\n    ' + panelAnchor);

  var bq  = read('engine/bohemia_bq.js');
  var rt  = read('engine/bohemia_quest_runtime.js');
  var lp  = read('engine/bohemia_loop.js');
  var css = read('slices/phone/phone.css');
  var app = read('slices/phone/phone_app.js');
  var S = '<' + 'script>', E = '</' + 'script>';
  var block = '\n' + MARK + '\n' +
    '<style>' + css + '</style>\n' +
    S + '\n/* engine/bohemia_bq.js */\n' + bq + '\n' + E + '\n' +
    S + '\n/* engine/bohemia_quest_runtime.js */\n' + rt + '\n' + E + '\n' +
    S + '\n/* engine/bohemia_loop.js */\n' + lp + '\n' + E + '\n' +
    S + '\n/* slices/phone/phone_app.js */\n' + app + '\n' + E + '\n';

  if ((html.match(/<\/body>/g) || []).length !== 1) throw new Error('expected exactly one </body>');
  return html.replace('</body></html>', block + '</body></html>');
}

var out = inject(strip(read(TARGET)));
fs.writeFileSync(TARGET, out);
console.log('phone injected into ' + TARGET + ' (' + out.length + ' bytes)');
