#!/usr/bin/env node
/* THE HAZARD SHEET (8/18/26, WORLD lane) — the batch output half of the factory.
 *
 * FACTORY LAW: typed spec, generator, BATCH OUTPUT, kill/approve pipeline, own gate. The
 * spec and the generator are engine/bohemia_hazard.js; the gate is gates/hazard_gate.js;
 * this is the batch output — records/BOHEMIA_THE_FLOOR_CAN_KILL_YOU_8_18_26.md, the sheet
 * that says which ground in this valley does what to a body standing on it.
 *
 * GENERATED, LIKE THE DOSSIERS, FOR THE SAME REASON. tools/bohemia_tilespec.js exists
 * because a hand-written note section drifts from the code it describes within days. A
 * hand-written hazard list would be worse: it would be a SECOND membership table sitting
 * beside the derived one, and the day they disagreed the file would win the argument in
 * everybody's head while the game did something else. Rerun this; never hand-edit it.
 *
 * REUSE CHECK: cooks no pixels and opens no bank. It reads the district registry through
 * engine/bohemia_district_kit.js and the classification through engine/bohemia_hazard.js,
 * and it re-implements neither.
 *
 *   node tools/bohemia_hazard_sheet.js
 */
const fs = require('fs'), path = require('path');
const ROOT = path.dirname(__dirname);
require(path.join(ROOT, 'engine/bohemia_world.js'));      // registers every generator
const K = require(path.join(ROOT, 'engine/bohemia_district_kit.js'));
const H = require(path.join(ROOT, 'engine/bohemia_hazard.js'));

const OUT = path.join(ROOT, 'records', 'BOHEMIA_THE_FLOOR_CAN_KILL_YOU_8_18_26.md');
const sweep = H.sweep(K);
const types = K.types();

const rows = [];
for (const d of Object.keys(sweep).sort())
  for (const c of Object.keys(sweep[d]).map(Number).sort((a, b) => a - b)) {
    const L = K.get(d).legend[c];
    rows.push({ d, c, cls: sweep[d][c], name: L.name, kind: L.kind, act1: L.act1 || '' });
  }
const byClass = {};
rows.forEach(r => (byClass[r.cls] = byClass[r.cls] || []).push(r));

/* HOW MUCH OF THE VALLEY EACH CLASS ACTUALLY COVERS — generated one cell per district so
   the number is a measurement of the generators rather than a guess. It is NOT a dial and
   it is not a target: it is what the world already does, which is the whole point. */
function tileShare(d) {
  try {
    const r = K.get(d).generate(1, { streets: ['S'], cw: 1, ch: 1 });
    const tot = r.g.length * r.g[0].length;
    const hit = {};
    for (const row of r.g) for (const v of row) {
      const cl = sweep[d][v];
      if (cl) hit[cl] = (hit[cl] || 0) + 1;
    }
    const out = {};
    for (const cl in hit) out[cl] = hit[cl] / tot;
    return out;
  } catch (e) { return null; }
}

let md = '';
md += '# THE FLOOR CAN DO SOMETHING TO YOU — the hazard sheet (8/18/26, WORLD lane)\n\n';
md += 'GENERATED by `node tools/bohemia_hazard_sheet.js` from `engine/bohemia_hazard.js` +\n';
md += 'the district registry. **Do not hand-edit.** A second membership table kept by hand\n';
md += 'is a table that will one day disagree with the game and win the argument anyway.\n\n';
md += '> Paolo 8/17, LOCKED: **"THE WORLD HAS TO FEEL MORE ALIVE."**\n';
md += '> `laws/BOHEMIA_ADDENDUM_THE_RF4_LIFT_8_17_26.md` §5 routes that order to WORLD and\n';
md += '> says why: it is TILE TYPES with combat-readable properties, not combat code.\n';
md += '> Its closing line is the brief: *a room only feels alive if the floor can do\n';
md += '> something to you.*\n\n';

md += '## NOBODY INVENTED A HAZARD AND NOBODY PLACED ONE\n\n';
md += 'Sixty-two district generators have been authoring real Mojave ground for weeks —\n';
md += 'drained pools, talus aprons, leachate ponds, standing pit water, ballast, crusted\n';
md += 'sludge. **Nothing had ever told the game any of it was dangerous.** So this is a\n';
md += 'READING of ground that already existed, produced by a rule run against each\n';
md += "district's own LEGEND. Author a drained pool into a new district next month and it\n";
md += 'is lethal ground that afternoon, with no edit anywhere. The gate proves that by\n';
md += 'mutating a legend and watching the class follow, in both directions.\n\n';

md += '**' + types.length + ' registered district types swept → ' + rows.length +
      ' hazard tiles in ' + Object.keys(sweep).length + ' districts.**\n\n';
md += '| class | what the floor does (his words) | tiles | districts |\n|---|---|---|---|\n';
['KILLS', 'AMPLIFIES', 'DISABLES', 'FAVOURS', 'DENIES'].forEach(cl => {
  const r = byClass[cl] || [];
  const ds = new Set(r.map(x => x.d));
  md += '| **' + cl + '** | ' + H.CLASSES[cl].says + ' | ' + r.length + ' | ' + ds.size + ' |\n';
});
md += '\n';

md += '## WHAT THE VALLEY ACTUALLY CONTAINS\n\n';
['KILLS', 'DISABLES', 'AMPLIFIES'].forEach(cl => {
  const r = byClass[cl] || [];
  if (!r.length) return;
  const rule = H.ruleFor(cl);
  md += '### ' + cl + ' — ' + H.CLASSES[cl].says + '\n\n';
  md += '_' + rule.why + '_\n\n';
  md += '| district | code | tile | kind | the act-1 material it was authored as |\n';
  md += '|---|---|---|---|---|\n';
  r.forEach(x => {
    md += '| ' + x.d + ' | ' + x.c + ' | **' + x.name + '** | ' + x.kind + ' | ' +
          x.act1.replace(/\|/g, '/') + ' |\n';
  });
  md += '\n';
});

md += '## HOW MUCH OF A CELL IT IS (measured, one generated cell per district)\n\n';
md += 'Not a dial and not a target — **what the generators already do.** How common each\n';
md += 'class SHOULD be is his call and that table ships empty.\n\n';
md += '| district | class | share of the cell |\n|---|---|---|\n';
Object.keys(sweep).sort().forEach(d => {
  const sh = tileShare(d);
  if (!sh) { md += '| ' + d + ' | — | (cell would not generate standalone) |\n'; return; }
  const keys = Object.keys(sh).sort();
  if (!keys.length) { md += '| ' + d + ' | — | 0% in a standalone cell |\n'; return; }
  keys.forEach(cl => {
    md += '| ' + d + ' | ' + cl + ' | ' + (sh[cl] * 100).toFixed(2) + '% |\n';
  });
});
md += '\n';

md += '## THE TWO CLASSES THAT SHIP EMPTY, AND WHY EACH ONE IS EMPTY\n\n';
md += '- **FAVOURS THEM** (cursed floor heals undead) — act one has no undead, and ACT ONE\n';
md += '  ONLY (7/28) forbids me designing the ones that might. The class is DEFINED so\n';
md += '  combat can read it; the day he rules what a cursed floor favours it is one entry,\n';
md += '  not a system.\n';
md += '- **DENIES** (standing on a body prevents resurrection) — **not a tile at all.** It\n';
md += '  is a predicate over OCCUPANCY, so no legend sweep could ever populate it. It ships\n';
md += '  as `deniesOn()`, which answers from a body.\n\n';

md += '## WHAT I REFUSED TO CLASSIFY, AND WHY\n\n';
md += "A classifier's refusals are as much a claim as its picks, and an unrecorded refusal\n";
md += 'is indistinguishable from an oversight.\n\n';
H.UNCLASSIFIED.forEach(u => { md += '- **' + u.tile + '** — ' + u.why + '\n'; });
md += '\n';

md += '## THE GAPS THIS FOUND IN THE WORLD ITSELF (WORLD lane, next)\n\n';
md += '1. **THE VALLEY HAS NO WALKABLE RUBBLE FIELD.** Every rubble/debris tile in six\n';
md += '   districts is a `prop`, which the walked surface blocks — so the single most\n';
md += '   classic piece of unstable ground in any game cannot be stood on here. A\n';
md += '   ground-layer rubble tile is the fix and it is a district-generator job.\n';
md += '2. **THE REAL LETHAL DROPS ARE MODELLED AS WALLS.** `quarry:7 bench lip / crest`,\n';
md += '   `intake:13 intake shaft / main` and `reclaim:6 crusted pond centre` are the three\n';
md += '   most genuinely fatal pieces of ground in this valley and all three are `structure`\n';
md += '   tiles — you bump into them instead of falling in. Making them voids changes\n';
md += '   occupancy in three districts and needs its own pass with its own gate.\n';
md += '3. **ONE CODE, TWO THINGS.** `gypsum:7` means both "the crest of a bench" (a lethal\n';
md += '   edge) and "the shell of the storage dome" (a roof). One code cannot carry two\n';
md += '   occupancies. Split it in the gypsum generator.\n';
md += '4. **THE WALKED SURFACE KNOWS FEWER DISTRICTS THAN THE ENGINE DOES.** Measured on the\n';
md += "   running page: the city world's kit registers 35 of the engine's " + types.length + ' types, and\n';
md += '   only 5 of the ' + Object.keys(sweep).length + ' hazard districts are among them. Every hazard in the other ' +
      (Object.keys(sweep).length - 5) + '\n';
md += '   exists in the engine and cannot be walked on. That is not a hazard problem, it is\n';
md += '   a district-registration gap on the one surface he plays, and it caps far more\n';
md += '   than this feature.\n\n';

md += '## THE ART ASK (hazard tile forms — ART lane, per §6 of the lift)\n\n';
md += 'The law says ART supplies pixels **once the types exist**. They exist as of today.\n';
md += 'What the floor needs to SHOW, so the readout can be retired (§2.6: never explain\n';
md += 'something the floor could have shown):\n\n';
md += '- a **drop** that reads as a drop from above — a rim, a shadow line, a floor at a\n';
md += '  different value. Drained pool, splash pool, treatment basin.\n';
md += '- **loose ground** that reads as loose — broken, unmatched, no two pieces alike.\n';
md += '  Talus, ballast, debris fill, crusted sludge.\n';
md += '- **standing liquid** that reads as wet without reading as clean. Leachate, pit\n';
md += '  water, coolant, shallows.\n\n';
md += 'All three at the 45 DEGREE ART LAW, act-1 dead. Three forms, not nineteen: the\n';
md += 'nineteen tiles already have their own materials — what is missing is the one visual\n';
md += 'mark that says *this ground is different*, readable at walking zoom.\n\n';

md += '---\n';
md += '**Spec + generator:** `engine/bohemia_hazard.js` · **Gate:** `gates/hazard_gate.js` ';
md += '(68 checks) · **On the surface:** `tools/bohemia_city_hazard_patch.py`\n';

fs.writeFileSync(OUT, md);
console.log('HAZARD SHEET: wrote ' + path.relative(ROOT, OUT));
console.log('    ' + rows.length + ' hazard tiles in ' + Object.keys(sweep).length +
            ' districts, swept from ' + types.length + ' registered types');
