#!/usr/bin/env python3
"""BOHEMIA OPENING -- the cold open stops being a tab and becomes the first
thing that happens to you.

THE DEMO PLAN SAYS THIS IN TWO SEPARATE ROWS AND NEITHER WAS DONE.
records/BOHEMIA_THE_DEMO_PLAN_8_4_26.md, THE CRITICAL PATH:
  "7. THE FIRST FIVE MINUTES: an opening that needs zero explanation -- the
      scripted-scene runtime (PEOPLE 0sc) playing a minimal cold open, or a
      clean wake-up-and-go if the cold open isn't ready."
  "10. THE COLD OPEN SCENE (PEOPLE 0sc scripted-scene runtime + RUN consumes...)"
The runtime shipped 8/9. The scene shipped. The CUTSCENE tab shipped and is
gated 40 claims deep. AND THE RUN NEVER CONSUMED IT -- measured, the run source
has ZERO references to the scene runtime and boots straight into wakeInBed(),
which is the plan's own FALLBACK. So the demo's first five minutes has been the
fallback this whole time while the real opening sat one tab away.

THIS IS THE SAME DISEASE AS THE BARKS, THREE DAYS RUNNING: the work exists, the
gates are green, and it is not in the surface he taps. Built, gated, unreachable.

WHERE IT GOES, AND WHY NOT IN THE RUN. The scene draws the family with drawChar
over Paolo's painted rig wearing FAMILY_CAST's wardrobe -- the rig and the cast
live in the ALPHA, not in the run frame, and porting them into the run would
mean a second body pipeline (ENGINE SYNC LAW says no). The alpha owns the RUN
tab as an iframe, so the opening plays OVER that frame in the alpha and reveals
the run when it ends. Nothing in the run's own logic is touched, which also
keeps this inside the PEOPLE lane's boundary.

*** IT PLAYS HIS DIRECTED VERSION, NOT THE SHIPPED ONE. *** DIR['scene:<id>'] is
what the DIRECT tab writes when he changes a line, a speaker, an order or a
beat. The opening reads that first and falls back to canon. So HE MUST BE ABLE
TO DIRECT IT (8/12) closes its loop here: what he edits in DIRECT is literally
what the game opens with, on his phone, on the next run.

WHEN IT PLAYS: first time the RUN tab opens on a device, and only with NO SAVE
(bohemia.save.v1). A returning player never sees it again, and SKIP is on screen
from the first frame because he is going to watch this a hundred times.

IT REPLACES, IT NEVER APPENDS (the 8/11 CHARACTER lane lesson: "an insert tool
run twice is a duplication tool"). Everything lives between markers and is
swapped whole; running it ten times leaves the file identical to running it once.

REUSE CHECK: cooks no pixels. Draws entirely through BohemiaStorySurface +
BohemiaColdOpenSet (12 tiles Paolo approved out of the interior pool) and
cutPaintBody, which are already inlined in the alpha by
tools/bohemia_cutscene_tab_patch.py. No new art, no new bank.

  python3 tools/bohemia_opening_patch.py
Gate: gates/opening_gate.js
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALPHA = os.path.join(ROOT, 'slices', 'BOHEMIA_ALPHA_0_9.html')

PANEL_BEGIN = '<!-- ===== BOHEMIA OPENING OVERLAY (generated) ===== -->'
PANEL_END = '<!-- ===== END BOHEMIA OPENING OVERLAY ===== -->'
JS_BEGIN = '<!-- ===== BOHEMIA OPENING (generated by tools/bohemia_opening_patch.py) ===== -->'
JS_END = '<!-- ===== END BOHEMIA OPENING ===== -->'

# The run panel is a bare iframe; the overlay is a sibling inside the same panel
# so it covers the run exactly and nothing else on the page.
PANEL = PANEL_BEGIN + '''
      <div id="openWrap" style="display:none;position:absolute;inset:0;z-index:40;background:#070906;
           flex-direction:column;align-items:center;justify-content:center">
        <canvas id="openCv" width="360" height="470"
          style="max-width:100%;max-height:74%;display:block;image-rendering:pixelated"></canvas>
        <div id="openCap" style="min-height:56px;width:92%;max-width:420px;margin-top:10px;padding:8px 10px;
             font:13px/1.5 ui-monospace,monospace;color:#e8dfc8;text-align:center"></div>
        <button id="openSkip" style="position:absolute;top:10px;right:10px;padding:6px 12px;
                border:1px solid #3a2f1c;border-radius:4px;background:rgba(12,10,7,.8);
                color:#9a8a5e;font:11px ui-monospace,monospace;letter-spacing:1px">SKIP</button>
      </div>
''' + PANEL_END

JS = JS_BEGIN + '''
<script>
/* ---- THE OPENING. The cold open, in the game, before the day. ---------------
   The CUTSCENE tab is a viewing room. This is the door. Same runtime, same set,
   same bodies -- the only new thing here is WHEN it happens and what it hands
   you to afterwards.

   IT PLAYS WHAT HE DIRECTED. openScene() reads DIR['scene:<id>'] before canon,
   so a line he retyped in DIRECT is the line the game opens with. That is the
   whole point of the 8/12 law and it was only half done while the opening was
   a tab nobody's run ever entered. */
var OPEN_SEEN_KEY = 'bohemia.opening.seen.v1';
var OPEN_PLAYER = null, OPEN_RUNNING = false;

/* THE ONE SCENE THE GAME OPENS WITH. Not "whatever is selected in the CUTSCENE
   tab" -- the opening is a fixed thing, found by the scene's own act/order
   rather than by index, so adding a scene to the catalogue cannot silently
   change what the game starts with. */
function openWhich(){
  var all = (typeof BOHEMIA_CUTSCENES !== 'undefined') ? BOHEMIA_CUTSCENES : [];
  for(var i=0;i<all.length;i++){
    var s = all[i] && all[i].scene;
    if(s && (s.id === 'act1_cold_open' || /cold_open/.test(String(s.id||'')))) return all[i];
  }
  return all[0] || null;
}
function openScene(){
  var c = openWhich(); if(!c) return null;
  var id = 'scene:' + c.scene.id;
  /* HIS VERSION FIRST. DIR is the DIRECT tab's store; it only has a row for a
     scene he has actually touched, so canon is the honest default. */
  try { if(typeof DIR !== 'undefined' && DIR && DIR[id]) return DIR[id]; } catch(_e){}
  return c.scene;
}

/* *** A FRESH PLAYER ALREADY HAS A SAVE, AND THAT IS NOT A BUG. *** The first
   cut of this gated on "no bohemia.save.v1" and never fired once. Measured on
   the real alpha: the RUN frame preloads on a 2.5s timer, boots, and writes an
   auto-save labelled "auto:start" at beat 0 / turn 0 before anybody has touched
   anything. So THE PRESENCE OF A SAVE IS NOT EVIDENCE OF PROGRESS, and any lane
   that reads the key as "has this person played?" is reading it wrong.
   What actually means "mid-story" is a save with something IN it. */
function openHasProgress(){
  try {
    var raw = localStorage.getItem('bohemia.save.v1');
    if(!raw) return false;
    var list = JSON.parse(raw);
    if(!list || !list.length) return false;
    for(var i=0;i<list.length;i++){
      var s = list[i]; if(!s) continue;
      if(String(s.label||'') !== 'auto:start') return true;   /* they saved, or slept, or died */
      if((s.beat|0) > 0 || ((s.engine && s.engine.turn)|0) > 0) return true;
    }
  } catch(_e){ return false; }
  return false;
}

/* WHO GETS TO SEE IT. Once per device, and never over a day already in progress
   -- somebody mid-story is not at the beginning, and being shown the beginning
   would read as a bug rather than as drama. */
function openShould(){
  try { if(localStorage.getItem(OPEN_SEEN_KEY)) return false; } catch(_e){ return false; }
  if(openHasProgress()) return false;
  return !!(typeof BohemiaStorySurface !== 'undefined' && openWhich());
}
function openMarkSeen(){ try{ localStorage.setItem(OPEN_SEEN_KEY,'1'); }catch(_e){} }

function openCaption(s, ended){
  var cap=document.getElementById('openCap'); if(!cap) return;
  if(ended || (s && s.ended)){ cap.textContent=''; return; }
  var L = s && s.line;
  if(!L || !L.text){
    cap.innerHTML='<span style="color:#6f6552;letter-spacing:2px">'+
      ((s && s.era==='pre_collapse') ? 'BEFORE' : 'TEN YEARS LATER')+'</span>';
    return;
  }
  cap.innerHTML='<span style="color:#9a8a5e;font-size:11px;letter-spacing:1px">'+
    (typeof cutSpeakerName==='function' ? cutSpeakerName(L.speaker) : String(L.speaker||''))+
    '</span><br>'+String(L.text).replace(/&/g,'&amp;').replace(/</g,'&lt;');
}

/* THE HANDOFF. However it ends -- played out, skipped, or thrown -- the player
   ends up in the day. An opening that can strand somebody on a black screen is
   worse than no opening, so every exit runs through here exactly once. */
function openDone(){
  if(!OPEN_RUNNING) return;
  OPEN_RUNNING=false;
  openMarkSeen();
  try{ if(OPEN_PLAYER && OPEN_PLAYER.stop) OPEN_PLAYER.stop(); }catch(_e){}
  var w=document.getElementById('openWrap'); if(!w) return;
  w.style.transition='opacity .45s'; w.style.opacity='0';
  setTimeout(function(){ w.style.display='none'; w.style.opacity='1'; w.style.transition=''; }, 460);
}

/* *** IT MUST NOT PLAY BEHIND THE SPLASH, AND IT WAS. *** Caught by LOOKING at
   the render rather than by asking the DOM: the overlay said display:flex, the
   canvas had pixels in it, the captions advanced BEFORE -> the mother's line ->
   the daughter's line, every check green -- and the screenshot was the TAP TO
   ENTER screen, because #front is position:fixed z-index:200 and sits over
   everything. The opening was burning through where nobody could see it.
   VERIFY ON THE REAL SURFACE (7/18) means look at the pixels a person sees, not
   the pixels you addressed. So: if the front screen is still up, wait for it.
   Raising the overlay above the splash would have been the wrong fix -- the
   splash is the door and the opening happens after you walk through it. */
function openFrontUp(){
  var f=document.getElementById('front');
  return !!f && getComputedStyle(f).display !== 'none';
}
/* *** THE RUN TAB DOES NOT SHOW THE RUN PANEL. *** Paolo 7/28, "Can you put the
   city in the run tab?" -- the switcher routes `run` to p-city and leaves the
   run iframe parked in a hidden p-run so postMessage still finds it. The first
   cut of this put the overlay in p-run, which NEVER gets the on class, so it
   computed display:flex inside a display:none parent: every DOM check passed,
   the canvas really was painting, and its bounding box was 0x0. Only the
   screenshot showed the truth.
   So the overlay MOVES to whatever panel is actually live at play time, rather
   than trusting any panel id. If the routing changes again this follows it. */
function openHost(){
  var on=document.querySelector('.panel.on');
  return on || document.getElementById('p-city') || document.getElementById('p-run');
}
function openStart(){
  if(OPEN_RUNNING || !openShould()) return;
  var w=document.getElementById('openWrap'), cv=document.getElementById('openCv');
  if(!w || !cv || typeof cutBoot!=='function') return;
  if(openFrontUp()){
    /* poll rather than hook the splash's own click: another lane owns that
       handler and a second listener on it is a boundary crossing waiting to
       break. Cheap, self-cancelling, and it cannot be got wrong by a reorder. */
    var tries=0;
    var iv=setInterval(function(){
      if(!openFrontUp()){ clearInterval(iv); openStart(); return; }
      if(++tries > 600) clearInterval(iv);        /* five minutes, then give up */
    }, 500);
    return;
  }
  OPEN_RUNNING=true;
  var host=openHost();
  if(host && w.parentElement!==host){
    if(getComputedStyle(host).position==='static') host.style.position='relative';
    host.appendChild(w);
  }
  w.style.display='flex';
  var cap=document.getElementById('openCap');
  if(cap) cap.innerHTML='<span style="color:#6f6552">...</span>';
  /* cutBoot bakes the family once and caches the frames; reusing them is the
     difference between an opening that starts in a second and one that makes a
     demo player stare at a black rectangle while six rigs rebuild. */
  cutBoot(function(){
    var sc=openScene();
    if(!sc){ openDone(); return; }
    OPEN_PLAYER=new BohemiaStorySurface.Story({
      canvas:cv, set:BohemiaColdOpenSet, scene:sc, runtime:BohemiaScene,
      stage:BOH_STAGE, floorplan:BOH_FLOORPLAN,
      paintBody:cutPaintBody, speak:cutVoice,
      onBeat:function(r,s){ openCaption(s); },
      onEnd:function(s){ openCaption(s,true); setTimeout(openDone, 900); }
    });
    if(typeof CUT_FRAMES!=='undefined' && CUT_FRAMES) OPEN_PLAYER.frames=CUT_FRAMES;
    OPEN_PLAYER.loadTiles(function(){
      function go(){ try{ OPEN_PLAYER.start(); }catch(_e){ openDone(); } }
      if(OPEN_PLAYER.frames && Object.keys(OPEN_PLAYER.frames).length) go();
      else OPEN_PLAYER.bake(go);
    });
  });
}

(function(){
  var sk=document.getElementById('openSkip');
  if(sk) sk.addEventListener('click', function(e){ e.stopPropagation(); openDone(); });
  /* THE TRIGGER. The run frame is lazy-loaded when the RUN tab is tapped (and
     preloaded on a timer), so the opening hangs off the same tap rather than
     off page load -- otherwise it would play over the splash for somebody who
     came to look at CLOTHES. */
  var t=document.getElementById('tabs'); if(!t) return;
  var rt=t.querySelector('.tab[data-p=run]');
  if(rt) rt.addEventListener('click', function(){ setTimeout(openStart, 60); });
})();
</script>
''' + JS_END


def swap(text, begin, end, block, what):
    """REPLACE, NEVER APPEND. Idempotent by construction."""
    i = text.find(begin)
    if i >= 0:
        j = text.find(end, i)
        if j < 0:
            sys.exit('REFUSING TO WRITE: %s has an opening marker and no closing one.' % what)
        return text[:i] + block + text[j + len(end):], True
    return text, False


def main():
    src = open(ALPHA, encoding='utf-8').read()

    src, had_panel = swap(src, PANEL_BEGIN, PANEL_END, PANEL, 'the overlay')
    if not had_panel:
        anchor = '<div class="panel" id="p-run">'
        n = src.count(anchor)
        if n != 1:
            sys.exit('REFUSING TO WRITE: the run panel anchor resolves %d times, not 1.' % n)
        # the overlay is absolutely positioned, so the panel must be a containing block
        old = anchor
        new = '<div class="panel" id="p-run" style="position:relative">\n' + PANEL + '\n      '
        src = src.replace(old, new, 1)

    src, had_js = swap(src, JS_BEGIN, JS_END, JS, 'the opening script')
    if not had_js:
        # AFTER the cutscene tab, always: it needs cutBoot, cutPaintBody, cutVoice,
        # BohemiaStorySurface and BohemiaColdOpenSet to already be defined, and it
        # needs DIR, which the DIRECT tab declares.
        anchor = '<!-- ===== END BOHEMIA DIRECT TAB ===== -->'
        n = src.count(anchor)
        if n != 1:
            sys.exit('REFUSING TO WRITE: the DIRECT tab end marker resolves %d times, not 1. '
                     'The opening must be emitted after both the CUTSCENE and DIRECT blocks.' % n)
        src = src.replace(anchor, anchor + '\n' + JS, 1)

    open(ALPHA, 'w', encoding='utf-8').write(src)
    print('OPENING: overlay %s, script %s' % ('replaced' if had_panel else 'inserted',
                                              'replaced' if had_js else 'inserted'))
    print('  alpha : %.1f MB' % (os.path.getsize(ALPHA) / 1e6))


if __name__ == '__main__':
    main()
