/* build_current_slice.js — regenerate slices/BOHEMIA_CURRENT_SLICE.html (the file the
   alpha's SLICE tab loads in an iframe) from the dev phone source
   slices/BOHEMIA_SOCIAL_PHONE_DEMO_7_20_26.html by INLINING the engine modules, so the
   slice is fully self-contained (works standalone on Pages/main, no external refs).

   Flow to show Paolo new phone work:
     1) edit slices/BOHEMIA_SOCIAL_PHONE_DEMO_7_20_26.html (references ../engine, easy to edit)
     2) node tools/build_current_slice.js         (regenerates the self-contained slice)
     3) browser-verify the slice
     4) push ONLY slices/BOHEMIA_CURRENT_SLICE.html to main (Pages serves main)
   Then: alpha SLICE tab -> iframe -> the phone. */
'use strict';
var fs = require('fs');
var SRC = 'slices/BOHEMIA_SOCIAL_PHONE_DEMO_7_20_26.html';
var OUT = 'slices/BOHEMIA_CURRENT_SLICE.html';
var MODS = ['bohemia_engine','bohemia_scheduler','bohemia_bq','bohemia_quest_runtime','bohemia_loop'];

var html = fs.readFileSync(SRC, 'utf8');
MODS.forEach(function(m){
  var tag = '<script src="../engine/' + m + '.js"></' + 'script>';
  if (html.indexOf(tag) < 0) throw new Error('missing module tag: ' + m);
  html = html.replace(tag, '<script>\n/* inlined: engine/' + m + '.js */\n' + fs.readFileSync('engine/' + m + '.js','utf8') + '\n</' + 'script>');
});
html = html.replace('<title>BOHEMIA — The Phone (systems preview)</title>',
  '<title>BOHEMIA — The Phone (current slice)</title>\n<!-- CURRENT SLICE: loaded by the alpha SLICE tab iframe. Self-contained. Generated by tools/build_current_slice.js -->');
if (/\.\.\/engine/.test(html)) throw new Error('external ../engine ref still present after inlining');
fs.writeFileSync(OUT, html);
console.log('built ' + OUT + ' (' + html.length + ' bytes)');
