/* build_run_slice.js — regenerate slices/BOHEMIA_RUN_CURRENT.html (the file the
   alpha's RUN tab loads in an iframe) from the dev source
   slices/BOHEMIA_RUN_SLICE_7_26_26.html, by INLINING every engine module it
   references so the run is fully self-contained (works standalone on Pages/main,
   no external refs). Same shape, same canonical module order, and the same
   freshness contract as tools/build_current_slice.js — one embed order everywhere.

   REUSE CHECK (REUSE-FIRST LAW, Paolo 7/22): before any pixel of the run's look
   was considered, this builder opens slices/BOHEMIA_SUBURB_WALK_7_18_26.html —
   the APPROVED dressed block (canon doors 7/21 + the approved house-skin roofs,
   yards and walls) — and lifts its art-bank block VERBATIM into the run page.
   Nothing new was cooked: the run wears the exact bytes Paolo already approved.

   Flow:
     1) edit slices/BOHEMIA_RUN_SLICE_7_26_26.html  (references ../engine, easy to edit)
     2) node tools/build_run_slice.js               (regenerates the self-contained run)
     3) node gates/run_gate.js                      (plays the whole loop headless)
     4) push slices/BOHEMIA_RUN_CURRENT.html (Pages serves main) */
'use strict';
var fs = require('fs');

var SRC  = 'slices/BOHEMIA_RUN_SLICE_7_26_26.html';
var OUT  = 'slices/BOHEMIA_RUN_CURRENT.html';
var WALK = 'slices/BOHEMIA_SUBURB_WALK_7_18_26.html';   // the APPROVED dressed block

var html = fs.readFileSync(SRC, 'utf8');

/* ---- the real canon faction graph (GDD v2 §9). Must be a real JS value before
   bohemia_loop.js's script runs (a bare {...} at script top level parses as a
   block, not an object), exactly as the phone slice does it. ---- */
if (html.indexOf('__FACTION_GRAPH_JSON__') < 0) throw new Error('missing __FACTION_GRAPH_JSON__ placeholder');
html = html.replace('__FACTION_GRAPH_JSON__', fs.readFileSync('engine/BOHEMIA_faction_graph.json', 'utf8').trim());

/* ---- THE NINE REAL CANON QUESTS, verbatim, as a JSON array of source strings:
   the SAME bytes gates/bohemia_canon_quests_gate.js proves playable. There is no
   second, drifting copy of a quest anywhere. ---- */
if (html.indexOf('__CANON_QUESTS_JSON__') < 0) throw new Error('missing __CANON_QUESTS_JSON__ placeholder');
var BQ_DIR = 'quests/bq';
var bqFiles = fs.readdirSync(BQ_DIR).filter(function (f) { return /\.bq$/.test(f); }).sort();
if (!bqFiles.length) throw new Error('no .bq canon quests found in ' + BQ_DIR);
html = html.replace('__CANON_QUESTS_JSON__', JSON.stringify(bqFiles.map(function (f) {
  return fs.readFileSync(BQ_DIR + '/' + f, 'utf8');
})));

/* ---- THE APPROVED ART BANKS, lifted verbatim from the approved walk surface.
   The block runs from `var DOOR_B64=[` through the `lampAt` helper: the canon
   door bank + the approved roof/yard/wall skins and their pickers. ---- */
var walk = fs.readFileSync(WALK, 'utf8');
var a = walk.indexOf('var DOOR_B64=[');
var bMark = 'function lampAt(';
var b = walk.indexOf(bMark, a);
if (a < 0 || b < 0) throw new Error('could not find the approved art banks in ' + WALK);
var end = walk.indexOf('\n', b);
var banks = walk.slice(a, end);
if (banks.indexOf('ROOF_IMG') < 0 || banks.indexOf('YARD_IMG') < 0 ||
    banks.indexOf('WALL_IMG') < 0 || banks.indexOf('DOOR_B64') < 0) {
  throw new Error('the lifted art block is missing one of the approved banks');
}
if (html.indexOf('__ART_BANKS__') < 0) throw new Error('missing __ART_BANKS__ placeholder');
html = html.replace('__ART_BANKS__', banks);

/* ---- the engine modules, inlined in the page's own (canonical) order. Every
   `<script src="../engine/X.js">` becomes the byte-identical body of engine/X.js,
   so gates/run_gate.js can prove freshness by substring. ---- */
var inlined = 0;
html = html.replace(/<script src="\.\.\/engine\/([a-zA-Z0-9_]+)\.js"><\/script>/g, function (_m, mod) {
  var body = fs.readFileSync('engine/' + mod + '.js', 'utf8');
  inlined++;
  return '<script>\n/* inlined: engine/' + mod + '.js */\n' + body + '\n</' + 'script>';
});
if (!inlined) throw new Error('no engine module tags found to inline');
if (/\.\.\/engine/.test(html)) throw new Error('external ../engine ref still present after inlining');

html = html.replace('<title>BOHEMIA — THE RUN (dev source)</title>',
  '<title>BOHEMIA — THE RUN</title>\n' +
  '<!-- THE RUN: loaded by the alpha RUN tab iframe. Self-contained. Generated by tools/build_run_slice.js — never edit this file directly. -->');

fs.writeFileSync(OUT, html);
console.log('built ' + OUT + ' (' + html.length + ' bytes, ' + inlined + ' engine modules inlined)');
