#!/usr/bin/env python3
"""Regenerate questbook/designs/INDEX.md: the QUESTS library of designs, filed by shelf.

Paolo 9/27 (rule 35b): the product is a library of quest designs already suited to our world,
filed by ACT, by EVENT, by ENDGAME CRISIS, by BOOM OR BUST. This reads every design's header and
writes the four views. Never hand-edit INDEX.md; gates/quests_library_gate.js checks it is current.
"""
import os
import re
from collections import defaultdict

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
DES = os.path.join(ROOT, 'questbook', 'designs')
SHELVES = ['act1', 'act2', 'act3', 'across']
FIELDS = ['ACT', 'KIND', 'CRISIS', 'ECONOMY', 'PLACE']


def read(rel):
    t = open(os.path.join(DES, rel), encoding='utf-8').read()
    m = re.search(r'^#\s*(QD-\S+?):?\s+(.+)$', t, re.M)
    d = {'rel': rel, 'id': m.group(1).rstrip(':') if m else rel, 'title': m.group(2).strip() if m else rel}
    for k in FIELDS:
        m = re.search(r'^' + k + r':\s*(.+)$', t, re.M)
        d[k] = m.group(1).strip() if m else '?'
    d['ids'] = len(set(re.findall(r'\bQ\d{3}\.[WPXN]\d+\b', t)))
    return d


def main():
    rows = []
    for s in SHELVES:
        p = os.path.join(DES, s)
        if os.path.isdir(p):
            rows += [read(s + '/' + f) for f in sorted(os.listdir(p)) if f.startswith('QD_') and f.endswith('.md')]

    def line(d):
        return '- [%s %s](%s)  %s | %s | %s | %d ids' % (
            d['id'], d['title'], d['rel'], d['KIND'], d['CRISIS'], d['ECONOMY'], d['ids'])

    out = ['# THE QUESTS DESIGN LIBRARY (generated by tools/quests_designs_index.py; never hand-edit)',
           '# RESEARCH ONLY (Paolo 9/27, rule 35): nothing here is built. Builders cite these by id.',
           '# Every design cites the 152-quest library by finding id; gates/quests_library_gate.js proves it.',
           '', '%d designs.' % len(rows), '']

    def view(title, key, norm):
        out.append('## BY ' + title)
        g = defaultdict(list)
        for d in rows:
            g[norm(d[key])].append(d)
        for k in sorted(g):
            out.append('### ' + k + ' (%d)' % len(g[k]))
            out.extend(line(d) for d in g[k])
        out.append('')

    view('ACT', 'rel', lambda r: r.split('/')[0].upper())
    view('KIND', 'KIND', lambda v: v.split()[0].lower())
    view('ENDGAME CRISIS', 'CRISIS', lambda v: v.split('(')[0].strip().lower())
    view('BOOM OR BUST', 'ECONOMY', lambda v: (v.split()[0].lower() if v.split() else '?'))
    open(os.path.join(DES, 'INDEX.md'), 'w', encoding='utf-8').write('\n'.join(out))
    print('wrote INDEX.md: %d designs' % len(rows))


if __name__ == '__main__':
    main()
